Sun Dec 22 20:46:32 UTC 2024
a/mkinitrd-1.4.11-x86_64-60.txz:  Rebuilt.
  init: support having the cryptkey.bin keyfile in the initrd itself.
  Thanks to kursu. I took this as the simplest patch, written in the closest to
  the existing style. Honorable mention to Didier Spaier, opty, and RyNo (this
  actually might be based on RyNo's patch) for providing alternative approaches
  for consideration.
a/pkgtools-15.1-noarch-23.txz:  Rebuilt.
  Clean up after --dry-run better (although this matters less now that we'll be
  mounting a tmpfs on /var/lib/pkgtools/setup/tmp). Thanks to Mechanikx.
  While we're here, change tabs to spaces (only found in installpkg).
a/sysvinit-3.12-x86_64-1.txz:  Upgraded.
a/sysvinit-scripts-15.1-noarch-24.txz:  Rebuilt.
  rc.M: mount a tmpfs on /var/lib/pkgtools/setup/tmp.
ap/man-db-2.13.0-x86_64-3.txz:  Rebuilt.
  man-db.{csh,sh}: export MANROFFOPT=-c to fix colors with most pager.
  Thanks to eduardr.
l/imagemagick-7.1.1_42-x86_64-1.txz:  Upgraded.
l/libvncserver-0.9.15-x86_64-1.txz:  Upgraded.
l/python-Jinja2-3.1.5-x86_64-1.txz:  Upgraded.
l/python-urllib3-2.3.0-x86_64-1.txz:  Upgraded.
x/fontconfig-2.15.0-x86_64-4.txz:  Rebuilt.
  60-latin.conf: Make Liberation Serif, Liberation Sans, and Liberation Mono
  the preferred fonts, as they were in Slackware 15.0.
x/hack-fonts-ttf-3.003-noarch-4.txz:  Rebuilt.
  I like the Hack font, but I'm not sure that it's the best default for an all-
  purpose monospace system font. So what we'll do is add a new file in
  conf.avail called 58-hack-default-monospace.conf that if symlinked into
  /etc/fonts/conf.d/ will make Hack the default monospace font.
  I'm considering adding similar override .conf files for DejaVu and Noto.

diff --git a/source/a/pkgtools/scripts/installpkg b/source/a/pkgtools/scripts/installpkg
--- a/source/a/pkgtools/scripts/installpkg
+++ b/source/a/pkgtools/scripts/installpkg
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Copyright 1994, 1998, 2000  Patrick Volkerding, Concord, CA, USA 
 # Copyright 2001, 2003  Slackware Linux, Inc., Concord, CA, USA
-# Copyright 2007, 2009, 2011, 2017, 2018, 2019, 2020, 2021  Patrick Volkerding, Sebeka, MN, USA 
+# Copyright 2007, 2009, 2011, 2017, 2018, 2019, 2020, 2021, 2024  Patrick Volkerding, Sebeka, MN, USA 
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -167,35 +167,35 @@ Installpkg is used to install a .t{gz,bz,lz,xz} package like this:
    installpkg slackware-package-1.0.0-i486-1.tgz (or .tbz, .tlz, .txz)
 
 options:      --warn (warn if files will be overwritten, but do not install)
-	      --dry-run (same as --warn)
-	      --root /mnt (install someplace else, like /mnt)
-	      --infobox (use dialog to draw an info box)
-	      --terse (display a one-line short description for install)
-	      --terselength <length> (line length in terse mode - default is
-		    the number of columns available)
-	      --menu (confirm package installation with a menu, unless
-		    the priority is [required] or ADD)
-	      --ask (used with menu mode: always ask if a package should be
-		   installed regardless of what the package's priority is)
-	      --priority ADD|REC|OPT|SKP (provide a priority for the entire
-		    package list to use instead of the priority in the
-		    tagfile)
-	      --tagfile /somedir/tagfile (specify a different file to use
-		    for package priorities. The default is "tagfile" in
-		    the package's directory)
-	      --threads <number> For xz/plzip compressed packages, set the max
-		    number of threads to be used for decompression. Only has
-		    an effect if a multithreaded compressor was used, and then
-		    only on large packages. For plzip, the default is equal to
-		    the number of CPU threads available on the machine. For xz,
-		    the default is equal to 2.
-	      --md5sum (record the package's md5sum in the metadata file)
-	      --no-overwrite When extracting the package, do not overwrite
-		    existing files. Usually, this option should not be used.
-		    It exists so that upgradepkg can use it for the second
-		    installation pass. The first pass has already overwritten
-		    the previous package's files, and this will catch the few
-		    corner cases without generating unnecessary writes.
+              --dry-run (same as --warn)
+              --root /mnt (install someplace else, like /mnt)
+              --infobox (use dialog to draw an info box)
+              --terse (display a one-line short description for install)
+              --terselength <length> (line length in terse mode - default is
+                    the number of columns available)
+              --menu (confirm package installation with a menu, unless
+                    the priority is [required] or ADD)
+              --ask (used with menu mode: always ask if a package should be
+                   installed regardless of what the package's priority is)
+              --priority ADD|REC|OPT|SKP (provide a priority for the entire
+                    package list to use instead of the priority in the
+                    tagfile)
+              --tagfile /somedir/tagfile (specify a different file to use
+                    for package priorities. The default is "tagfile" in
+                    the package's directory)
+              --threads <number> For xz/plzip compressed packages, set the max
+                    number of threads to be used for decompression. Only has
+                    an effect if a multithreaded compressor was used, and then
+                    only on large packages. For plzip, the default is equal to
+                    the number of CPU threads available on the machine. For xz,
+                    the default is equal to 2.
+              --md5sum (record the package's md5sum in the metadata file)
+              --no-overwrite When extracting the package, do not overwrite
+                    existing files. Usually, this option should not be used.
+                    It exists so that upgradepkg can use it for the second
+                    installation pass. The first pass has already overwritten
+                    the previous package's files, and this will catch the few
+                    corner cases without generating unnecessary writes.
 
 EOF
 }
@@ -335,7 +335,6 @@ fi
 # If -warn mode was requested, produce the output and then exit:
 if [ "$MODE" = "warn" ]; then
   while [ -f "$1" ]; do
-    mkdir -p $TMP/scan${MCOOKIE}
     # Determine extension:
     packageext="$( echo $1 | rev | cut -f 1 -d . | rev)"
     # Determine decompressor utility:
@@ -345,50 +344,51 @@ if [ "$MODE" = "warn" ]; then
       ;;
     'tbz' )
       if which lbzip2 1> /dev/null 2> /dev/null ; then
-	packagecompression=lbzip2
+        packagecompression=lbzip2
       else
-	packagecompression=bzip2
+        packagecompression=bzip2
       fi
       ;;
     'tlz' )
       if which plzip 1> /dev/null 2> /dev/null ; then
-	packagecompression="plzip --threads=${THREADS}"
+        packagecompression="plzip --threads=${THREADS}"
       elif which lzip 1> /dev/null 2> /dev/null ; then
-	packagecompression=lzip
+        packagecompression=lzip
       else
-	echo "ERROR:  lzip compression utility not found in \$PATH."
-	exit 3
+        echo "ERROR:  lzip compression utility not found in \$PATH."
+        exit 3
       fi
       ;;
     'txz' )
       if [ "$XZ_THREADS_FORCED" = "yes" ]; then
-	packagecompression="xz --threads=${THREADS}"
+        packagecompression="xz --threads=${THREADS}"
       else
-	# Let xz determine how many threads to use:
-	packagecompression="xz --threads=0"
+        # Let xz determine how many threads to use:
+        packagecompression="xz --threads=0"
       fi
       ;;
     esac
+    mkdir -p $TMP/scan${MCOOKIE}
     ( cd $TMP/scan${MCOOKIE} ; $packagecompression -dc | tar xf - install ) < $1 2> /dev/null 
     if [ -r $TMP/scan${MCOOKIE}/install/doinst.sh ]; then
       if grep ' rm -rf ' $TMP/scan${MCOOKIE}/install/doinst.sh 1>/dev/null 2>/dev/null ; then
-	grep ' rm -rf ' $TMP/scan${MCOOKIE}/install/doinst.sh > $TMP/scan${MCOOKIE}/install/delete
-	for f in `cat $TMP/scan${MCOOKIE}/install/delete | cut -f 3,7 -d ' ' | tr ' ' '/'`; do
-	  f="/$f"
-	  if [ -f "$f" -o -L "$f" ]; then
-	    echo "$f"
-	  fi
-	done
+        grep ' rm -rf ' $TMP/scan${MCOOKIE}/install/doinst.sh > $TMP/scan${MCOOKIE}/install/delete
+        for f in `cat $TMP/scan${MCOOKIE}/install/delete | cut -f 3,7 -d ' ' | tr ' ' '/'`; do
+          f="/$f"
+          if [ -f "$f" -o -L "$f" ]; then
+            echo "$f"
+          fi
+        done
       fi
-      if [ -d $TMP/scan${MCOOKIE} ]; then
-	( cd $TMP/scan${MCOOKIE} ; rm -rf install ) 2> /dev/null
-	( cd $TMP ; rmdir scan${MCOOKIE} ) 2> /dev/null
-      fi
+    fi
+    if [ -d $TMP/scan${MCOOKIE} ]; then
+      ( cd $TMP/scan${MCOOKIE} ; rm -rf install ) 2> /dev/null
+      ( cd $TMP ; rmdir scan${MCOOKIE} ) 2> /dev/null
     fi
     for f in `( $packagecompression -dc | tar tf - ) < $1 | grep -v 'drwx'`; do
       f="/$f"
       if [ -f "$f" -o -L "$f" ]; then
-	echo "$f"
+        echo "$f"
       fi
     done
     shift 1
@@ -617,7 +617,7 @@ EOF
       "No" "Do not install package $shortname" \
       "Quit" "Abort software installation completely" 2> $TMP/reply${MCOOKIE}
       if [ ! $? = 0 ]; then
-	echo "No" > $TMP/reply${MCOOKIE}
+        echo "No" > $TMP/reply${MCOOKIE}
       fi
     ) 9> $INSTLOCKDIR/dialog.lock
     REPLY="$(cat $TMP/reply${MCOOKIE})"
@@ -702,22 +702,22 @@ EOF
       # rather than spawning subshells which is slow on ARM.  This will also speed up
       # install script processing on any platform.
       if [ -x /bin/bash ]; then
-	( cd $ROOT/ ; sed -e's?^( cd \([^;]*\);\(.*\) )$?pushd \1 \&\> /dev/null ; \2 ; popd \&\> /dev/null?g ' $INSTDIR/doinst.sh | /bin/bash )
+        ( cd $ROOT/ ; sed -e's?^( cd \([^;]*\);\(.*\) )$?pushd \1 \&\> /dev/null ; \2 ; popd \&\> /dev/null?g ' $INSTDIR/doinst.sh | /bin/bash )
       else
-	( cd $ROOT/ ; sh $INSTDIR/doinst.sh )
+        ( cd $ROOT/ ; sh $INSTDIR/doinst.sh )
       fi
     else # use locking
       # If bash is available, use sed to convert the install script to use pushd/popd
       # rather than spawning subshells which is slow on ARM.  This will also speed up
       # install script processing on any platform.
       if [ -x /bin/bash ]; then
-	( flock 9 || exit 11
-	  cd $ROOT/ ; sed -e's?^( cd \([^;]*\);\(.*\) )$?pushd \1 \&\> /dev/null ; \2 ; popd \&\> /dev/null?g ' $INSTDIR/doinst.sh | /bin/bash
-	) 9> $INSTLOCKDIR/doinst.sh.lock
+        ( flock 9 || exit 11
+          cd $ROOT/ ; sed -e's?^( cd \([^;]*\);\(.*\) )$?pushd \1 \&\> /dev/null ; \2 ; popd \&\> /dev/null?g ' $INSTDIR/doinst.sh | /bin/bash
+        ) 9> $INSTLOCKDIR/doinst.sh.lock
       else
-	( flock 9 || exit 11
-	  cd $ROOT/ ; sh $INSTDIR/doinst.sh
-	) 9> $INSTLOCKDIR/doinst.sh.lock
+        ( flock 9 || exit 11
+          cd $ROOT/ ; sh $INSTDIR/doinst.sh
+        ) 9> $INSTLOCKDIR/doinst.sh.lock
       fi
     fi
   fi 
