Sat Feb  8 23:52:14 UTC 2025
a/kernel-firmware-20250208_4ccb15a-noarch-1.txz:  Upgraded.
a/kernel-generic-6.12.13-x86_64-1.txz:  Upgraded.
a/pkgtools-15.1-noarch-27.txz:  Rebuilt.
  installpkg: --terse remains the same, default output drops the huge amount
  of debugging output such as the file/link/dir lists, and --verbose is added
  as an option in case you actually want to see that stuff. New --save-cookies
  option added for upgradepkg to use. This lets us preserve some data from the
  first pass so that we don't have to redo some expensive operations.
  removepkg: default to --terse, but add a --verbose option.
  Change sed delimiter from / to | to fix using ROOT=. Thanks to USUARIONUEVO.
  upgradepkg: export a global MCOOKIE, and call installpkg with --save-cookies
  for the first pass. Pass along the --verbose option to installpkg/removepkg
  if upgradepkg is called with it. Render the banner with a little more care.
  I think we're done improving these tools -- hopefully Dijkstra would be a
  little less embarrassed for me now. ;-)
a/sysvinit-3.14-x86_64-1.txz:  Upgraded.
d/kernel-headers-6.12.13-x86-1.txz:  Upgraded.
k/kernel-source-6.12.13-noarch-1.txz:  Upgraded.
l/SDL2_image-2.8.5-x86_64-1.txz:  Upgraded.
l/SDL2_mixer-2.8.1-x86_64-1.txz:  Upgraded.
l/wireplumber-0.5.8-x86_64-1.txz:  Upgraded.
n/gnutls-3.8.9-x86_64-1.txz:  Upgraded.
  libgnutls: Fix potential DoS in handling certificates with numerous name
  constraints, as a follow-up of CVE-2024-12133 in libtasn1. The bundled
  copy of libtasn1 has also been updated to the latest 4.20.0 release to
  complete the fix.  Reported by Bing Shi.
  For more information, see:
    https://www.cve.org/CVERecord?id=CVE-2024-12243
  (* Security fix *)
isolinux/initrd.img:  Rebuilt.
kernels/*:  Upgraded.
testing/packages/kernel-generic-6.13.2-x86_64-1.txz:  Upgraded.
testing/packages/kernel-headers-6.13.2-x86-1.txz:  Upgraded.
testing/packages/kernel-source-6.13.2-noarch-1.txz:  Upgraded.
usb-and-pxe-installers/usbboot.img:  Rebuilt.

diff --git a/source/a/pkgtools/scripts/installpkg b/source/a/pkgtools/scripts/installpkg
--- a/source/a/pkgtools/scripts/installpkg
+++ b/source/a/pkgtools/scripts/installpkg
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Copyright 1994, 1998, 2000  Patrick Volkerding, Concord, CA, USA 
 # Copyright 2001, 2003  Slackware Linux, Inc., Concord, CA, USA
-# Copyright 2007, 2009, 2011, 2017, 2018, 2019, 2020, 2021, 2024  Patrick Volkerding, Sebeka, MN, USA 
+# Copyright 2007, 2009, 2011, 2017, 2018, 2019, 2020, 2021, 2024, 2025  Patrick Volkerding, Sebeka, MN, USA 
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,6 +20,15 @@
 #  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+#
+# Sat Feb  8 19:01:48 UTC 2025
+# Add --save-cookies option. This won't delete some cookies in the $TMP
+# directory containing the package's description and size. This lets a
+# second pass from upgradepkg access this data without having to derive it
+# all over again.
+#
+# Fri Feb  7 15:38:56 CST 2025
+# Add --verbose option to show all the files in the package.
 #
 # Thu May 20 18:55:21 UTC 2021
 # Add support for the flag ALWAYS_RUN_INSTALL_SCRIPT in doinst.sh. If it
@@ -141,14 +150,15 @@ umask 022
 # then we can stop needlessly erasing files in the /install directory while
 # also making installpkg thread-safe. Don't check for recent tar - we'll
 # already break from --attrs and --xattrs anyway if the wrong tar is used.
-if which mcookie 1> /dev/null 2> /dev/null ; then
-  MCOOKIE=$(mcookie)
-  INSTDIR=installpkg-${MCOOKIE}
-else
-  # Well, we will make due with this:
-  MCOOKIE=$$
-  INSTDIR=installpkg-${MCOOKIE}
+if [ -z "$MCOOKIE" ]; then
+  if which mcookie 1> /dev/null 2> /dev/null ; then
+    MCOOKIE=$(mcookie)
+  else
+    # Well, we will make due with this:
+    MCOOKIE=$$
+  fi
 fi
+INSTDIR=installpkg-${MCOOKIE}
 
 # Create a lockfile directory if it doesn't exist. We can use it to prevent
 # screen corruption (from multiple dialogs) and install script collisions
@@ -164,7 +174,7 @@ usage() {
 Usage: installpkg [options] <package_filename>
 
 Installpkg is used to install a .t{gz,bz,lz,xz} package like this:
-   installpkg slackware-package-1.0.0-i486-1.tgz (or .tbz, .tlz, .txz)
+   installpkg slackware-package-1.0.0-x64_64-1.txz (or .tgz, .tbz, .tlz)
 
 options:      --warn (warn if files will be overwritten, but do not install)
               --dry-run (same as --warn)
@@ -173,6 +183,7 @@ options:      --warn (warn if files will be overwritten, but do not install)
               --terse (display a one-line short description for install)
               --terselength <length> (line length in terse mode - default is
                     the number of columns available)
+              --verbose (list all the files that are installed)
               --menu (confirm package installation with a menu, unless
                     the priority is [required] or ADD)
               --ask (used with menu mode: always ask if a package should be
@@ -196,15 +207,11 @@ options:      --warn (warn if files will be overwritten, but do not install)
                     installation pass. The first pass has already overwritten
                     the previous package's files, and this will catch the few
                     corner cases without generating unnecessary writes.
+              --save-cookies When called by upgradepkg, save some data in the
+                    temp directory after the first installpkg pass so that
+                    the second pass can use it (avoiding redundant processing).
 
 EOF
-}
-
-# Eliminate whitespace function:
-crunch() {
-  while read FOO ; do
-    echo $FOO
-  done
 }
 
 # Strip version, architecture and build from the end of the name
@@ -247,6 +254,9 @@ while [ 0 ]; do
   elif [ "$1" = "-terselength" -o "$1" = "--terselength" ]; then
     TERSELENGTH=$2
     shift 2
+  elif [ "$1" = "-verbose" -o "$1" = "--verbose" ]; then
+    VERBOSE=true
+    shift 1
   elif [ "$1" = "-menu" -o "$1" = "--menu" ]; then
     MODE=menu
     shift 1
@@ -255,6 +265,9 @@ while [ 0 ]; do
     shift 1
   elif [ "$1" = "--no-overwrite" ]; then
     NO_OVERWRITE=" --skip-old-files "
+    shift 1
+  elif [ "$1" = "--save-cookies" ]; then
+    DONT_DELETE_COOKIES="true"
     shift 1
   elif [ "$1" = "-tagfile" -o "$1" = "--tagfile" ]; then
     if [ -r "$2" ]; then
@@ -507,31 +520,57 @@ for package in $* ; do
 
   # Figure out some package information, like the compressed and uncompressed
   # sizes, and where to find the package description:
-  COMPRESSED="$(/bin/du -sh "$(readlink -f $package)" | cut -f 1)"
+
+  # See if we can get the compressed size from a cookie (previous pass):
+  if [ -r $TMP/comp-$MCOOKIE ]; then
+    COMPRESSED="$(cat $TMP/comp-$MCOOKIE)"
+  else
+    # Calculate it and save a cookie:
+    COMPRESSED="$(/bin/du -sh "$(readlink -f $package)" | cut -f 1)"
+    echo $COMPRESSED > $TMP/comp-$MCOOKIE
+  fi
+ 
+  # Clear the description variable:
   DESCRIPTION=""
-  # First check for .txt file next to the package, since this is faster:
-  if grep "^$packagebase:" "$packagedir/$shortname.txt" 1> /dev/null 2> /dev/null ; then
-    DESCRIPTION="$packagedir/$shortname.txt"
-  elif grep "^$shortname:" "$packagedir/$shortname.txt" 1> /dev/null 2> /dev/null ; then
-    DESCRIPTION="$packagedir/$shortname.txt"
+
+  # See if we can get the description from a cookie (previous pass):
+  if [ -r $TMP/desc-$MCOOKIE ]; then
+    DESCRIPTION="$TMP/desc-$MCOOKIE"
   fi
 
-  # Test tarball integrity and get uncompressed package size:
-  if [ "$MODE" = "install" ]; then
-    echo "Verifying package $(basename $package)."
-  fi
-  cat $package | $packagecompression -dc | LC_ALL=C dd 2> $TMP/tmpsize${MCOOKIE} | tar tf - 2> /dev/null 1> $TMP/tmplist${MCOOKIE}
-  TARERROR=$?
-  if [ ! "$TARERROR" = "0" ]; then
-    EXITSTATUS=1 # tar file corrupt
-    if [ "$MODE" = "install" ]; then
-      echo "Unable to install $package:  tar archive is corrupt (tar returned error code $TARERROR)"
+  # Then check for .txt file next to the package (also fast):
+  if [ "$DESCRIPTION" = "" ]; then
+    if grep "^$packagebase:" "$packagedir/$shortname.txt" 1> /dev/null 2> /dev/null ; then
+      DESCRIPTION="$packagedir/$shortname.txt"
+    elif grep "^$shortname:" "$packagedir/$shortname.txt" 1> /dev/null 2> /dev/null ; then
+      DESCRIPTION="$packagedir/$shortname.txt"
     fi
-    rm -f $TMP/tmplist${MCOOKIE} $TMP/tmpsize${MCOOKIE}
-    continue
   fi
-  UNCOMPRESSED="$(cat $TMP/tmpsize${MCOOKIE} | tail -n 1 | cut -f 1 -d ' ' | numfmt --to=iec)"
-  rm -f $TMP/tmpsize${MCOOKIE}
+
+  # If we already have the uncompressed size in a cookie, then we are on the
+  # second pass from upgradepkg, and the package has already been verified.
+  if [ -r $TMP/uncomp-$MCOOKIE ]; then
+    UNCOMPRESSED="$(cat $TMP/uncomp-$MCOOKIE)"
+  else
+    # Test tarball integrity and get uncompressed package size:
+    if [ "$MODE" = "install" ]; then
+      echo "Verifying package $(basename $package)."
+    fi
+    cat $package | $packagecompression -dc | LC_ALL=C dd 2> $TMP/tmpsize${MCOOKIE} | tar tf - 2> /dev/null 1> $TMP/tmplist${MCOOKIE}
+    TARERROR=$?
+    if [ ! "$TARERROR" = "0" ]; then
+      EXITSTATUS=1 # tar file corrupt
+      if [ "$MODE" = "install" ]; then
+        echo "Unable to install $package:  tar archive is corrupt (tar returned error code $TARERROR)"
+      fi
+      rm -f $TMP/tmplist${MCOOKIE} $TMP/tmpsize${MCOOKIE}
+      continue
+    fi
+    UNCOMPRESSED="$(cat $TMP/tmpsize${MCOOKIE} | tail -n 1 | cut -f 1 -d ' ' | numfmt --to=iec)"
+    rm -f $TMP/tmpsize${MCOOKIE}
+    # Save the uncompressed size in a cookie:
+    echo "$UNCOMPRESSED" > $TMP/uncomp-$MCOOKIE
+  fi
 
   # If we still don't have a package description, look inside the package.
   # This requires a costly untar.
@@ -548,6 +587,17 @@ for package in $* ; do
   if [ "$DESCRIPTION" = "" ]; then
     #echo "WARNING NO SLACK-DESC"
     DESCRIPTION="/dev/null"
+  fi
+
+  # If it doesn't exist already, write the description into a cookie:
+  if [ ! -r $TMP/desc-$MCOOKIE ]; then
+    cat $DESCRIPTION > $TMP/desc-$MCOOKIE
+    DESCRIPTION="$TMP/desc-$MCOOKIE"
+  fi
+
+  # If we used a scan directory, get rid of it:
+  if [ -d "$TMP/scan${MCOOKIE}" ]; then
+    rm -rf "$TMP/scan${MCOOKIE}"
   fi
 
   # Gather package infomation into a temporary file:
@@ -636,7 +686,6 @@ EOF
       rm -f "$ROOT/$file"
     fi
   done
-  rm -f $TMP/tmplist${MCOOKIE}
 
   # Write the package file database entry and install the package:
   echo "PACKAGE NAME:     $shortname" > $ADM_DIR/packages/$shortname
@@ -653,10 +702,19 @@ EOF
     grep "^$shortname:" $DESCRIPTION >> $ADM_DIR/packages/$shortname 2> /dev/null
   fi
   echo "FILE LIST:" >> $ADM_DIR/packages/$shortname
+
   if [ "$INSTDIR" = "install" ]; then
-    ( cd $ROOT/ ; $packagecompression -dc | tar --acls --xattrs --xattrs-include='*' --keep-directory-symlink $NO_OVERWRITE -xpvf - | LC_ALL=C sort ) < $package >> $TMP/$shortname 2> /dev/null
+    if [ "$VERBOSE" = "true" -a -z "$NO_OVERWRITE" ]; then
+      ( cd $ROOT/ ; $packagecompression -dc | tar --acls --xattrs --xattrs-include='*' --keep-directory-symlink $NO_OVERWRITE -xpvf - | LC_ALL=C sort ) < $package 2> /dev/null | tee -a $TMP/$shortname | sed "s/^/\//g"
+    else
+      ( cd $ROOT/ ; $packagecompression -dc | tar --acls --xattrs --xattrs-include='*' --keep-directory-symlink $NO_OVERWRITE -xpvf - | LC_ALL=C sort ) < $package >> $TMP/$shortname 2> /dev/null
+    fi
   else
-    ( cd $ROOT/ ; $packagecompression -dc | tar --transform "s,^install$,$INSTDIR," --transform "s,^install/,$INSTDIR/," --acls --xattrs --xattrs-include='*' --keep-directory-symlink $NO_OVERWRITE -xpvf - | LC_ALL=C sort ) < $package >> $TMP/$shortname 2> /dev/null
+    if [ "$VERBOSE" = "true" -a -z "$NO_OVERWRITE" ]; then
+      ( cd $ROOT/ ; $packagecompression -dc | tar --transform "s,^install$,$INSTDIR," --transform "s,^install/,$INSTDIR/," --acls --xattrs --xattrs-include='*' --keep-directory-symlink $NO_OVERWRITE -xpvf - | LC_ALL=C sort ) < $package 2> /dev/null | tee -a $TMP/$shortname | sed "s/^/\//g"
+    else
+      ( cd $ROOT/ ; $packagecompression -dc | tar --transform "s,^install$,$INSTDIR," --transform "s,^install/,$INSTDIR/," --acls --xattrs --xattrs-include='*' --keep-directory-symlink $NO_OVERWRITE -xpvf - | LC_ALL=C sort ) < $package >> $TMP/$shortname 2> /dev/null
+    fi
   fi
   if [ "$( grep '^\./' $TMP/$shortname | wc -l | tr -d ' ')" = "1" ]; then
     # Good.  We have a package that meets the Slackware spec.
@@ -737,11 +795,10 @@ EOF
     ( cd $ROOT/$INSTDIR ; rm -f do*inst.sh slack-* 1> /dev/null 2>&1 )
     rmdir $ROOT/$INSTDIR 1> /dev/null 2>&1
   fi
-  # If we used a scan directory, get rid of it:
-  if [ -d "$TMP/scan${MCOOKIE}" ]; then
-    rm -rf "$TMP/scan${MCOOKIE}"
+  # Either save or purge the remaining cookies:
+  if [ ! "$DONT_DELETE_COOKIES" = "true" ]; then
+    rm -f $TMP/*${MCOOKIE}
   fi
-  rm -f $TMP/tmpmsg${MCOOKIE} $TMP/reply${MCOOKIE}
   if [ "$MODE" = "install" ]; then
     echo "Package $(basename $package) installed."
   fi
