Fri Dec 13 22:59:13 UTC 2024
a/mkinitrd-1.4.11-x86_64-57.txz:  Rebuilt.
  setup.01.mkinitrd: improve sanity checking on the kernel file/symlink.
  Thanks to Mechanikx.
a/pkgtools-15.1-noarch-22.txz:  Rebuilt.
  make-kernel-backup: improve sanity checking on the kernel file/symlink.
  Thanks to Mechanikx.
l/libjpeg-turbo-3.1.0-x86_64-1.txz:  Upgraded.
l/mozjs128-128.5.2esr-x86_64-1.txz:  Upgraded.
l/pcaudiolib-1.3-x86_64-1.txz:  Upgraded.
l/python-versioneer-0.29-x86_64-1.txz:  Added.
xap/mozilla-firefox-128.5.2esr-x86_64-1.txz:  Upgraded.
  This is a bugfix release.
  For more information, see:
    https://www.mozilla.org/en-US/firefox/128.5.2/releasenotes/
xap/xsnow-3.8.1-x86_64-1.txz:  Upgraded.

diff --git a/source/a/pkgtools/scripts/make-kernel-backup b/source/a/pkgtools/scripts/make-kernel-backup
--- a/source/a/pkgtools/scripts/make-kernel-backup
+++ b/source/a/pkgtools/scripts/make-kernel-backup
@@ -69,11 +69,20 @@ fi
 # If we don't have KERNEL_FILE set by now, use this:
 KERNEL_FILE=${KERNEL_FILE:-/boot/vmlinuz-generic}
 
-# In case this is a symlink, find the real file:
-KERNEL_FILE=$(readlink -f $KERNEL_FILE)
+# In case this is a symlink, get the real file:
+if [ -L "$KERNEL_FILE" ]; then
+  if [ ! -e "$KERNEL_FILE" ]; then
+    echo "error: $KERNEL_FILE is not a valid symlink."
+    exit 1
+  fi
+elif [ ! -e "$KERNEL_FILE" ]; then
+  echo "error: $KERNEL_FILE does not exist."
+  exit 1
+fi
+KERNEL_FILE="$(readlink -f $KERNEL_FILE)"
 
 # Is this a Linux kernel?
-if ! file $KERNEL_FILE | grep -q "Linux kernel" ; then
+if ! file "$KERNEL_FILE" | grep -q "Linux kernel" ; then
   echo "ERROR: $KERNEL_FILE does not appear to be a Linux kernel."
   exit 1
 fi
