Tue Sep 10 21:28:36 UTC 2019
a/glibc-solibs-2.30-x86_64-1.txz:  Upgraded.
a/kernel-firmware-20190909_6c6918a-noarch-1.txz:  Upgraded.
a/kernel-generic-4.19.72-x86_64-1.txz:  Upgraded.
a/kernel-huge-4.19.72-x86_64-1.txz:  Upgraded.
a/kernel-modules-4.19.72-x86_64-1.txz:  Upgraded.
d/kernel-headers-4.19.72-x86-1.txz:  Upgraded.
k/kernel-source-4.19.72-noarch-1.txz:  Upgraded.
l/gdk-pixbuf2-2.38.2-x86_64-1.txz:  Upgraded.
l/glibc-2.30-x86_64-1.txz:  Upgraded.
l/glibc-i18n-2.30-x86_64-1.txz:  Upgraded.
l/glibc-profile-2.30-x86_64-1.txz:  Upgraded.
n/libmilter-8.15.2-x86_64-3.txz:  Rebuilt.
  Use gethostbyname2() since RES_USE_INET6 is removed in glibc-2.30.
n/libqmi-1.22.6-x86_64-1.txz:  Upgraded.
n/postfix-3.4.6-x86_64-2.txz:  Rebuilt.
  Patched to fix removed macros in glibc-2.30.
n/yptools-2.14-x86_64-12.txz:  Rebuilt.
  Patched ypbind-mt for gettid() included in glibc-2.30.
xap/blackbox-0.75-x86_64-1.txz:  Upgraded.
isolinux/initrd.img:  Rebuilt.
kernels/*:  Upgraded.
usb-and-pxe-installers/usbboot.img:  Rebuilt.

diff --git a/source/l/glibc/glibc.SlackBuild b/source/l/glibc/glibc.SlackBuild
--- a/source/l/glibc/glibc.SlackBuild
+++ b/source/l/glibc/glibc.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Copyright 2006, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2006, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,14 +20,12 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-## build glibc-$VERSION for Slackware
-
 cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=glibc
 VERSION=${VERSION:-$(echo glibc-*.tar.xz | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
 CHECKOUT=${CHECKOUT:-""}
-BUILD=${BUILD:-3}
+BUILD=${BUILD:-1}
 
 # I was considering disabling NSCD, but MoZes talked me out of it.  :)
 #DISABLE_NSCD=" --disable-nscd "
@@ -157,6 +155,10 @@ apply_patches() {
   zcat $CWD/glibc-c-utf8-locale.patch.gz | patch -p1 --verbose || exit 1
   # Don't use AM/PM format for date(1). That's just plain crazy.
   zcat $CWD/glibc-2.29.en_US.no.am.pm.date.format.diff.gz | patch -p1 --verbose || exit 1
+  # Other regression fixes from git:
+  for git_patch in $CWD/patches/*.patch.gz ; do
+    zcat $git_patch | patch -p1 --verbose || exit 1
+  done
 }
 
 # This is going to be the initial $DESTDIR:
@@ -195,31 +197,26 @@ mkdir -p $PKG/var/run/nscd
 cd $TMP
 rm -rf glibc-$CVSVER
 tar xvf $CWD/glibc-$CVSVER.tar.xz \
+  || tar xvf $CWD/glibc-$CVSVER.tar.lz \
   || tar xvf $CWD/glibc-$CVSVER.tar.bz2 \
   || tar xvf $CWD/glibc-$CVSVER.tar.gz
 cd glibc-$CVSVER
-
-chown -R root:root .
-find . -perm 666 -exec chmod 644 {} \;
-find . -perm 664 -exec chmod 644 {} \;
-find . -perm 600 -exec chmod 644 {} \;
-find . -perm 444 -exec chmod 644 {} \;
-find . -perm 400 -exec chmod 644 {} \;
-find . -perm 440 -exec chmod 644 {} \;
-find . -perm 777 -exec chmod 755 {} \;
-find . -perm 775 -exec chmod 755 {} \;
-find . -perm 511 -exec chmod 755 {} \;
-find . -perm 711 -exec chmod 755 {} \;
-find . -perm 555 -exec chmod 755 {} \;
-
-# Clean up leftover CVS directories:
-find . -type d -name CVS -exec rm -r {} \; 2> /dev/null
 
 # Apply patches; exit if any fail.
 apply_patches
 if [ ! $? = 0 ]; then
   exit 1
 fi
+
+# Clean up leftover CVS directories:
+find . -type d -name CVS -exec rm -r {} \; 2> /dev/null
+
+chown -R root:root .
+find . \
+  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
+  -exec chmod 755 {} \; -o \
+  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
+  -exec chmod 644 {} \;
 
 # Make build directory:
 mkdir build-glibc-$VERSION
