Thu Sep  6 23:22:45 UTC 2018
a/pkgtools-15.0-noarch-23.txz:  Rebuilt.
  Removed stray cat and loop kludges for lack of reported size, since this
  is fixed now in tar.
a/tar-1.30-x86_64-3.txz:  Rebuilt.
  Fixed a bug in the nolonezero patch that was evidently causing all of the
  issues in installpkg that we'd been kludging around (e.g. the "stray cat").
  Thanks *very* much to NonNonBa for the patch, and to SeB for the initial
  analysis of the problem.
ap/ghostscript-9.24-x86_64-2.txz:  Rebuilt.
  Applied upstream patch to fix "Filter failed". Thanks to th_r and bamunds.
d/gdb-8.2-x86_64-1.txz:  Upgraded.
d/indent-2.2.12-x86_64-1.txz:  Upgraded.
isolinux/initrd.img:  Rebuilt.
usb-and-pxe-installers/usbboot.img:  Rebuilt.

diff --git a/source/ap/ghostscript/ghostscript.SlackBuild b/source/ap/ghostscript/ghostscript.SlackBuild
--- a/source/ap/ghostscript/ghostscript.SlackBuild
+++ b/source/ap/ghostscript/ghostscript.SlackBuild
@@ -27,7 +27,7 @@ if [ -r gnu-ghostscript-*.tar.?z ]; then
   SRCPREFIX="gnu-"
 fi
 VERSION=${VERSION:-$(echo $SRCPREFIX$PKGNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -75,6 +75,9 @@ cd ${SRCPREFIX}${PKGNAM}-$VERSION || exit 1
 
 # Remove unmaintained garbage:
 rm -rf freetype jpeg lcms2 libpng libtiff png tiff zlib
+
+# Upstream patch to fix "Filter failed." issue:
+zcat $CWD/ghostscript.fix.filter.failed.bc3df077.patch.gz | patch -p1 --verbose || exit 1
 
 # Regenerate ./configure.  Needed if patched, or to prevent libtool mismatch.
 autoreconf --force --install
diff --git a/source/d/indent/indent.SlackBuild b/source/d/indent/indent.SlackBuild
--- a/source/d/indent/indent.SlackBuild
+++ b/source/d/indent/indent.SlackBuild
@@ -23,8 +23,8 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=indent
-VERSION=${VERSION:-2.2.10}
-BUILD=${BUILD:-2}
+VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
+BUILD=${BUILD:-1}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -65,7 +65,7 @@ mkdir -p $TMP $PKG
 
 cd $TMP
 rm -rf indent-$VERSION
-tar xvf $CWD/indent-$VERSION.tar.bz2 || exit 1
+tar xvf $CWD/indent-$VERSION.tar.?z || exit 1
 cd indent-$VERSION || exit 1
 chown -R root:root .
 find . \
@@ -90,13 +90,13 @@ CXXFLAGS="$SLKCFLAGS" \
 make $NUMJOBS || make || exit 1
 make install DESTDIR=$PKG || exit 1
 
-# I'm not sure why this man page fails, but...
-if find $PKG -type f -size 0c -name indent.1 ; then
-  ( cd man
-    ./texinfo2man ./indent.1.in ./../doc/indent.texinfo > indent.1
-    cat indent.1 > $PKG/usr/man/man1/indent.1
-  )
-fi
+## I'm not sure why this man page fails, but...
+#if find $PKG -type f -size 0c -name indent.1 ; then
+#  ( cd man
+#    ./texinfo2man ./indent.1.in ./../doc/indent.texinfo > indent.1
+#    cat indent.1 > $PKG/usr/man/man1/indent.1
+#  )
+#fi
 
 # Strip binaries and libraries:
 find $PKG | xargs file | grep -e "executable" -e "shared object" \
