Sat Dec 21 21:02:24 UTC 2019
a/kernel-generic-5.4.6-x86_64-1.txz:  Upgraded.
a/kernel-huge-5.4.6-x86_64-1.txz:  Upgraded.
a/kernel-modules-5.4.6-x86_64-1.txz:  Upgraded.
a/procps-ng-3.3.16-x86_64-2.txz:  Rebuilt.
  Patched to hardcode the pgrep command string buffer size to 4096 as was done
  in the previous release. This avoids an allocation error when the stack size
  is unlimited. Thanks to Jeroslaw Siebert.
a/xfsprogs-5.4.0-x86_64-1.txz:  Upgraded.
d/kernel-headers-5.4.6-x86-1.txz:  Upgraded.
k/kernel-source-5.4.6-noarch-1.txz:  Upgraded.
l/QScintilla-2.11.4-x86_64-1.txz:  Upgraded.
n/dhcpcd-8.1.4-x86_64-1.txz:  Upgraded.
n/lftp-4.9.0-x86_64-1.txz:  Upgraded.
xap/hexchat-2.14.3-x86_64-1.txz:  Upgraded.
isolinux/initrd.img:  Rebuilt.
kernels/*:  Upgraded.
usb-and-pxe-installers/usbboot.img:  Rebuilt.

diff --git a/source/a/procps-ng/procps-ng.SlackBuild b/source/a/procps-ng/procps-ng.SlackBuild
--- a/source/a/procps-ng/procps-ng.SlackBuild
+++ b/source/a/procps-ng/procps-ng.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Copyright 2005-2018  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2005-2019  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -27,7 +27,7 @@ VERSION=${VERSION:-3.3.16}
 PSMISCVER=${PSMISCVER:-23.3}
 PROCINFONGVER=${PROCINFONGVER:-2.0.304}
 PROCINFOVER=${PROCINFOVER:-18}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -80,6 +80,10 @@ find -L . \
   -o -perm 511 \) -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
+
+# Revert to hardcoded command string size from procps-ng-3.3.15, as the
+# newer stack-based allocation fails in some cases where ulimit is unlimited:
+zcat $CWD/procps-ng.pgrep.CMDSTRSIZE.diff.gz | patch -p1 --verbose || exit 1
 
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
