Fri Jun 21 00:44:39 UTC 2024
a/mcelog-200-x86_64-1.txz:  Upgraded.
a/shadow-4.16.0-x86_64-1.txz:  Upgraded.
d/llvm-18.1.8-x86_64-1.txz:  Upgraded.
  Build from git rather than individual tarballs (this simplifies things).
  Build additional projects: bolt, flang, mlir.
l/gmime-3.2.15-x86_64-1.txz:  Upgraded.
l/gst-plugins-bad-free-1.24.5-x86_64-1.txz:  Upgraded.
l/gst-plugins-base-1.24.5-x86_64-1.txz:  Upgraded.
l/gst-plugins-good-1.24.5-x86_64-1.txz:  Upgraded.
l/gst-plugins-libav-1.24.5-x86_64-1.txz:  Upgraded.
l/gstreamer-1.24.5-x86_64-1.txz:  Upgraded.
l/libclc-18.1.8-x86_64-1.txz:  Upgraded.
l/mujs-1.3.5-x86_64-1.txz:  Upgraded.
l/nodejs-20.15.0-x86_64-1.txz:  Upgraded.
l/python-importlib_metadata-7.2.0-x86_64-1.txz:  Upgraded.
l/qt6-6.7.2_20240610_3f005f1e-x86_64-1.txz:  Upgraded.
n/openvpn-2.6.11-x86_64-1.txz:  Upgraded.
x/libva-2.22.0-x86_64-1.txz:  Upgraded.
x/libva-utils-2.22.0-x86_64-1.txz:  Upgraded.

diff --git a/source/d/llvm/libclc.SlackBuild b/source/d/llvm/libclc.SlackBuild
--- a/source/d/llvm/libclc.SlackBuild
+++ b/source/d/llvm/libclc.SlackBuild
@@ -3,7 +3,7 @@
 # Slackware build script for libclc
 
 # Copyright 2016  Heinz Wiesinger, Amsterdam, The Netherlands
-# Copyright 2017, 2018, 2021  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2017, 2018, 2021, 2024  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -26,7 +26,7 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=libclc
-VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z | rev | cut -f 4- -d . | cut -f 1 -d - | rev)}
+VERSION=${VERSION:-$(echo llvmorg-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
 BUILD=${BUILD:-1}
 
 NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}
@@ -69,14 +69,23 @@ else
 fi
 
 TMP=${TMP:-/tmp}
-PKG=$TMP/package-libclc
+PKG=$TMP/package-$PKGNAM
+BUILDDIR=${TMP}/libclc-build-${VERSION}
 
-rm -rf $PKG
-mkdir -p $TMP $PKG
-cd $TMP
-rm -rf libclc-${VERSION}.src
-tar xvf $CWD/libclc-$VERSION.src.tar.?z || exit 1
-cd libclc-${VERSION}.src || exit 1
+rm -rf $PKG $BUILDDIR
+mkdir -p $TMP $PKG $BUILDDIR
+cd $BUILDDIR
+
+# Add a fake configure script so the cleanup script used here at Slackware
+# knows to delete this stuff later. Other folks can just ignore this... it
+# doesn't have any other purpose.
+touch configure
+chmod 755 configure
+
+echo "Extracting $CWD/llvmorg-$VERSION.tar.?z..."
+tar xf $CWD/llvmorg-$VERSION.tar.?z llvm-project-llvmorg-$VERSION/libclc || tar xf $CWD/llvmorg-$VERSION.tar.?z llvmorg-$VERSION/libclc || exit 1
+cd llvm-project-llvmorg-$VERSION/libclc || cd llvmorg-$VERSION/libclc || exit 1
+
 chown -R root:root .
 find . \
   \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
@@ -103,7 +112,8 @@ find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | gr
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
 mkdir -p $PKG/usr/doc/$PKGNAM-$VERSION
-cp -a *.TXT $PKG/usr/doc/$PKGNAM-$VERSION
+cp -a *.{txt,md,TXT,rst} $PKG/usr/doc/$PKGNAM-$VERSION
+rm -f $PKG/usr/doc/$PKGNAM-$VERSION/CMakeLists.txt
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
