Fri Sep 21 18:51:07 UTC 2018
a/eudev-3.2.6-x86_64-1.txz:  Upgraded.
a/glibc-solibs-2.28-x86_64-2.txz:  Upgraded.
a/grub-2.02-x86_64-3.txz:  Rebuilt.
  Patched to fix compatibility with recent xfsprogs. Thanks to Markus Wiesner.
a/kernel-generic-4.14.71-x86_64-1.txz:  Upgraded.
a/kernel-huge-4.14.71-x86_64-1.txz:  Upgraded.
a/kernel-modules-4.14.71-x86_64-1.txz:  Upgraded.
ap/opus-tools-0.2-x86_64-1.txz:  Upgraded.
ap/sqlite-3.25.1-x86_64-1.txz:  Upgraded.
d/icecream-20180905_cdc6ff8-x86_64-1.txz:  Upgraded.
d/kernel-headers-4.14.71-x86-1.txz:  Upgraded.
d/llvm-7.0.0-x86_64-1.txz:  Upgraded.
  Shared library .so-version bump.
k/kernel-source-4.14.71-noarch-1.txz:  Upgraded.
l/ffmpeg-3.4.4-x86_64-2.txz:  Rebuilt.
  Don't try to link with Samba since the latest version is not compatible.
l/glibc-2.28-x86_64-2.txz:  Upgraded.
  All packages have been patched where needed for glibc-2.28 and compile
  tested here. Thanks to nobodino for the help.
l/glibc-i18n-2.28-x86_64-2.txz:  Upgraded.
l/glibc-profile-2.28-x86_64-2.txz:  Upgraded.
l/gst-plugins-base-1.14.3-x86_64-1.txz:  Upgraded.
l/gst-plugins-good-1.14.3-x86_64-1.txz:  Upgraded.
l/gst-plugins-libav-1.14.3-x86_64-1.txz:  Upgraded.
l/gstreamer-1.14.3-x86_64-1.txz:  Upgraded.
l/imagemagick-6.9.10_11-x86_64-1.txz:  Upgraded.
l/libopusenc-0.2-x86_64-1.txz:  Added.
l/librsvg-2.44.3-x86_64-1.txz:  Upgraded.
l/opus-1.3_rc2-x86_64-1.txz:  Upgraded.
l/opusfile-0.11-x86_64-1.txz:  Upgraded.
l/soprano-2.9.4-x86_64-3.txz:  Rebuilt.
  Recompiled to drop virtuoso dependency.
l/virtuoso-ose-6.1.8-x86_64-9.txz:  Removed.
  Even KDE4 has migrated away from actually using this for anything. The last
  thing in Slackware that was dependent on it was Soprano, which has been
  recompiled to no longer use it.
n/postfix-3.3.1-x86_64-2.txz:  Rebuilt.
  Recompiled so that it quits whining about OpenSSL. Thanks to shastah.
x/mesa-18.2.1-x86_64-1.txz:  Upgraded.
  Compiled against llvm-7.0.0.
x/xf86-video-vmware-13.3.0-x86_64-2.txz:  Rebuilt.
  Recompiled against llvm-7.0.0.
x/xterm-336-x86_64-1.txz:  Upgraded.
extra/pure-alsa-system/ffmpeg-3.4.4-x86_64-2_alsa.txz:  Rebuilt.
  Don't try to link with Samba since the latest version is not compatible.
extra/pure-alsa-system/gst-plugins-good-1.14.3-x86_64-1_alsa.txz:  Upgraded.
isolinux/initrd.img:  Rebuilt.
kernels/*:  Upgraded.
usb-and-pxe-installers/usbboot.img:  Rebuilt.

diff --git a/source/d/llvm/llvm.SlackBuild b/source/d/llvm/llvm.SlackBuild
--- a/source/d/llvm/llvm.SlackBuild
+++ b/source/d/llvm/llvm.SlackBuild
@@ -27,9 +27,9 @@ cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=llvm
 VERSION=${VERSION:-$(echo llvm-*.tar.xz | rev | cut -f 4- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-2}
+BUILD=${BUILD:-1}
 
-NUMJOBS=${NUMJOBS:-" -j7 "}
+NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -101,11 +101,15 @@ cd ../
 # Support GCC built for i586-slackware-linux:
 zcat $CWD/clang.toolchains.i586.triple.diff.gz | patch -p1 --verbose || exit 1
 
-## This seems obsolete, so commenting it out:
-#
-## Use i586 $ARCH on 32-bit x86:
-#sed -r "/ifeq.*CompilerTargetArch/s#i386#i586#g" \
-#  -i projects/compiler-rt/make/platform/clang_linux.mk
+# As of clang-tools-extra-7.0.0 we get the following error on i586 or i686:
+# CMakeFiles/clangDaemon.dir/Trace.cpp.o:Trace.cpp:function std::unique_ptr<clang::clangd::trace::(anonymous namespace)::JSONTracer::JSONSpan, std::default_delete<clang::clangd::trace::(anonymous namespace)::JSONTracer::JSONSpan> >::~unique_ptr(): error: undefined reference to '__atomic_load_8'
+# Attempts to try to fix this have failed here, so for now we will not build
+# clangd to avoid the failure. Any help with a proper fix is appreciated.
+# I have not reported this upstream since I suspect that it's an artifact
+# of our convoluted build method.
+if [ $ARCH = i586 ] || [ $ARCH = i686 ]; then
+  zcat $CWD/clang-tools-extra.no.clangd.diff.gz | patch -p1 --verbose --backup --suffix=.orig || exit 1
+fi
 
 chown -R root:root .
 find . \
@@ -134,6 +138,7 @@ cd build
     -DCLANG_BUILD_SHARED_LIBS=ON \
     -DLLVM_BUILD_LLVM_DYLIB=ON \
     -DLLVM_LINK_LLVM_DYLIB=ON \
+    -DLLVM_USE_LINKER=gold \
     -DLLVM_ENABLE_RTTI=ON \
     -DLLVM_ENABLE_FFI=ON \
     -DLLVM_ENABLE_ASSERTIONS=OFF \
@@ -142,10 +147,37 @@ cd build
     -DCLANG_RESOURCE_DIR="../lib${LIBDIRSUFFIX}/clang/${VERSION}" \
     .. || exit 1
 
-  # breaks with one of the patches above. Maybe revisit later
+  # Breaks with one of the patches above. Maybe revisit later?
   # -DBUILD_SHARED_LIBS=ON \
 
-  make $NUMJOBS VERBOSE=1 || make || exit 1
+  # This seems to not like a parallel build, at least as of 7.0.0. I don't have
+  # days to wait for the compile though, so let's just smack it with a hammer
+  # fifty times before dropping back to a single-threaded build:
+  for index in $(seq 1 50) ; do
+    #make $NUMJOBS VERBOSE=1
+    make $NUMJOBS
+    ERR_RESULT=$?
+    if [ $ERR_RESULT = 0 ]; then
+      break
+    fi
+    echo "*** PARALLEL MAKE RESTART NUMBER $index"
+  done
+  if [ ! $ERR_RESULT = 0 ]; then
+    # Fifty more for the single thread:
+    for index in $(seq 1 50) ; do
+      #make VERBOSE=1
+      make
+      ERR_RESULT=$?
+      if [ $ERR_RESULT = 0 ]; then
+        break
+      fi
+      echo "*** NON-PARALLEL MAKE RESTART NUMBER $index"
+    done
+  fi
+  if [ ! $ERR_RESULT = 0 ]; then
+    exit 1
+  fi
+
   make install DESTDIR=$PKG || exit 1
 cd ..
 
