add LoongArch support

diff --git a/source/d/llvm/llvm.SlackBuild b/source/d/llvm/llvm.SlackBuild
--- a/source/d/llvm/llvm.SlackBuild
+++ b/source/d/llvm/llvm.SlackBuild
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -x
 
 # Slackware build script for llvm
 
@@ -35,6 +36,7 @@ if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
     i?86) ARCH=i586 ;;
     arm*) ARCH=arm ;;
+    loongarch64) ARCH=loongarch64 ;;
        *) ARCH=$( uname -m ) ;;
   esac
 fi
@@ -73,6 +75,9 @@ elif [ "$ARCH" = "i686" ]; then
 elif [ "$ARCH" = "x86_64" ]; then
   SLKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
+elif [ "$ARCH" = "loongarch64" ]; then
+  SLKCFLAGS="-O2 -fPIC"
+  LIBDIRSUFFIX="64"
 else
   SLKCFLAGS="-O2"
   LIBDIRSUFFIX=""
@@ -106,49 +111,56 @@ tar xvf $CWD/$PKGNAM-$VERSION.src.tar.xz || exit 1
 cd $PKGNAM-${VERSION}.src/tools || cd $PKGNAM-${VERSION}/tools || exit 1
   tar xvf $CWD/clang-$VERSION.src.tar.xz || exit 1
   mv clang-${VERSION} clang 2>/dev/null || mv clang-${VERSION}.src clang || exit 1
+  zcat $CWD/clang-14-add-loongarch64-support.patch.gz | patch -p1 --verbose || exit 1
+echo "============================= T n0"
   #tar xvf $CWD/flang-$VERSION.src.tar.xz || exit 1
   #mv flang-${VERSION} flang 2>/dev/null || mv flang-${VERSION}.src flang || exit 1
-  tar xvf $CWD/lldb-$VERSION.src.tar.xz || exit 1
-  mv lldb-${VERSION} lldb 2>/dev/null || mv lldb-${VERSION}.src lldb || exit 1
-  tar xvf $CWD/lld-$VERSION.src.tar.xz || exit 1
-  mv lld-${VERSION} lld 2>/dev/null || mv lld-${VERSION}.src lld || exit 1
+#  tar xvf $CWD/lldb-$VERSION.src.tar.xz || exit 1
+#  mv lldb-${VERSION} lldb 2>/dev/null || mv lldb-${VERSION}.src lldb || exit 1
+#  tar xvf $CWD/lld-$VERSION.src.tar.xz || exit 1
+#  mv lld-${VERSION} lld 2>/dev/null || mv lld-${VERSION}.src lld || exit 1
 cd ../
 
 cd tools/clang/tools || exit 1
-  tar xvf $CWD/clang-tools-extra-$VERSION.src.tar.xz || exit 1
-  mv clang-tools-extra-${VERSION} extra 2>/dev/null \
-    || mv clang-tools-extra-${VERSION}.src extra || exit 1
-  # HACK # Otherwise the build fails because files aren't found.
-  rm -rf $TMP/clang-tools-extra
-  cp -a extra $TMP/clang-tools-extra
+#  tar xvf $CWD/clang-tools-extra-$VERSION.src.tar.xz || exit 1
+#  mv clang-tools-extra-${VERSION} extra 2>/dev/null \
+#    || mv clang-tools-extra-${VERSION}.src extra || exit 1
+#  # HACK # Otherwise the build fails because files aren't found.
+#  rm -rf $TMP/clang-tools-extra
+#  cp -a extra $TMP/clang-tools-extra
 cd ../../../
 
 cd projects || exit 1
-  tar xvf $CWD/compiler-rt-$VERSION.src.tar.xz || exit 1
-  mv compiler-rt-${VERSION} compiler-rt 2>/dev/null || mv compiler-rt-${VERSION}.src compiler-rt || exit 1
-  tar xvf $CWD/openmp-$VERSION.src.tar.xz || exit 1
-  mv openmp-${VERSION} openmp 2>/dev/null || mv openmp-${VERSION}.src openmp || exit 1
-  tar xvf $CWD/libcxx-${VERSION}.src.tar.xz || exit 1
-  mv libcxx-${VERSION} libcxx 2>/dev/null || mv libcxx-${VERSION}.src libcxx || exit 1
-  tar xvf $CWD/libcxxabi-${VERSION}.src.tar.xz || exit 1
-  mv libcxxabi-${VERSION} libcxxabi 2>/dev/null || mv libcxxabi-${VERSION}.src libcxxabi || exit 1
-  tar xvf $CWD/polly-$VERSION.src.tar.xz || exit 1
-  mv polly-${VERSION} polly 2>/dev/null || mv polly-${VERSION}.src polly || exit 1
-  # We just need a header file from this...
-  tar xvf $CWD/libunwind-${VERSION}.src.tar.xz || exit 1
-  mv libunwind-${VERSION}.src libunwind || mv libunwind-${VERSION} libunwind || exit 1
+#  tar xvf $CWD/compiler-rt-$VERSION.src.tar.xz || exit 1
+#  mv compiler-rt-${VERSION} compiler-rt 2>/dev/null || mv compiler-rt-${VERSION}.src compiler-rt || exit 1
+#  tar xvf $CWD/openmp-$VERSION.src.tar.xz || exit 1
+#  mv openmp-${VERSION} openmp 2>/dev/null || mv openmp-${VERSION}.src openmp || exit 1
+#  tar xvf $CWD/libcxx-${VERSION}.src.tar.xz || exit 1
+#  mv libcxx-${VERSION} libcxx 2>/dev/null || mv libcxx-${VERSION}.src libcxx || exit 1
+#  tar xvf $CWD/libcxxabi-${VERSION}.src.tar.xz || exit 1
+#  mv libcxxabi-${VERSION} libcxxabi 2>/dev/null || mv libcxxabi-${VERSION}.src libcxxabi || exit 1
+#  tar xvf $CWD/polly-$VERSION.src.tar.xz || exit 1
+#  mv polly-${VERSION} polly 2>/dev/null || mv polly-${VERSION}.src polly || exit 1
+#  # We just need a header file from this...
+#  tar xvf $CWD/libunwind-${VERSION}.src.tar.xz || exit 1
+#  mv libunwind-${VERSION}.src libunwind || mv libunwind-${VERSION} libunwind || exit 1
 cd ../
 
 # Support GCC built for i586-slackware-linux:
 zcat $CWD/clang.toolchains.i586.triple.diff.gz | patch -p1 --verbose || exit 1
+echo "============================= T n1"
 
-# Hack to fix build with polly. Maybe we should just not use polly... ?
-zcat $CWD/llvm.polly.hack.diff.gz | patch -p1 --verbose || exit 1
+## Hack to fix build with polly. Maybe we should just not use polly... ?
+#zcat $CWD/llvm.polly.hack.diff.gz | patch -p1 --verbose || exit 1
+echo "============================= T n2"
 
 # We require libatomic on 32-bit platforms:
 if [ "$ARCH" = "i586" -o "$ARCH" = "i686" ]; then
   zcat $CWD/lldb.32-bit.link.libatomic.diff.gz | patch -p1 --verbose || exit 1
 fi
+
+zcat $CWD/llvm-14-add-loongarch64-support.patch.gz | patch -p2 --verbose || exit 1
+echo "============================= T n3"
 
 # Won't build without this. See https://github.com/llvm/llvm-project/issues/54941
 #zcat $CWD/llvm.bypass.broken.benchmarks.diff.gz | patch -p1 --verbose || exit 1
@@ -156,9 +168,9 @@ fi
 # These hackish links seem to be required...
 cd ..
 ln -sf */utils/gn/secondary/third-party .
-ln -sf */runtimes .
-ln -sf */projects/libcxx .
-ln -sf */projects/libcxxabi .
+#ln -sf */runtimes .
+#ln -sf */projects/libcxx .
+#ln -sf */projects/libcxxabi .
 cd -
 
 chown -R root:root .
@@ -176,8 +188,8 @@ cd build
   # Nuke LLVM libunwind as it conflicts with the one already on the system:
   rm -r ../projects/libunwind
   cmake -GNinja \
-    -DCMAKE_C_COMPILER="clang" \
-    -DCMAKE_CXX_COMPILER="clang++" \
+    -DCMAKE_C_COMPILER="gcc" \
+    -DCMAKE_CXX_COMPILER="g++" \
     -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
     -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
     -DCMAKE_INSTALL_PREFIX=/usr \
@@ -186,14 +198,14 @@ cd build
     -DLLVM_BUILD_LLVM_DYLIB=ON \
     -DLLVM_LINK_LLVM_DYLIB=ON \
     -DCLANG_LINK_CLANG_DYLIB=ON \
-    -DLLVM_USE_LINKER=gold \
     -DLLVM_ENABLE_RTTI=ON \
     -DLLVM_ENABLE_FFI=ON \
     -DLLVM_ENABLE_ASSERTIONS=OFF \
     -DLLVM_INSTALL_UTILS=ON \
     -DLLVM_BINUTILS_INCDIR=/usr/include \
     -DCLANG_RESOURCE_DIR="../lib${LIBDIRSUFFIX}/clang/${VERSION}" \
-    -DLLVM_TARGETS_TO_BUILD="host;AMDGPU;BPF" \
+    -DLLVM_TARGETS_TO_BUILD= \
+    -DLLVM_TARGET_ARCH=LoongArch \
     -DLLDB_USE_SYSTEM_SIX=1 \
     -DLLVM_INCLUDE_BENCHMARKS=OFF \
     -DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
diff --git a/source/l/glibc/glibc.SlackBuild b/source/l/glibc/glibc.SlackBuild
--- a/source/l/glibc/glibc.SlackBuild
+++ b/source/l/glibc/glibc.SlackBuild
@@ -36,6 +36,7 @@ if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
     i?86) export ARCH=i586 ;;
     arm*) export ARCH=arm ;;
+    loongarch64) export ARCH=loongarch64 ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
   esac
@@ -95,6 +96,10 @@ case $ARCH  in
     OPTIMIZ="-O3 -fPIC"
     LIBDIRSUFFIX="64"
     ;;
+  loongarch64)
+    OPTIMIZ="-O3 -fPIC"
+    LIBDIRSUFFIX="64"
+    ;;
   *)
     OPTIMIZ="-O3"
     LIBDIRSUFFIX=""
@@ -104,6 +109,9 @@ esac
 case $ARCH in
   x86_64)
     TARGET=${TARGET:-x86_64}
+    ;;
+  loongarch64)
+    TARGET=${TARGET:-loongarch64}
     ;;
   i586)
     # This should be i586 for all 32-bit x86 arch:
@@ -143,21 +151,21 @@ fix_doinst() {
   fi
 }
 
-# This is a patch function to put all glibc patches in the build script
-# up near the top.
-apply_patches() {
-  # Use old-style locale directories rather than a single (and strangely
-  # formatted) /usr/lib/locale/locale-archive file:
-  zcat $CWD/glibc.locale.no-archive.diff.gz | patch -p1 --verbose || exit 1
-  # Support ru_RU.CP1251 locale:
-  zcat $CWD/glibc.ru_RU.CP1251.diff.gz | patch -p1 --verbose || exit 1
-  # Don't use AM/PM format for date(1). That's just plain crazy.
-  zcat $CWD/glibc-2.32.en_US.no.am.pm.date.format.diff.gz | patch -p1 --verbose || exit 1
-  # Other regression fixes from git:
-  for git_patch in $CWD/patches/*.patch.gz ; do
-    zcat $git_patch | patch -p1 --verbose || exit 1
-  done
-}
+## This is a patch function to put all glibc patches in the build script
+## up near the top.
+#apply_patches() {
+#  # Use old-style locale directories rather than a single (and strangely
+#  # formatted) /usr/lib/locale/locale-archive file:
+#  zcat $CWD/glibc.locale.no-archive.diff.gz | patch -p1 --verbose || exit 1
+#  # Support ru_RU.CP1251 locale:
+#  zcat $CWD/glibc.ru_RU.CP1251.diff.gz | patch -p1 --verbose || exit 1
+#  # Don't use AM/PM format for date(1). That's just plain crazy.
+#  zcat $CWD/glibc-2.32.en_US.no.am.pm.date.format.diff.gz | patch -p1 --verbose || exit 1
+#  # Other regression fixes from git:
+#  for git_patch in $CWD/patches/*.patch.gz ; do
+#    zcat $git_patch | patch -p1 --verbose || exit 1
+#  done
+#}
 
 # This is going to be the initial $DESTDIR:
 export PKG=$TMP/package-glibc-incoming-tree
@@ -200,11 +208,11 @@ tar xvf $CWD/glibc-$CVSVER.tar.xz \
   || tar xvf $CWD/glibc-$CVSVER.tar.gz
 cd glibc-$CVSVER
 
-# Apply patches; exit if any fail.
-apply_patches
-if [ ! $? = 0 ]; then
-  exit 1
-fi
+## Apply patches; exit if any fail.
+#apply_patches
+#if [ ! $? = 0 ]; then
+#  exit 1
+#fi
 
 # Clean up leftover CVS directories:
 find . -type d -name CVS -exec rm -r {} \+ 2> /dev/null
@@ -225,12 +233,13 @@ echo "BUILDING DAS NPTL GLIBC"
 # in shared libraries. Without this, glibc compiled with -march= may not
 # run on some CPUs that it should be able to support. Needed for glibc-2.33.
 # FIXME: revisit this with future glibc releases!
-libc_cv_include_x86_isa_level=no \
+#libc_cv_include_x86_isa_level=no \
 CFLAGS="-g $OPTIMIZ" \
 ../configure \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --enable-kernel=2.6.32 \
+  --disable-multi-arch \
   --with-headers=/usr/include \
   --enable-add-ons \
   --enable-profile \
@@ -419,7 +428,8 @@ cp -a $PKG/lib${LIBDIRSUFFIX}/* lib${LIBDIRSUFFIX}
   # and does no good since we'll never have multiple $ARCH libraries
   # installed in the same directory anyway. So give it the previous name
   # format:
-  mv ld-linux*-${VERSION}.so ld-${VERSION}.so
+  #mv ld-linux*-${VERSION}.so ld-${VERSION}.so
+  cp -rfa ld-linux*-${VERSION}.so ld-${VERSION}.so
 )
 mkdir -p usr
 cp -a $PKG/usr/bin usr
diff --git a/source/l/libwmf/libwmf.SlackBuild b/source/l/libwmf/libwmf.SlackBuild
--- a/source/l/libwmf/libwmf.SlackBuild
+++ b/source/l/libwmf/libwmf.SlackBuild
@@ -31,6 +31,7 @@ if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
     i?86) export ARCH=i586 ;;
     arm*) export ARCH=arm ;;
+    loongarch64) export ARCH=loongarch64 ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
   esac
@@ -51,6 +52,9 @@ elif [ "$ARCH" = "s390" ]; then
   SLKCFLAGS="-O2"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-O2 -fPIC"
+  LIBDIRSUFFIX="64"
+elif [ "$ARCH" = "loongarch64" ]; then
   SLKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
 else
@@ -78,6 +82,7 @@ find . \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \+
 
+cp -rfa /usr/share/autoconf/build-aux/config.* .
 CFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/usr \
@@ -97,13 +102,13 @@ rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
   cat $CWD/fontmap > fontmap
   rm *.afm *.t1
   # Link to system fonts:
-  for file in n019003l.afm n019003l.pfb n019004l.afm n019004l.pfb n019023l.afm n019023l.pfb n019024l.afm n019024l.pfb n021003l.afm n021003l.pfb n021004l.afm n021004l.pfb n021023l.afm n021023l.pfb n021024l.afm n021024l.pfb n022003l.afm n022003l.pfb n022004l.afm n022004l.pfb n022023l.afm n022023l.pfb n022024l.afm n022024l.pfb s050000l.afm s050000l.pfb ; do
-    if [ ! -r /usr/share/fonts/Type1/$file ]; then
-      echo "FONT $file NOT FOUND ON SYSTEM"
-      exit 1
-    fi
-    ln -sf ../../fonts/Type1/$file .
-  done || exit 1
+#  for file in n019003l.afm n019003l.pfb n019004l.afm n019004l.pfb n019023l.afm n019023l.pfb n019024l.afm n019024l.pfb n021003l.afm n021003l.pfb n021004l.afm n021004l.pfb n021023l.afm n021023l.pfb n021024l.afm n021024l.pfb n022003l.afm n022003l.pfb n022004l.afm n022004l.pfb n022023l.afm n022023l.pfb n022024l.afm n022024l.pfb s050000l.afm s050000l.pfb ; do
+#    if [ ! -r /usr/share/fonts/Type1/$file ]; then
+#      echo "FONT $file NOT FOUND ON SYSTEM"
+#      exit 1
+#    fi
+#    ln -sf ../../fonts/Type1/$file .
+#  done || exit 1
 ) || exit 1
 
 find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
