Thu Dec 14 18:33:00 UTC 2023
ap/sudo-1.9.15p3-x86_64-1.txz:  Upgraded.
l/PyQt-builder-1.15.4-x86_64-1.txz:  Added.
l/PyQt5-5.15.10-x86_64-1.txz:  Upgraded.
l/PyQt5_sip-12.13.0-x86_64-1.txz:  Added.
l/QScintilla-2.14.1-x86_64-1.txz:  Upgraded.
l/SDL2_image-2.8.1-x86_64-1.txz:  Upgraded.
l/sip-6.8.1-x86_64-1.txz:  Upgraded.
x/mesa-23.3.1-x86_64-1.txz:  Upgraded.

diff --git a/source/l/QScintilla/QScintilla.SlackBuild b/source/l/QScintilla/QScintilla.SlackBuild
--- a/source/l/QScintilla/QScintilla.SlackBuild
+++ b/source/l/QScintilla/QScintilla.SlackBuild
@@ -1,9 +1,7 @@
 #!/bin/sh
 
-# Slackware build script for QScintilla
-
 # Copyright 2008  Robby Workman <rworkman@slackware.com> Northport, AL, USA
-# Copyright 2008, 2009, 2010, 2011, 2012, 2018, 2019  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2008, 2009, 2010, 2011, 2012, 2018, 2019, 2023  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -28,8 +26,9 @@
 cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=QScintilla
-VERSION=${VERSION:-$(echo ${PKGNAM}-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-5}
+SRCNAM=QScintilla_src
+VERSION=${VERSION:-$(echo ${SRCNAM}-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
+BUILD=${BUILD:-1}
 
 NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}
 
@@ -75,12 +74,9 @@ fi
 rm -rf $PKG
 mkdir -p $TMP $PKG
 cd $TMP
-rm -rf ${PKGNAM}-$VERSION
-tar xvf $CWD/${PKGNAM}-$VERSION.tar.?z || exit 1
-cd ${PKGNAM}-$VERSION || exit 1
-
-# Fix compilation:
-zcat $CWD/QScintilla_qsciscintillabase_qurl.diff.gz | patch -p1 --verbose || exit 1
+rm -rf ${SRCNAM}-$VERSION
+tar xvf $CWD/${SRCNAM}-$VERSION.tar.?z || exit 1
+cd ${SRCNAM}-$VERSION || exit 1
 
 chown -R root:root .
 find . \
@@ -89,69 +85,56 @@ find . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \+
 
+# Prevent Qsci from failing to generate the bindings:
+export LD_LIBRARY_PATH=$TMP/${SRCNAM}-$VERSION/src
+
 # Define QMAKEFEATURES to that we can re-use already built libs
 # without spamming the harddisk:
-export QMAKEFEATURES=${PWD}/Qt4Qt5/features/
+export QMAKEFEATURES=${PWD}/src/features/
+cd src
+qmake-qt5
+make $NUMJOBS || exit 1
 
-# Conditional build of Qt5 support:
-if qtpaths-qt5 --qt-version 1>/dev/null 2>/dev/null ; then
-  echo "-- Compiling Qt5 support --"
-  # QT5 support first:
-  cd Qt4Qt5
-    echo "-- >> Qt4Qt5 --"
-    qmake-qt5 \
-      -o Makefile \
-      QMAKE_CFLAGS+="$SLKCFLAGS" \
-      QMAKE_CXXFLAGS+="$SLKCFLAGS -std=c++11" \
-      qscintilla.pro || exit 1
-    make $NUMJOBS || exit 1
-    make install DESTDIR=$PKG INSTALL_ROOT=$PKG || exit 1
-  cd -
+cd ../designer
+qmake-qt5 INCLUDEPATH+=../src QMAKE_LIBDIR+=../src
+make $NUMJOBS || exit 1
 
-  cd designer-Qt4Qt5
-    echo "-- >> designer-Qt4Qt5 --"
-    qmake-qt5 \
-      -o Makefile \
-      INCLUDEPATH+=../Qt4Qt5 QMAKE_LIBDIR+=../Qt4Qt5 \
-      QMAKE_CFLAGS+="$SLKCFLAGS" \
-      QMAKE_CXXFLAGS+="$SLKCFLAGS -std=c++11" \
-      designer.pro || exit 1
-    make $NUMJOBS || exit 1
-    make install DESTDIR=$PKG INSTALL_ROOT=$PKG || exit 1
-  cd -
+cd ../Python
+mv pyproject-qt5.toml pyproject.toml
+sip-build \
+  --no-make \
+  --qsci-features-dir ../src/features \
+  --qsci-include-dir ../src \
+  --qsci-library-dir ../src \
+  --api-dir /usr/share/qt5/qsci/api/python || exit 1
+cd build
+make $NUMJOBS || exit 1
 
-  cd Python
-    echo "-- >> Python --"
-    python3 configure.py \
-      --verbose \
-      --qmake /usr/bin/qmake-qt5 \
-      --pyqt=PyQt5 \
-      -n ../Qt4Qt5/ -o ../Qt4Qt5/ -c \
-      || exit 1
-    make  || exit 1
-    make -j1 install DESTDIR=$PKG INSTALL_ROOT=$PKG || exit 1
-
-    make clean || exit 1
-    ## No Qt5 python2 support!
-    #python2 configure.py \
-    #  --verbose \
-    #  --qmake /usr/bin/qmake-qt5 \
-    #  --pyqt=PyQt5 \
-    #  -n ../Qt4Qt5/ -o ../Qt4Qt5/ -c \
-    #  || exit 1
-    #make  || exit 1
-    #make -j1 install DESTDIR=$PKG INSTALL_ROOT=$PKG || exit 1
-  cd -
-fi
+# Install:
+cd ../src
+make DESTDIR=$PKG INSTALL_ROOT=$PKG install || exit 1
+cd ../designer
+make DESTDIR=$PKG INSTALL_ROOT=$PKG install || exit 1
+cd ../Python/build
+make DESTDIR=$PKG INSTALL_ROOT=$PKG install || exit 1
+cd ../..
 
 find $PKG | xargs file | grep -e "executable" -e "shared object" \
   | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 
 mkdir -p $PKG/usr/doc/$PKGNAM-$VERSION
 cp -a \
-  LICENSE NEWS README* \
-  doc/html-Qt4Qt5 doc/Scintilla \
+  LICENSE* NEWS* README* \
+  doc/README.doc doc/Scintilla doc/html \
   $PKG/usr/doc/$PKGNAM-$VERSION
+
+# If there's a ChangeLog, installing at least part of the recent history
+# is useful, but don't let it get totally out of control:
+if [ -r ChangeLog ]; then
+  DOCSDIR=$(echo $PKG/usr/doc/${PKGNAM}-$VERSION)
+  cat ChangeLog | head -n 1000 > $DOCSDIR/ChangeLog
+  touch -r ChangeLog $DOCSDIR/ChangeLog
+fi
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
