Tue Mar 10 19:53:39 UTC 2020
d/guile-3.0.1-x86_64-1.txz:  Upgraded.
l/SDL2-2.0.10-x86_64-2.txz:  Rebuilt.
  Rebuilt to pick up wayland support. Thanks to franzen.
l/dconf-0.36.0-x86_64-1.txz:  Upgraded.
l/dconf-editor-3.36.0-x86_64-1.txz:  Upgraded.
l/gsettings-desktop-schemas-3.36.0-x86_64-1.txz:  Upgraded.
l/python-pygments-2.5.2-x86_64-1.txz:  Upgraded.
  It seems like the pragmatic thing to do here is to revert this one to fix
  the python2 programs and modules that depend on it. We'll have to do a bit
  more research to determine what the best course of action is regarding
  python2 in general, though. Certainly we shouldn't be requiring python2
  for anything important moving forward, but even that will take some work.
  Plasma 5 as currently built has multiple dependencies on python2, for
  example.
n/bind-9.16.0-x86_64-4.txz:  Rebuilt.
  Drop python2 support and switch to python3.
x/liberation-fonts-ttf-2.1.0-noarch-1.txz:  Upgraded.
xap/mozilla-firefox-68.6.0esr-x86_64-1.txz:  Upgraded.
  This release contains security fixes and improvements.
  For more information, see:
    https://www.mozilla.org/en-US/firefox/68.6.0/releasenotes/
    https://www.mozilla.org/security/advisories/mfsa2020-09/
    https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-6805
    https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-6806
    https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-6807
    https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-6811
    https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-20503
    https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-6812
    https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-6814
  (* Security fix *)

diff --git a/source/l/SDL2/SDL2.SlackBuild b/source/l/SDL2/SDL2.SlackBuild
--- a/source/l/SDL2/SDL2.SlackBuild
+++ b/source/l/SDL2/SDL2.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Copyright 2017, 2018, 2019  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2017, 2018, 2019, 2020  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -24,7 +24,7 @@ cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=SDL2
 VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -84,6 +84,9 @@ find . \
   -exec chmod 755 {} \+ -o \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \+
+
+# Fix video-opengles1 build failure:
+zcat $CWD/SDL2-2.0.9-khrplatform.patch.gz | patch -p1 --verbose || exit 1
 
 # Configure:
 CFLAGS="$SLKCFLAGS" \
