Thu Jan 19 21:07:32 UTC 2023
a/pkgtools-15.1-noarch-4.txz:  Rebuilt.
  makepkg: also let xz decide how many threads to use on ARM platforms aarch64
  and riscv64. Thanks to Stuart Winter.
  installpkg: fix reversed test for if a --threads option was given. It appears
  that it's been wrong for years but since xz didn't support threaded
  decompression yet it wasn't noticed.
a/xz-5.4.1-x86_64-2.txz:  Rebuilt.
  Reduce default verbosity from V_WARNING to V_ERROR to avoid sending non-fatal
  memory usage information to stderr.
kde/plasma-wayland-protocols-1.10.0-x86_64-1.txz:  Upgraded.
l/exiv2-0.27.6-x86_64-1.txz:  Upgraded.
l/tdb-1.4.8-x86_64-1.txz:  Upgraded.
x/igt-gpu-tools-1.27.1-x86_64-1.txz:  Upgraded.
x/libX11-1.8.3-x86_64-2.txz:  Rebuilt.
  [PATCH] Fix a9e845 and 797755 Allow X*IfEvent() to reenter libX11
  Thanks to marav.

diff --git a/source/a/xz/xz.SlackBuild b/source/a/xz/xz.SlackBuild
--- a/source/a/xz/xz.SlackBuild
+++ b/source/a/xz/xz.SlackBuild
@@ -24,7 +24,7 @@ cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=xz
 VERSION=${VERSION:-$(echo $PKGNAM-*.tar.xz | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -88,6 +88,11 @@ find . \
   -exec chmod 755 {} \+ -o \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \+
+
+# Change default verbosity from V_WARNING to V_ERROR to prevent spamming
+# the screen with messages concerning steps that xz it taking to reduce
+# memory use (these aren't indicating any sort of failure, so...)
+zcat $CWD/xz.default.verbosity.V_ERROR.diff.gz | patch -p1 --verbose || exit 1
 
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
