Thu Oct 28 01:11:07 UTC 2021
a/kernel-generic-5.14.15-x86_64-1.txz:  Upgraded.
a/kernel-huge-5.14.15-x86_64-1.txz:  Upgraded.
a/kernel-modules-5.14.15-x86_64-1.txz:  Upgraded.
d/cmake-3.21.4-x86_64-1.txz:  Upgraded.
d/kernel-headers-5.14.15-x86-1.txz:  Upgraded.
k/kernel-source-5.14.15-noarch-1.txz:  Upgraded.
  We're going to go ahead and take both of those changes that were considered
  in /testing. GazL almost had me talked out of the autogroup change, but it's
  easy to disable if traditional "nice" behavior is important to someone.
  -DRM_I810 n
  -INLINE_READ_UNLOCK y
  -INLINE_READ_UNLOCK_IRQ y
  -INLINE_SPIN_UNLOCK_IRQ y
  -INLINE_WRITE_UNLOCK y
  -INLINE_WRITE_UNLOCK_IRQ y
   PREEMPT n -> y
   PREEMPT_VOLUNTARY y -> n
   SCHED_AUTOGROUP n -> y
  +CEC_GPIO n
  +DEBUG_PREEMPT y
  +PREEMPTION y
  +PREEMPT_COUNT y
  +PREEMPT_DYNAMIC y
  +PREEMPT_RCU y
  +PREEMPT_TRACER n
  +RCU_BOOST n
  +TASKS_RCU y
  +UNINLINE_SPIN_UNLOCK y
kde/plasma-desktop-5.23.2.1-x86_64-1.txz:  Upgraded.
l/imagemagick-7.1.0_12-x86_64-1.txz:  Upgraded.
l/librsvg-2.52.3-x86_64-1.txz:  Upgraded.
n/bind-9.16.22-x86_64-1.txz:  Upgraded.
  This update fixes bugs and the following security issue:
  The "lame-ttl" option is now forcibly set to 0. This effectively disables
  the lame server cache, as it could previously be abused by an attacker to
  significantly degrade resolver performance.
  For more information, see:
    https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-25219
  (* Security fix *)
n/c-ares-1.18.1-x86_64-1.txz:  Upgraded.
n/samba-4.15.1-x86_64-1.txz:  Upgraded.
isolinux/initrd.img:  Rebuilt.
kernels/*:  Upgraded.
usb-and-pxe-installers/usbboot.img:  Rebuilt.

diff --git a/source/k/kernel-source.SlackBuild b/source/k/kernel-source.SlackBuild
--- a/source/k/kernel-source.SlackBuild
+++ b/source/k/kernel-source.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2018, 2020  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2018, 2020, 2021  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -27,6 +27,9 @@ BUILD=${BUILD:-1}
 NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-$PKGNAM
+# If CONFIG_PREEMPT=y and CONFIG_PREEMPT_DYNAMIC=y, then set a default preempt
+# mode (none, voluntary, or full):
+CONFIG_PREEMPT_DEFAULT_MODE=${CONFIG_PREEMPT_DEFAULT_MODE:-none}
 
 # If a $VERSION is not passed to this script, use the newest linux-*.tar.xz
 # found in this directory:
@@ -145,6 +148,21 @@ echo "Untarring $CWD/linux-${VERSION}.tar.?z in $PKG/usr/src..."
     echo "Saving new .config as: $CWD/kernel-configs/config-generic${LOCALVERSION}-${VERSION}${LOCALVERSION}${CONFIG_SUFFIX}"
     cp -a .config $CWD/kernel-configs/config-generic${LOCALVERSION}-${VERSION}${LOCALVERSION}${CONFIG_SUFFIX}
   fi
+
+  # If CONFIG_PREEMPT=y and CONFIG_PREEMPT_DYNAMIC=y, then set a default preempt
+  # mode (none, voluntary, or full):
+  if grep -wq CONFIG_PREEMPT=y .config ; then
+    if grep -wq CONFIG_PREEMPT_DYNAMIC=y .config ; then
+      # Sanity check:
+      if ! echo $CONFIG_PREEMPT_DEFAULT_MODE | grep -wq -e none -e voluntary -e full ; then
+        echo "ERROR: Invalid mode for CONFIG_PREEMPT_DEFAULT_MODE: $CONFIG_PREEMPT_DEFAULT_MODE"
+        exit 1
+      fi
+      echo "Setting default PREEMPT mode: $CONFIG_PREEMPT_DEFAULT_MODE"
+      sed -i "s/^int preempt_dynamic_mode = preempt_dynamic_full;$/int preempt_dynamic_mode = preempt_dynamic_$CONFIG_PREEMPT_DEFAULT_MODE;/g" kernel/sched/core.c
+    fi
+  fi
+
   echo "Building kernel and modules (needed before clean for building NVIDIA to work)..."
   make ${NUMJOBS} || exit 1
   make ${NUMJOBS} modules || exit 1
