Fri Jan  3 19:03:30 UTC 2025
a/aaa_libraries-15.1-x86_64-37.txz:  Rebuilt.
  Added: libassuan.so.9.0.1.
  Prevent slackpkg+ abandonware footbullet (at least some forms of it).
a/hwdata-0.391-noarch-1.txz:  Upgraded.
a/mdadm-4.4-x86_64-2.txz:  Rebuilt.
  Fixed empty mdadm.conf.new. Thanks to Robby Workman.
l/zxing-cpp-2.3.0-x86_64-1.txz:  Upgraded.
testing/packages/mesa-24.3.3-x86_64-1.txz:  Upgraded.
  Is this working yet?

diff --git a/source/a/mdadm/mdadm.SlackBuild b/source/a/mdadm/mdadm.SlackBuild
--- a/source/a/mdadm/mdadm.SlackBuild
+++ b/source/a/mdadm/mdadm.SlackBuild
@@ -24,7 +24,7 @@ cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=mdadm
 VERSION=${VERSION:-$(echo mdadm-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -100,7 +100,12 @@ if [ -d $PKG/usr/man ]; then
 fi
 
 mkdir -p $PKG/etc
-cat mdadm.conf-example > $PKG/etc/mdadm.conf.new
+if [ -r documentation/mdadm.conf-example ]; then
+  cat documentation/mdadm.conf-example > $PKG/etc/mdadm.conf.new
+else
+  echo "documentation/mdadm.conf-example not found"
+  exit 1
+fi
 
 mkdir -p $PKG/usr/doc/mdadm-$VERSION
 cp -a \
