Fri Apr 12 19:08:59 UTC 2024
a/less-653-x86_64-1.txz:  Upgraded.
d/ninja-1.12.0-x86_64-1.txz:  Upgraded.
d/valgrind-3.22.0-x86_64-1.txz:  Added.
  Thanks to Kyle Guinn, Peter Wang, and Willy Sudiarto Raharjo.
l/netpbm-11.06.01-x86_64-1.txz:  Upgraded.
n/php-8.3.6-x86_64-1.txz:  Upgraded.
  This update fixes bugs and security issues.
  For more information, see:
    https://www.php.net/ChangeLog-8.php#8.3.6
  (* Security fix *)

diff --git a/source/d/valgrind/valgrind.SlackBuild b/source/d/valgrind/valgrind.SlackBuild
--- a/source/d/valgrind/valgrind.SlackBuild
+++ b/source/d/valgrind/valgrind.SlackBuild
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-# Copyright 2005-2024  Patrick J. Volkerding, Sebeka, MN, USA
+# Written by Kyle Guinn <elyk03@gmail.com>
+# Updated by Peter Wang <novalazy@gmail.com>
+# Updated by Willy Sudiarto Raharjo <willysr@slackbuilds.org>
+# Copyright 2024  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -22,18 +25,19 @@
 
 cd $(dirname $0) ; CWD=$(pwd)
 
-PKGNAM=less
-VERSION=${VERSION:-$(echo less-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
+PKGNAM=valgrind
+VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
 BUILD=${BUILD:-1}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
-  case "$( uname -m )" in
-    i?86) export ARCH=i586 ;;
-    arm*) export ARCH=arm ;;
+  case "$(uname -m)" in
+    i?86) ARCH=i586 ;;
+    arm*) readelf /usr/bin/file -A | egrep -q "Tag_CPU.*[4,5]" && ARCH=arm || ARCH=armv7hl ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
-       *) export ARCH=$( uname -m ) ;;
+    *) ARCH=$(uname -m) ;;
   esac
+  export ARCH
 fi
 
 # If the variable PRINT_PACKAGE_NAME is set, then this script will report what
@@ -44,19 +48,24 @@ if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   exit 0
 fi
 
-NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}
+NUMJOBS=${NUMJOBS:-" -j $(expr $(nproc) + 1) "}
 
 if [ "$ARCH" = "i586" ]; then
   SLKCFLAGS="-O2 -march=i586 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-O2 -march=i686"
+  LIBDIRSUFFIX=""
 elif [ "$ARCH" = "s390" ]; then
   SLKCFLAGS="-O2"
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
-elif [ "$ARCH" = "arm" ]; then
-  SLKCFLAGS="-O2 -march=armv4 -mtune=xscale"
   LIBDIRSUFFIX=""
-elif [ "$ARCH" = "armel" ]; then
-  SLKCFLAGS="-O2 -march=armv4t"
+elif [ "$ARCH" = "x86_64" ]; then
+  # The valgrind build system already passes -fpic
+  # and forcing -fPIC results in a build failure.
+  SLKCFLAGS="-O2"
+  LIBDIRSUFFIX="64"
+elif [ "$ARCH" = "armv7hl" ]; then
+  SLKCFLAGS="-O3 -march=armv7-a -mfpu=vfpv3-d16"
   LIBDIRSUFFIX=""
 else
   SLKCFLAGS="-O2"
@@ -64,19 +73,15 @@ else
 fi
 
 TMP=${TMP:-/tmp}
-PKG=$TMP/package-less
+PKG=$TMP/package-$PKGNAM
+
 rm -rf $PKG
 mkdir -p $TMP $PKG
 
 cd $TMP
-rm -rf less-$VERSION
-tar xvf $CWD/less-$VERSION.tar.?z || exit 1
-cd less-$VERSION || exit 1
-
-# Fix path in manpage:
-if [ -r less.nro ]; then
-  sed -i "s,/usr/local/etc,/etc,g" less.nro
-fi
+rm -rf $PKGNAM-$VERSION
+tar xvf $CWD/$PKGNAM-$VERSION.tar.?z || exit 1
+cd $PKGNAM-$VERSION || exit 1
 
 chown -R root:root .
 find . \
@@ -85,6 +90,7 @@ find . \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \+
 
+# Configure, build, and install:
 if [ ! -r configure ]; then
   if [ -x ./autogen.sh ]; then
     NOCONFIGURE=1 ./autogen.sh
@@ -92,60 +98,47 @@ if [ ! -r configure ]; then
     autoreconf -vif
   fi
 fi
-
-# Prep needed if using the git archive:
-for file in funcs.h less.nro lesskey.nro lessecho.nro ; do
-  if [ ! -r $file ]; then
-    make -f Makefile.aut $file
-  fi
-done
-
 CFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/usr \
+  --libdir=/usr/lib${LIBDIRSUFFIX} \
   --sysconfdir=/etc \
-  --mandir=/usr/man || exit 1
-
+  --localstatedir=/var \
+  --docdir=/usr/doc/$PKGNAM-$VERSION \
+  --mandir=/usr/man \
+  --build=$ARCH-slackware-linux || exit 1
 make $NUMJOBS || make || exit 1
 make install DESTDIR=$PKG || exit 1
 
-zcat $CWD/lesspipe.sh.gz > $PKG/usr/bin/lesspipe.sh
-chmod 755 $PKG/usr/bin/lesspipe.sh
+# Don't ship .la files:
+rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
 
-# Compress and link manpages, if any:
-if [ -d $PKG/usr/man ]; then
-  ( cd $PKG/usr/man
-    for manpagedir in $(find . -type d -name "man*") ; do
-      ( cd $manpagedir
-        for eachpage in $( find . -type l -maxdepth 1 | grep -v '\.gz$') ; do
-          ln -s $( readlink $eachpage ).gz $eachpage.gz
-          rm $eachpage
-        done
-        gzip -9 *.?
-      )
-    done
-  )
-fi
+# Strip executables, but do NOT strip the shared objects, as recommended by the developers:
+find $PKG | xargs file | grep -e "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 
-( cd $PKG
-  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
-  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
-)
-
-mkdir -p $PKG/usr/doc/less-$VERSION
-cp -a \
-  COPYING* LICENSE README NEWS \
-  $PKG/usr/doc/less-$VERSION
-
-mkdir -p $PKG/usr/man/man1
-for page in less.nro lesskey.nro ; do
-  cat $page | gzip -9c > $PKG/usr/man/man1/`basename $page .nro`.1.gz
+# Compress manual pages:
+find $PKG/usr/man -type f -exec gzip -9 {} \+
+for i in $( find $PKG/usr/man -type l ) ; do
+  ln -s $( readlink $i ).gz $i.gz
+  rm $i
 done
+
+# Add a documentation directory:
+mkdir -p $PKG/usr/doc/${PKGNAM}-$VERSION
+cp -a \
+  AUTHORS* COPYING* FAQ* NEWS* README* \
+  $PKG/usr/doc/${PKGNAM}-$VERSION
+mv $PKG/usr/share/doc/valgrind/html $PKG/usr/doc/${PKGNAM}-$VERSION
+
+# The doc directory is the only thing in $PKG/usr/share, and the only things
+# left in it now are pdf and a ps doc files. They are large, so we won't keep
+# them around. If you still want them, uncomment the line below.
+# mv $PKG/usr/share/doc/valgrind/*.{ps,pdf} $PKG/usr/doc/$PKGNAM-$VERSION
+rm -rf $PKG/usr/share
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
-# Build the package:
 cd $PKG
-/sbin/makepkg -l y -c n $TMP/less-$VERSION-$ARCH-$BUILD.txz
-
+/sbin/makepkg -l y -c n $TMP/$PKGNAM-$VERSION-$ARCH-$BUILD.txz
