d: add LoongArch support

diff --git a/source/d/valgrind/valgrind.SlackBuild b/source/d/valgrind/valgrind.SlackBuild
--- a/source/d/valgrind/valgrind.SlackBuild
+++ b/source/d/valgrind/valgrind.SlackBuild
@@ -34,6 +34,7 @@ if [ -z "$ARCH" ]; then
   case "$(uname -m)" in
     i?86) ARCH=i686 ;;
     arm*) readelf /usr/bin/file -A | egrep -q "Tag_CPU.*[4,5]" && ARCH=arm || ARCH=armv7hl ;;
+    loongarch64) ARCH=loong64 ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
     *) ARCH=$(uname -m) ;;
   esac
@@ -61,6 +62,11 @@ elif [ "$ARCH" = "x86_64" ]; then
   # and forcing -fPIC results in a build failure.
   SLKCFLAGS="-O2 -march=x86-64 -mtune=generic"
   LIBDIRSUFFIX="64"
+elif [ "$ARCH" = "loong64" ]; then
+  # The valgrind build system already passes -fpic
+  # and forcing -fPIC results in a build failure.
+  SLKCFLAGS="-O2 "
+  LIBDIRSUFFIX="64"
 else
   SLKCFLAGS="-O2"
   LIBDIRSUFFIX=""
@@ -84,6 +90,12 @@ find . \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \+
 
+# add LoongArch support
+cat $CWD/0001-Add-libVEX-support-for-loongarch64.patch | patch -p1 --verbose || exit 1
+cat $CWD/0002-Add-support-for-loongarch64-linux.patch | patch -p1 --verbose || exit 1
+cat $CWD/0003-Add-tests-for-loongarch64.patch | patch -p1 --verbose || exit 1
+cat $CWD/0004-Add-nightly-tests-and-README-for-loongarch64.patch | patch -p1 --verbose || exit 1
+
 # Configure, build, and install:
 if [ ! -r configure ]; then
   if [ -x ./autogen.sh ]; then
@@ -92,6 +104,8 @@ if [ ! -r configure ]; then
     autoreconf -vif
   fi
 fi
+#cp -rf /usr/share/automake-1.17/config.* .
+NOCONFIGURE=1 ./autogen.sh
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
 ./configure \
@@ -101,7 +115,7 @@ CXXFLAGS="$SLKCFLAGS" \
   --localstatedir=/var \
   --docdir=/usr/doc/$PKGNAM-$VERSION \
   --mandir=/usr/man \
-  --build=$ARCH-slackware-linux || exit 1
+  --build=loongarch64-slackware-linux || exit 1
 make $NUMJOBS || make || exit 1
 make install DESTDIR=$PKG || exit 1
 
