Tue May 11 19:35:17 UTC 2021
a/btrfs-progs-5.12-x86_64-1.txz:  Upgraded.
a/hdparm-9.62-x86_64-1.txz:  Upgraded.
a/kernel-generic-5.10.36-x86_64-1.txz:  Upgraded.
a/kernel-huge-5.10.36-x86_64-1.txz:  Upgraded.
a/kernel-modules-5.10.36-x86_64-1.txz:  Upgraded.
d/kernel-headers-5.10.36-x86-1.txz:  Upgraded.
d/meson-0.58.0-x86_64-2.txz:  Rebuilt.
  Applied upstream fix for GNOME projects failing to build.
  Some projects still require an adjustment to implicit_include_directories.
k/kernel-source-5.10.36-noarch-1.txz:  Upgraded.
l/elfutils-0.184-x86_64-1.txz:  Upgraded.
l/glib2-2.68.2-x86_64-1.txz:  Upgraded.
n/libtirpc-1.3.2-x86_64-1.txz:  Upgraded.
n/snownews-1.8-x86_64-1.txz:  Upgraded.
isolinux/initrd.img:  Rebuilt.
kernels/*:  Upgraded.
usb-and-pxe-installers/usbboot.img:  Rebuilt.

diff --git a/source/d/meson/meson.SlackBuild b/source/d/meson/meson.SlackBuild
--- a/source/d/meson/meson.SlackBuild
+++ b/source/d/meson/meson.SlackBuild
@@ -25,7 +25,7 @@ cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=meson
 VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -52,6 +52,11 @@ cd $TMP
 rm -rf $PKGNAM-$VERSION
 tar xvf $CWD/$PKGNAM-$VERSION.tar.?z || exit 1
 cd $PKGNAM-$VERSION || exit 1
+
+# Upstream fix for GNOME projects build failures:
+zcat $CWD/39bb5e07eab736b525abfc66eb5ad0dd626aedc6.patch.gz | patch -p1 --verbose || exit 1
+# Needs this as well:
+zcat $CWD/meson.import.copy.diff.gz | patch -p1 --verbose || exit 1
 
 chown -R root:root .
 find -L . \
