Mon May 28 19:12:29 UTC 2018
a/pkgtools-15.0-noarch-13.txz:  Rebuilt.
  installpkg: default line length for --terselength is the number of columns.
  removepkg: added --terse mode.
  upgradepkg: default line length for --terselength is the number of columns.
  upgradepkg: accept -option in addition to --option.
ap/vim-8.1.0026-x86_64-1.txz:  Upgraded.
d/bison-3.0.5-x86_64-1.txz:  Upgraded.
e/emacs-26.1-x86_64-1.txz:  Upgraded.
kde/kopete-4.14.3-x86_64-8.txz:  Rebuilt.
  Recompiled against libidn-1.35.
n/conntrack-tools-1.4.5-x86_64-1.txz:  Upgraded.
n/libnetfilter_conntrack-1.0.7-x86_64-1.txz:  Upgraded.
n/libnftnl-1.1.0-x86_64-1.txz:  Upgraded.
n/links-2.16-x86_64-2.txz:  Rebuilt.
  Rebuilt to enable X driver for -g mode.
n/lynx-2.8.9dev.19-x86_64-1.txz:  Upgraded.
n/nftables-0.8.5-x86_64-1.txz:  Upgraded.
n/p11-kit-0.23.11-x86_64-1.txz:  Upgraded.
n/ulogd-2.0.7-x86_64-1.txz:  Upgraded.
n/whois-5.3.1-x86_64-1.txz:  Upgraded.
xap/network-manager-applet-1.8.12-x86_64-1.txz:  Upgraded.
xap/vim-gvim-8.1.0026-x86_64-1.txz:  Upgraded.

diff --git a/extra/source/recordmydesktop/recordmydesktop.SlackBuild b/extra/source/recordmydesktop/recordmydesktop.SlackBuild
--- a/extra/source/recordmydesktop/recordmydesktop.SlackBuild
+++ b/extra/source/recordmydesktop/recordmydesktop.SlackBuild
@@ -1,6 +1,7 @@
 #!/bin/sh
 # $Id: recordmydesktop.SlackBuild,v 1.8 2009/05/12 22:14:43 root Exp root $
 # Copyright (c) 2008 Eric Hameleers <alien@slackware.com>
+# Copyright 2018  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 #   Permission to use, copy, modify, and distribute this software for
@@ -43,16 +44,16 @@
 
 # Set initial variables:
 
-PRGNAM=recordmydesktop
+PKGNAM=recordmydesktop
 VERSION=${VERSION:-0.3.8.1}
 QTVER=${QTVER:-0.3.8}
-BUILD=${BUILD:-3}
-NUMJOBS=${NUMJOBS:" -j4 "}
+BUILD=${BUILD:-4}
+NUMJOBS=${NUMJOBS:" -j7 "}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$(uname -m)" in
-    i?86) ARCH=i486 ;;
+    i?86) ARCH=i586 ;;
     arm*) readelf /usr/bin/file -A | egrep -q "Tag_CPU.*[4,5]" && ARCH=arm || ARCH=armv7lh ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
     *) ARCH=$(uname -m) ;;
@@ -60,22 +61,30 @@ if [ -z "$ARCH" ]; then
   export ARCH
 fi
 
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
+  exit 0
+fi
+
 DOCS="AUTHORS COPYING README ChangeLog"
 QTDOCS="AUTHORS COPYING README ChangeLog"
 
 # Where do we look for sources?
-SRCDIR=$(cd $(dirname $0); pwd)
+cd $(dirname $0) ; SRCDIR=$(pwd)
 
 # Place to build (TMP) package (PKG) and output (OUTPUT) the program:
 TMP=${TMP:-/tmp/build}
-PKG=$TMP/package-$PRGNAM
+PKG=$TMP/package-$PKGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
-SOURCE[0]="$SRCDIR/${PRGNAM}-${VERSION}.tar.gz"
-SRCURL[0]="http://downloads.sourceforge.net/${PRGNAM}/${PRGNAM}-${VERSION}.tar.gz"
+SOURCE[0]="$SRCDIR/${PKGNAM}-${VERSION}.tar.gz"
+SRCURL[0]="http://downloads.sourceforge.net/${PKGNAM}/${PKGNAM}-${VERSION}.tar.gz"
 
-SOURCE[1]="$SRCDIR/qt-${PRGNAM}-${QTVER}.tar.gz"
-SRCURL[1]="http://downloads.sourceforge.net/${PRGNAM}/qt-${PRGNAM}-${QTVER}.tar.gz"
+SOURCE[1]="$SRCDIR/qt-${PKGNAM}-${QTVER}.tar.gz"
+SRCURL[1]="http://downloads.sourceforge.net/${PKGNAM}/qt-${PKGNAM}-${QTVER}.tar.gz"
 
 ##
 ## --- with a little luck, you won't have to edit below this point --- ##
@@ -83,13 +92,13 @@ SRCURL[1]="http://downloads.sourceforge.net/${PRGNAM}/qt-${PRGNAM}-${QTVER}.tar.
 
 # Exit the script on errors:
 set -e
-trap 'echo "$0 FAILED at line ${LINENO}" | tee $OUTPUT/error-${PRGNAM}.log' ERR
+trap 'echo "$0 FAILED at line ${LINENO}" | tee $OUTPUT/error-${PKGNAM}.log' ERR
 # Catch unitialized variables:
 set -u
 P1=${1:-1}
 
 case "$ARCH" in
-  i486)      SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  i586)      SLKCFLAGS="-O2 -march=i586 -mtune=i686"
              SLKLDFLAGS=""; LIBDIRSUFFIX=""
              ;;
   s390)      SLKCFLAGS="-O2"
@@ -108,11 +117,11 @@ esac
 
 # Create working directories:
 mkdir -p $OUTPUT          # place for the package to be saved
-mkdir -p $TMP/tmp-$PRGNAM # location to build the source
+mkdir -p $TMP/tmp-$PKGNAM # location to build the source
 mkdir -p $PKG             # place for the package to be built
 rm -rf $PKG/*             # always erase old package's contents
-rm -rf $TMP/tmp-$PRGNAM/* # remove the remnants of previous build
-rm -rf $OUTPUT/{configure,make,install,error,makepkg}-$PRGNAM.log
+rm -rf $TMP/tmp-$PKGNAM/* # remove the remnants of previous build
+rm -rf $OUTPUT/{configure,make,install,error,makepkg}-$PKGNAM.log
                           # remove old log files
 
 # Source file availability:
@@ -144,11 +153,11 @@ fi
 # --- PACKAGE BUILDING ---
 
 echo "++"
-echo "|| $PRGNAM-$VERSION"
+echo "|| $PKGNAM-$VERSION"
 echo "++"
 
-cd $TMP/tmp-$PRGNAM
-echo "Extracting the source archive(s) for $PRGNAM..."
+cd $TMP/tmp-$PKGNAM
+echo "Extracting the source archive(s) for $PKGNAM..."
 for (( i = 0; i < ${#SOURCE[*]}; i++ )) ; do
 tar -xvf ${SOURCE[$i]}
 done
@@ -158,7 +167,10 @@ chmod -R u+w,go+r-w,a-s *
 echo Building ...
 
 # First, the commandline program:
-cd ${PRGNAM}-${VERSION}
+cd ${PKGNAM}-${VERSION}
+  # Apply bugfix patches from Arch:
+  zcat $SRCDIR/recordmydesktop-bitrate.patch.gz | patch -p1 --verbose || exit 1
+  zcat $SRCDIR/shmstr-to-shmproto.patch.gz | patch -p0 --verbose || exit 1
   LDFLAGS="$SLKLDFLAGS" \
   CXXFLAGS="$SLKCFLAGS" \
   CFLAGS="$SLKCFLAGS" \
@@ -170,18 +182,18 @@ cd ${PRGNAM}-${VERSION}
     --program-prefix= \
     --program-suffix= \
     --build=$ARCH-slackware-linux \
-    2>&1 | tee $OUTPUT/configure-${PRGNAM}.log
-  make 2>&1 | tee $OUTPUT/make-${PRGNAM}.log
+    2>&1 | tee $OUTPUT/configure-${PKGNAM}.log
+  make 2>&1 | tee $OUTPUT/make-${PKGNAM}.log
 
   if $(which installwatch > /dev/null 2>&1); then
-    installwatch -o $OUTPUT/install-${PRGNAM}.log make DESTDIR=$PKG install
+    installwatch -o $OUTPUT/install-${PKGNAM}.log make DESTDIR=$PKG install
   else
-    make DESTDIR=$PKG install 2>&1 |tee $OUTPUT/install-${PRGNAM}.log
+    make DESTDIR=$PKG install 2>&1 |tee $OUTPUT/install-${PKGNAM}.log
   fi
 cd ..
 
 # Next, the QT4 GUI program:
-cd qt-${PRGNAM}-${QTVER}
+cd qt-${PKGNAM}-${QTVER}
   LDFLAGS="$SLKLDFLAGS" \
   CXXFLAGS="$SLKCFLAGS" \
   CFLAGS="$SLKCFLAGS" \
@@ -193,13 +205,13 @@ cd qt-${PRGNAM}-${QTVER}
     --program-prefix= \
     --program-suffix= \
     --build=$ARCH-slackware-linux \
-    2>&1 | tee $OUTPUT/configure-qt-${PRGNAM}.log
-  make 2>&1 | tee $OUTPUT/make-qt-${PRGNAM}.log
+    2>&1 | tee $OUTPUT/configure-qt-${PKGNAM}.log
+  make 2>&1 | tee $OUTPUT/make-qt-${PKGNAM}.log
 
   if $(which installwatch > /dev/null 2>&1); then
-    installwatch -o $OUTPUT/install-${PRGNAM}.log make DESTDIR=$PKG install
+    installwatch -o $OUTPUT/install-${PKGNAM}.log make DESTDIR=$PKG install
   else
-    make DESTDIR=$PKG install 2>&1 |tee $OUTPUT/install-${PRGNAM}.log
+    make DESTDIR=$PKG install 2>&1 |tee $OUTPUT/install-${PKGNAM}.log
   fi
 cd ..
 
@@ -214,15 +226,15 @@ fi
 EOT
 
 # Add documentation:
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/qt-${PRGNAM}
-( cd ${PRGNAM}-${VERSION}
-  cp -a $DOCS $PKG/usr/doc/$PRGNAM-$VERSION || true
+mkdir -p $PKG/usr/doc/$PKGNAM-$VERSION/qt-${PKGNAM}
+( cd ${PKGNAM}-${VERSION}
+  cp -a $DOCS $PKG/usr/doc/$PKGNAM-$VERSION || true
 )
-( cd qt-${PRGNAM}-${QTVER}
-  cp -a $QTDOCS $PKG/usr/doc/$PRGNAM-$VERSION/qt-${PRGNAM} || true
+( cd qt-${PKGNAM}-${QTVER}
+  cp -a $QTDOCS $PKG/usr/doc/$PKGNAM-$VERSION/qt-${PKGNAM} || true
 )
-cp -a $SRCDIR/$(basename $0) $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
-chown -R root:root $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a $SRCDIR/$(basename $0) $PKG/usr/doc/$PKGNAM-$VERSION/$PKGNAM.SlackBuild
+chown -R root:root $PKG/usr/doc/$PKGNAM-$VERSION
 find $PKG/usr/doc -type f -exec chmod 644 {} \;
 
 # Compress the man page(s):
@@ -244,12 +256,12 @@ fi
 
 # Build the package:
 cd $PKG
-makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}.txz 2>&1 | tee $OUTPUT/makepkg-${PRGNAM}.log
+makepkg --linkadd y --chown n $OUTPUT/${PKGNAM}-${VERSION}-${ARCH}-${BUILD}.txz 2>&1 | tee $OUTPUT/makepkg-${PKGNAM}.log
 cd $OUTPUT
-md5sum ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}.txz > ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}.txz.md5
+md5sum ${PKGNAM}-${VERSION}-${ARCH}-${BUILD}.txz > ${PKGNAM}-${VERSION}-${ARCH}-${BUILD}.txz.md5
 cd -
-cat $PKG/install/slack-desc | grep "^${PRGNAM}" > $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}.txt
+cat $PKG/install/slack-desc | grep "^${PKGNAM}" > $OUTPUT/${PKGNAM}-${VERSION}-${ARCH}-${BUILD}.txt
 if [ -f $PKG/install/slack-required ]; then
-  cat $PKG/install/slack-required > $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}.dep
+  cat $PKG/install/slack-required > $OUTPUT/${PKGNAM}-${VERSION}-${ARCH}-${BUILD}.dep
 fi
 
diff --git a/source/a/glibc-zoneinfo/glibc-zoneinfo.SlackBuild b/source/a/glibc-zoneinfo/glibc-zoneinfo.SlackBuild
--- a/source/a/glibc-zoneinfo/glibc-zoneinfo.SlackBuild
+++ b/source/a/glibc-zoneinfo/glibc-zoneinfo.SlackBuild
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright 2015, 2016  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2015, 2016, 2018  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,10 +20,11 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=glibc-zoneinfo
 ZONE_VERSIONS="$(echo tzdata* | cut -f1 -d . | cut -b7-11)"
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -36,35 +37,42 @@ if [ -z "$ARCH" ]; then
   export ARCH
 fi
 
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$ZONE_VERSIONS-noarch-$BUILD.txz"
+  exit 0
+fi
+
 NUMJOBS=${NUMJOBS:-" -j7 "}
 
 if [ "$ARCH" = "i386" ]; then
-  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
+  SLKCFLAGS="-DHAVE_SNPRINTF=1 -O2 -march=i386 -mcpu=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  SLKCFLAGS="-DHAVE_SNPRINTF=1 -O2 -march=i486 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
+  SLKCFLAGS="-DHAVE_SNPRINTF=1 -O2 -march=i586 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686"
+  SLKCFLAGS="-DHAVE_SNPRINTF=1 -O2 -march=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "s390" ]; then
-  SLKCFLAGS="-O2"
+  SLKCFLAGS="-DHAVE_SNPRINTF=1 -O2"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
+  SLKCFLAGS="-DHAVE_SNPRINTF=1 -O2 -fPIC"
   LIBDIRSUFFIX="64"
 elif [ "$ARCH" = "armv7hl" ]; then
-  SLKCFLAGS="-O3 -march=armv7-a -mfpu=vfpv3-d16"
+  SLKCFLAGS="-DHAVE_SNPRINTF=1 -O3 -march=armv7-a -mfpu=vfpv3-d16"
   LIBDIRSUFFIX=""
 else
-  SLKCFLAGS="-O2"
+  SLKCFLAGS="-DHAVE_SNPRINTF=1 -O2"
   LIBDIRSUFFIX=""
 fi
 
-CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-$PKGNAM
 
@@ -76,8 +84,8 @@ cd $TMP
 rm -rf tzcodedata-build
 mkdir tzcodedata-build
 cd tzcodedata-build
-tar xzf $CWD/tzdata?????.tar.gz
-tar xzf $CWD/tzcode?????.tar.gz
+tar xzf $CWD/tzdata?????.tar.gz || exit 1
+tar xzf $CWD/tzcode?????.tar.gz || exit 1
 
 chown -R root:root .
 find . \
@@ -88,19 +96,25 @@ find . \
 
 sed -i "s,/usr/local,$(pwd),g" Makefile
 sed -i "s,/etc/zoneinfo,/zoneinfo,g" Makefile
-make
-make install
-mkdir -p $PKG/usr/share/zoneinfo
-cd etc
-cp -a zoneinfo/* $PKG/usr/share/zoneinfo
+sed -i "s,^CFLAGS=,CFLAGS=		$SLKCFLAGS,g" Makefile
+make || exit 1
+make install DESTDIR=$PKG/stage || exit 1
+
+# Install the primary zone files:
+mkdir -p $PKG/usr/share
+mv $PKG/stage/usr/share/zoneinfo $PKG/usr/share
 
 # These are all identical to the normal zoneinfo files, so let's hard link
 # them to save space:
 cp -al $PKG/usr/share/zoneinfo $PKG/usr/share/posix
 mv $PKG/usr/share/posix $PKG/usr/share/zoneinfo
 
+# Install the "right" files:
 mkdir -p $PKG/usr/share/zoneinfo/right
-cp -a zoneinfo-leaps/* $PKG/usr/share/zoneinfo/right
+cp -a $PKG/stage/usr/share/zoneinfo-leaps/* $PKG/usr/share/zoneinfo/right
+
+# Clean up staged file residue:
+rm -rf $PKG/stage
 
 # Remove $PKG/usr/share/zoneinfo/localtime -- the install script will
 # create it as a link to /etc/localtime.
@@ -127,7 +141,6 @@ if [ ! -r $PKG/usr/share/zoneinfo/localtime ]; then
   ( cd $PKG/usr/share/zoneinfo ; ln -sf /etc/localtime . )
 fi
 
-cd ..
 mkdir -p $PKG/usr/doc/glibc-zoneinfo-$ZONE_VERSIONS
 cp -a \
   CONTRIBUTING NEWS README Theory \
diff --git a/source/a/mkinitrd/mkinitrd b/source/a/mkinitrd/mkinitrd
--- a/source/a/mkinitrd/mkinitrd
+++ b/source/a/mkinitrd/mkinitrd
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Copyright 2004  Slackware Linux, Inc., Concord, CA, USA
 # Copyright 2004  Patrick J. Volkerding, Concord, CA, USA
-# Copyright 2007, 2008, 2009, 2010, 2011, 2015, 2016  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2007, 2008, 2009, 2010, 2011, 2015, 2016, 2017  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -44,8 +44,17 @@
 #   Yada yada yada.
 # Modified by Patrick Volkerding <volkerdi@slackware.com> 21 August 2012
 #   Add Btrfs multi-device filesystem support option (-B).
+# Modified by Robby Workman <rworkman@slackware.com> 08 March 2017
+#   to add support for TRIM on LUKS root devs 
+# Modified by Patrick Volkerding <volkerdi@slackware.com> 29 June 2017
+#   Add support for prepending a microcode update archive (-P).
+# Modified by Patrick Volkerding <volkerdi@slackware.com> 12 July 2017
+#   Add support for including Slackware and kernel versions in the
+#   output filename. Thanks to SeB.
 
-MKINITRD_VERSION=1.4.8
+MKINITRD_VERSION=1.4.11
+
+COMMAND_LINE="$0 $*"
 
 # Don't include these things from /lib/udev/ in the initrd image
 LIBUDEV_BLACKLIST="\
@@ -55,6 +64,7 @@ LIBUDEV_BLACKLIST="\
   check-ptp-camera \
   udev-configure-printer \
   rules.d/60-openobex.rules \
+  rules.d/85-regulatory.rules \
   "
 
 print_usage() {
@@ -92,6 +102,11 @@ initrd, and the script is easy to modify.  Be creative.  :-)
           unlocked by the initrd using cryptsetup. All devices that must
           be unlocked in order to access the root filesystem must be
           specified. (Use with '-r' parameter).
+  -T      A colon (:) delimited list of luks encrypted block devices to be
+          passed the "--allow-discards" option when unlocked by the initrd 
+          using cryptsetup. This has the effect of allowing TRIM on SSD drives.
+          Be sure your SSD supports this feature (correctly) before enabling
+          it. See fstrim(8) for more information.
   -L      Add support for LVM partitions
   -K      Use a USB key (fat-formatted) to unlock the root LUKS volume
           The parameter value is filename of a keyfile, as well as the label
@@ -105,6 +120,7 @@ initrd, and the script is easy to modify.  Be creative.  :-)
   -B      Add /sbin/btrfs to enable scanning for a root filesystem that is
           part of a Btrfs multi-device filesystem.
   -M      Add the files in /etc/modprobe.d/ and /lib/modprobe.d/ to the initrd
+  -P      Prepend the output image with the microcode CPIO archive given in arguments.
   -R      Add support for RAID partitions
   -V      Display version number
 
@@ -183,6 +199,11 @@ build_initrd_image() {
     rm -f $OUTPUT_IMAGE
     find . | cpio -o -H newc | gzip -9c > $OUTPUT_IMAGE
   )
+
+  if [ ! -z "${MICROCODE_ARCH}" ] ; then
+    cat ${MICROCODE_ARCH} ${OUTPUT_IMAGE} > ${OUTPUT_IMAGE}.2
+    mv ${OUTPUT_IMAGE}.2 ${OUTPUT_IMAGE}
+  fi
   echo "$OUTPUT_IMAGE created."
   echo "Be sure to run lilo again if you use it."
 }
@@ -245,7 +266,19 @@ copy_modconf() {
   cp -a /etc/modprobe.d $SOURCE_TREE/etc
   cp -a /lib/modprobe.d $SOURCE_TREE/lib/
 }
-     
+
+# Normalize the string $1 by replacing occurences of 
+# recognized tags by their current values.
+#
+# this version take the following tags into account:
+#  %KVER% (kernel version)
+#  %SLACKVER% (slackware version)
+#
+function normalize_string() {
+  echo "$1" | sed -e "s?%KVER%?${KERNEL_VERSION}?g" \
+                  -e "s?%SLACKVER%?$(cat /etc/slackware-version|cut -f2 -d" ")?g"
+}
+
 # If --help is given, print_usage and exit:
 if echo $* | grep -wq '\--help' ; then
   print_usage
@@ -269,7 +302,7 @@ UDEV=1
 # Default actions without options:
 if [ -z "$1" ]; then
   # We need a sensible default for this special case:
-  OUTPUT_IMAGE=${OUTPUT_IMAGE:-/boot/initrd.gz}
+  OUTPUT_IMAGE=$(normalize_string ${OUTPUT_IMAGE:-/boot/initrd.gz})
   # If the output tree doesn't exist, create it and then exit:
   if [ ! -d $SOURCE_TREE ]; then
     echo "Nothing found at location $SOURCE_TREE, so we will create an"
@@ -362,6 +395,10 @@ while [ ! -z "$1" ]; do
       LUKSKEY="$2"
       shift 2
       ;;
+    -T)
+      LUKSTRIM="$2"
+      shift 2
+      ;;
     -L)
       LVM=1
       shift
@@ -374,6 +411,16 @@ while [ ! -z "$1" ]; do
       MODCONF=1
       shift
       ;;
+    -P)
+      # canonicalize filename:
+      MICROCODE_ARCH="$(readlink -m $2)"
+      if [ ! -e "${MICROCODE_ARCH}" ] ; then
+        echo "Error, the microcode cpio archive ${MICROCODE_ARCH} does not exist."
+        exit 1
+      fi
+      shift 2
+    ;;
+
     -R)
       RAID=1
       shift
@@ -383,6 +430,19 @@ while [ ! -z "$1" ]; do
       ;;
   esac
 done
+
+# Resolve TAGS (i.e %KVER%, %SLACKVER%) found in OUTPUT_IMAGE.
+#
+# Note:
+# ----
+# This must be done after all options have been handled and
+# not when handling case '-o' because -k can be passed after
+# -o in which case, the tag %KVER% would be replaced with the 
+# current kernel version instead of version passed with -k.
+#
+if echo "$OUTPUT_IMAGE" | grep -qE "%KVER%|%SLACKVER%" ; then
+  OUTPUT_IMAGE="$(normalize_string $OUTPUT_IMAGE)"
+fi
 
 # If kernel modules are needed but the kernel version is absent, exit now:
 if [ ! -d /lib/modules/$KERNEL_VERSION ]; then
@@ -420,6 +480,17 @@ if [ ! -z "$ROOTFS" ]; then
   echo $ROOTFS > $SOURCE_TREE/rootfs
 fi
 
+# Put a copy of the command line used to create this initrd in
+# initrd-tree/command_line:
+echo "$COMMAND_LINE" > $SOURCE_TREE/command_line
+
+# If /etc/mkinitrd.conf exists, put a copy of that in there as well.
+# (May or may not have been used according to the -F option, but we'll
+# save a copy anyway just in case):
+if [ -e /etc/mkinitrd.conf ]; then
+  cp -a /etc/mkinitrd.conf $SOURCE_TREE/mkinitrd.conf
+fi
+
 # If $WAIT is not set, assume we need only one second
 # to have all devices done
 # (unless we find that value is already set in the initrd-tree):
@@ -435,7 +506,7 @@ if [ ! -z "$WAIT" ]; then
 fi
 
 # If no OUTPUT_IMAGE was specified, read it from the SOURCE_TREE if possible:
-OUTPUT_IMAGE=${OUTPUT_IMAGE:-"$(cat $SOURCE_TREE/initrd-name)"}
+OUTPUT_IMAGE=$(normalize_string ${OUTPUT_IMAGE:-"$(cat $SOURCE_TREE/initrd-name)"})
 # If we still have no value, apply the default:
 OUTPUT_IMAGE=${OUTPUT_IMAGE:-"/boot/initrd.gz"}
 # Finally, write the image name into the SOURCE_TREE:
@@ -455,6 +526,11 @@ fi
 # If LUKSDEV was set in the config file, then we need to set CRYPT=1
 if [ ! -z "$LUKSDEV" ]; then
   CRYPT=1
+fi
+
+# Check for LUKSTRIM
+if [ ! -z "$LUKSTRIM" ]; then
+  echo $LUKSTRIM > $SOURCE_TREE/lukstrim
 fi
 
 # If LUKSKEY was set in the config file, then give it a warm welcome:
@@ -524,21 +600,12 @@ if [ ! -z "$LVM" ]; then
   if [ -f /sbin/lvm ]; then
     mkdir -p $SOURCE_TREE/sbin
     cp /sbin/lvm $SOURCE_TREE/sbin/lvm
-    cp /sbin/dmsetup $SOURCE_TREE/sbin/dmsetup
-    find /lib /lib64 -name "libdevmapper*so*" 2> /dev/null | xargs -I'{}' cp -P --parents '{}' $SOURCE_TREE/
     ( cd $SOURCE_TREE/sbin
       ln -s lvm vgchange 2>/dev/null
       ln -s lvm vgscan 2>/dev/null )
-    if [ -z "${MODULE_LIST}" ] ; then
-      MODULE_LIST="dm-mod"
-    elif ! echo ${MODULE_LIST} | grep -q dm-mod ; then
-      MODULE_LIST="$MODULE_LIST:dm-mod"
-    fi
-    mkdir -p $SOURCE_TREE/lib/udev/rules.d
-    echo 'KERNEL=="dm-[0-9]*", OPTIONS+="db_persist"' > \
-      $SOURCE_TREE/lib/udev/rules.d/95-dm-initrd.rules
   else
     echo "LVM binary is missing, LVM support isn't installed"
+    LVM=""
   fi
 fi
 
@@ -555,16 +622,26 @@ EOF
       chmod 0755 $SOURCE_TREE/sbin/udevadm
     fi
 
-    if [ -z "${MODULE_LIST}" ] ; then
-      MODULE_LIST="dm-mod"
-    elif ! echo ${MODULE_LIST} | grep -q dm-mod ; then
-      MODULE_LIST="$MODULE_LIST:dm-mod"
-    fi
     # Write the underlying luks device to the initrd-tree:
     echo $LUKSDEV > $SOURCE_TREE/luksdev
   else
     echo "Cryptsetup binary is missing, CRYPT support isn't installed"
+    CRYPT=""
   fi
+fi
+
+# Include device mapper in initrd (needed for LUKS and LVM)
+if [ ! -z "$CRYPT" -o ! -z "$LVM" ]; then
+  cp /sbin/dmsetup $SOURCE_TREE/sbin/dmsetup
+  find /lib /lib64 -name "libdevmapper*so*" 2> /dev/null | xargs -I'{}' cp -P --parents '{}' $SOURCE_TREE/
+  if [ -z "${MODULE_LIST}" ] ; then
+    MODULE_LIST="dm-mod"
+  elif ! echo ${MODULE_LIST} | grep -q dm-mod ; then
+    MODULE_LIST="$MODULE_LIST:dm-mod"
+  fi
+  mkdir -p $SOURCE_TREE/lib/udev/rules.d
+  echo 'KERNEL=="dm-[0-9]*", OPTIONS+="db_persist"' > \
+    $SOURCE_TREE/lib/udev/rules.d/95-dm-initrd.rules
 fi
 
 # Make module directory:
diff --git a/source/a/patch/patch.SlackBuild b/source/a/patch/patch.SlackBuild
--- a/source/a/patch/patch.SlackBuild
+++ b/source/a/patch/patch.SlackBuild
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright 2005-2009, 2010, 2012, 2015  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2005-2009, 2010, 2012, 2015, 2018  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,9 +20,11 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+cd $(dirname $0) ; CWD=$(pwd)
+
 PKGNAM=patch
-VERSION=${VERSION:-$(echo $PKGNAM-*.tar.xz | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-1}
+VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
+BUILD=${BUILD:-3}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -34,7 +36,14 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-CWD=$(pwd)
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
+  exit 0
+fi
+
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-patch
 
@@ -53,7 +62,7 @@ fi
 
 cd $TMP
 rm -rf patch-${VERSION}
-tar xvf $CWD/patch-${VERSION}.tar.xz || exit 1
+tar xvf $CWD/patch-${VERSION}.tar.?z || exit 1
 cd patch-${VERSION} || exit 1
 
 chown -R root:root .
@@ -63,14 +72,21 @@ find . \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \;
 
+# Patch CVE-2018-1000156, arbitrary shell command execution by (obsolete)
+# ed patch format:
+zcat $CWD/0001-Refuse-to-apply-ed-scripts-by-default.patch.gz | patch -p1 --verbose || exit 1
+
+# This avoids failure in tests/ expecting an old automake:
+autoreconf -vif
+
 CFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/usr \
   --mandir=/usr/man \
-  --build=$ARCH-slackware-linux
+  --build=$ARCH-slackware-linux || exit 1
 
 make -j4 || make || exit 1
-make install DESTDIR=$PKG
+make install DESTDIR=$PKG || exit 1
 
 # Strip everything for good measure:
 ( cd $PKG
diff --git a/source/a/pkgtools/scripts/explodepkg b/source/a/pkgtools/scripts/explodepkg
--- a/source/a/pkgtools/scripts/explodepkg
+++ b/source/a/pkgtools/scripts/explodepkg
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Copyright 1994, 1998, 2000  Patrick Volkerding, Concord, CA, USA
 # Copyright 2001, 2003  Slackware Linux, Inc., Concord, CA, USA
-# Copyright 2007, 2009  Patrick Volkerding, Sebeka, MN, USA
+# Copyright 2007, 2009, 2017, 2018  Patrick Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -21,32 +21,15 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-TAR=tar-1.13
-$TAR --help 1> /dev/null 2> /dev/null
-if [ ! $? = 0 ]; then
-  TAR=tar
-fi
-if [ ! "`LC_MESSAGES=C $TAR --version`" = "tar (GNU tar) 1.13
-
-Copyright (C) 1988, 92,93,94,95,96,97,98, 1999 Free Software Foundation, Inc.
-This is free software; see the source for copying conditions.  There is NO
-warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-
-Written by John Gilmore and Jay Fenlason." ]; then
-  echo "WARNING: pkgtools are unstable with tar > 1.13."
-  echo "         You should provide a \"tar-1.13\" in your \$PATH."
-  sleep 5
-fi
-
 if [ $# = 0 ]; then
   cat << EOF
 Usage: explodepkg package_name [package_name2, ...]
 
 Explodes a Slackware compatible software package
-(or any tar+{gzip,bzip2,lzma,xz archive) in the current directory.
+(or any tar+{gzip,bzip2,lz,xz archive) in the current directory.
 Equivalent to (for each package listed):
 
-  ( umask 000 ; cat package_name | COMPRESSOR -dc | tar xvf package_name )
+  ( umask 000 ; cat package_name | COMPRESSOR -dc | tar xpvf package_name )
 
 Note: This should only be used for debugging or examining packages, not for 
 installing them.  It doesn't execute installation scripts or update the package
@@ -54,6 +37,10 @@ indexes in /var/log/packages and /var/log/scripts.
 
 EOF
 fi
+
+# Set maximum number of threads to use. By default, this will be the number
+# of CPU threads:
+THREADS="$(nproc)"
 
 # Main loop:
 for PKG in $* ; do
@@ -69,25 +56,50 @@ for PKG in $* ; do
     packagecompression=gzip
     ;;
   'tbz' )
-    packagecompression=bzip2
+    if which lbzip2 1> /dev/null 2> /dev/null ; then
+      packagecompression=lbzip2
+    else
+      packagecompression=bzip2
+    fi
     ;;
   'bz2' )
-    packagecompression=bzip2
+    if which lbzip2 1> /dev/null 2> /dev/null ; then
+      packagecompression=lbzip2
+    else
+      packagecompression=bzip2
+    fi
     ;;
   'tlz' )
-    packagecompression=lzma
+    if which plzip 1> /dev/null 2> /dev/null ; then
+      packagecompression="plzip --threads=${THREADS}"
+    elif which lzip 1> /dev/null 2> /dev/null ; then
+      packagecompression=lzip
+    else
+      echo "ERROR:  lzip compression utility not found in \$PATH."
+      exit 3
+    fi
+    ;;
+  'lz' )
+    if which plzip 1> /dev/null 2> /dev/null ; then
+      packagecompression="plzip --threads=${THREADS}"
+    elif which lzip 1> /dev/null 2> /dev/null ; then
+      packagecompression=lzip
+    else
+      echo "ERROR:  lzip compression utility not found in \$PATH."
+      exit 3
+    fi
     ;;
   'lzma' )
     packagecompression=lzma
     ;;
   'txz' )
-    packagecompression=xz
+    packagecompression="xz --threads=${THREADS}"
     ;;
   'xz' )
-    packagecompression=xz
+    packagecompression="xz --threads=${THREADS}"
     ;;
   esac
-  ( umask 000 ; cat $PKG | $packagecompression -dc | $TAR xvf - 2> /dev/null )
+  ( umask 000 ; cat $PKG | $packagecompression -dc | tar --xattrs --xattrs-include='*' --keep-directory-symlink -xpvf - 2> /dev/null )
   if [ -r install/doinst.sh ]; then
     echo
     echo "An installation script was detected in ./install/doinst.sh, but"
diff --git a/source/a/pkgtools/scripts/makepkg b/source/a/pkgtools/scripts/makepkg
--- a/source/a/pkgtools/scripts/makepkg
+++ b/source/a/pkgtools/scripts/makepkg
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Copyright 1994, 1998, 2008  Patrick Volkerding, Moorhead, Minnesota USA 
 # Copyright 2003  Slackware Linux, Inc.  Concord, CA USA
-# Copyright 2009, 2015  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2009, 2015, 2017, 2018  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -21,6 +21,16 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
+# Mon May 21 18:31:20 UTC 2018
+# Add --compress option, usually used to change the preset compression level
+# or block size.
+#
+# Tue Feb 13 00:46:12 UTC 2018
+# Use recent tar, and support storing POSIX ACLs and extended attributes.
+#
+# Tue Dec 12 21:55:59 UTC 2017
+# If possible, use multiple compression threads.
+#
 # Wed Sep 23 18:36:43 UTC 2015
 # Support spaces in file/directory names.  <alphageek>
 #
@@ -36,23 +46,7 @@
 
 CWD=$(pwd)
 
-TAR=tar-1.13
 umask 022
-$TAR --help 1> /dev/null 2> /dev/null
-if [ ! $? = 0 ]; then
-  TAR=tar
-fi
-if [ ! "$(LC_MESSAGES=C $TAR --version)" = "tar (GNU tar) 1.13
-
-Copyright (C) 1988, 92,93,94,95,96,97,98, 1999 Free Software Foundation, Inc.
-This is free software; see the source for copying conditions.  There is NO
-warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-
-Written by John Gilmore and Jay Fenlason." ]; then
-  echo "WARNING: pkgtools are unstable with tar > 1.13."
-  echo "         You should provide a \"tar-1.13\" in your \$PATH."
-  sleep 5
-fi
 
 make_install_script() {
   TAB="$(echo -e "\t")"
@@ -80,26 +74,48 @@ Usage: makepkg package_name.tgz
        (or: package_name.tbz, package_name.tlz, package_name.txz)
 
 Makes a Slackware compatible package containing the contents of the current
-and all subdirectories.  If symbolic links exist, they will be removed and
+and all subdirectories. If symbolic links exist, they will be removed and
 an installation script will be made to recreate them later. This script will
 be called "install/doinst.sh". You may add any of your own ash-compatible
 shell scripts to this file and rebuild the package if you wish.
 
 options:  -l, --linkadd y|n (moves symlinks into doinst.sh: recommended)
           -p, --prepend (prepend rather than append symlinks to an existing
-                         doinst.sh.  Useful to link libraries needed by
-                         programs in the doinst.sh script)
-          -c, --chown y|n (resets all permissions to root:root 755
-                           - not generally recommended)
+               doinst.sh.  Useful to link libraries needed by programs in
+               the doinst.sh script)
+          -c, --chown y|n (resets all permissions to root:root 755 - not
+               generally recommended)
+          --threads <number> For xz/plzip compressed packages, set the max
+               number of threads to be used for compression. Only has an
+               effect on large packages. For plzip, the default is equal to
+               the number of CPU threads available on the machine. For xz,
+               the default is equal to 2 (due to commonly occuring memory
+               related failures when using many threads with multi-threaded
+               xz compression).
+          --compress <option> Supply a custom option to the compressor.
+               This will be used in place of the default, which is: -9
+          --acls Support storing POSIX ACLs in the package. The resulting
+               package will not be compatible with pkgtools version < 15.0.
+          --xattrs Support storing extended attributes in the package. The
+               resulting package will not be compatible with pkgtools
+               version < 15.0.
 
-If these options are not set, makepkg will prompt as appropriate.
+If these options are not set, makepkg will prompt if appropriate.
 EOF
 }
 
 TMP=/tmp # This can be a hole, but I'm going to be careful about file
          # creation in there, so don't panic. :^)
 
+# Set maximum number of threads to use. By default, this will be the number
+# of CPU threads:
+THREADS="$(nproc)"
+
+# Set default compression option.
+COMPRESS_OPTION="-9"
+
 # Parse options
+unset ACLS XATTRS
 while [ 0 ]; do
   if [ "$1" = "--linkadd" -o "$1" = "-l" ]; then
     if [ "$2" = "y" ]; then
@@ -124,6 +140,21 @@ while [ 0 ]; do
   elif [ "$1" = "-p" -o "$1" = "--prepend" ]; then
     PREPEND=y
     shift 1
+  elif [ "$1" = "-threads" -o "$1" = "--threads" ]; then
+    THREADS="$2"
+    shift 2
+    # xz has memory issues with threads it seems, so we'll use two threads by
+    # default unless we see that something else was user-selected:
+    XZ_THREADS_FORCED=yes
+  elif [ "$1" = "-compress" -o "$1" = "--compress" ]; then
+    COMPRESS_OPTION="$2"
+    shift 2
+  elif [ "$1" = "--acls" ]; then
+    ACLS="--acls"
+    shift 1
+  elif [ "$1" = "--xattrs" ]; then
+    XATTRS="--xattrs"
+    shift 1 
   elif [ "$1" = "-h" -o "$1" = "-H" -o "$1" = "--help" -o $# = 0 ]; then
     usage
     exit 0
@@ -136,26 +167,109 @@ PACKAGE_NAME="$1"
 TARGET_NAME="$(dirname $PACKAGE_NAME)"
 PACKAGE_NAME="$(basename $PACKAGE_NAME)"
 
-# Identify package extension:
+# Identify package extension and compression type to use:
 if [ ! "$(basename $PACKAGE_NAME .tgz)" = "$PACKAGE_NAME" ]; then
   EXTENSION="tgz"
+  COMPEXT="gz"
+  COMPRESSOR="gzip ${COMPRESS_OPTION} -c"
+  if ! which gzip 1> /dev/null 2> /dev/null ; then
+    echo "ERROR:  gzip compression utility not found in \$PATH."
+    exit 3
+  fi
 elif [ ! "$(basename $PACKAGE_NAME .tar.gz)" = "$PACKAGE_NAME" ]; then
-  # .tar.compression is also supported, although the resulting "packages" will
-  # not be installable by installpkg without the correct 3 letter extension
-  # instead.
   EXTENSION="tar.gz"
+  COMPRESSOR="gzip ${COMPRESS_OPTION} -c"
+  if ! which gzip 1> /dev/null 2> /dev/null ; then
+    echo "ERROR:  gzip compression utility not found in \$PATH."
+    exit 3
+  fi
 elif [ ! "$(basename $PACKAGE_NAME .tbz)" = "$PACKAGE_NAME" ]; then
   EXTENSION="tbz"
+  if which lbzip2 1> /dev/null 2> /dev/null ; then
+    COMPRESSOR="lbzip2 ${COMPRESS_OPTION} -c"
+  else
+    if which bzip2 1> /dev/null 2> /dev/null ; then
+      COMPRESSOR="bzip2 ${COMPRESS_OPTION} -c"
+    else
+      echo "ERROR:  bzip2 compression utility not found in \$PATH."
+      exit 3
+    fi
+  fi
 elif [ ! "$(basename $PACKAGE_NAME .tar.bz2)" = "$PACKAGE_NAME" ]; then
   EXTENSION="tar.bz2"
+  if which lbzip2 1> /dev/null 2> /dev/null ; then
+    COMPRESSOR="lbzip2 ${COMPRESS_OPTION} -c"
+  else
+    if which bzip2 1> /dev/null 2> /dev/null ; then
+      COMPRESSOR="bzip2 ${COMPRESS_OPTION} -c"
+    else
+      echo "ERROR:  bzip2 compression utility not found in \$PATH."
+      exit 3
+    fi
+  fi
 elif [ ! "$(basename $PACKAGE_NAME .tlz)" = "$PACKAGE_NAME" ]; then
   EXTENSION="tlz"
+  if which plzip 1> /dev/null 2> /dev/null ; then
+    COMPRESSOR="plzip ${COMPRESS_OPTION} --threads=${THREADS} -c"
+  else
+    echo "WARNING:  plzip compression utility not found in \$PATH."
+    echo "WARNING:  package will not support multithreaded decompression."
+    if which lzip 1> /dev/null 2> /dev/null ; then
+      COMPRESSOR="lzip ${COMPRESS_OPTION} -c"
+    else
+      echo "ERROR:  lzip compression utility not found in \$PATH."
+      exit 3
+    fi
+  fi
+elif [ ! "$(basename $PACKAGE_NAME .tar.lz)" = "$PACKAGE_NAME" ]; then
+  EXTENSION="tar.lz"
+  if which plzip 1> /dev/null 2> /dev/null ; then
+    COMPRESSOR="plzip ${COMPRESS_OPTION} --threads=${THREADS} -c"
+  else
+    echo "WARNING:  plzip compression utility not found in \$PATH."
+    echo "WARNING:  package will not support multithreaded decompression."
+    if which lzip 1> /dev/null 2> /dev/null ; then
+      COMPRESSOR="lzip ${COMPRESS_OPTION} -c"
+    else
+      echo "ERROR:  lzip compression utility not found in \$PATH."
+      exit 3
+    fi
+  fi
 elif [ ! "$(basename $PACKAGE_NAME .tar.lzma)" = "$PACKAGE_NAME" ]; then
   EXTENSION="tar.lzma"
+  COMPRESSOR="lzma ${COMPRESS_OPTION} -c"
+  if ! which lzma 1> /dev/null 2> /dev/null ; then
+    echo "ERROR:  lzma compression utility not found in \$PATH."
+    exit 3
+  fi
 elif [ ! "$(basename $PACKAGE_NAME .txz)" = "$PACKAGE_NAME" ]; then
   EXTENSION="txz"
+  if [ ! "$XZ_THREADS_FORCED" = "yes" ]; then
+    # Two threads by default with xz due to memory failures on 32-bit. Not that
+    # it matters much... if upstream ever gets around to implementing multi-
+    # threaded decompression we'll revisit this default.  :-D
+    COMPRESSOR="xz ${COMPRESS_OPTION} --threads=2 -c"
+  else
+    COMPRESSOR="xz ${COMPRESS_OPTION} --threads=${THREADS} -c"
+  fi
+  if ! which xz 1> /dev/null 2> /dev/null ; then
+    echo "ERROR:  xz compression utility not found in \$PATH."
+    exit 3
+  fi
 elif [ ! "$(basename $PACKAGE_NAME .tar.xz)" = "$PACKAGE_NAME" ]; then
   EXTENSION="tar.xz"
+  if [ ! "$XZ_THREADS_FORCED" = "yes" ]; then
+    # Two threads by default with xz due to memory failures on 32-bit. Not that
+    # it matters much... if upstream ever gets around to implementing multi-
+    # threaded decompression we'll revisit this default.  :-D
+    COMPRESSOR="xz ${COMPRESS_OPTION} --threads=2 -c"
+  else
+    COMPRESSOR="xz ${COMPRESS_OPTION} --threads=${THREADS} -c"
+  fi
+  if ! which xz 1> /dev/null 2> /dev/null ; then
+    echo "ERROR:  xz compression utility not found in \$PATH."
+    exit 3
+  fi
 else
   EXTENSION="$(echo $PACKAGE_NAME | rev | cut -f 1 -d . | rev)"
   echo "ERROR:  Package extension .$EXTENSION is not supported."
@@ -170,36 +284,8 @@ if [ "$CWD" = "$TARGET_NAME" -o "." = "$TARGET_NAME" ]; then
   exit 2
 fi
 
-# Make sure external compression utility is available:
-case $EXTENSION in
-'tgz' | 'tar.gz' )
-  if ! which gzip 1> /dev/null 2> /dev/null ; then
-    echo "ERROR:  gzip compression utility not found in \$PATH."
-    exit 3
-  fi
-  ;;
-'tbz' | 'tar.bz2' )
-  if ! which bzip2 1> /dev/null 2> /dev/null ; then
-    echo "ERROR:  bzip2 compression utility not found in \$PATH."
-    exit 3
-  fi
-  ;;
-'tlz' | 'tar.lzma' )
-  if ! which lzma 1> /dev/null 2> /dev/null ; then
-    echo "ERROR:  lzma compression utility not found in \$PATH."
-    exit 3
-  fi
-  ;;
-'txz' | 'tar.xz' )
-  if ! which xz 1> /dev/null 2> /dev/null ; then
-    echo "ERROR:  xz compression utility not found in \$PATH."
-    exit 3
-  fi
-  ;;
-esac
-
 echo
-echo "Slackware package maker, version 3.141593."
+echo "Slackware package maker, version 3.14159265."
 echo
 echo "Searching for symbolic links:"
 # Get rid of possible pre-existing trouble:
@@ -303,36 +389,27 @@ fi
 echo "Creating Slackware package:  ${TARGET_NAME}/${TAR_NAME}.${EXTENSION}"
 echo
 rm -f ${TARGET_NAME}/${TAR_NAME}.${EXTENSION}
-case $EXTENSION in
-'tgz' | 'tar.gz' )
-  $TAR cvf - . | gzip -9c > ${TARGET_NAME}/${TAR_NAME}.${EXTENSION}
-  ERRCODE=$?
-  if [ ! $? = 0 ]; then
-    echo "ERROR:  gzip returned error code $? -- makepkg failed."
-  fi
-  ;;
-'tbz' | 'tar.bz2' )
-  $TAR cvf - . | bzip2 -9c > ${TARGET_NAME}/${TAR_NAME}.${EXTENSION}
-  ERRCODE=$?
-  if [ ! $ERRCODE = 0 ]; then
-    echo "ERROR:  bzip2 returned error code $ERRCODE -- makepkg failed."
-  fi
-  ;;
-'tlz' | 'tar.lzma' )
-  $TAR cvf - . | lzma -c > ${TARGET_NAME}/${TAR_NAME}.${EXTENSION}
-  ERRCODE=$?
-  if [ ! $ERRCODE = 0 ]; then
-    echo "ERROR:  lzma returned error code $ERRCODE -- makepkg failed."
-  fi
-  ;;
-'txz' | 'tar.xz' )
-  $TAR cvf - . | xz -c > ${TARGET_NAME}/${TAR_NAME}.${EXTENSION}
-  ERRCODE=$?
-  if [ ! $ERRCODE = 0 ]; then
-    echo "ERROR:  xz returned error code $ERRCODE -- makepkg failed."
-  fi
-  ;;
-esac
+
+# HISTORICAL NOTE 2/2018:
+# In the interest of maximizing portability of this script, we'll use find
+# and sed to create a filelist compatible with tar-1.13, and then use a
+# more modern tar version to create the archive.
+#
+# Other (but possibly less portable) ways to achieve the same result:
+#
+# Use the tar --transform and --show-transformed-names options:
+# tar --transform "s,^\./\(.\),\1," --show-transformed-names $ACLS $XATTRS -cvf - . | $COMPRESSOR > ${TARGET_NAME}/${TAR_NAME}.${EXTENSION}
+#
+# Use cpio:
+# find ./ | sed '2,$s,^\./,,' | cpio --quiet -ovHustar > ${TARGET_NAME}/${TAR_NAME}.tar
+
+# Create the package:
+find ./ | sed '2,$s,^\./,,' | tar --no-recursion $ACLS $XATTRS  -T - -cvf - | $COMPRESSOR > ${TARGET_NAME}/${TAR_NAME}.${EXTENSION}
+ERRCODE=$?
+if [ ! $ERRCODE = 0 ]; then
+  echo "ERROR:  $COMPRESSOR returned error code $ERRCODE -- makepkg failed."
+  exit 1
+fi
 
 # Warn of zero-length files:
 find . -type f -size 0c | while read file ; do
diff --git a/source/a/pkgtools/scripts/removepkg b/source/a/pkgtools/scripts/removepkg
--- a/source/a/pkgtools/scripts/removepkg
+++ b/source/a/pkgtools/scripts/removepkg
@@ -1,6 +1,50 @@
 #!/bin/sh
 # Slackware remove package script
 #
+# Copyright 1994, 1995, 1998  Patrick Volkerding, Moorhead, Minnesota USA
+# Copyright 2001, Slackware Linux, Inc., Concord, CA USA
+# Copyright 2009, 2015, 2016  Patrick J. Volkerding, Sebeka, MN, USA
+# All rights reserved.
+#
+# Redistribution and use of this script, with or without modification, is
+# permitted provided that the following conditions are met:
+#
+# 1. Redistributions of this script must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+#
+#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
+#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
+#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
+#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
+#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
+#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
+#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
+#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
+#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+#
+
+# Sun May 27 18:02:23 UTC 2018
+# Added --terse mode to print one line per removed package.
+#
+# Wed May 23 17:31:23 UTC 2018
+# Use file locking to prevent more than one copy of ldconfig from running at
+# a time.
+#
+# Thu Sep 15 17:46:28 UTC 2016 <volkerdi>
+# If removepkg is called with a short package name (no -$VERSION-$ARCH-$BUILD),
+# remove the most recently installed matching package, not the oldest one.
+#
+# Thu Sep 15 08:09:01 BST 2016 <mozes>
+# - Handle finding >1 match for a package.  Thanks to SeB on LQ for the feedback.
+#
+# Wed Sep 14 20:44:00 BST 2016 <mozes>
+# - Modify package_name function to cater for package file names that contain
+#   >=4 hyphens.
+#   Thanks to coralfang on LQ for the report and to Jim Hawkins for the patch.
+# - Modified to handle packages that contain file names with backslashes
+#   Thanks to aaazen on LQ for the report and the patch.
+#
 # Thu Sep 24 03:31:58 UTC 2015 <alphageek>
 # extract_links() sed adjusted to handle symlinks with spaces.
 #
@@ -76,28 +120,8 @@
 # Original Version from Slackware 3.0
 #
 
-# Copyright 1994, 1995, 1998  Patrick Volkerding, Moorhead, Minnesota USA
-# Copyright 2001, Slackware Linux, Inc., Concord, CA USA
-# Copyright 2009, 2015  Patrick J. Volkerding, Sebeka, MN, USA
-# All rights reserved.
-#
-# Redistribution and use of this script, with or without modification, is 
-# permitted provided that the following conditions are met:
-#
-# 1. Redistributions of this script must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
-#
-#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
-#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
-#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
-#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
-#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
-#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
-#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
-#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
-#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
-#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-#
+# Needed to find package names within the 'remove_packages' function:
+shopt -s extglob
 
 # Return a package name that has been stripped of the dirname portion
 # and any of the valid extensions (only):
@@ -120,6 +144,13 @@ fi
 ADM_DIR=$ROOT/var/log
 PRES_DIR=$TMP/preserved_packages
 
+# Lock directory for ldconfig... share it with installpkg so that upgradepkg
+# becomes properly ldconfig-locked, too.
+INSTLOCKDIR=${INSTLOCKDIR:-/run/installpkg-lock}
+if [ ! -d $INSTLOCKDIR ]; then
+  mkdir -p $INSTLOCKDIR
+fi
+
 # This simple cat_except() should be used on the installer,
 # since the busybox "find" can't handle the complex find
 # syntax:
@@ -131,8 +162,8 @@ PRES_DIR=$TMP/preserved_packages
 # removed when ROOT= is used:
 cat_except() {
   ( cd "$1" && \
-    if [ $(find . -type f -maxdepth 1 | wc -l) -ne 1 ]; then
-      cat $(find . -type f -maxdepth 1 | grep -v "$2")
+    if [ $(find . -type f -maxdepth 1 2> /dev/null | wc -l) -ne 1 ]; then
+      cat $(find . -type f -maxdepth 1 2> /dev/null | grep -v "$2") 2> /dev/null
     fi
   )
 }
@@ -166,11 +197,11 @@ keep_files() {
  while read FILE ; do
   if [ ! -d "$ROOT/$FILE" ]; then
    if [ -r "$ROOT/$FILE" ]; then
-    echo "  --> $ROOT/$FILE was found in another package. Skipping."
+    ! [ $TERSE ] && echo "  --> $ROOT/$FILE was found in another package. Skipping."
     preserve_file "$FILE"
    else
     if [ "$(echo $FILE | cut -b1-8)" != "install/" ]; then
-     echo "WARNING: Nonexistent $ROOT/$FILE was found in another package. Skipping."
+     ! [ $TERSE ] && echo "WARNING: Nonexistent $ROOT/$FILE was found in another package. Skipping."
     fi
    fi
   else
@@ -182,29 +213,31 @@ keep_files() {
 keep_links() {
  while read LINK ; do
   if [ -L "$ROOT/$LINK" ]; then
-   echo "  --> $ROOT/$LINK (symlink) was found in another package. Skipping."
+   ! [ $TERSE ] && echo "  --> $ROOT/$LINK (symlink) was found in another package. Skipping."
   else
-   echo "WARNING: Nonexistent $ROOT/$LINK (symlink) was found in another package. Skipping."
+   ! [ $TERSE ] && echo "WARNING: Nonexistent $ROOT/$LINK (symlink) was found in another package. Skipping."
   fi
  done
 }
 
 delete_files() {
- while read FILE ; do
+ local unset LC_ALL         # Locally (within this delete_files function) allow handling of backslashes
+ while read -r AFILE ; do   # do not expand backslashes on read
+  FILE=$(printf "%b" "$AFILE")   # unescape octal characters
   if [ ! -d "$ROOT/$FILE" ]; then
    if [ -r "$ROOT/$FILE" ]; then
     if [ "$ROOT/$FILE" -nt "$ADM_DIR/packages/$PKGNAME" ]; then
-     echo "WARNING: $ROOT/$FILE changed after package installation."
+     ! [ $TERSE ] && echo "WARNING: $ROOT/$FILE changed after package installation."
     fi
     if [ ! "$WARN" = "true" ]; then
-     echo "  --> Deleting $ROOT/$FILE"
+     ! [ $TERSE ] && echo "  --> Deleting $ROOT/$FILE"
      preserve_file "$FILE" && rm -f "$ROOT/$FILE"
     else
-     echo "  --> $ROOT/$FILE would be deleted"
+     ! [ $TERSE ] && echo "  --> $ROOT/$FILE would be deleted"
      preserve_file "$FILE"
     fi
    else
-    echo "  --> $ROOT/$FILE no longer exists. Skipping."
+    ! [ $TERSE ] && echo "  --> $ROOT/$FILE no longer exists. Skipping."
    fi
   else
    preserve_dir "$FILE"
@@ -216,13 +249,13 @@ delete_links() {
  while read LINK ; do
   if [ -L "$ROOT/$LINK" ]; then
    if [ ! "$WARN" = "true" ]; then
-    echo "  --> Deleting symlink $ROOT/$LINK"
+    ! [ $TERSE ] && echo "  --> Deleting symlink $ROOT/$LINK"
     rm -f "$ROOT/$LINK"
    else
-    echo "  --> $ROOT/$LINK (symlink) would be deleted"
+    ! [ $TERSE ] && echo "  --> $ROOT/$LINK (symlink) would be deleted"
    fi
   else
-   echo "  --> $ROOT/$LINK (symlink) no longer exists. Skipping."
+   ! [ $TERSE ] && echo "  --> $ROOT/$LINK (symlink) no longer exists. Skipping."
   fi
  done
 }
@@ -233,13 +266,13 @@ delete_dirs() {
   if [ -d "$ROOT/$DIR" ]; then
     if [ ! "$WARN" = "true" ]; then
       if [ $(ls -a "$ROOT/$DIR" | wc -l) -eq 2 ]; then
-        echo "  --> Deleting empty directory $ROOT/$DIR"
+        ! [ $TERSE ] && echo "  --> Deleting empty directory $ROOT/$DIR"
         rmdir "$ROOT/$DIR"
       else
-        echo "WARNING: Unique directory $ROOT/$DIR contains new files"
+        ! [ $TERSE ] && echo "WARNING: Unique directory $ROOT/$DIR contains new files"
       fi
     else
-     echo "  --> $ROOT/$DIR (dir) would be deleted if empty"
+     ! [ $TERSE ] && echo "  --> $ROOT/$DIR (dir) would be deleted if empty"
     fi
   fi
  done
@@ -250,33 +283,21 @@ delete_cats() {
  while read FILE ; do
    if [ -f "$ROOT/$FILE" ]; then
      if [ ! "$WARN" = "true" ]; then
-       echo "  --> Deleting $ROOT/$FILE (fmt man page)"
+       ! [ $TERSE ] && echo "  --> Deleting $ROOT/$FILE (fmt man page)"
        rm -f $ROOT/$FILE
      else
-       echo "  --> $ROOT/$FILE (fmt man page) would be deleted"
+       ! [ $TERSE ] && echo "  --> $ROOT/$FILE (fmt man page) would be deleted"
      fi
    fi
  done
 }
 
-package_name() {
-  STRING=$(pkgbase $1 | sed 's?-[^-]*-[^-]*-[^-]*$??')
-  # If we don't do this, commands run later will take the '-' to be an option
-  # and will destroy the package database.  Packages should not contain spaces
-  # in them.  Normally this type of problem results from a command line typo.
-  if [ "$(echo $STRING | cut -b 1)" = "-" ]; then
-    STRING="malformed-package-name-detected"
-  fi
-  echo $STRING
-}
-
 # Conversion to 'comm' utility by Mark Wisdom.
 # is pretty nifty! :^)
 remove_packages() {
- for PKGLIST in $* 
+ for PKGLIST in $*
  do
   PKGNAME=$(pkgbase $PKGLIST)
-  echo
   # If we don't have a package match here, then we will attempt to find
   # a package using the long name format (name-version-arch-build) for
   # which the base package name was given.  On a properly-managed machine,
@@ -285,24 +306,22 @@ remove_packages() {
   # be removed.  If you want to remove them all, you'll need to run
   # removepkg again until it removes all the same-named packages.
   if [ ! -e $ADM_DIR/packages/$PKGNAME ]; then
-   SHORT="$(package_name $PKGNAME)"
-   for long_package in $ADM_DIR/packages/${PKGNAME}* ; do
-    if [ "$SHORT" = "$(package_name $long_package)" ]; then
-     PKGNAME="$(basename $long_package)"
+    # Short name not found - finally try looking for full name - e.g. foo-1.0-arm-1
+    pushd $ADM_DIR/packages > /dev/null
+    # Don't set PKGNAME if there are no matches:
+    if [ ! "$( ls -1 $PKGNAME-+([^-])-+([^-])-+([^-]) 2>/dev/null | wc -l  )" = "0" ]; then
+      # If there is more than one package with the same name, set PKGNAME to the
+      # most recently installed version.  This does not affect the behavior of
+      # upgradepkg, which always removes all other existing versions of the
+      # same package.
+      PKGNAME=$( ls -1t $PKGNAME-+([^-])-+([^-])-+([^-]) 2> /dev/null | head -n1 )
     fi
-   done
-  fi
-
-  if [ ! -e $ADM_DIR/packages/$PKGNAME ]; then
-    long_package=$(ls -1 $ADM_DIR/packages/${PKGNAME}* | grep -m 1 "^${PKGNAME}-[^-]*-[^-]*-[^-]*$")
-    if [ -e "$long_package" ]; then
-      PKGNAME=$(basename $long_package)
-    fi
+    popd > /dev/null
   fi
 
   if [ -r $ADM_DIR/packages/$PKGNAME ]; then
    if [ ! "$WARN" = true ]; then
-    echo "Removing package $ADM_DIR/packages/$PKGNAME..."
+    echo "Removing package: $(basename $ADM_DIR/packages/$PKGNAME)"
    fi
    if fgrep "./" $ADM_DIR/packages/$PKGNAME 1> /dev/null 2>&1; then
     TRIGGER="^\.\/"
@@ -310,7 +329,7 @@ remove_packages() {
     TRIGGER="FILE LIST:"
    fi
    if [ ! "$WARN" = true ]; then
-    echo "Removing files:"
+    ! [ $TERSE ] && echo "Removing files:"
    fi
    sed -n "/$TRIGGER/,/^$/p" < $ADM_DIR/packages/$PKGNAME | \
     fgrep -v "FILE LIST:" | sort -u > $TMP/delete_list$$
@@ -325,7 +344,7 @@ remove_packages() {
     comm -12 $TMP/del_link_list$$ $TMP/required_list$$ | keep_links
     comm -23 $TMP/del_link_list$$ $TMP/required_list$$ | delete_links
    else
-    cat $ADM_DIR/scripts/* | extract_links | \
+    cat $ADM_DIR/scripts/* 2> /dev/null | extract_links | \
      sort -u > $TMP/required_links$$
     mv $TMP/required_list$$ $TMP/required_files$$
     sort -u $TMP/required_links$$ $TMP/required_files$$ >$TMP/required_list$$
@@ -348,22 +367,27 @@ remove_packages() {
     fi
    fi
    if [ ! "$WARN" = "true" ]; then
-    for DIR in $ADM_DIR/removed_packages $ADM_DIR/removed_scripts ; do
-     if [ ! -d $DIR ] ; then mkdir -p $DIR ; chmod 755 $DIR ; fi
-    done
+    mkdir -p $ADM_DIR/removed_packages $ADM_DIR/removed_scripts
     mv $ADM_DIR/packages/$PKGNAME $ADM_DIR/removed_packages
     if [ -r $ADM_DIR/scripts/$PKGNAME ]; then
      mv $ADM_DIR/scripts/$PKGNAME $ADM_DIR/removed_scripts
     fi
    fi
   else
-   echo "No such package: $ADM_DIR/packages/$PKGNAME. Can't remove."
+   echo "No such package: $(basename $ADM_DIR/packages/$PKGNAME). Can't remove."
+  fi
+  # In the case where a library and symlink are removed but an earlier version
+  # remains on the machine, this will link it up and save potential problems:
+  if [ "$ROOT" = "" ] && [ -x /sbin/ldconfig ]; then
+   ( flock 9 || exit 11
+    /sbin/ldconfig 2> /dev/null
+   ) 9> $INSTLOCKDIR/ldconfig.lock
   fi
  done
 }
 
 if [ "$#" = "0" ]; then
-  echo "Usage: $(basename $0) [-copy] [-keep] [-preserve] [-warn] packagename ..."; exit 1
+  echo "Usage: $(basename $0) [--copy] [--keep] [--preserve] [--terse] [--warn] packagename ..."; exit 1
 fi
 
 while : ; do
@@ -371,6 +395,7 @@ while : ; do
   -copy | --copy) WARN=true; PRESERVE=true; shift;;
   -keep | --keep) KEEP=true; shift;;
   -preserve | --preserve) PRESERVE=true; shift;;
+  -terse | --terse) TERSE=0; shift;;
   -warn | --warn) WARN=true; shift;;
   -* | --*) echo "Usage: $(basename $0) [-copy] [-keep] [-preserve] [-warn] packagename ..."; exit 1;;
   *) break
@@ -378,6 +403,7 @@ while : ; do
 done
 
 if [ "$WARN" = "true" ]; then
+ unset TERSE
  echo "Only warning... not actually removing any files."
  if [ "$PRESERVE" = "true" ]; then
   echo "Package contents is copied to $PRES_DIR."
@@ -392,4 +418,3 @@ else
 fi
 
 remove_packages $*
-
diff --git a/source/a/pkgtools/scripts/upgradepkg b/source/a/pkgtools/scripts/upgradepkg
--- a/source/a/pkgtools/scripts/upgradepkg
+++ b/source/a/pkgtools/scripts/upgradepkg
@@ -13,7 +13,7 @@
 #
 #  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
 #  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
+#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
 #  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 #  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 #  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
@@ -22,24 +22,32 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
-# Modified to handle either old 8.3 or new package-version-arch-build.tgz
-# packages, Sat Nov 17 14:25:58 PST 2001 volkerdi
+# Thu May 24 20:23:55 UTC 2018
+# Added --terselength option to set the line length in --terse mode.
+# Use a lockfile to prevent output collisions in --terse mode.
 #
-# Rewritten to clean out _all_ old packages of a given basename, not just
-# the first one found, Thu Apr  4 01:01:05 PST 2002 volkerdi
+# Wed May 23 03:35:28 UTC 2018
+# Added --terse, which limits screen output to one line per package.
 #
-# Added --install-new and --reinstall, Fri May 31 14:11:14 PDT 2002 volkerdi
-# Added --dry-run, Sat Apr 26 18:13:29 PDT 2003
+# Sat 17 Jan 16:21:32 UTC 2015  mina86
+# Various optimisation mostly resolving around avoiding having to fork
+# and call cut, basename and other helper commands.  Slight
+# refactoring of code calling removepkg.
 #
 # Sat Apr 25 21:18:53 UTC 2009
 # Support new compression types and package extensions.
 # Converted to use new pkgbase() function to remove pathname and
 # valid package extensions.
 #
-# Sat 17 Jan 16:21:32 UTC 2015  mina86
-# Various optimisation mostly resolving around avoiding having to fork
-# and call cut, basename and other helper commands.  Slight
-# refactoring of code calling removepkg.
+# Added --dry-run, Sat Apr 26 18:13:29 PDT 2003
+#
+# Added --install-new and --reinstall, Fri May 31 14:11:14 PDT 2002 volkerdi
+#
+# Rewritten to clean out _all_ old packages of a given basename, not just
+# the first one found, Thu Apr  4 01:01:05 PST 2002 volkerdi
+#
+# Modified to handle either old 8.3 or new package-version-arch-build.tgz
+# packages, Sat Nov 17 14:25:58 PST 2001 volkerdi
 
 # Return a package name that has been stripped of the dirname portion
 # and any of the valid extensions (only):
@@ -58,20 +66,20 @@ Usage: upgradepkg newpackage [newpackage2 ... ]
        upgradepkg oldpackage%newpackage [oldpackage2%newpackage2 ... ]
 
 Upgradepkg upgrades a Slackware package (.tgz, .tbz, .tlz, .txz) from an
-older version to a newer one.  It does this by INSTALLING the new package
+older version to a newer one. It does this by INSTALLING the new package
 onto the system, and then REMOVING any files from the old package that
-aren't in the new package.  If the old and new packages have the same
-name, a single argument is all that is required.  If the packages have
+aren't in the new package. If the old and new packages have the same
+name, a single argument is all that is required. If the packages have
 different names, supply the name of the old package followed by a percent
-symbol (%), then the name of the new package.  Do not add any extra
+symbol (%), then the name of the new package. Do not add any extra
 whitespace between pairs of old/new package names.
 
 Before upgrading a package, save any configuration files (such as in /etc)
-that you wish to keep.  Sometimes these will be preserved, but it depends
-on the package.  If you want to force new versions of the config files
+that you wish to keep. Sometimes these will be preserved, but it depends
+on the package. If you want to force new versions of the config files
 to be installed, remove the old ones manually prior to running upgradepkg.
 
-To upgrade in a directory other than / (such as /mnt):  
+To upgrade in a directory other than / (such as /mnt):
 
    ROOT=/mnt upgradepkg package.tgz (or .tbz, .tlz, .txz)
 
@@ -103,41 +111,71 @@ if [ "$1" = "" -o "$1" = "--help" -o "$1" = "-?" ]; then
   exit 1;
 fi
 
-# Arg processing loop.  These must come before any packages are listed.
+# Create a lockfile directory if it doesn't exist. We can use it to prevent
+# output line collisions in --terse mode.
+INSTLOCKDIR=${INSTLOCKDIR:-/run/upgradepkg-lock}
+if [ ! -d $INSTLOCKDIR ]; then
+  mkdir -p $INSTLOCKDIR
+fi
+
+# Set default line length for terse mode:
+if which tput 1> /dev/null 2> /dev/null ; then
+  TERSELENGTH=$(tput cols)
+else
+  TERSELENGTH=80
+fi
+
+# Arg processing loop. These must come before any packages are listed.
 while [ 0 ]; do
-  if [ "$1" = "--no-paranoia" ]; then
-    # Enable --no-paranoia mode.  This is so not-recommended that we're
-    # not even going to document it. ;)   If a file used to be directly
+  if [ "$1" = "-no-paranoia" -o "$1" = "--no-paranoia" ]; then
+    # Enable --no-paranoia mode. This is so not-recommended that we're
+    # not even going to document it. ;) If a file used to be directly
     # managed and now is moved into place, using --no-paranoia will cause
-    # it to improperly disappear.  It does slightly speed things up, though.
+    # it to improperly disappear. It does slightly speed things up, though.
     # Don't use it.
     NOT_PARANOID="true"
     shift 1
-  elif [ "$1" = "--install-new" ]; then
+  elif [ "$1" = "-install-new" -o "$1" = "--install-new" ]; then
     # Install packages that do not already have an installed version.
     # The usual default is to skip them.
     INSTALL_NEW="yes"
     shift 1
-  elif [ "$1" = "--reinstall" ]; then
+  elif [ "$1" = "-reinstall" -o "$1" = "--reinstall" ]; then
     # Reinstall packages even if the installed one is the same version.
     REINSTALL="true"
     shift 1
-  elif [ "$1" = "--verbose" -o "$1" = "-v" ]; then
+  elif [ "$1" = "-verbose" -o "$1" = "--verbose" -o "$1" = "-v" ]; then
     # We're adding a --verbose mode that doesn't filter removepkg as much
     VERBOSE="verbose"
     shift 1
-  elif [ "$1" = "--dry-run" ]; then
+  elif [ "$1" = "-dry-run" -o "$1" = "--dry-run" ]; then
     # Output a report about which packages would be installed or upgraded
     # but don't actually perform the upgrades.
     DRY_RUN="true"
     shift 1
+  elif [ "$1" = "-terse" -o "$1" = "--terse" ]; then
+    # Output one line per installed/upgraded package by calling installpkg
+    # with --terse. Use TERSE=0 for true, so we can check with test.
+    TERSE=0
+    shift 1
+  elif [ "$1" = "-terselength" -o "$1" = "--terselength" ]; then
+    # Set line length in --terse mode:
+    TERSELENGTH=$2
+    shift 2
   else # no more args
     break;
   fi
 done # processing args
 
+# A couple not-really-documented features to adjust the behavior of --terse
+# mode. These need to be used in addition to --terse, and passed in as
+# environment variables.
+# PLAINTERSE=0 (This outputs the standard terse line from installpkg, rather
+# than prefixing it with "Upgrading:" or "Installing:")
+# INFOBOX=0 (This outputs the installpkg --infobox instead of a terse line)
+
 # Here's a function to figure out the package name from one of those
-# new long filenames.  We'll need this to double check the name of the
+# new long filenames. We'll need this to double check the name of the
 # old package.
 
 package_name() {
@@ -170,7 +208,7 @@ for ARG; do
   # Simple package integrity check:
   if ! [ -f "$NEW" ]; then
     ERRCODE=4
-    echo "Cannot install $ARG:  file not found"
+    ! [ $TERSE ] && echo "Cannot install $ARG:  file not found"
     continue;
   fi
 
@@ -186,7 +224,7 @@ for ARG; do
   # Make sure the extension is valid:
   if [ "$NNAME" = "$NEW" ]; then
     # We won't throw an ERRCODE for this, but the package is skipped:
-    echo "Cannot install $OLD:  invalid package extension"
+    ! [ $TERSE ] && echo "Cannot install $OLD: invalid package extension"
     continue;
   fi
 
@@ -204,31 +242,42 @@ for ARG; do
   fi
 
   # Test to see if both the old and new packages are where we expect them
-  # to be -- skip to the next package (or package pair) if anything's wrong:
+  # to be - skip to the next package (or package pair) if anything's wrong:
 
   if [ ! -r $ROOT/var/log/packages/$OLD ]; then
     if [ ! "$INSTALL_NEW" = "yes" ]; then
       if [ "$DRY_RUN" = "true" ]; then
         echo "$OLD would not be upgraded (no installed package named $SHORT)."
       else
-        echo
-        echo "Error:  there is no installed package named $OLD."
-        echo "        (looking for $ROOT/var/log/packages/$OLD)"
-        echo
+        ! [ $TERSE ] && echo
+        ! [ $TERSE ] && echo "Error: there is no installed package named $OLD."
+        ! [ $TERSE ] && echo "       (looking for $ROOT/var/log/packages/$OLD)"
+        ! [ $TERSE ] && echo
       fi
       ERRCODE=1
     else # --install-new was given, so install the new package:
       if [ "$DRY_RUN" = "true" ]; then
         echo "$NEW would be installed (new package)."
       else
-        cat << EOF
+        if [ $PLAINTERSE ]; then
+          /sbin/installpkg --terse --terselength $TERSELENGTH $INCOMINGDIR/$NNAME
+        elif [ $INFOBOX ]; then
+          /sbin/installpkg --infobox $INCOMINGDIR/$NNAME
+        elif [ $TERSE ]; then
+          OUTPUTLINE="$(/sbin/installpkg --terse --terselength $(expr $TERSELENGTH - 12) $INCOMINGDIR/$NNAME)"
+          ( flock 9 || exit 11
+            echo "Installing: ${OUTPUTLINE}"
+          ) 9> $INSTLOCKDIR/outputline.lock
+        else
+          cat << EOF
 
 +==============================================================================
 | Installing new package $INCOMINGDIR/$NNAME
 +==============================================================================
 
 EOF
-        /sbin/installpkg $INCOMINGDIR/$NNAME
+          /sbin/installpkg $INCOMINGDIR/$NNAME
+        fi
       fi
     fi
     continue;
@@ -236,9 +285,9 @@ EOF
     if [ "$DRY_RUN" = "true" ]; then
       echo "$NEW incoming package not found (command line)."
     else
-      echo
-      echo "Error:  incoming package $INCOMINGDIR/$NNAME not found."
-      echo
+      ! [ $TERSE ] && echo
+      ! [ $TERSE ] && echo "Error: incoming package $INCOMINGDIR/$NNAME not found."
+      ! [ $TERSE ] && echo
     fi
     ERRCODE=1
     continue;
@@ -251,13 +300,15 @@ EOF
       if [ "$DRY_RUN" = "true" ]; then
         echo "$NEW would be skipped (already installed)."
       else
-        cat << EOF
+        if ! [ $TERSE ]; then
+          cat << EOF
 
 +==============================================================================
 | Skipping package $NEW (already installed)
 +==============================================================================
 
 EOF
+        fi
       fi
       continue;
     fi
@@ -292,57 +343,73 @@ EOF
   done
 
   # Print a banner for the current upgrade:
-  cat << EOF
+  if ! [ $TERSE ]; then
+    cat << EOF
 
 +==============================================================================
 | Upgrading $OLD package using $INCOMINGDIR/$NNAME
 +==============================================================================
-
 EOF
-
+  fi
   # Next, the new package is pre-installed:
   if [ "$VERBOSE" = "verbose" ]; then
-    /sbin/installpkg $INCOMINGDIR/$NNAME
-    RETCODE=$?
+    if ! [ $TERSE ]; then
+      /sbin/installpkg $INCOMINGDIR/$NNAME
+      RETCODE=$?
+    else
+      /sbin/installpkg $INCOMINGDIR/$NNAME 1> /dev/null
+      RETCODE=$?
+    fi
   else
-    echo "Pre-installing package $NEW..."
-    /sbin/installpkg $INCOMINGDIR/$NNAME 1> /dev/null
-    RETCODE=$?
+    if [ $PLAINTERSE ]; then
+      /sbin/installpkg --terse --terselength $TERSELENGTH $INCOMINGDIR/$NNAME
+    elif [ $INFOBOX ]; then
+      /sbin/installpkg --infobox $INCOMINGDIR/$NNAME
+    elif [ $TERSE ]; then
+      OUTPUTLINE="$(/sbin/installpkg --terse --terselength $(expr $TERSELENGTH - 12) $INCOMINGDIR/$NNAME)"
+      RETCODE=$?
+      ( flock 9 || exit 11
+        echo "Upgrading:  ${OUTPUTLINE}"
+      ) 9> $INSTLOCKDIR/outputline.lock
+    else
+      echo "Pre-installing package $NEW..."
+      /sbin/installpkg $INCOMINGDIR/$NNAME 1> /dev/null
+      RETCODE=$?
+    fi
   fi
   # Make sure that worked:
   if [ ! $RETCODE = 0 ]; then
-    echo "ERROR:  Package $INCOMINGDIR/$NNAME did not install"
-    echo "correctly.  You may need to reinstall your old package"
-    echo "to avoid problems.  Make sure the new package is not"
+    echo "ERROR: Package $INCOMINGDIR/$NNAME did not install"
+    echo "correctly. You may need to reinstall your old package"
+    echo "to avoid problems. Make sure the new package is not"
     echo "corrupted."
-    sleep 30
+    sleep 15
     # Skip this package, but still try to proceed.  Good luck...
     continue;
   fi
-
   # Now, the leftovers from the old package(s) can go.  Pretty simple, huh? :)
-  for rempkg in "$ROOT/var/log/packages/"*"-$TIMESTAMP"; do
-    if [ "$VERBOSE" = "verbose" ]; then
-      /sbin/removepkg "${rempkg##*/}"
-    else
-      /sbin/removepkg "${rempkg##*/}" | grep -v 'Skipping\.\|Removing files:'
-    fi
-  done
-  echo
-
+  ( flock 9 || exit 11
+    for rempkg in "$ROOT/var/log/packages/"*"-$TIMESTAMP"; do
+      if [ "$VERBOSE" = "verbose" ]; then
+        /sbin/removepkg "${rempkg##*/}"
+      elif ! [ $TERSE ]; then
+        /sbin/removepkg "${rempkg##*/}" | grep -v 'Skipping\.\|Removing files:'
+      else
+        /sbin/removepkg "${rempkg##*/}" > /dev/null
+      fi
+    done
+  ) 9> $INSTLOCKDIR/removepkg.lock
   # Again!  Again!
   # Seriously, the reinstalling of a package can be crucial if any files
   # shift location, so we should always reinstall as the final step:
   if [ ! "$NOT_PARANOID" = "true" ]; then
-    /sbin/installpkg $INCOMINGDIR/$NNAME
+    if ! [ $TERSE ]; then
+      /sbin/installpkg $INCOMINGDIR/$NNAME
+    else
+      /sbin/installpkg $INCOMINGDIR/$NNAME 1> /dev/null
+    fi
   fi
-
-  echo "Package $OLD upgraded with new package $INCOMINGDIR/$NNAME."
+  ! [ $TERSE ] && echo "Package $OLD upgraded with new package $INCOMINGDIR/$NNAME."
   ERRCODE=0
 done
-
-if [ ! "$DRY_RUN" = "true" ]; then
-  echo
-fi
 exit $ERRCODE
-
diff --git a/source/a/util-linux/util-linux.SlackBuild b/source/a/util-linux/util-linux.SlackBuild
--- a/source/a/util-linux/util-linux.SlackBuild
+++ b/source/a/util-linux/util-linux.SlackBuild
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright 2008, 2009, 2010, 2011, 2012, 2013, 2015  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2008, 2009, 2010, 2011, 2012, 2013, 2015, 2017, 2018  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -22,14 +22,17 @@
 
 # Slackware build script for util-linux
 
+cd $(dirname $0) ; CWD=$(pwd)
+
+PKGNAM=util-linux
 VERSION=${VERSION:-$(echo util-linux*.tar.xz | cut -d - -f 3  | rev | cut -f 3- -d . | rev)}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 
 ADJTIMEXVERS=1.29
 SETSERIALVERS=2.17
 ZIPTOOLVERS=1.4.0
 
-NUMJOBS=${--j8}
+NUMJOBS=${NUMJOBS:-" -j7 "}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -39,6 +42,14 @@ if [ -z "$ARCH" ]; then
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
   esac
+fi
+
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
+  exit 0
 fi
 
 if [ "$ARCH" = "i586" ]; then
@@ -55,7 +66,6 @@ else
   LIBDIRSUFFIX=""
 fi
 
-CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-util-linux
 
@@ -77,7 +87,15 @@ find . \
 # 83 back to "Linux swap":
 zcat $CWD/util-linux.fdisk-no-solaris.diff.gz | patch -p1 --verbose || exit 1
 
-CFLAGS="$SLKCFLAGS" \
+# This just call the configure script with $1 either being 2 for python2
+# or 3 for python3.
+#
+# The releasenotes say to use --runstatedir, but it doesn't work and the
+# configure script fails. So we'll leave things using localstatedir, but
+# check again later:
+#
+#   --runstatedir=/run
+configure_with_python(){
 ./configure \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
@@ -88,15 +106,15 @@ CFLAGS="$SLKCFLAGS" \
   --docdir=/usr/doc/util-linux-$VERSION \
   --disable-static \
   --enable-agetty \
-  --disable-eject \
   --enable-kill \
   --disable-last \
+  --enable-libmount-support-mtab \
   --enable-line \
   --enable-mesg \
   --enable-partx \
+  --enable-pg \
   --enable-raw \
   --enable-rename \
-  --enable-reset \
   --disable-login \
   --enable-schedutils \
   --enable-wall \
@@ -106,19 +124,24 @@ CFLAGS="$SLKCFLAGS" \
   --enable-libmount \
   --enable-libuuid \
   --disable-uuidd \
-  --with-python=2 \
-  --without-readline \
-  --build=$ARCH-slackware-linux \
-  || exit 1
+  --with-python=$1 \
+  --build=$ARCH-slackware-linux
+}
 
-# UNUSED, but maybe needed if we enable readline here:
-#
-# Yet another project that doesn't seem to get that -readline requires either
-# -ltermcap or -lncurses on systems that don't make assumptions...
-#sed -i -e 's|-lreadline|\0 -lncursesw|g' Makefile
+CFLAGS="$SLKCFLAGS" \
+  configure_with_python 2 || exit 1
 
-make $NUMBJOBS || make || exit 1
-make install DESTDIR=$PKG || make install DESTDIR=$PKG
+make $NUMJOBS || make || exit 1
+make install DESTDIR=$PKG || exit 1
+
+# Build python3 bindings for libmount:
+make clean
+CFLAGS="$SLKCFLAGS" \
+  configure_with_python 3 || exit 1
+make \
+  install-pylibmountexecLTLIBRARIES \
+  install-pylibmountexecPYTHON \
+  DESTDIR=$PKG || exit 1
 
 # Remove all overlap with the shadow package, since --disable-login doesn't quite do that:
 rm $PKG/sbin/nologin $PKG/usr/man/man8/nologin.8 $PKG/sbin/sulogin $PKG/usr/man/man8/sulogin.8
@@ -161,7 +184,7 @@ cp -a ddate $PKG/usr/bin
 cat ddate.1 > $PKG/usr/man/man1/ddate.1
 chown root:root $PKG/usr/bin/ddate
 
-# Build ziptool
+# Build ziptool (install as jaztool to avoid conflict with libzip):
 cd $TMP || exit 1
 rm -rf ziptool-$ZIPTOOLVERS
 tar xvf $CWD/ziptool-$ZIPTOOLVERS.tar.xz || exit 1
@@ -172,12 +195,12 @@ cat $CWD/scsi_ioctl.h > scsi/scsi_ioctl.h
 chown -R root:root .
 make || exit 1
 strip ziptool
-cat ziptool > $PKG/sbin/ziptool
-chmod 0755 $PKG/sbin/ziptool
+cat ziptool > $PKG/sbin/jaztool
+chmod 0755 $PKG/sbin/jaztool
 mkdir -p $PKG/usr/doc/ziptool-$ZIPTOOLVERS
 cp -a README $PKG/usr/doc/ziptool-$ZIPTOOLVERS
 chmod 644 $PKG/usr/doc/ziptool-$ZIPTOOLVERS/*
-cat ziptool.1.gz > $PKG/usr/man/man1/ziptool.1.gz
+cat ziptool.1.gz > $PKG/usr/man/man1/jaztool.1.gz
 
 # Build bsdstrings
 cd $TMP || exit 1
@@ -187,34 +210,9 @@ cd bsdstrings || exit 1
 zcat $CWD/bsdstrings-util-linux_overflow.diff.gz | patch -p1 --verbose || exit 1
 make || exit 1
 strip strings
-cat strings > $PKG/usr/bin/strings
-chmod 0755 $PKG/usr/bin/strings
-cat strings.1 | gzip -9c > $PKG/usr/man/man1/strings.1.gz
-
-# Add just the hostname utilities from net-tools, so that anyone
-# installing just the A series will not have a hostname (null):
-cd $TMP || exit 1
-rm -rf net-tools-1.60.20120726git
-tar xvf $CWD/net-tools-1.60.20120726git.tar.xz
-cd net-tools-1.60.20120726git
-zcat $CWD/net-tools.config.h.gz > config.h
-make
-make hostname
-strip hostname
-cat hostname > $PKG/bin/hostname
-chmod 755 $PKG/bin/hostname
-chown root:root $PKG/bin/hostname
-( cd $PKG/bin
-  ln -sf hostname dnsdomainname
-  ln -sf hostname nisdomainname
-  ln -sf hostname ypdomainname
-  ln -sf hostname domainname
-)
-cd man/en_US
-for page in hostname.1 dnsdomainname.1 nisdomainname.1 ypdomainname.1 \
-domainname.1 ; do
-  cat $page | gzip -9c > $PKG/usr/man/man1/$page.gz
-done
+cat strings > $PKG/usr/bin/strings-BSD
+chmod 0755 $PKG/usr/bin/strings-BSD
+cat strings.1 | gzip -9c > $PKG/usr/man/man1/strings-BSD.1.gz
 
 # Build adjtimex
 cd $TMP || exit 1
@@ -268,7 +266,7 @@ cd $TMP/util-linux-$VERSION # Go back home :)
 ( cd $PKG/sbin
   ln -s ../bin/mount .
   ln -s ../bin/umount .
-  ln -s ziptool jaztool
+  #ln -s ziptool jaztool
   ln -s hwclock clock
   cd $PKG/usr/sbin
   ln -s ../../sbin/cfdisk .
@@ -281,13 +279,16 @@ cd $TMP/util-linux-$VERSION # Go back home :)
   ln -s ../../bin/more .
   ln -s ../../sbin/raw .
   cd $PKG/usr/man/man1
-  ln -s ziptool.1 jaztool.1
+  #ln -s ziptool.1 jaztool.1
   cd $PKG/usr/man/man8
   ln -s hwclock.8 clock.8
 )
 
 find $PKG | xargs file | grep -e "executable" -e "shared object" \
   | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+
+# Don't ship .la files:
+rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
 
 # Compress and if needed symlink the man pages:
 if [ -d $PKG/usr/man ]; then
@@ -309,8 +310,9 @@ rm $PKG/usr/info/dir
 gzip -9 $PKG/usr/info/*
 
 mkdir -p $PKG/usr/doc/util-linux-$VERSION
-cp -a AUTHORS COPYING DEPRECATED NEWS README* TODO \
-  docs/v${VERSION}-ReleaseNotes \
+cp -a AUTHORS COPYING* DEPRECATED NEWS README* \
+  Documentation/v${VERSION}-ReleaseNotes \
+  Documentation/licenses/* Documentation/{TODO,*.txt} \
   $PKG/usr/doc/util-linux-$VERSION
 
 mkdir $PKG/install
diff --git a/source/ap/ghostscript/ghostscript.SlackBuild b/source/ap/ghostscript/ghostscript.SlackBuild
--- a/source/ap/ghostscript/ghostscript.SlackBuild
+++ b/source/ap/ghostscript/ghostscript.SlackBuild
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2016  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2016, 2017, 2018  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,13 +20,14 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=ghostscript
-if [ -r gnu-ghostscript-*.tar.xz ]; then
+if [ -r gnu-ghostscript-*.tar.?z ]; then
   SRCPREFIX="gnu-"
 fi
-VERSION=${VERSION:-$(echo $SRCPREFIX$PKGNAM-*.tar.xz | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-2}
+VERSION=${VERSION:-$(echo $SRCPREFIX$PKGNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
+BUILD=${BUILD:-3}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -38,9 +39,16 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
+  exit 0
+fi
+
 NUMJOBS=${NUMJOBS:-" -j7 "}
 
-CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-${PKGNAM}
 rm -rf $PKG
@@ -62,8 +70,8 @@ fi
 
 cd $TMP
 rm -rf ${SRCPREFIX}${PKGNAM}-${VERSION}
-tar xvf $CWD/${SRCPREFIX}${PKGNAM}-$VERSION.tar.xz || exit 1
-cd ${SRCPREFIX}${PKGNAM}-$VERSION
+tar xvf $CWD/${SRCPREFIX}${PKGNAM}-$VERSION.tar.?z || exit 1
+cd ${SRCPREFIX}${PKGNAM}-$VERSION || exit 1
 
 # Remove unmaintained garbage:
 rm -rf freetype jpeg lcms2 libpng libtiff png tiff zlib
@@ -93,7 +101,7 @@ find . \
   --enable-static=no \
   --program-prefix= \
   --program-suffix= \
-  --build=$ARCH-slackware-linux
+  --build=$ARCH-slackware-linux || exit 1
   make $NUMJOBS || make || exit 1
   make install || exit 1
   make install DESTDIR=$PKG || exit 1
@@ -106,6 +114,7 @@ CFLAGS="$SLKCFLAGS" \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --sysconfdir=/etc \
   --mandir=/usr/man \
+  --docdir=/usr/share/ghostscript/$VERSION/tmpdoc \
   --with-fontpath=/usr/share/fonts/TTF \
   --with-ijs \
   --disable-compile-inits \
@@ -114,7 +123,7 @@ CFLAGS="$SLKCFLAGS" \
   --enable-cups \
   --program-prefix= \
   --program-suffix= \
-  --build=$ARCH-slackware-linux
+  --build=$ARCH-slackware-linux || exit 1
 
 # Build and install:
 make $NUMJOBS || make || exit 1
@@ -122,6 +131,11 @@ make install DESTDIR=$PKG || exit 1
 make clean || exit 1
 make $NUMJOBS so || make so || exit 1
 make soinstall DESTDIR=$PKG || exit 1
+
+# Add back ijs-config, which is needed by at least gutenprint to find IJS
+# and produce a ghostscript driver:
+cat $CWD/ijs-config | sed -e "s/lib64/lib${LIBDIRSUFFIX}/g" > $PKG/usr/bin/ijs-config
+chmod 755 $PKG/usr/bin/ijs-config
 
 # Replace the default cidfmap with one containing additional
 # support for CJK printing:
@@ -132,34 +146,25 @@ if [ -r $PKG/usr/share/ghostscript/*.*/Resource/Init/cidfmap ]; then
   zcat $CWD/cidfmap.gz > $PKG/usr/share/ghostscript/${SHARE_VERSION}/Resource/Init/cidfmap.new
 fi
 
-### Moved to cups-filters...
-## Many programs expect to find this filter with the old name:
-#( cd $PKG/usr/lib${LIBDIRSUFFIX}/cups/filter
-#  if [ ! -e pstoraster ]; then
-#    ln -sf gstoraster pstoraster
-#  fi
-#)
-
 # Strip binaries:
 ( cd $PKG
   find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
   find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 )
 
-# Compress and link manpages, if any:
-if [ -d $PKG/usr/man ]; then
-  ( cd $PKG/usr/man
-    for manpagedir in $(find . -type d -name "man*") ; do
-      ( cd $manpagedir
-        for eachpage in $( find . -type l -maxdepth 1) ; do
-          ln -s $( readlink $eachpage ).gz $eachpage.gz
-          rm $eachpage
-        done
-        gzip -9 *.*
-      )
-    done
-  )
-fi
+# Don't ship .la files:
+pushd $PKG
+  for lafile in usr/lib${LIBDIRSUFFIX}/*.la ; do
+    rm -f ${lafile} /${lafile}
+  done
+popd
+
+# Compress manual pages:
+find $PKG/usr/man -type f -exec gzip -9 {} \;
+for i in $( find $PKG/usr/man -type l ) ; do
+  ln -s $( readlink $i ).gz $i.gz
+  rm $i
+done
 
 # Compress info files, if any:
 if [ -d $PKG/usr/info ]; then
@@ -168,6 +173,16 @@ if [ -d $PKG/usr/info ]; then
     gzip -9 *
   )
 fi
+
+# gs9.23 fails if you try to have --docdir put things in the proper place.
+# Not much choice but to have things put in the wrong place and then move them.
+# First, remove broken symlinks:
+rm -f $PKG/usr/share/ghostscript/$VERSION/doc $PKG/usr/share/ghostscript/$VERSION/tmpdoc/$VERSION/$VERSION
+# Then, move the docs to the proper location:
+mv $PKG/usr/share/ghostscript/$VERSION/tmpdoc/$VERSION $PKG/usr/share/ghostscript/$VERSION/doc
+# Remove this (probably empty) directory:
+rm -rf $PKG/usr/share/ghostscript/$VERSION/tmpdoc
+# And finally, pray for upstream to quit drinking while coding. ;-)
 
 # Add a documentation directory:
 mkdir -p $PKG/usr/doc/${PKGNAM}-$VERSION
@@ -187,17 +202,22 @@ mkdir -p $PKG/usr/doc/${PKGNAM}-$VERSION
     History*.htm \
     $PKG/usr/share/ghostscript/$VERSION/doc
   rm -f $PKG/usr/share/ghostscript/$VERSION/doc/History{1,2,3,4,5,6,7,8}.htm
+  # More cruft:
+  rm -f $PKG/usr/share/ghostscript/$VERSION/doc/Details{1,2,3,4,5,6,7,8}.htm
+  # This is also bloat:
+  rm -f $PKG/usr/share/ghostscript/$VERSION/doc/*.pdf
   chown root:root $PKG/usr/share/ghostscript/$VERSION/doc/History*htm
   chmod 644 $PKG/usr/share/ghostscript/$VERSION/doc/History*htm
 )
 
-cd $TMP
-cp -a ${PKGNAM}-${VERSION}/examples/cjk $PKG/usr/share/ghostscript/${VERSION}/examples/
+# Install example files:
+rm -rf $PKG/usr/share/ghostscript/${VERSION}/examples
+cp -a $TMP/${PKGNAM}-${VERSION}/examples $PKG/usr/share/ghostscript/${VERSION}
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 cat << EOF > $PKG/install/doinst.sh
-#!/bin/sh
+#!/bin/bash
 config() {
   NEW="\$1"
   OLD="\$(dirname \$NEW)/\$(basename \$NEW .new)"
diff --git a/source/d/clisp/clisp.SlackBuild b/source/d/clisp/clisp.SlackBuild
--- a/source/d/clisp/clisp.SlackBuild
+++ b/source/d/clisp/clisp.SlackBuild
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright 2008, 2009, 2010, 2013, 2015  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2008, 2009, 2010, 2013, 2015, 2017, 2018  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,26 +20,35 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+cd $(dirname $0) ; CWD=$(pwd)
 
-VERSION=2.49
-DIRNAME=2.49
-BUILD=${BUILD:-3}
+PKGNAM=clisp
+VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
+BUILD=${BUILD:-1}
 
 # Bundled libraries:
-FFCALLVER=20120424cvs
+FFCALLVER=2.1
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) export ARCH=i486 ;;
+    i?86) export ARCH=i586 ;;
     arm*) export ARCH=arm ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
   esac
 fi
 
-if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
+  exit 0
+fi
+
+if [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "s390" ]; then
   SLKCFLAGS="-O2"
@@ -54,7 +63,6 @@ fi
 
 NUMJOBS=${NUMJOBS:-" -j7 "}
 
-CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-clisp
 
@@ -64,12 +72,9 @@ mkdir -p $TMP $PKG
 #=================================================================
 # Build ffcall - needed for --dynamic-ffi with clisp.
 cd $TMP
-rm -rf ffcall*
-tar xvf $CWD/ffcall-$FFCALLVER.tar.?z* || exit 1
-cd ffcall* || exit 1
-
-# Not sure if this is useful or not, but I'll leave it for MoZes:
-zcat $CWD/ffcall-arm.patch.gz | patch -p1 --verbose || exit 1
+rm -rf libffcall-$FFCALLVER
+tar xvf $CWD/libffcall-$FFCALLVER.tar.?z || exit 1
+cd libffcall-$FFCALLVER || exit 1
 
 chown -R root:root .
 find . \
@@ -83,22 +88,21 @@ CFLAGS="$SLKCFLAGS" \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --mandir=/usr/man \
+  --enable-static=yes \
+  --enable-shared=no \
   --build=$ARCH-slackware-linux || exit 1
 
 make $NUMJOBS || make || exit 1
 
 make install DESTDIR=$PKG || exit 1
-# We need ffcall installed in order to build clisp:
-make install
-
-# Don't need this:
-rm -f $PKG/usr/lib${LIBDIRSUFFIX}/*.la
+# We need libffcall installed in order to build clisp:
+make install || exit 1
 
 # Move docs around:
-mkdir -pm755 $PKG/usr/doc/clisp-$VERSION/ffcall-$FFCALLVER
+mkdir -pm755 $PKG/usr/doc/clisp-$VERSION/libffcall-$FFCALLVER
 install -vpm644 README NEWS COPYING \
-  $PKG/usr/doc/clisp-$VERSION/ffcall-$FFCALLVER
-mv -f $PKG/usr/share/html/* $PKG/usr/doc/clisp-$VERSION/ffcall-$FFCALLVER
+  $PKG/usr/doc/clisp-$VERSION/libffcall-$FFCALLVER
+mv -f $PKG/usr/share/html/* $PKG/usr/doc/clisp-$VERSION/libffcall-$FFCALLVER
 rmdir $PKG/usr/share/html/
 rmdir $PKG/usr/share/
 
@@ -107,8 +111,8 @@ rmdir $PKG/usr/share/
 # OK, now we compile CLISP:
 cd $TMP
 rm -rf clisp-$VERSION
-tar xvf $CWD/clisp-$VERSION.tar.?z* || exit 1
-cd clisp-$DIRNAME || exit 1
+tar xvf $CWD/clisp-$VERSION.tar.?z || exit 1
+cd clisp-$VERSION || exit 1
 chown -R root:root .
 find . \
   \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
@@ -116,47 +120,50 @@ find . \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \;
 
+# Fix build failure with missing struct member:
+zcat $CWD/clisp.c_data.compact_empty_buckets.diff.gz | patch -p1 --verbose || exit
+
+# I'll be unsafe if I want to:
+export FORCE_UNSAFE_CONFIGURE=1
+
+# --cbc instead of --config below will check the build.
+# --cbcx will do even more extra checking.
+
 CFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --mandir=/usr/man \
   --docdir=/usr/doc/clisp-$VERSION \
+  --with-module=asdf \
+  --with-module=berkeley-db \
+  --with-module=bindings/glibc \
   --with-module=clx/new-clx \
+  --with-module=dbus \
+  --with-module=gdbm \
+  --with-module=gtk2 \
   --with-module=pcre \
   --with-module=rawsock \
-  --with-module=wildcard \
   --with-module=zlib \
-  --cbc with-gcc-wall \
+  --config builddir \
   --with-dynamic-ffi || exit 1
 
-cd with-gcc-wall
-./makemake \
-  --with-dynamic-ffi  \
-  --prefix=/usr \
-  --libdir=/usr/lib${LIBDIRSUFFIX} \
-  --with-module=clx/new-clx \
-  --with-module=pcre \
-  --with-module=rawsock \
-  --with-module=wildcard \
-  --with-module=zlib \
-  --srcdir=../src \
-  > Makefile
-make config.lisp
-make init
-make allc
-make $NUMJOBS lisp.run
-make interpreted.mem
-make halfcompiled.mem
-make lispinit.mem
-make manual
-make modular
+# Build:
+make $NUMJOBS -C builddir || make -C builddir || exit 1
 
-make install DESTDIR=$PKG || exit 1
+# Install into package:
+make -C builddir install DESTDIR=$PKG || exit 1
 
 # Strip stuff:
 find $PKG | xargs file | grep -e "executable" -e "shared object" \
   | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+
+# Don't ship .la files:
+pushd $PKG
+  for lafile in usr/lib${LIBDIRSUFFIX}/*.la ; do
+    rm -f ${lafile} /${lafile}
+  done
+popd
 
 #mv $PKG/usr/share/doc/clisp/* $PKG/usr/doc/clisp-$VERSION
 rm -r $PKG/usr/share/doc
diff --git a/source/d/cvs/cvs.SlackBuild b/source/d/cvs/cvs.SlackBuild
--- a/source/d/cvs/cvs.SlackBuild
+++ b/source/d/cvs/cvs.SlackBuild
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright 2008, 2009, 2010, 2013  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2008, 2009, 2010, 2013, 2018  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,24 +20,34 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+cd $(dirname $0) ; CWD=$(pwd)
 
+PKGNAM=cvs
 VERSION=1.11.23
-BUILD=${BUILD:-2}
+BUILD=${BUILD:-3}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) export ARCH=i486 ;;
+    i?86) export ARCH=i586 ;;
     arm*) export ARCH=arm ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
   esac
 fi
 
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
+  exit 0
+fi
+
 NUMJOBS=${NUMJOBS:-" -j7 "}
 
-if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+if [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
 elif [ "$ARCH" = "s390" ]; then
   SLKCFLAGS="-O2"
 elif [ "$ARCH" = "x86_64" ]; then
@@ -46,7 +56,6 @@ else
   SLKCFLAGS="-O2"
 fi
 
-CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-cvs
 rm -rf $PKG
@@ -55,7 +64,7 @@ mkdir -p $TMP $PKG
 cd $TMP
 rm -rf cvs-$VERSION
 tar xvf $CWD/cvs-$VERSION.tar.bz2 || exit 1
-cd cvs-$VERSION
+cd cvs-$VERSION || exit 1
 
 # Patch to handle recent glib crypt():
 zcat $CWD/cvs.crypt-2.diff.gz | patch -p1 --verbose || exit 1
@@ -73,7 +82,7 @@ CFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/usr \
   --mandir=/usr/man \
-  --infodir=/usr/info
+  --infodir=/usr/info || exit 1
 
 make $NUMJOBS || make || exit 1
 make install DESTDIR=$PKG || exit 1
@@ -86,14 +95,17 @@ gzip -9 $PKG/usr/info/*
 
 gzip -9 $PKG/usr/man/man?/*.?
 
-( cd doc ; make txt )
 mkdir -p $PKG/usr/doc/cvs-$VERSION
 cp -a \
   BUGS COPYING* DEVEL-CVS FAQ HACKING INSTALL MINOR-BUGS NEWS PROJECTS \
   README TESTS TODO \
   $PKG/usr/doc/cvs-$VERSION
-cat doc/cvs.txt | gzip -9c > $PKG/usr/doc/cvs-$VERSION/cvs.txt.gz
-cat doc/cvsclient.txt | gzip -9c > $PKG/usr/doc/cvs-$VERSION/cvsclient.txt.gz
+
+# This fails, but who cares in 2018
+#( cd doc ; make txt || exit 1 ) || exit 1
+#cat doc/cvs.txt | gzip -9c > $PKG/usr/doc/cvs-$VERSION/cvs.txt.gz
+#cat doc/cvsclient.txt | gzip -9c > $PKG/usr/doc/cvs-$VERSION/cvsclient.txt.gz
+
 chmod 644 $PKG/usr/doc/cvs-$VERSION/*
 gzip -9 $PKG/usr/doc/cvs-$VERSION/FAQ
 ( cd $PKG/usr/doc/cvs-$VERSION ; rm -rf contrib )
diff --git a/source/l/ncurses/ncurses.SlackBuild b/source/l/ncurses/ncurses.SlackBuild
--- a/source/l/ncurses/ncurses.SlackBuild
+++ b/source/l/ncurses/ncurses.SlackBuild
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright 2000-2011, 2013, 2014, 2015  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2000-2011, 2013, 2014, 2015, 2016, 2017, 2018  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,26 +20,37 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+cd $(dirname $0) ; CWD=$(pwd)
+
 PKGNAM=ncurses
-VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
+VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z | cut -f 2- -d - | cut -f 1,2 -d .)}
 BUILD=${BUILD:-4}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) export ARCH=i486 ;;
+    i?86) export ARCH=i586 ;;
     arm*) export ARCH=arm ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
   esac
 fi
 
-CWD=$(pwd)
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$(echo $VERSION | tr - _)-$ARCH-$BUILD.txz"
+  exit 0
+fi
+
+NUMJOBS=${NUMJOBS:-" -j7 "}
+
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-ncurses
 
-if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+if [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "s390" ]; then
   SLKCFLAGS="-O2"
@@ -59,12 +70,18 @@ CFLAGS="$SLKCFLAGS" \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --mandir=/usr/man \
-  --with-gpm \
-  --disable-termcap \
-  --with-shared \
+  --enable-colorfgbg \
+  --enable-hard-tabs \
+  --enable-overwrite \
+  --enable-xmc-glitch \
   --with-cxx-shared \
-  --without-normal \
+  --with-ospeed=unsigned \
+  --with-termlib=tinfo \
+  --with-ticlib=tic \
+  --with-gpm \
+  --with-shared \
   --without-debug \
+  --disable-static \
   --without-profile \
   --enable-symlinks \
   --enable-pc-files \
@@ -86,51 +103,71 @@ tar xvf $CWD/ncurses-$VERSION.tar.?z || exit 1
 cd ncurses-$VERSION || exit 1
 chown -R root:root .
 
-# This allows some other patches to come first by making them bz2...  gz next
-if [ ! -z "$(ls $CWD/patches/ncurses*bz2 2> /dev/null)" ]; then
-  bzcat $CWD/patches/ncurses*bz2 > tmp-patch.sh
-  bash tmp-patch.sh || exit 1
-fi
-# Apply official upstream patches.
-if [ ! -z "$(ls $CWD/patches/ncurses-$VERSION-2*.patch.gz 2> /dev/null)" ]; then
-  for file in $CWD/patches/ncurses-$VERSION-2*.patch.gz ; do
-    zcat $file | patch -p1 --verbose || exit 1
-  done
-fi
-
-# Apply upstream patch collection:
-xzcat $CWD/ncurses-5.9-20141206-patch.sh.xz > ncurses-5.9-20141206-patch.sh
-sh ncurses-5.9-20141206-patch.sh
+## NOTE: nevermind trying this... patches have multiple failures. Use the
+## dated archive from upstream instead.
+#
+### No rollup (*.patch.sh) patch available yet for ncurses-6.1, so we'll
+### comment this out for now.
+## Apply upstream patch collection:
+#xzcat $CWD/ncurses-6.0-20160910-patch.sh.xz > ncurses-6.0-20160910-patch.sh
+#sh ncurses-6.0-20160910-patch.sh
+## Apply weekly ncurses patch updates:
+#for file in $CWD/patches/*.patch.gz ; do
+#  zcat $file | patch -p1 --verbose || exit 1
+#done
 
 zcat $CWD/ncurses.mkhashsize.diff.gz | patch -p1 --verbose || exit 1
 
-ncurses_configure
-make -j4 || exit 1
-# Spamming the partition.
-# Sorry, but it's about the only way to get a good 'tic'.
-make install
-# Install the package:
-make install DESTDIR=$PKG
+# Configure/build/install to package the standard ncurses libraries:
+ncurses_configure || exit 1
+make $NUMJOBS || exit 1
+make install DESTDIR=$PKG || exit 1
 
-# Build/install again with wide character support:
+# Configure/build/install again with wide character support:
 make clean
 WIDEC=--enable-widec
-ncurses_configure
-make -j4 || exit 1
-make install
-make install DESTDIR=$PKG
+ncurses_configure || exit 1
+make $NUMJOBS || exit 1
+make install DESTDIR=$PKG || exit 1
 
-if [ ! -d $PKG/usr/include/ncursesw -a ! -L $PKG/usr/include/ncursesw ]; then
-  ( cd $PKG/usr/include ; ln -sf ncurses ncursesw )
-fi
+# Make a termcap file in case anyone actually needs it:
+echo "#       /etc/termcap" > misc/termcap
+grep \$Revision: misc/terminfo.src >> misc/termcap
+grep \$Date: misc/terminfo.src >> misc/termcap
+echo "#" >> misc/termcap
+echo "#       Converted from terminfo.src for Slackware:" >> misc/termcap
+echo "#       tic -C -t terminfo.src > termcap" >> misc/termcap
+echo "#" >> misc/termcap
+echo "#       This file is included to support legacy applications using libtermcap." >> misc/termcap
+echo "#       Modern applications will use ncurses/terminfo instead." >> misc/termcap
+echo "#" >> misc/termcap
+echo "#------------------------------------------------------------------------------" >> misc/termcap
+echo "#" >> misc/termcap
+tic -C -t misc/terminfo.src >> misc/termcap
+touch -r misc/terminfo.src misc/termcap
+mkdir $PKG/etc
+cp -a misc/termcap $PKG/etc/termcap
 
 # Strip stuff:
 find $PKG | xargs file | grep -e "executable" -e "shared object" \
   | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 
-# Move the include files from /usr/include into
-# /usr/include/ncurses, then make symlinks back
-# into /usr/include.
+# Remove static libraries:
+for file in libform.a libformw.a libmenu.a libmenuw.a libncurses++.a \
+  libncurses++w.a libncurses.a libncursesw.a libpanel.a libpanelw.a \
+  libtic.a libtinfo.a libcurses.a ; do
+  rm -f $PKG/usr/lib${LIBDIRSUFFIX}/$file
+done
+
+# Check for new static residue:
+if ls $PKG/usr/lib${LIBDIRSUFFIX}/*.a 1> /dev/null 2> /dev/null ; then
+  echo "BAILING OUT.  A NEW STATIC LIBRARY HAS APPEARED:"
+  ls -l $PKG/usr/lib${LIBDIRSUFFIX}/*.a
+  exit 1
+fi
+
+# Move the include files from /usr/include into /usr/include/ncurses,
+# then make symlinks back into /usr/include.
 ( cd $PKG/usr/include
   rm -rf ncurses
   mkdir ncurses
@@ -138,50 +175,54 @@ find $PKG | xargs file | grep -e "executable" -e "shared object" \
   for file in ncurses/* ; do
     ln -sf $file .
   done
-  # This shouldn't clobber the real one:
-  mv termcap.h termcap-ncurses.h
 )
+
+# Make an ncursesw symlink to /usr/include/ncurses:
+if [ ! -d $PKG/usr/include/ncursesw -a ! -L $PKG/usr/include/ncursesw ]; then
+  ( cd $PKG/usr/include ; ln -sf ncurses ncursesw )
+fi
 
 # Move the ncurses libraries into /lib, since they're important:
 mkdir -p $PKG/lib${LIBDIRSUFFIX}
 ( cd $PKG/usr/lib${LIBDIRSUFFIX}
   chmod 755 *.so
   chmod 644 *.a
-  mv libncurses.so.5* $PKG/lib${LIBDIRSUFFIX}
-  mv libncursesw.so.5* $PKG/lib${LIBDIRSUFFIX}
-  rm -f libncurses.so
-  ln -sf /lib${LIBDIRSUFFIX}/libncurses.so.5 libncurses.so
-  rm -f libncursesw.so
-  ln -sf /lib${LIBDIRSUFFIX}/libncursesw.so.5 libncursesw.so
-  # Olde obsolete names, just in case
-  rm -f libcurses.so
-  ln -sf libncurses.so libcurses.so
-  rm -f libcursesw.so
-  ln -sf libncursesw.so libcursesw.so
+  mv libncurses.so.6* $PKG/lib${LIBDIRSUFFIX}
+  mv libncursesw.so.6* $PKG/lib${LIBDIRSUFFIX}
+  mv libtinfo.so.6* $PKG/lib${LIBDIRSUFFIX}
+  rm -f libtinfo.so.6
+  ln -sf ../../lib${LIBDIRSUFFIX}/libtinfo.so.6 .
 )
 
-# Set TERMINFO to point to the package:
+# Use linker loader scripts to make sure -tinfo dependency works:
+( cd $PKG/usr/lib${LIBDIRSUFFIX}
+  rm -f libcurses.so libcursesw.so libncurses.so libncursesw.so libtermcap.so
+  echo "INPUT(-lncurses)" > libcurses.so
+  echo "INPUT(-lncursesw)" > libcursesw.so
+  echo "INPUT(libncurses.so.6 -ltinfo)" > libncurses.so
+  echo "INPUT(libncursesw.so.6 -ltinfo)" > libncursesw.so
+  echo "INPUT(-ltinfo)" > libtermcap.so
+)
+
+# Use various upstream/fixed/better terminfo files to update the terminfo
+# database. Only *.terminfo files in $CWD/terminfo will be used.
 export TERMINFO=$PKG/usr/share/terminfo
-# Fix the xterm, screen, rxvt, and Eterm entries:
-for tfile in $CWD/xterm.terminfo $CWD/screeninfo.src $CWD/rxvt.terminfo $CWD/Eterm.ti ; do
+for tfile in $CWD/terminfo/*.terminfo ; do
   if [ -r $tfile ]; then
     progs/tic -v $tfile
   fi
 done
 unset TERMINFO
 
-# Then, add /usr/doc/ncurses-xxxxx with appropriate files.
+# Add /usr/doc/ncurses-xxxxx with appropriate files:
 mkdir -p $PKG/usr/doc/ncurses-$VERSION
 cp -a \
-  ANNOUNCE INSTALL MANIFEST NEWS README* TO-DO \
+  ANNOUNCE AUTHORS COPYING* INSTALL MANIFEST NEWS README* TO-DO VERSION \
   $PKG/usr/doc/ncurses-$VERSION
 mkdir -p $PKG/usr/doc/ncurses-$VERSION/c++
 cp -a \
   c++/NEWS c++/PROBLEMS c++/README-first \
   $PKG/usr/doc/ncurses-$VERSION/c++
-if [ -r $PKG/usr/man/man1/tack.1 ]; then
-  gzip -9 --force $PKG/usr/man/man1/tack.1
-fi
 
 # We don't need the log of every change here, but we'll take some.
 # If you need the whole thing probably you already extracted the
@@ -197,10 +238,10 @@ if [ -r NEWS ]; then
   touch -r NEWS $DOCSDIR/NEWS
 fi
 
-# desc file:
 mkdir -p $PKG/install
+zcat $CWD/doinst.sh.gz | sed "s,usr/lib,usr/lib${LIBDIRSUFFIX},g" > $PKG/install/doinst.sh
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
-/sbin/makepkg -l y -c n $TMP/ncurses-$VERSION-$ARCH-$BUILD.txz
+/sbin/makepkg -l y -c n $TMP/ncurses-$(echo $VERSION | tr - _)-$ARCH-$BUILD.txz
 
diff --git a/source/n/crda/crda.SlackBuild b/source/n/crda/crda.SlackBuild
--- a/source/n/crda/crda.SlackBuild
+++ b/source/n/crda/crda.SlackBuild
@@ -1,7 +1,7 @@
-#!/bin/sh
+#!/bin/bash
 
 # Copyright 2009  Robby Workman, Northport, AL, USA
-# Copyright 2009, 2010, 2016  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2009, 2010, 2016, 2018  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -21,9 +21,11 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+cd $(dirname $0) ; CWD=$(pwd)
 
+PKGNAM=crda
 VERSION=${VERSION:-3.18}
-BUILD=${BUILD:-3}
+BUILD=${BUILD:-7}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -35,9 +37,16 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-REGDBVERS=2016.02.08
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
+  exit 0
+fi
 
-CWD=$(pwd)
+REGDBVERS=2018.05.09
+
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-crda
 
@@ -71,12 +80,12 @@ find . \
  -exec chmod 644 {} \;
 
 # If this isn't installed on the system, crda will not build:
-mkdir -p /usr/lib/crda
-cat regulatory.bin > /usr/lib/crda/regulatory.bin
+make install MANDIR=/usr/man || exit 1
 
-mkdir -p $PKG/usr/lib/crda $PKG/usr/man/man5 $PKG/usr/doc/crda-$VERSION/regdb
-cat regulatory.bin > $PKG/usr/lib/crda/regulatory.bin
-gzip -9c regulatory.bin.5 > $PKG/usr/man/man5/regulatory.bin.5.gz
+# Install to the package directory:
+make install DESTDIR=$PKG MANDIR=/usr/man || exit 1
+
+mkdir -p $PKG/usr/doc/crda-$VERSION/regdb
 cp -a LICENSE README db.txt $PKG/usr/doc/crda-$VERSION/regdb
 
 # Now we'll do crda itself
@@ -91,16 +100,17 @@ find . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
 
-# There's some weirdness going on here, but this seems to fix it:
-make ; make clean ; make
+# This thing uses our CFLAGS on its own, but if we specify them,
+# it fails to build. The build failure is wacky, as if it's not
+# linking libnl into crda.o -- the detection for libnl is broken,
+# but even if it's fixed, the errors still occur. This works, so...
+sed -i -e "s,-Werror ,,g" -e "s,fpic,fPIC,g" Makefile
 
 make \
-  CFLAGS="$SLKCFLAGS" \
   MANDIR=/usr/man \
   LIBDIR=/usr/lib${LIBDIRSUFFIX} \
   || exit 1
 make install \
-  CFLAGS="$SLKCFLAGS" \
   MANDIR=/usr/man \
   LIBDIR=/usr/lib${LIBDIRSUFFIX} \
   DESTDIR=$PKG \
diff --git a/source/n/ppp/ppp.SlackBuild b/source/n/ppp/ppp.SlackBuild
--- a/source/n/ppp/ppp.SlackBuild
+++ b/source/n/ppp/ppp.SlackBuild
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright 2008, 2009, 2010, 2013, 2015  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2008, 2009, 2010, 2013, 2015, 2018  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,21 +20,32 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+cd $(dirname $0) ; CWD=$(pwd)
+
+PKGNAM=ppp
 VERSION=2.4.7
 RADVER=1.1.6
 PPPVER=1.98
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-3}
 
 NUMJOBS=${NUMJOBS:-" -j7 "}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) export ARCH=i486 ;;
+    i?86) export ARCH=i586 ;;
     arm*) export ARCH=arm ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
   esac
+fi
+
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
+  exit 0
 fi
 
 if [ "$ARCH" = "x86_64" ]; then
@@ -43,7 +54,6 @@ else
   LIBDIRSUFFIX=""
 fi
 
-CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-ppp
 
@@ -72,11 +82,14 @@ rm -f include/linux/if_pppol2tp.h
 
 zcat $CWD/ppp.CVE-2015-3310.diff.gz | patch -p1 --verbose || exit 1
 
+zcat $CWD/0028-pppoe-include-netinet-in.h-before-linux-in.h.patch.gz | patch -p1 --verbose || exit 1
+
 ./configure \
   --prefix=/usr \
-  --libdir=/usr/lib${LIBDIRSUFFIX}
+  --libdir=/usr/lib${LIBDIRSUFFIX} || exit 1
+
 make $NUMJOBS || make || exit 1
-make install DESTDIR=$PKG/usr
+make install DESTDIR=$PKG/usr || exit 1
 
 # Install PPP config files:
 mkdir -p $PKG/etc/ppp
@@ -93,6 +106,12 @@ zcat $CWD/options.new.gz > $PKG/etc/ppp/options.new
 # Feel free to "chmod 4750 pppoatm.so rp-pppoe.so" at your own risk.
 # Since they are only runnable by group root, the risk really isn't much...
 chmod 755 $PKG/usr/lib${LIBDIRSUFFIX}/pppd/*/*.so
+
+# The Makefile doesn't error out if building rp-pppoe.so fails, so check for it:
+if [ ! -r $PKG/usr/lib${LIBDIRSUFFIX}/pppd/${VERSION}/rp-pppoe.so ]; then
+  echo "FATAL: /usr/lib${LIBDIRSUFFIX}/pppd/${VERSION}/rp-pppoe.so failed to build."
+  exit 1
+fi
 
 mkdir -p $PKG/usr/doc/ppp-$VERSION
 cp -a \
@@ -111,7 +130,7 @@ chown -R root:root .
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --sysconfdir=/etc \
-  --build=$ARCH-slackware-linux
+  --build=$ARCH-slackware-linux || exit 1
 make $NUMJOBS || make || exit 1
 make install DESTDIR=$PKG || exit 1
 zcat $CWD/radius.msdict.gz > $PKG/etc/radiusclient/dictionary.microsoft
@@ -147,6 +166,9 @@ mkdir -p $PKG/usr/doc/pppsetup
 cp -a \
   README.pppsetup ppp-compile.txt pppsetup-$PPPVER.README pppsetup-$PPPVER.lsm \
   $PKG/usr/doc/pppsetup
+
+# Don't ship .la files:
+rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
 
 ( cd $PKG
   find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
diff --git a/source/xap/MPlayer/MPlayer.SlackBuild b/source/xap/MPlayer/MPlayer.SlackBuild
--- a/source/xap/MPlayer/MPlayer.SlackBuild
+++ b/source/xap/MPlayer/MPlayer.SlackBuild
@@ -1,7 +1,7 @@
-#!/bin/sh
+#!/bin/bash
 # $Id: MPlayer.SlackBuild,v 1.27 2012/07/01 13:07:08 root Exp root $
 # Copyright 2006, 2007, 2008, 2010, 2011, 2012  Eric Hameleers, Eindhoven, NL
-# Copyright 2013  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2013, 2018  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 #   Permission to use, copy, modify, and distribute this software for
@@ -21,88 +21,14 @@
 #   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 #   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 #   SUCH DAMAGE.
-# -----------------------------------------------------------------------------
-#
-# Slackware SlackBuild script
-# ===========================
-# By:        Eric Hameleers <alien@slackware.com>
-# For:       MPlayer
-# Descr:     a movie player for LINUX
-# URL:       http://www.mplayerhq.hu/
-# Needs:
-# Changelog:
-# 1.0rc1-1:   05/Nov/2006 by Eric Hameleers <alien@slackware.com>
-#            * Initial build.
-# 1.0rc1-2:   07/Nov/2006 by Eric Hameleers <alien@slackware.com>
-#            * Removed MPlayer's internal libdvdcss code from the build, so
-#              that MPlayer no longer plays encrypted DVD's by default (and the
-#              package is now safe to upload to public repositories).
-#              If it is allowed in your country, you can either install
-#              libdvdcss (which is picked up automatically by MPlayer), or
-#              rebuild MPlayer yourself using this SlackBuild - and set the
-#              variable REMOVECSS="no" first (see further down).
-#              Use this commandline if you can't or won't modify the script:
-#                REMOVECSS="no" ./MPlayer.SlackBuild
-# 1.0rc1-3:   08/Nov/2006 by Eric Hameleers <alien@slackware.com>
-#             * Install the mplayer.conf into correct location '/etc/mplayer/'
-# 1.0rc1-4:   15/mar/2007 by Eric Hameleers <alien@slackware.com>
-#             * Differentiate between versions of X11 (modular X has another
-#               install-prefix); update default skin; enable mplayer menu;
-#               add security fix
-# 1.0rc1-5:   07/jun/2007 by Eric Hameleers <alien@slackware.com>
-#             * Add security fix.
-# 1.0rc2-1:   09/oct/2007 by Eric Hameleers <alien@slackware.com>
-#             * New version.
-# 1.0rc2-2:   01/feb/2008 by Eric Hameleers <alien@slackware.com>
-#             * Apply 4 security fixes.
-# 1.0rc2-3:   10/mar/2008 by Eric Hameleers <alien@slackware.com>
-#             * Apply a patch that allows compilation against the ivtv driver
-#               in the 2.6.24.x kernels.
-# r28148-1:   14/dec/2008 by Eric Hameleers <alien@slackware.com>
-#             * Build SVN snapshot - remove support for *all* patented or
-#               questionable software if "USE_PATENTS" is set to "NO" - think
-#               of DECSS dvd decryption code, and mp3/aac/amr audio encoders.
-# r28929-1:   10/mar/2009 by Eric Hameleers <alien@slackware.com>
-#             * Update.
-# r29301-1:   12/may/2009 by Eric Hameleers <alien@slackware.com>
-#             * Update.
-# r29301-1:   12/may/2009 by Eric Hameleers <alien@slackware.com>
-#             * Update.
-# 20100926-1: 26/sep/2010 by Eric Hameleers <alien@slackware.com>
-#             * Slackware has MPlayer now of course, but it does not hurt
-#               to have a full-featured binary package available. The 1.0rc3
-#               was released recently but I prefer to build a snapshot.
-# 20110624-1: 24/jun/2011 by Eric Hameleers <alien@slackware.com>
-#             * Provide an up-to-date snapshot to be used in conjunction
-#               with UMPlayer (a MPlayer GUI). New MPlayer source requires
-#               a separate ffmpeg download.
-# 20120514-1: 14/may/2012 by volkerdi@slackware.com
-#             * Update.
-# 1.1_20120701-1: 28/jun/2012 by alien@slackware.com
-#             * Update to the 1.1 branch (essentially this is MPlayer-1.1 but
-#               I like to check it out of SVN).
-# 1.1_20130819-1: 19/aug/2013 by volkerdi@slackware.com
-#             * Update to the latest 1.1 branch, and the same ffmpeg that was
-#               shipped with the 1.1.1 tarball.  The official 1.1.1 release
-#               did not start a new repo branch, so this is the latest.
-# 20150308-1: 09/mar/2015 by pprkut@slackware.com
-#             * Update to latest version from trunk, together with ffmpeg 2.6,
-#               which was released roughly around that date as well.
-# 20140403-1: 03/apr/2015 by volkerdi@slackware.com
-#             * Update to latest version from trunk and ffmpeg-2.6.1.
-#
-# Run 'sh MPlayer.SlackBuild' to build a Slackware package.
-# The package (.txz) plus descriptive .txt file are created in /tmp .
-# Install using 'installpkg'.
-#
-# -----------------------------------------------------------------------------
 
 # Set initial variables:
 
-PRGNAM=MPlayer
-VERSION=${VERSION:-20160125}
-BRANCH=${BRANCH:-1.2}        # leave empty if you want to build MPlayer trunk
-FFMPEG=${FFMPEG:-2.8.6}
+PKGNAM=MPlayer
+VERSION=${VERSION:-20180208}
+# Need to build trunk until there's a stable branch compatible with the
+# latest ffmpeg stable release:
+#BRANCH=${BRANCH:-1.3}        # leave empty if you want to build MPlayer trunk
 BUILD=${BUILD:-3}
 TAG=${TAG:-}
 NUMJOBS=${NUMJOBS:-" -j7 "}
@@ -120,10 +46,8 @@ else
   MPBRANCH="trunk"
 fi
 
-FFURI=git://git.videolan.org/ffmpeg.git
-
 DEFSKIN=${DEFSKIN:-"Blue"}  # Download more skins at the following url:
-SKINVER=${SKINVER:-"1.11"}   # http://www.mplayerhq.hu/design7/dload.html
+SKINVER=${SKINVER:-"1.13"}   # http://www.mplayerhq.hu/design7/dload.html
 
 # Available languages: all cs de en es fr hu it pl ru zh_CN
 LANGUAGES="en,de,es,fr"
@@ -148,10 +72,26 @@ elif [ "$ARCH" = "i486" -o \
        "$ARCH" = "i586" -o \
        "$ARCH" = "i686" ]; then
   LIBDIRSUFFIX=""
-  EXTRACONFIGUREOPTIONS="--enable-runtime-cpudetection"
+  # --enable-runtime-cpudetection is failing on 32-bit, so we'll set -march=i586
+  # manually after ./configure.
+  #EXTRACONFIGUREOPTIONS="--enable-runtime-cpudetection"
+  EXTRACONFIGUREOPTIONS=""
 else
   LIBDIRSUFFIX=""
   EXTRACONFIGUREOPTIONS=""
+fi
+
+# If this package is being built for ALSA (no PulseAudio), use the _alsa $TAG:
+if [ ! -r /usr/lib${LIBDIRSUFFIX}/pkgconfig/libpulse.pc ]; then
+  TAG="_alsa"
+fi
+
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "${PKGNAM}-${PKGVERSION}-${ARCH}-${BUILD}${TAG}.txz"
+  exit 0
 fi
 
 # Where the WIN32 codecs are expectedfor instance
@@ -159,9 +99,9 @@ CODECSDIR=/usr/lib${LIBDIRSUFFIX}/codecs
 
 # ---------------------------------------------------------------------------
 # -- PATENT ALERT! --
-# MPLayer can be built with MP3 (lame) and AMR audio encoders
+# MPLayer can be built with AMR audio encoders
 # (needed for FLV and .3GP videos) but these libraries are 'contaminated'
-# with patents from Fraunhofer and GGP.
+# with patents from 3GPP.
 # Also, the AAC encoder has patent issues.
 # You can build these patended algorithms into ffmpeg, and if you are an
 # ordinary end user, no one will bother you for using them.
@@ -169,7 +109,7 @@ CODECSDIR=/usr/lib${LIBDIRSUFFIX}/codecs
 # different story. I am not allowed to distribute binary packages that
 # incorporate patented code. So here you go. My Slackware package was
 # built with "USE_PATENTS=NO" i.e. without using
-# the lame mp3, faac, AMR and dvdcss libraries.
+# the faac, AMR and dvdcss libraries.
 # ---------------------------------------------------------------------------
 USE_PATENTS=${USE_PATENTS:-"NO"}
 
@@ -186,18 +126,14 @@ OSDFONTS="LiberationSans-Regular.ttf \
           DejaVuSans.ttf Vera.ttf"
 
 # Where do we look for sources?
-SRCDIR=$(cd $(dirname $0); pwd)
+cd $(dirname $0) ; SRCDIR=$(pwd)
 
-SOURCE[0]="$SRCDIR/${PRGNAM}-${VERSION}.tar.xz"
+SOURCE[0]="$SRCDIR/${PKGNAM}-${VERSION}.tar.xz"
 SRCURL[0]=""
 
 # The default skin to use (we need to add at least one)
 SOURCE[1]="$SRCDIR/${DEFSKIN}-${SKINVER}.tar.bz2"
 SRCURL[1]="http://www.mplayerhq.hu/MPlayer/skins/${DEFSKIN}-${SKINVER}.tar.bz2"
-
-# Ffmpeg needs to be checked out separately now:
-SOURCE[2]="$SRCDIR/ffmpeg-${FFMPEG}.tar.xz"
-SRCURL[2]=""
 
 # Use the src_checkout() function if no downloadable tarball exists.
 # This function checks out sources from SVN/CVS and creates a tarball of them.
@@ -229,19 +165,6 @@ src_checkout() {
        && tar --exclude-vcs -${TARCOMP}cf ${2} MPlayer-${VERSION}
      rm -rf MPlayer-${VERSION}
      ;;
-  2) # ffmpeg-${FFMPEG}
-     mkdir ffmpeg_temp_checkout_$$ \
-       && cd ffmpeg_temp_checkout_$$
-       echo "Checking out tag n$FFMPEG from '$FFURI':"
-       git clone ${FFURI} ffmpeg \
-       && cd ffmpeg \
-       && git checkout n$FFMPEG \
-       && cd ..
-       chown -R root:root . \
-       && tar --exclude-vcs -${TARCOMP}cf ${2} ffmpeg
-     cd ..
-     rm -rf ffmpeg_temp_checkout_$$
-     ;;
   *) # Do nothing
      ;;
   esac
@@ -249,7 +172,7 @@ src_checkout() {
 
 # Place to build (TMP) package (PKG) and output (OUTPUT) the program:
 TMP=${TMP:-/tmp/build}
-PKG=$TMP/package-$PRGNAM
+PKG=$TMP/package-$PKGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
 ##
@@ -258,14 +181,14 @@ OUTPUT=${OUTPUT:-/tmp}
 
 # Exit the script on errors:
 set -e
-trap 'echo "$0 FAILED at line $LINENO!" | tee $OUTPUT/error-${PRGNAM}.log' ERR
+trap 'echo "$0 FAILED at line $LINENO!" | tee $OUTPUT/error-${PKGNAM}.log' ERR
 # Catch unitialized variables:
 set -u
 P1=${1:-1}
 
 # Create working directories:
-mkdir -p $TMP/tmp-$PRGNAM # location to build the source
-rm -rf $TMP/tmp-$PRGNAM/* # remove the remnants of previous build
+mkdir -p $TMP/tmp-$PKGNAM # location to build the source
+rm -rf $TMP/tmp-$PKGNAM/* # remove the remnants of previous build
 mkdir -p $PKG             # place for the package to be built
 rm -rf $PKG/*             # erase old package's contents
 mkdir -p $OUTPUT          # place for the package to be saved
@@ -304,30 +227,16 @@ fi
 # --- PACKAGE BUILDING ---
 
 echo "++"
-echo "|| $PRGNAM-$VERSION"
+echo "|| $PKGNAM-$VERSION"
 echo "++"
 
-cd $TMP/tmp-$PRGNAM
-echo "Extracting the source archive(s) for $PRGNAM..."
+cd $TMP/tmp-$PKGNAM
+echo "Extracting the source archive(s) for $PKGNAM..."
 tar -xvf ${SOURCE[0]}
-
-cd ${PRGNAM}-${VERSION}
-  # remove MPlayer's copy of libswscale
-  rm -rf ffmpeg
-
-  # Extract the ffmpeg source inside the MPlayer directory:
-  tar -xvf ${SOURCE[2]}
-
-  # in case we build with an official tarball
-  if [ -e "ffmpeg-$FFMPEG" ]; then
-    mv "ffmpeg-$FFMPEG" ffmpeg
-  fi
-
-cd ..
 
 chown -R root:root *
 chmod -R u+w,go+r-w,a+X-s *
-cd ${PRGNAM}-${VERSION}
+cd ${PKGNAM}-${VERSION}
 
 # Determine what X we're running (the modular X returns the prefix
 # in the next command, while older versions stay silent):
@@ -336,8 +245,7 @@ XPREF=$(pkg-config --variable=prefix x11) || true
 
 # Remove support for patent encumbered and possibly illegal code:
 if [ "$USE_PATENTS" != "YES" ]; then
-  DO_PATENTED="--disable-mp3lame --disable-mp3lame-lavc \
-               --disable-libopencore_amrnb \
+  DO_PATENTED="--disable-libopencore_amrnb \
                --disable-libopencore_amrwb"
 else
   DO_PATENTED=""
@@ -345,12 +253,6 @@ fi
 
 # fix building against samba 4
 zcat $SRCDIR/include-samba-4.0.patch.gz | patch -p1 --verbose || exit 1
-
-# fix building against openjpeg 2
-sed -i "s|lopenjpeg|lopenmj2|" ./configure
-
-# fix flac playback with embedded album art:
-zcat $SRCDIR/MPlayer.demux_lavf.flac.diff.gz | patch -p1 --verbose || exit 1
 
 echo Building ...
 # MPlayer wants to automatically determine compiler flags,
@@ -365,18 +267,27 @@ echo Building ...
   --disable-arts \
   --disable-ossaudio \
   --disable-bitmap-font \
+  --disable-ffmpeg_a \
   --codecsdir=${CODECSDIR} \
   --language="${LANGUAGES}" \
-  --extra-cflags="-I/usr/include/openmj2-2.1/" \
   ${EXTRACONFIGUREOPTIONS} \
   ${DO_PATENTED} \
-  2>&1 | tee $OUTPUT/configure-${PRGNAM}.log
+  2>&1 | tee $OUTPUT/configure-${PKGNAM}.log
+
 # So that MPlayer does not report "UNKNOWN" as it's version:
 if [ ! -f VERSION ]; then
   echo $VERSION > VERSION
 fi
-make $NUMJOBS 2>&1 | tee $OUTPUT/make-${PRGNAM}.log
-make DESTDIR=$PKG install 2>&1 |tee $OUTPUT/install-${PRGNAM}.log
+
+# Set -march/-mtune manually since runtime cpu detection causes a compile error
+# on 32-bit x86:
+if [ "$ARCH" = "i586" ]; then
+  sed -i "s/march=native/march=i586/g" config.mak
+  sed -i "s/mtune=native/mtune=generic/g" config.mak
+fi
+
+make $NUMJOBS 2>&1 | tee $OUTPUT/make-${PKGNAM}.log
+make DESTDIR=$PKG install 2>&1 |tee $OUTPUT/install-${PKGNAM}.log
 
 # Build the html documentation (not all languages are available):
 if [ "$LANGUAGES" = "all" ]; then
@@ -457,19 +368,19 @@ fi
 EOINS
 
 # Add documentation:
-mkdir -p $PKG/usr/doc/$PRGNAM-$PKGVERSION
-cp -a $DOCS $PKG/usr/doc/$PRGNAM-$PKGVERSION || true
-cp -a $SRCDIR/$(basename $0) $PKG/usr/doc/$PRGNAM-$PKGVERSION/$PRGNAM.SlackBuild
-mv $PKG/usr/doc/$PRGNAM-$PKGVERSION/HTML $PKG/usr/doc/$PRGNAM-$PKGVERSION/html
+mkdir -p $PKG/usr/doc/$PKGNAM-$PKGVERSION
+cp -a $DOCS $PKG/usr/doc/$PKGNAM-$PKGVERSION || true
+cp -a $SRCDIR/$(basename $0) $PKG/usr/doc/$PKGNAM-$PKGVERSION/$PKGNAM.SlackBuild
+mv $PKG/usr/doc/$PKGNAM-$PKGVERSION/HTML $PKG/usr/doc/$PKGNAM-$PKGVERSION/html
 # Save a sample of all configuration files:
 for i in etc/*.conf ; do
-  cp $i $PKG/usr/doc/$PRGNAM-$PKGVERSION/$(basename $i)-sample
+  cp $i $PKG/usr/doc/$PKGNAM-$PKGVERSION/$(basename $i)-sample
 done
 # Save a transcript of all configured options for this specific build:
-if [ -n $OUTPUT/configure-${PRGNAM}.log ]; then
-  cat $OUTPUT/configure-${PRGNAM}.log \
+if [ -n $OUTPUT/configure-${PKGNAM}.log ]; then
+  cat $OUTPUT/configure-${PKGNAM}.log \
     | sed -n "/^Config files successfully generated/,/^'config.h' and 'config.mak' contain your configuration options./p" \
-    > $PKG/usr/doc/$PRGNAM-$PKGVERSION/${PRGNAM}.configuration
+    > $PKG/usr/doc/$PKGNAM-$PKGVERSION/${PKGNAM}.configuration
 fi
 find $PKG/usr/doc -type f -exec chmod 644 {} \;
 
@@ -492,9 +403,9 @@ fi
 
 # Build the package:
 cd $PKG
-makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${PKGVERSION}-${ARCH}-${BUILD}${TAG}.txz 2>&1 | tee $OUTPUT/makepkg-${PRGNAM}.log
+makepkg --linkadd y --chown n $OUTPUT/${PKGNAM}-${PKGVERSION}-${ARCH}-${BUILD}${TAG}.txz 2>&1 | tee $OUTPUT/makepkg-${PKGNAM}.log
 cd $OUTPUT
-md5sum ${PRGNAM}-${PKGVERSION}-${ARCH}-${BUILD}${TAG}.txz > ${PRGNAM}-${PKGVERSION}-${ARCH}-${BUILD}${TAG}.txz.md5
+md5sum ${PKGNAM}-${PKGVERSION}-${ARCH}-${BUILD}${TAG}.txz > ${PKGNAM}-${PKGVERSION}-${ARCH}-${BUILD}${TAG}.txz.md5
 cd -
-cat $PKG/install/slack-desc | grep "^${PRGNAM}" > $OUTPUT/${PRGNAM}-${PKGVERSION}-${ARCH}-${BUILD}${TAG}.txt
+cat $PKG/install/slack-desc | grep "^${PKGNAM}" > $OUTPUT/${PKGNAM}-${PKGVERSION}-${ARCH}-${BUILD}${TAG}.txt
 
diff --git a/source/xap/electricsheep/electricsheep.SlackBuild b/source/xap/electricsheep/electricsheep.SlackBuild
--- a/source/xap/electricsheep/electricsheep.SlackBuild
+++ b/source/xap/electricsheep/electricsheep.SlackBuild
@@ -1,7 +1,7 @@
-#!/bin/sh
+#!/bin/bash
 
 # Copyright 2008, 2009  Eric Hameleers, Eindhoven, Netherlands
-# Copyright 2009  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2009, 2018  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 #   Permission to use, copy, modify, and distribute this software for
@@ -32,33 +32,41 @@
 # Needs:      MPlayer (to display the sheep)
 # -----------------------------------------------------------------------------
 
-PRGNAM=electricsheep
+PKGNAM=electricsheep
 VERSION=${VERSION:-20090306}
-BUILD=${BUILD:-4}
+BUILD=${BUILD:-5}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) export ARCH=i486 ;;
+    i?86) export ARCH=i586 ;;
     arm*) export ARCH=arm ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
   esac
 fi
 
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
+  exit 0
+fi
+
 # Where do we look for sources?
-SRCDIR=$(cd $(dirname $0); pwd)
+cd $(dirname $0) ; SRCDIR=$(pwd)
 
 DOCS="COPYING README $SRCDIR/README.slackware"
 DOCS_FLAM3="COPYING* README*"
 DOCS_FFMPEG="COPYING* CREDITS Changelog MAINTAINERS README"
 
-SOURCE="$SRCDIR/${PRGNAM}-${VERSION}.tar.xz"
+SOURCE="$SRCDIR/${PKGNAM}-${VERSION}.tar.xz"
 SRCURL=""
 
 # Place to build (TMP) package (PKG) and output (OUTPUT) the program:
 TMP=${TMP:-/tmp/build}
-PKG=$TMP/package-$PRGNAM
+PKG=$TMP/package-$PKGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
 # Use the src_checkout() function if no downloadable tarball exists.
@@ -98,13 +106,13 @@ src_checkout() {
 
 # Exit the script on errors:
 set -e
-trap 'echo "$0 FAILED at line ${LINENO}" | tee $OUTPUT/error-${PRGNAM}.log' ERR
+trap 'echo "$0 FAILED at line ${LINENO}" | tee $OUTPUT/error-${PKGNAM}.log' ERR
 # Catch unitialized variables:
 set -u
 P1=${1:-1}
 
 case "$ARCH" in
-  i486)      SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  i586)      SLKCFLAGS="-O2 -march=i586 -mtune=i686"
              SLKLDFLAGS=""; LIBDIRSUFFIX=""
              ;;
   s390)      SLKCFLAGS="-O2"
@@ -132,11 +140,11 @@ esac
 
 # Create working directories:
 mkdir -p $OUTPUT          # place for the package to be saved
-mkdir -p $TMP/tmp-$PRGNAM # location to build the source
+mkdir -p $TMP/tmp-$PKGNAM # location to build the source
 mkdir -p $PKG             # place for the package to be built
 rm -rf $PKG/*             # always erase old package's contents
-rm -rf $TMP/tmp-$PRGNAM/* # remove the remnants of previous build
-rm -rf $OUTPUT/{configure,make,install,error,makepkg}-$PRGNAM.log
+rm -rf $TMP/tmp-$PKGNAM/* # remove the remnants of previous build
+rm -rf $OUTPUT/{configure,make,install,error,makepkg}-$PKGNAM.log
                           # remove old log files
 
 # Source file availability:
@@ -171,13 +179,13 @@ fi
 # --- PACKAGE BUILDING ---
 
 echo "++"
-echo "|| $PRGNAM-$VERSION"
+echo "|| $PKGNAM-$VERSION"
 echo "++"
 
-cd $TMP/tmp-$PRGNAM
-echo "Extracting the source archive(s) for $PRGNAM..."
+cd $TMP/tmp-$PKGNAM
+echo "Extracting the source archive(s) for $PKGNAM..."
 tar -xvf ${SOURCE}
-cd ${PRGNAM}-${VERSION}
+cd ${PKGNAM}-${VERSION}
 chown -R root:root .
 find . \
   \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
@@ -194,7 +202,7 @@ cd client
   chmod +x ffmpeg/doc/texi2pod.pl
   # We do not use gnome:
   cat $SRCDIR/electricsheep_gnome-open.patch | patch -p1 --verbose \
-    2>&1 | tee $OUTPUT/patch-$PRGNAM.log
+    2>&1 | tee $OUTPUT/patch-$PKGNAM.log
   # Prevent install errors due to missing gnome
   sed -i -e "/^install-data-local:/,/^$/d" Makefile.in
   LDFLAGS="$SLKLDFLAGS" \
@@ -205,9 +213,9 @@ cd client
     --libdir=/usr/lib${LIBDIRSUFFIX} \
     --mandir=/usr/man \
     --build=$ARCH-slackware-linux \
-    2>&1 | tee $OUTPUT/configure-${PRGNAM}.log
-  make -j 7 2>&1 | tee $OUTPUT/make-${PRGNAM}.log
-  make DESTDIR=$PKG install 2>&1 |tee $OUTPUT/install-${PRGNAM}.log
+    2>&1 | tee $OUTPUT/configure-${PKGNAM}.log
+  make -j 7 2>&1 | tee $OUTPUT/make-${PKGNAM}.log
+  make DESTDIR=$PKG install 2>&1 |tee $OUTPUT/install-${PKGNAM}.log
 cd ..
 # Then the flam3 (fractal flames) renderer:
 cd flam3
@@ -220,23 +228,26 @@ cd flam3
     --libdir=/usr/lib${LIBDIRSUFFIX} \
     --mandir=/usr/man \
     --build=$ARCH-slackware-linux \
-    2>&1 | tee $OUTPUT/configure-${PRGNAM}.log
-  make -j 7 2>&1 | tee $OUTPUT/make-${PRGNAM}.log
-  make DESTDIR=$PKG install 2>&1 |tee $OUTPUT/install-${PRGNAM}.log
+    2>&1 | tee $OUTPUT/configure-${PKGNAM}.log
+  make -j 7 2>&1 | tee $OUTPUT/make-${PKGNAM}.log
+  make DESTDIR=$PKG install 2>&1 |tee $OUTPUT/install-${PKGNAM}.log
 cd ..
 
+# Don't ship .la files:
+rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
+
 # Add documentation:
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/{flam3,ffmpeg}
+mkdir -p $PKG/usr/doc/$PKGNAM-$VERSION/{flam3,ffmpeg}
 ( cd client
-  cp -a $DOCS $PKG/usr/doc/$PRGNAM-$VERSION
+  cp -a $DOCS $PKG/usr/doc/$PKGNAM-$VERSION
 )
 ( cd client/ffmpeg
-  cp -a $DOCS_FFMPEG $PKG/usr/doc/$PRGNAM-$VERSION/ffmpeg
+  cp -a $DOCS_FFMPEG $PKG/usr/doc/$PKGNAM-$VERSION/ffmpeg
 )
 ( cd flam3
-  cp -a $DOCS_FLAM3 $PKG/usr/doc/$PRGNAM-$VERSION/flam3
+  cp -a $DOCS_FLAM3 $PKG/usr/doc/$PKGNAM-$VERSION/flam3
 )
-chown -R root:root $PKG/usr/doc/$PRGNAM-$VERSION
+chown -R root:root $PKG/usr/doc/$PKGNAM-$VERSION
 find $PKG/usr/doc -type f -exec chmod 644 {} \;
 
 cd client
@@ -272,8 +283,8 @@ cat $SRCDIR/slack-desc > $PKG/install/slack-desc
 
 # Build the package:
 cd $PKG
-makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}.txz 2>&1 | tee $OUTPUT/makepkg-${PRGNAM}.log
+makepkg --linkadd y --chown n $OUTPUT/${PKGNAM}-${VERSION}-${ARCH}-${BUILD}.txz 2>&1 | tee $OUTPUT/makepkg-${PKGNAM}.log
 cd $OUTPUT
-md5sum ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}.txz > ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}.txz.md5
+md5sum ${PKGNAM}-${VERSION}-${ARCH}-${BUILD}.txz > ${PKGNAM}-${VERSION}-${ARCH}-${BUILD}.txz.md5
 cd -
-cat $PKG/install/slack-desc | grep "^${PRGNAM}" > $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}.txt
+cat $PKG/install/slack-desc | grep "^${PKGNAM}" > $OUTPUT/${PKGNAM}-${VERSION}-${ARCH}-${BUILD}.txt
diff --git a/source/xap/gnuplot/gnuplot.SlackBuild b/source/xap/gnuplot/gnuplot.SlackBuild
--- a/source/xap/gnuplot/gnuplot.SlackBuild
+++ b/source/xap/gnuplot/gnuplot.SlackBuild
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright 2008, 2009, 2010, 2016  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2008, 2009, 2010, 2016, 2017, 2018  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,9 +20,11 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+cd $(dirname $0) ; CWD=$(pwd)
+
 PKGNAM=gnuplot
-VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z* | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-2}
+VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
+BUILD=${BUILD:-1}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -32,6 +34,14 @@ if [ -z "$ARCH" ]; then
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
   esac
+fi
+
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
+  exit 0
 fi
 
 NUMJOBS=${NUMJOBS:-" -j7 "}
@@ -50,7 +60,6 @@ else
   LIBDIRSUFFIX=""
 fi
 
-CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-gnuplot
 
@@ -58,7 +67,7 @@ rm -rf $PKG
 mkdir -p $TMP $PKG
 cd $TMP
 rm -rf gnuplot-$VERSION
-tar xvf $CWD/gnuplot-$VERSION.tar.?z* || exit 1
+tar xvf $CWD/gnuplot-$VERSION.tar.?z || exit 1
 cd gnuplot-$VERSION || exit 1
 
 chown -R root:root .
@@ -67,6 +76,16 @@ find . \
   -exec chmod 755 {} \; -o \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \;
+
+# Fix default source location; use the GDFONTPATH variable to modify at runtime.
+# Thanks to the arch-folks.
+sed -i 's|/usr/X11R6/lib/X11/fonts/truetype|/usr/share/fonts/TTF|' src/variable.c
+sed -i -e 's|/usr/X11R6/lib/X11/fonts/Type1|/usr/share/fonts/Type1|' \
+  -e 's|$(X11ROOT)/X11R6/lib/X11/fonts/Type1|$(X11ROOT)/usr/share/fonts/Type1|' \
+  src/variable.c
+
+# Fix failure in building info file:
+zcat $CWD/gnuplot.fix.info.generation.diff.gz | patch -p1 --verbose || exit 1
 
 # To distribute gnuplot binaries, you can not use GNU readline, as
 # gnuplot does not use a GPL compatible free license.
@@ -78,13 +97,16 @@ CFLAGS="$SLKCFLAGS" \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --with-gd \
   --with-caca \
+  --with-qt=no \
+  --without-libcerf \
+  --with-texdir=/usr/share/texmf-dist/tex/latex/gnuplot \
   --datadir=/usr/share/gnuplot \
   --with-readline=builtin \
   --build=${ARCH}-slackware-linux || exit 1
 
 #
 # I think most people would rather not have a Qt dependency here.
-# --enable-qt
+# --with-qt=yes
 # 
 
 make $NUMJOBS || make || exit 1
@@ -119,7 +141,7 @@ fi
 
 mkdir -p $PKG/usr/doc/gnuplot-$VERSION
 cp -a \
-  BUGS CodeStyle Copyright FAQ.bloat INSTALL NEWS PATCHLEVEL PGPKEYS PORTING \
+  BUGS CodeStyle Copyright INSTALL NEWS PATCHLEVEL PGPKEYS PORTING \
   README* TODO VERSION \
   $PKG/usr/doc/gnuplot-$VERSION
 cp -a demo $PKG/usr/doc/gnuplot-$VERSION
diff --git a/source/xap/mozilla-firefox/mozilla-firefox.SlackBuild b/source/xap/mozilla-firefox/mozilla-firefox.SlackBuild
--- a/source/xap/mozilla-firefox/mozilla-firefox.SlackBuild
+++ b/source/xap/mozilla-firefox/mozilla-firefox.SlackBuild
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2018  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -23,7 +23,10 @@
 # Thanks to the folks at the Mozilla Foundation for permission to
 # distribute this, and for all the great work!  :-)
 
-VERSION=$(basename $(ls firefox-*.tar.?z* | cut -d - -f 2 | rev | cut -f 3- -d . | rev) .source)
+cd $(dirname $0) ; CWD=$(pwd)
+
+PKGNAM=mozilla-firefox
+VERSION=$(basename $(ls firefox-*.tar.?z | cut -d - -f 2 | rev | cut -f 3- -d . | rev) .source)
 RELEASEVER=$(echo $VERSION | cut -f 1 -d r | cut -f 1 -d b | cut -f 1 -d e)
 BUILD=${BUILD:-1}
 
@@ -35,15 +38,61 @@ BUILD=${BUILD:-1}
 #
 MOZLOCALIZE=${MOZLOCALIZE:-}
 
+# Without LANG=C, building the Python environment may fail with:
+# "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)"
+LANG=C
+
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) export ARCH=i586 ;;
+    i?86) export ARCH=i686 ;;
     arm*) export ARCH=arm ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
   esac
 fi
+
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  if [ -z $MOZLOCALIZE ]; then
+    echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
+  else
+    echo "$PKGNAM-$VERSION-$ARCH-${BUILD}_$MOZLOCALIZE.txz"
+  fi
+  exit 0
+fi
+
+# Firefox has been requiring more and more memory, especially while linking
+# libxul. If it fails to build natively on x86 32-bit, it can be useful to
+# attempt the build using an x86_64 kernel and a 32-bit userspace. Detect this
+# situation and set the ARCH to i686. Later in the script we'll add some
+# options to the .mozconfig so that the compile will do the riight thing.
+if [ "$(uname -m)" = "x86_64" -a "$(file -L /usr/bin/gcc | grep 80386 | grep 32-bit)" != "" ]; then
+  COMPILE_X86_UNDER_X86_64=true
+  ARCH=i686
+  # Also use the gold linker for this:
+  PATH="$(pwd)/gold:$PATH"
+  export CC=${CC:-"gcc -B$(pwd)/gold"}
+  export CXX=${CXX:-"g++ -B$(pwd)/gold"}
+elif [ "$ARCH" = "i686" ]; then
+  # This might also help with the linker memory situation on some $ARCH. Feel free
+  # to match any other $ARCH that could benefit from this.
+  SLKLDFLAGS=" -Wl,--as-needed -Wl,--reduce-memory-overheads -Wl,--no-keep-memory -Wl,--stats"
+  export LDFLAGS="$SLKLDFLAGS"
+  export MOZ_LINK_FLAGS="$SLKLDFLAGS"
+else
+  # Link using gold.  This also helps prevent running out of memory on 32-bit
+  # systems, and avoids a recurring build failure with GNU ld on other systems.
+  PATH="$(pwd)/gold:$PATH"
+  export CC=${CC:-"gcc -B$(pwd)/gold"}
+  export CXX=${CXX:-"g++ -B$(pwd)/gold"}
+fi
+
+# Put Rust objects on a diet to keep the linker from running into memory
+# issues (especially on 32-bit):
+export RUSTFLAGS="-Cdebuginfo=0"
 
 # Use PGO?  Doubles the time and drive space requirements for the build,
 # but should provide a performance increase.  How much depends on which
@@ -75,48 +124,46 @@ PGO=${PGO:-no}
 if [ "$ARCH" = "i586" ]; then
   SLKCFLAGS=""
   LIBDIRSUFFIX=""
-  OPTIMIZE=" --enable-optimize=-O2 "
-  # On IA32, use gold since GNU ld runs out of memory linking libxul.so:
-  PATH="$(pwd)/gold:$PATH"
-  export CC="gcc -B$(pwd)/gold"
-  export CXX="g++ -B$(pwd)/gold"
+  OPTIMIZE=${OPTIMIZE:-"-O1"}
+elif [ "$ARCH" = "i686" ]; then
+  SLKCFLAGS=""
+  LIBDIRSUFFIX=""
+  OPTIMIZE=${OPTIMIZE:-"-O1"}
 elif [ "$ARCH" = "s390" ]; then
-  SLKCFLAGS="-O2"
+  SLKCFLAGS=""
   LIBDIRSUFFIX=""
-  OPTIMIZE=" --enable-optimize=-O2 "
+  OPTIMIZE=${OPTIMIZE:-"-O1"}
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
+  SLKCFLAGS="-fPIC"
   LIBDIRSUFFIX="64"
-  OPTIMIZE=" --enable-optimize=-O2 "
+  OPTIMIZE=${OPTIMIZE:-"-O1"}
 elif [ "$ARCH" = "arm" ]; then
-  SLKCFLAGS="-O2 -march=armv4 -mtune=xscale"
+  SLKCFLAGS="-march=armv4 -mtune=xscale"
   LIBDIRSUFFIX=""
-  OPTIMIZE=" --enable-optimize=-O2 "
+  OPTIMIZE=${OPTIMIZE:-"-O1"}
 elif [ "$ARCH" = "armel" ]; then
-  SLKCFLAGS="-O2 -march=armv4t"
+  SLKCFLAGS="-march=armv4t"
   LIBDIRSUFFIX=""
-  OPTIMIZE=" --enable-optimize=-O2 "
+  OPTIMIZE=${OPTIMIZE:-"-O1"}
 else
-  SLKCFLAGS="-O2"
+  SLKCFLAGS=""
   LIBDIRSUFFIX=""
-  OPTIMIZE=" --enable-optimize=-O2 "
+  OPTIMIZE=${OPTIMIZE:-"-O1"}
 fi
 
-# Workaround to prevent unidentified crashes.  Since this seems to be
-# fixed in recent betas, only use the fix for known crashing versions:
-if [ $VERSION = 43.0 \
-     -o $VERSION = 43.0.1 \
-     -o $VERSION = 43.0.2 \
-     -o $VERSION = 43.0.3 \
-     -o $VERSION = 43.0.4 ]; then
-  OPTIMIZE="$(echo "$OPTIMIZE" | sed 's/O2/Os/g')"
-  echo "Detected Firefox $VERSION...  enabling crash workaround O2 -> Os."
-  sleep 1
-fi
-
-CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-mozilla-firefox
+
+# If there is a private Google API key available at compile time, use
+# it to enable support for Google Safe Browsing. For Slackware builds,
+# we use a private key issued for the Slackware project. If you are
+# rebuilding and need this support, or you are producing your own
+# distribution, you may obtain your own Google API key at no charge by
+# following these instructions:
+# https://bugzilla.mozilla.org/show_bug.cgi?id=1377987#c0
+if [ -r /root/google-api-key ]; then
+  GOOGLE_API_KEY="--with-google-api-keyfile=/root/google-api-key"
+fi
 
 # If not specified, figure out if this is a beta or a release
 MOZVERS=${MOZVERS:-release}
@@ -127,25 +174,35 @@ NUMJOBS=${NUMJOBS:-" -j7 "}
 rm -rf $PKG
 mkdir -p $TMP $PKG/usr/lib${LIBDIRSUFFIX}
 
+# We need to use the incredibly ancient autoconf-2.13 for this  :/
+( cd $CWD/autoconf ; ./autoconf.build )
+PATH=$TMP/autoconf-tmp/usr/bin:$PATH
+
 cd $TMP
 rm -rf firefox-$VERSION
 # Unpack this in a subdirectory to prevent changing permissions on /tmp:
 rm -rf firefox-unpack
 mkdir firefox-unpack
 cd firefox-unpack
-tar xvf $CWD/firefox-$VERSION.source.tar.?z* || exit 1
+tar xvf $CWD/firefox-$VERSION.source.tar.?z || exit 1
 mv * ..
 cd ..
 rm -rf firefox-unpack
 cd firefox-$VERSION || exit 1
 
-# Fetch localization, if requested:
+# Prevent failures building gkrust by suppressing useless warnings:
+sed -i.allow-warnings -e '/#!\[deny(warnings)\]/a #![allow(unused_imports)]' \
+  servo/components/style/lib.rs
+
+# Retain GTK+ v2 scrolling behavior:
+zcat $CWD/ff.ui.scrollToClick.diff.gz | patch -p1 --verbose || exit 1
+
+# Fetch localization, if requested
+# https://bugzilla.mozilla.org/show_bug.cgi?id=1256955
 if [ ! -z $MOZLOCALIZE ]; then
-  LOC_TAG="FIREFOX_$( echo $VERSION | tr \. _ )_RELEASE"
-  rm -f $LOC_TAG.tar.bz2
-  wget https://hg.mozilla.org/releases/l10n/mozilla-$MOZVERS/$MOZLOCALIZE/archive/$LOC_TAG.tar.bz2
-  tar xvf $LOC_TAG.tar.bz2
-  mv $MOZLOCALIZE-$LOC_TAG $MOZLOCALIZE
+  LOC_URL="http://ftp.mozilla.org/pub/firefox/candidates/$VERSION-candidates/build1/l10n_changesets.txt"
+  LOC_COMMIT=$(wget -q -O - $LOC_URL | grep ^$MOZLOCALIZE | cut -d\  -f2)
+  hg clone https://hg.mozilla.org/l10n-central/$MOZLOCALIZE -r $LOC_COMMIT
 fi
 
 # Patch mimeTypes.rdf
@@ -165,28 +222,17 @@ OPTIONS="\
   --enable-official-branding \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
-  --with-default-mozilla-five-home=/usr/lib${LIBDIRSUFFIX}/firefox-$RELEASEVER \
   --with-system-zlib \
+  --enable-alsa \
   --enable-application=browser \
-  --enable-default-toolkit=cairo-gtk2 \
+  --enable-default-toolkit=cairo-gtk3 \
   --enable-startup-notification \
-  --enable-crypto \
-  --enable-gstreamer=1.0 \
-  --enable-svg \
-  --enable-canvas \
-  --enable-logging \
-  --enable-xft \
-  --enable-webm \
-  $OPTIMIZE \
-  --enable-reorder \
+  $GOOGLE_API_KEY \
   --enable-strip \
   --enable-cpp-rtti \
-  --disable-gnomevfs \
-  --disable-accessibility \
+  --enable-accessibility \
   --disable-crashreporter \
-  --disable-debug \
-  --disable-pedantic \
-  --disable-installer"
+  --disable-debug"
 # Complains about missing APNG support in Slackware's libpng:
 # --with-system-png \
 # This option breaks mozilla-12.0:
@@ -231,7 +277,20 @@ if [ "$MOZLOCALIZE" ]; then
   echo "mk_add_options MOZ_CO_LOCALES=\"$MOZLOCALIZE\"" >> .mozconfig
 fi
 
-# Write in it the options above
+# Tell .mozconfig about the selected compiler:
+echo "export CC=\"${CC}\"" >> .mozconfig
+echo "export CXX=\"${CXX}\"" >> .mozconfig
+
+# Set options for $OPTIMIZE:
+echo "ac_add_options --enable-optimize=\"${OPTIMIZE}\"" >> .mozconfig
+
+if [ "$COMPILE_X86_UNDER_X86_64" = "true" ]; then
+  # Compile for i686 under an x86_64 kernel:
+  echo "ac_add_options --host=i686-pc-linux-gnu" >> .mozconfig
+  echo "ac_add_options --target=i686-pc-linux-gnu" >> .mozconfig
+fi
+
+# Add the $OPTIONS above to .mozconfig:
 for option in $OPTIONS; do echo "ac_add_options $option" >> .mozconfig; done
 
 # https://developer.mozilla.org/en-US/docs/Building_with_Profile-Guided_Optimization
@@ -244,15 +303,16 @@ if [ "$PGO" = "yes" ]; then
   # Launch Xvfb to let the profile scripts run in a X session.
   # Ugly note: if the build breaks you may want to do a "killall Xvfb".
   Xvfb -nolisten tcp -extension GLX -screen 0 1280x1024x24 $DISPLAY &
-  dbus-launch --exit-with-session make -f client.mk build || exit 1
+  dbus-launch --exit-with-session ./mach build || exit 1
   kill $! || true
 else
   # Do a normal build
   echo "ac_add_options --disable-tests" >> .mozconfig
-  make -f client.mk build || exit 1
+  ./mach build || exit 1
 fi
 
-make -f client.mk install DESTDIR=$PKG || exit 1
+./mach buildsymbols || exit 1
+DESTDIR=$PKG ./mach install || exit 1
 
 # We don't need these (just symlinks anyway):
 rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/firefox-devel-$RELEASEVER
diff --git a/source/xap/mozilla-thunderbird/mozilla-thunderbird.SlackBuild b/source/xap/mozilla-thunderbird/mozilla-thunderbird.SlackBuild
--- a/source/xap/mozilla-thunderbird/mozilla-thunderbird.SlackBuild
+++ b/source/xap/mozilla-thunderbird/mozilla-thunderbird.SlackBuild
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright 2008, 2009, 2010, 2011, 2012, 2014, 2016  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2008, 2009, 2010, 2011, 2012, 2014, 2016, 2017, 2018  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -25,6 +25,9 @@
 # Thanks to the folks at the Mozilla Foundation for permission to
 # distribute this, and for all the great work!  :-)
 
+cd $(dirname $0) ; CWD=$(pwd)
+
+PKGNAM=mozilla-thunderbird
 VERSION=$(basename $(ls thunderbird-*.tar.?z* | cut -d - -f 2 | rev | cut -f 3- -d . | rev) .source)
 RELEASEVER=$(echo $VERSION | cut -f 1 -d e | cut -f 1 -d b)
 BUILD=${BUILD:-1}
@@ -37,6 +40,14 @@ BUILD=${BUILD:-1}
 #
 MOZLOCALIZE=${MOZLOCALIZE:-}
 
+# This can be set to YES or NO:
+ENABLE_CALENDAR=${ENABLE_CALENDAR:-YES}
+if [ "$ENABLE_CALENDAR" = "NO" ]; then
+  ENABLE_CALENDAR="--disable-calendar"
+else
+  ENABLE_CALENDAR="--enable-calendar"
+fi
+
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -48,29 +59,68 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-if [ "$ARCH" = "i586" ]; then
-  LIBDIRSUFFIX=""
-  OPTIMIZE=" --enable-optimize=-O2 "
-  # On IA32, use gold since GNU ld runs out of memory linking libxul.so:
-  PATH="$(pwd)/gold:$PATH"
-  export CC="gcc -B$(pwd)/gold"
-  export CXX="g++ -B$(pwd)/gold"
-elif [ "$ARCH" = "x86_64" ]; then
-  LIBDIRSUFFIX="64"
-  OPTIMIZE=" --enable-optimize=-O2 "
-else
-  LIBDIRSUFFIX=""
-  OPTIMIZE=" --enable-optimize=-O2 "
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  if [ -z $MOZLOCALIZE ]; then
+    echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
+  else
+    echo "$PKGNAM-$VERSION-$ARCH-${BUILD}_$MOZLOCALIZE.txz"
+  fi
+  exit 0
 fi
 
-CWD=$(pwd)
+if [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS=""
+  LIBDIRSUFFIX=""
+  OPTIMIZE=${OPTIMIZE:-"-O1"}
+elif [ "$ARCH" = "i686" ]; then
+  SLKCFLAGS=""
+  LIBDIRSUFFIX=""
+  OPTIMIZE=${OPTIMIZE:-"-O1"}
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-fPIC"
+  LIBDIRSUFFIX="64"
+  OPTIMIZE=${OPTIMIZE:-"-O1"}
+elif [ "$ARCH" = "arm" ]; then
+  SLKCFLAGS="-march=armv4 -mtune=xscale"
+  LIBDIRSUFFIX=""
+  OPTIMIZE=${OPTIMIZE:-"-O1"}
+else
+  SLKCFLAGS=""
+  LIBDIRSUFFIX=""
+  OPTIMIZE=${OPTIMIZE:-"-O1"}
+fi
+
+# Link using gold.  This avoids running out of memory on 32-bit systems, and
+# avoids a recurring build failure with GNU ld on other systems.
+PATH="$(pwd)/gold:$PATH"
+export CC=${CC:-"gcc -B$(pwd)/gold"}
+export CXX=${CXX:-"g++ -B$(pwd)/gold"}
+
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-mozilla-thunderbird
+
+# If there is a private Google API key available at compile time, use
+# it to enable support for Google Safe Browsing. For Slackware builds,
+# we use a private key issued for the Slackware project. If you are
+# rebuilding and need this support, or you are producing your own
+# distribution, you may obtain your own Google API key at no charge by
+# following these instructions:
+# https://bugzilla.mozilla.org/show_bug.cgi?id=1377987#c0
+if [ -r /root/google-api-key ]; then
+  GOOGLE_API_KEY="--with-google-api-keyfile=/root/google-api-key"
+fi
 
 NUMJOBS=${NUMJOBS:-" -j7 "}
 
 rm -rf $PKG
 mkdir -p $TMP $PKG/usr/lib${LIBDIRSUFFIX}
+
+# We need to use the incredibly ancient autoconf-2.13 for this  :/
+( cd $CWD/autoconf ; ./autoconf.build )
+PATH=$TMP/autoconf-tmp/usr/bin:$PATH
 
 cd $TMP
 rm -rf thunderbird-$VERSION
@@ -83,6 +133,9 @@ mv * ..
 cd ..
 rm -rf thunderbird-unpack
 cd thunderbird-$VERSION || exit 1
+
+# Retain GTK+ v2 scrolling behavior:
+zcat $CWD/tb.ui.scrollToClick.diff.gz | patch -p1 --verbose || exit 1
 
 # Fetch localization, if requested:
 if [ ! -z $MOZLOCALIZE ]; then
@@ -115,30 +168,23 @@ OPTIONS="\
   --enable-official-branding \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
-  --with-default-mozilla-five-home=/usr/lib${LIBDIRSUFFIX}/thunderbird-$VERSION \
+  --with-default-mozilla-five-home=/usr/lib${LIBDIRSUFFIX}/thunderbird-$RELEASEVER \
   --with-system-zlib \
+  --enable-alsa \
   --enable-application=mail \
-  --enable-calendar \
-  --enable-default-toolkit=cairo-gtk2 \
+  $ENABLE_CALENDAR \
+  --enable-default-toolkit=cairo-gtk3 \
   --enable-startup-notification \
-  --enable-crypto \
   --enable-ldap \
-  --enable-libxul \
-  --enable-svg \
-  --enable-canvas \
-  --enable-xft \
-  $OPTIMIZE \
-  --enable-reorder \
   --enable-strip \
   --enable-cpp-rtti \
-  --disable-accessibility \
+  --enable-accessibility \
+  $GOOGLE_API_KEY \
   --disable-crashreporter \
   --disable-debug \
   --disable-tests \
-  --disable-pedantic \
   --host=$ARCH-slackware-linux \
-  --target=$ARCH-slackware-linux \
-  --build=$ARCH-slackware-linux"
+  --target=$ARCH-slackware-linux"
   # Complains about missing APNG support in Slackware's libpng:
   #--with-system-png \
   # Broken with 12.0:
@@ -157,6 +203,8 @@ fi
 export BUILD_OFFICIAL=1
 export MOZILLA_OFFICIAL=1
 export MOZ_PHOENIX=1
+export CFLAGS="$SLKCFLAGS"
+export CXXFLAGS="$SLKCFLAGS"
 export MOZ_MAKE_FLAGS="$NUMJOBS"
 
 # Clear some variables that could break the build
@@ -166,6 +214,10 @@ unset DBUS_SESSION_BUS_ADDRESS ORBIT_SOCKETDIR SESSION_MANAGER \
 # Assemble our .mozconfig:
 echo > .mozconfig
 
+# Tell .mozconfig about the selected compiler:
+echo "export CC=\"${CC}\"" >> .mozconfig
+echo "export CXX=\"${CXX}\"" >> .mozconfig
+
 # Mozilla devs enforce using an objdir for building
 # https://developer.mozilla.org/en/Configuring_Build_Options#Building_with_an_objdir
 mkdir obj
@@ -173,7 +225,10 @@ echo "mk_add_options MOZ_OBJDIR=$(pwd)/obj" >> .mozconfig
 # This directory is also needed or the build will fail:
 mkdir -p mozilla/obj
 
-# Write in it the options above
+# Set options for $OPTIMIZE:
+echo "ac_add_options --enable-optimize=\"${OPTIMIZE}\"" >> .mozconfig
+
+# Add the $OPTIONS above to .mozconfig:
 for option in $OPTIONS; do echo "ac_add_options $option" >> .mozconfig; done
 
 make -f client.mk build || exit 1
@@ -196,7 +251,8 @@ mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/mozilla/plugins
 mkdir -p $PKG/usr/share/applications
 cat $CWD/mozilla-thunderbird.desktop > $PKG/usr/share/applications/mozilla-thunderbird.desktop
 mkdir -p $PKG/usr/share/pixmaps
-cat $CWD/thunderbird.png > $PKG/usr/share/pixmaps/thunderbird.png
+# Symlinked below.
+#cat $CWD/thunderbird.png > $PKG/usr/share/pixmaps/thunderbird.png
 
 # These files/directories are usually created if Thunderbird is run as root,
 # which on many systems might (and possibly should) be never.  Therefore, if we
@@ -218,7 +274,7 @@ for i in 16 22 24 32 48 256; do
     $PKG/usr/share/icons/hicolor/${i}x${i}/apps/thunderbird.png
 done
 mkdir -p $PKG/usr/share/pixmaps
-( cd $PKG/usr/share/pixmaps ; ln -sf /usr/share/icons/hicolor/256x256/apps/thunderbird . )
+( cd $PKG/usr/share/pixmaps ; ln -sf /usr/share/icons/hicolor/256x256/apps/thunderbird.png . )
 mkdir -p $PKG/usr/lib$LIBDIRSUFFIX/thunderbird-$RELEASEVER/chrome/icons/default
 install -m 644 other-licenses/branding/thunderbird/mailicon16.png \
   $PKG/usr/lib$LIBDIRSUFFIX/thunderbird-$RELEASEVER/icons/
diff --git a/source/xap/seamonkey/seamonkey.SlackBuild b/source/xap/seamonkey/seamonkey.SlackBuild
--- a/source/xap/seamonkey/seamonkey.SlackBuild
+++ b/source/xap/seamonkey/seamonkey.SlackBuild
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,6 +20,9 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+cd $(dirname $0) ; CWD=$(pwd)
+
+PKGNAM=seamonkey
 TARBALLVER=${VERSION:-$(basename $(ls seamonkey-*.tar.* | cut -d - -f 2 | rev | cut -f 3- -d . | rev) .source)}
 # Strip the end from beta versions:
 VERSION=$(echo $TARBALLVER | cut -f 1 -d b)
@@ -35,44 +38,72 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$TARBALLVER-$ARCH-$BUILD.txz"
+  echo "$PKGNAM-solibs-$TARBALLVER-$ARCH-$BUILD.txz"
+  exit 0
+fi
+
 if [ "$ARCH" = "i586" ]; then
   LIBDIRSUFFIX=""
-  OPTIMIZE_FLAG="-O2"
-  # On IA32, use gold since GNU ld runs out of memory linking libxul.so:
-  PATH="$(pwd)/gold:$PATH"
-  export CC="gcc -B$(pwd)/gold"
-  export CXX="g++ -B$(pwd)/gold"
+  OPTIMIZE_FLAG=${OPTIMIZE_FLAG:-"-O1"}
+elif [ "$ARCH" = "i686" ]; then
+  LIBDIRSUFFIX=""
+  OPTIMIZE_FLAG=${OPTIMIZE_FLAG:-"-O1"}
 elif [ "$ARCH" = "x86_64" ]; then
   LIBDIRSUFFIX="64"
-  OPTIMIZE_FLAG="-O2"
+  OPTIMIZE_FLAG=${OPTIMIZE_FLAG:-"-O1"}
 else
   LIBDIRSUFFIX=""
-  OPTIMIZE_FLAG="-O2"
+  OPTIMIZE_FLAG=${OPTIMIZE_FLAG:-"-O1"}
 fi
+
+# Link using gold.  This avoids running out of memory on 32-bit systems, and
+# avoids a recurring build failure with GNU ld on other systems.
+PATH="$(pwd)/gold:$PATH"
+export CC=${CC:-"gcc -B$(pwd)/gold"}
+export CXX=${CXX:-"g++ -B$(pwd)/gold -fno-delete-null-pointer-checks"}
 
 NUMJOBS=${NUMJOBS:-" -j7 "}
 
-# Workaround to prevent unidentified crashes when compiling with recent gcc.
-# Presumably a newer version will fix this (as it did with Firefox), so only
-# enable the workaround for known crashing versions.
-# Test page to check for crash:  http://onet.pl
-if [ $VERSION = 2.39 -o \
-     $VERSION = 2.40 ]; then
-  OPTIMIZE_FLAG="$(echo "$OPTIMIZE_FLAG" | sed 's/O2/Os/g')"
-  echo "Detected Seamonkey $VERSION...  enabling crash workaround O2 -> Os."
-  sleep 1
-fi
-
-CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-seamonkey
+
+# If there is a private Google API key available at compile time, use
+# it to enable support for Google Safe Browsing. For Slackware builds,
+# we use a private key issued for the Slackware project. If you are
+# rebuilding and need this support, or you are producing your own
+# distribution, you may obtain your own Google API key at no charge by
+# following these instructions:
+# https://bugzilla.mozilla.org/show_bug.cgi?id=1377987#c0
+if [ -r /root/google-api-key ]; then
+  GOOGLE_API_KEY="--with-google-api-keyfile=/root/google-api-key"
+fi
+
 rm -rf $PKG
 mkdir -p $TMP $PKG/usr
 
+# We need to use the incredibly ancient autoconf-2.13 for this  :/
+( cd $CWD/autoconf ; ./autoconf.build )
+PATH=$TMP/autoconf-tmp/usr/bin:$PATH
+
 cd $TMP
 rm -rf seamonkey-${TARBALLVER}
+# Unpack this in a subdirectory to prevent changing permissions on /tmp:
+rm -rf seamonkey-unpack
+mkdir seamonkey-unpack
+cd seamonkey-unpack
 tar xvf $CWD/seamonkey-${TARBALLVER}.source.tar.?z* || exit 1
+mv * ..
+cd ..
+rm -rf seamonkey-unpack
 cd seamonkey-${TARBALLVER} || exit 1
+
+# Retain GTK+ v2 scrolling behavior:
+zcat $CWD/sm.ui.scrollToClick.diff.gz | patch -p1 --verbose || exit 1
 
 # Make sure the perms/ownerships are sane:
 chown -R root:root .
@@ -88,35 +119,28 @@ chown -R root:root .
 OPTIONS="\
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
-  --enable-optimize=$OPTIMIZE_FLAG \
   --enable-cpp-rtti \
-  --enable-default-toolkit=cairo-gtk2 \
+  --enable-default-toolkit=cairo-gtk3 \
   --enable-startup-notification \
+  --enable-alsa \
   --disable-debug \
   --with-default-mozilla-five-home=/usr/lib${LIBDIRSUFFIX}/seamonkey-${VERSION} \
   --enable-strip \
   --disable-tests \
   --disable-crashreporter \
-  --enable-svg \
-  --enable-canvas \
-  --enable-gstreamer=1.0 \
-  --disable-short-wchar \
-  --enable-nspr-autoconf \
+  --enable-accessibility \
+  $GOOGLE_API_KEY \
+  --enable-safe-browsing \
+  --disable-updater \
+  --enable-chrome-format=omni \
+  --disable-necko-wifi \
   --enable-extensions=default,irc \
-  --enable-crypto \
-  --enable-libxul \
-  --disable-xprint \
   --without-system-nspr \
   --with-system-zlib \
-  --with-system-mng \
   --enable-application=suite \
-  --enable-xft \
+  --with-pthreads \
   --host=$ARCH-slackware-linux \
-  --target=$ARCH-slackware-linux \
-  --build=$ARCH-slackware-linux"
-
-  # --enable-system-cairo \
-  # --with-system-png
+  --target=$ARCH-slackware-linux"
 
 export BUILD_OFFICIAL=1
 export MOZILLA_OFFICIAL=1
@@ -129,6 +153,10 @@ unset DBUS_SESSION_BUS_ADDRESS ORBIT_SOCKETDIR SESSION_MANAGER \
 # Assemble our .mozconfig:
 echo > .mozconfig
 
+# Tell .mozconfig about the selected compiler:
+echo "export CC=\"${CC}\"" >> .mozconfig
+echo "export CXX=\"${CXX}\"" >> .mozconfig
+
 # Mozilla devs enforce using an objdir for building
 # https://developer.mozilla.org/en/Configuring_Build_Options#Building_with_an_objdir
 mkdir obj
@@ -136,12 +164,21 @@ echo "mk_add_options MOZ_OBJDIR=$(pwd)/obj" >> .mozconfig
 # This directory is also needed or the build will fail:
 mkdir -p mozilla/obj
 
-# Write in it the options above
+# Set options for $OPTIMIZE_FLAG:
+echo "ac_add_options --enable-optimize=\"${OPTIMIZE_FLAG}\"" >> .mozconfig
+
+# Add the $OPTIONS above to .mozconfig:
 for option in $OPTIONS; do echo "ac_add_options $option" >> .mozconfig; done
 
 echo "ac_add_options --disable-tests" >> .mozconfig
 make -f client.mk build || exit 1
 make -f client.mk install DESTDIR=$PKG || exit 1
+
+# Keep the "obsolete" nspr headers:
+if [ ! -d mozilla/dist/include/nspr/obsolete ]; then
+  mkdir -p mozilla/dist/include/nspr/obsolete
+  cp -a mozilla/nsprpub/pr/include/obsolete/*.h mozilla/dist/include/nspr/obsolete
+fi
 
 # Install nspr/nss headers.
 for includedir in nspr nspr/obsolete nspr/private ; do
