Wed Dec 18 22:12:02 UTC 2024
a/lilo-24.2-x86_64-13.txz:  Rebuilt.
  liloconfig: add a line for /boot/initrd-generic.img if it exists, if not try
  /boot/initrd.gz, and if that's not there do not use an initrd.
  Thanks to Fuzero.
a/mkinitrd-1.4.11-x86_64-59.txz:  Rebuilt.
  /etc/default/geninitrd: now that none of lilo, elilo, or grub want that
  initrd.gz symlink, default to not creating it. If you're using lilo, you
  may need to edit lilo.conf to change from initrd.gz to initrd-generic.img.
l/libtraceevent-1.8.4-x86_64-2.txz:  Rebuilt.
  Drop static library, ship man pages. Thanks to Heinz Wiesinger.
l/libtracefs-1.8.1-x86_64-2.txz:  Rebuilt.
  Drop static library, ship man pages. Thanks to Heinz Wiesinger.
l/protobuf-29.2-x86_64-1.txz:  Upgraded.
x/xorg-server-21.1.15-x86_64-1.txz:  Upgraded.
x/xorg-server-xephyr-21.1.15-x86_64-1.txz:  Upgraded.
x/xorg-server-xnest-21.1.15-x86_64-1.txz:  Upgraded.
x/xorg-server-xvfb-21.1.15-x86_64-1.txz:  Upgraded.
xfce/Greybird-3.23.4-noarch-1.txz:  Upgraded.
extra/brltty/brltty-6.7-x86_64-4.txz:  Rebuilt.
  Fixed redundant misplaced TCL_DIR. Thanks to chrisretusn.
extra/tigervnc/tigervnc-1.14.1-x86_64-3.txz:  Rebuilt.
  Rebuilt against xorg-server-21.1.15.

diff --git a/source/a/lilo/liloconfig b/source/a/lilo/liloconfig
--- a/source/a/lilo/liloconfig
+++ b/source/a/lilo/liloconfig
@@ -2,7 +2,7 @@
 #
 # Copyright 1994, 1998, 1999  Patrick Volkerding, Moorhead, Minnesota USA
 # Copyright 2002, 2003  Slackware Linux, Inc, Concord, CA
-# Copyright 2007, 2008, 2011, 2013, 2018, 2020  Patrick Volkerding, Sebeka, Minnesota, USA
+# Copyright 2007, 2008, 2011, 2013, 2018, 2020, 2024  Patrick Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -452,14 +452,28 @@ EOF
  LNXP="$(PROBE -l | grep "Linux$")" 
  LNXP="$(echo $LNXP | cut -f 1 -d ' ' | sort)"
  if [ ! "$LNXP" = "" ]; then
-  cat << EOF >> $T_PX/etc/lilo.conf
+
+  if [ -z "$INITRD" ]; then
+   cat << EOF >> $T_PX/etc/lilo.conf
 # Linux bootable partition config begins
 image = $KERNEL
   root = $ROOT_DEVICE
   label = Linux
-  read-only
+  read-only  # Partitions should be mounted read-only for checking
 # Linux bootable partition config ends
 EOF
+  else
+   cat << EOF >> $T_PX/etc/lilo.conf
+# Linux bootable partition config begins
+image = $KERNEL
+  initrd = $INITRD
+  root = $ROOT_DEVICE
+  label = Linux
+  read-only  # Partitions should be mounted read-only for checking
+# Linux bootable partition config ends
+EOF
+  fi
+
   echo "Linux    -  (Linux partition)" >> $T_PX/boot/boot_message.txt
  fi
 # DEAD CODE, BUT IN CASE OS/2 MAKES A COMEBACK!
@@ -664,18 +678,29 @@ if [ "$ROOT_DEVICE" = "" ]; then
   ROOT_DEVICE="$(mount | grep " on $T_PX " | cut -f 1 -d " " | head -n 1)"
  fi
 fi
+
 # Figure out where the kernel is:
 ARCHTYPE=i386
-if [ -r $T_PX/vmlinuz ]; then
-  KERNEL=/vmlinuz
+if [ -r $T_PX/boot/vmlinuz-generic ]; then
+  KERNEL=/boot/vmlinuz-generic
 elif [ -r $T_PX/boot/vmlinuz ]; then
   KERNEL=/boot/vmlinuz
 elif [ -r $T_PX/usr/src/linux/arch/$ARCHTYPE/boot/bzImage ]; then
   KERNEL=/usr/src/linux/arch/$ARCHTYPE/boot/bzImage
-elif [ -r $T_PX/usr/src/linux/arch/$ARCHTYPE/boot/zImage ]; then
-  KERNEL=/usr/src/linux/arch/$ARCHTYPE/boot/zImage
 else
-  exit 99 # no kernel?  guess you couldn't read.  bye bye.
+  echo "ERROR: could not find a Linux kernel."
+  echo "Tried: $T_PX/boot/vmlinuz-generic $T_PX/boot/vmlinuz $T_PX/usr/src/linux/arch/$ARCHTYPE/boot/bzImage"
+  exit 99
+fi
+
+# Figure out where the initrd is:
+if [ -r $T_PX/boot/initrd-generic.img ]; then
+  INITRD=/boot/initrd-generic.img
+elif [ -r $T_PX/boot/initrd.gz ]; then
+  INITRD=/boot/initrd.gz
+else
+  # Having an initrd is not mandatory.
+  unset INITRD
 fi
 
  # OK, now let's see if we should automate things:
@@ -965,7 +990,9 @@ SINGLE WORD." 11 60 2> $TMP/reply
      continue
     fi
     LABEL="$(cat $TMP/reply)"
-    cat << EOF >> $TMP/lilo.conf
+
+    if [ -z "$INITRD" ]; then
+     cat << EOF >> $TMP/lilo.conf
 # Linux bootable partition config begins
 image = $KERNEL
   root = $LINUX_PART
@@ -973,6 +1000,18 @@ image = $KERNEL
   read-only  # Partitions should be mounted read-only for checking
 # Linux bootable partition config ends
 EOF
+    else
+     cat << EOF >> $TMP/lilo.conf
+# Linux bootable partition config begins
+image = $KERNEL
+  initrd = $INITRD
+  root = $LINUX_PART
+  label = $LABEL
+  read-only  # Partitions should be mounted read-only for checking
+# Linux bootable partition config ends
+EOF
+    fi
+
    else
     dialog --title "CAN'T ADD LINUX PARTITION" --msgbox "You can't add \
 partitions unless you start over with a new LILO header." 6 60
