Tue Nov  9 20:22:27 UTC 2021
a/dialog-1.3_20211107-x86_64-1.txz:  Upgraded.
ap/mariadb-10.5.13-x86_64-1.txz:  Upgraded.
  This update fixes a security issue:
  Easily exploitable vulnerability allows high privileged attacker with network
  access via multiple protocols to compromise MariaDB Server. Successful
  attacks of this vulnerability can result in unauthorized ability to cause a
  hang or frequently repeatable crash (complete DOS) of MariaDB Server as well
  as unauthorized update, insert or delete access to some of MariaDB Server
  accessible data.
  For more information, see:
    https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-35604
  (* Security fix *)
kde/bluedevil-5.23.3-x86_64-1.txz:  Upgraded.
kde/breeze-5.23.3-x86_64-1.txz:  Upgraded.
kde/breeze-grub-5.23.3-x86_64-1.txz:  Upgraded.
kde/breeze-gtk-5.23.3-x86_64-1.txz:  Upgraded.
kde/drkonqi-5.23.3-x86_64-1.txz:  Upgraded.
kde/kactivitymanagerd-5.23.3-x86_64-1.txz:  Upgraded.
kde/kde-cli-tools-5.23.3-x86_64-1.txz:  Upgraded.
kde/kde-gtk-config-5.23.3-x86_64-1.txz:  Upgraded.
kde/kdecoration-5.23.3-x86_64-1.txz:  Upgraded.
kde/kdeplasma-addons-5.23.3-x86_64-1.txz:  Upgraded.
kde/kdev-python-5.6.2-x86_64-4.txz:  Added.
kde/kgamma5-5.23.3-x86_64-1.txz:  Upgraded.
kde/khotkeys-5.23.3-x86_64-1.txz:  Upgraded.
kde/kinfocenter-5.23.3-x86_64-1.txz:  Upgraded.
kde/kmenuedit-5.23.3-x86_64-1.txz:  Upgraded.
kde/kscreen-5.23.3-x86_64-1.txz:  Upgraded.
kde/kscreenlocker-5.23.3-x86_64-1.txz:  Upgraded.
kde/ksshaskpass-5.23.3-x86_64-1.txz:  Upgraded.
kde/ksystemstats-5.23.3-x86_64-1.txz:  Upgraded.
kde/kwallet-pam-5.23.3-x86_64-1.txz:  Upgraded.
kde/kwayland-integration-5.23.3-x86_64-1.txz:  Upgraded.
kde/kwayland-server-5.23.3-x86_64-1.txz:  Upgraded.
kde/kwin-5.23.3-x86_64-1.txz:  Upgraded.
kde/kwrited-5.23.3-x86_64-1.txz:  Upgraded.
kde/layer-shell-qt-5.23.3-x86_64-1.txz:  Upgraded.
kde/libkscreen-5.23.3-x86_64-1.txz:  Upgraded.
kde/libksysguard-5.23.3-x86_64-1.txz:  Upgraded.
kde/milou-5.23.3-x86_64-1.txz:  Upgraded.
kde/oxygen-5.23.3-x86_64-1.txz:  Upgraded.
kde/plasma-browser-integration-5.23.3-x86_64-1.txz:  Upgraded.
kde/plasma-desktop-5.23.3-x86_64-1.txz:  Upgraded.
kde/plasma-disks-5.23.3-x86_64-1.txz:  Upgraded.
kde/plasma-firewall-5.23.3-x86_64-1.txz:  Upgraded.
kde/plasma-integration-5.23.3-x86_64-1.txz:  Upgraded.
kde/plasma-nm-5.23.3-x86_64-1.txz:  Upgraded.
kde/plasma-pa-5.23.3-x86_64-1.txz:  Upgraded.
kde/plasma-sdk-5.23.3-x86_64-1.txz:  Upgraded.
kde/plasma-systemmonitor-5.23.3-x86_64-1.txz:  Upgraded.
kde/plasma-vault-5.23.3-x86_64-1.txz:  Upgraded.
kde/plasma-workspace-5.23.3-x86_64-1.txz:  Upgraded.
kde/plasma-workspace-wallpapers-5.23.3-x86_64-1.txz:  Upgraded.
kde/polkit-kde-agent-1-5.23.3-x86_64-1.txz:  Upgraded.
kde/powerdevil-5.23.3-x86_64-1.txz:  Upgraded.
kde/qqc2-breeze-style-5.23.3-x86_64-1.txz:  Upgraded.
kde/sddm-kcm-5.23.3-x86_64-1.txz:  Upgraded.
kde/systemsettings-5.23.3-x86_64-1.txz:  Upgraded.
kde/xdg-desktop-portal-kde-5.23.3-x86_64-1.txz:  Upgraded.
l/libxml2-2.9.12-x86_64-5.txz:  Rebuilt.
  Applied upstream patch:
  [PATCH] Work around lxml API abuse.
  Thanks to brobr.
x/libdrm-2.4.108-x86_64-1.txz:  Upgraded.
x/libevdev-1.12.0-x86_64-1.txz:  Upgraded.
xap/xsnow-3.3.2-x86_64-1.txz:  Upgraded.
  Just in time for tomorrow night here in Minnesota. :-)

diff --git a/source/installer/sources/initrd/usr/lib/setup/setup b/source/installer/sources/initrd/usr/lib/setup/setup
--- a/source/installer/sources/initrd/usr/lib/setup/setup
+++ b/source/installer/sources/initrd/usr/lib/setup/setup
@@ -2,7 +2,7 @@
 #
 # Copyright 1993, 1994, 1999  Patrick Volkerding, Moorhead, Minnesota USA
 # Copyright 2001, 2003, 2004  Slackware Linux, Inc., Concord, CA
-# Copyright 2006, 2007, 2018  Patrick Volkerding, Sebeka, Minnesota USA
+# Copyright 2006, 2007, 2018, 2021 Patrick Volkerding, Sebeka, Minnesota USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is 
@@ -421,42 +421,59 @@ if [ -f ${T_PX}/etc/fstab ]; then
      --title "Slackware Linux Setup is complete" "$@" \
      --msgbox "\nPlease remove the installation disc.\n" 7 40
   fi
-  # Offer to reboot or drop to shell:
-  dialog \
+
+  # Offer to reboot or drop to shell or power off.
+  exec 3>&1
+  installerexittype=$( dialog \
+     --clear \
      --title "Slackware Linux Setup is complete" "$@" \
-     --yesno \
-     "\nWould you like to reboot your system?\n\n\n\
-If you choose \"No\", you will be dropped to a shell.\n" 11 50
-    retval=$?
-    if [ $retval = 1 ]; then
-      clear
-      echo
-      echo "You may now reboot your system once you are ready."
-      echo "You can issue the 'reboot' command; or if your system has"
-      echo "a keyboard attached, you can use the key combination: control+alt+delete"
-      echo
-    else
-      touch /reboot
-    fi
+     --default-item Reboot "$@" \
+     --menu "Slackware Linux setup is complete.
+             \n\nYou may now reboot your machine into the Slackware OS.\n
+             \nIf you have some post-installation tweaks you'd like to make manually, you can open a shell.\n
+             \
+             \nIf you want to make some changes to the hardware before booting the
+               Slackware OS, you may wish to power off computer.\n" \
+             17 80 3 \
+	     Shell	 "" \
+	     Reboot	 "" \
+	     "Power Off" "" \
+   2>&1 1>&3 )
+   retval=$?
+   exec 3>&-
 fi
 
 # Fix the date:
 /sbin/fixdate
 
-# final cleanup
+# Final cleanup
 rm -f $TMP/tagfile $TMP/SeT* $TMP/tar-error $TMP/PKGTOOL_REMOVED
 rm -f /var/log/mount/treecache
 rmdir /var/log/mntiso 2>/dev/null
 rm -rf $TMP/treecache
 rm -rf $TMP/pkgcache
 rmdir ${T_PX}/tmp/orbit-root 2> /dev/null
+sync
 
-# If the OS had been installed and the user elected to reboot:
-if [ -f /reboot ]; then
-   clear
-   echo "** Starting reboot **"
-   sleep 1
-   reboot
-fi
+# Handle installer exit types:
+case "$installerexittype" in
+   "Reboot")
+       clear
+       printf "\n** Starting reboot **\n\n"
+       sleep 1.5
+       reboot ;;
+   "Power Off")
+       clear
+       printf "\n** Powering off **\n\n"
+       sleep 1.5
+       poweroff ;;
+   "Shell")
+       # Note: the shell the user receives at this point is the parent from which
+       # they entered this 'setup' script.  This is why we don't explictly open a shell here.
+       clear
+       printf "\nYou may now reboot your system once you are ready.\n"
+       printf "You can issue the 'reboot' command; or if your system has\n"
+       printf "a keyboard attached, you can use the key combination: control+alt+delete\n\n" ;;
+esac
 
-# end slackware setup script
+# End of Slackware setup script
