Wed May 22 18:57:13 UTC 2024
a/e2fsprogs-1.47.1-x86_64-1.txz:  Upgraded.
a/iniparser-4.2.2-x86_64-1.txz:  Upgraded.
  Shared library .so-version bump.
a/ndctl-79-x86_64-2.txz:  Rebuilt.
  Recompiled against iniparser-4.2.2.
d/python-setuptools-70.0.0-x86_64-1.txz:  Upgraded.
kde/calligra-3.2.1-x86_64-39.txz:  Rebuilt.
  Recompiled against poppler-24.05.0.
kde/cantor-23.08.5-x86_64-6.txz:  Rebuilt.
  Recompiled against poppler-24.05.0.
kde/kfilemetadata-5.116.0-x86_64-2.txz:  Rebuilt.
  Recompiled against poppler-24.05.0.
kde/kile-2.9.93-x86_64-33.txz:  Rebuilt.
  Recompiled against poppler-24.05.0.
kde/kitinerary-23.08.5-x86_64-4.txz:  Rebuilt.
  Recompiled against poppler-24.05.0.
kde/krita-5.2.2-x86_64-9.txz:  Rebuilt.
  Recompiled against poppler-24.05.0.
kde/okular-23.08.5-x86_64-4.txz:  Rebuilt.
  Recompiled against poppler-24.05.0.
kde/qqc2-desktop-style-5.116.1-x86_64-1.txz:  Upgraded.
l/hicolor-icon-theme-0.18-noarch-1.txz:  Upgraded.
l/libcupsfilters-2.0.0-x86_64-2.txz:  Rebuilt.
  Recompiled against poppler-24.05.0.
l/lmdb-0.9.33-x86_64-1.txz:  Upgraded.
l/poppler-24.05.0-x86_64-1.txz:  Upgraded.
  This seems to require C++20 now...
  Shared library .so-version bump.
l/python-requests-2.32.1-x86_64-1.txz:  Upgraded.
l/qt6-6.7.1_20240516_6977d02f-x86_64-1.txz:  Upgraded.
n/curl-8.8.0-x86_64-1.txz:  Upgraded.
n/openldap-2.6.8-x86_64-1.txz:  Upgraded.
x/xorg-server-xwayland-24.1.0-x86_64-1.txz:  Upgraded.
  Thanks to marav for the patch.

diff --git a/source/l/qt6/qt6.SlackBuild b/source/l/qt6/qt6.SlackBuild
--- a/source/l/qt6/qt6.SlackBuild
+++ b/source/l/qt6/qt6.SlackBuild
@@ -42,7 +42,7 @@ SYSTEM_FFMPEG=${SYSTEM_FFMPEG:-YES}
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$(uname -m)" in
-    i?86) ARCH=i586 ;;
+    i?86) ARCH=i686 ;;
     arm*) readelf /usr/bin/file -A | grep -E -q "Tag_CPU.*[4,5]" && ARCH=arm || ARCH=armv7hl ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
     *) ARCH=$(uname -m) ;;
@@ -64,6 +64,11 @@ if [ "$ARCH" = "i486" ]; then
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i586" ]; then
   SLKCFLAGS="-O2 -march=i586 -mtune=i686"
+  SLKLDFLAGS=""
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i686" ]; then
+  # Looks like this is baseline now... maybe time to bump everything to at least i686
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686 -mfpmath=sse -msse -msse2 -fcf-protection=none"
   SLKLDFLAGS=""
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "s390" ]; then
@@ -147,14 +152,16 @@ pushd qtwebengine
 popd
 cat $CWD/patches/nodejs-allow-32bit.patch | patch -p1 --verbose || exit 1
 
-# GCC13 requires this include:
-cat $CWD/patches/qt6-3d_gcc13.patch | patch -p0 --verbose || exit 1
+# Patch header issue that causes the compile to fail with "x11 not defined"
+pushd qtwebengine
+  cat $CWD/patches/qtwebengine-6.7.0-displaykey-header.patch | patch -p1 --verbose || exit 1
+popd
 
 # Previously we didn't have a protobuf package in Slackware.
 # Now that we do, it's apparently too new to use with Qt6, so let's just
 # disable it to get the same features that we previously did.
 # Patches would be accepted here. :-)
-PROTOBUF="-DQT_FEATURE_qtprotobufgen=OFF"
+#PROTOBUF="-DQT_FEATURE_qtprotobufgen=OFF"
 
 # The qtquick3dphysics only compiles on a limited set of architectures:
 case "${ARCH}" in
