Sat May 10 19:28:49 UTC 2025
a/mkinitrd-1.4.11-x86_64-68.txz:  Rebuilt.
  In addition to GENINITRD_OVERRIDE_SCRIPT which defines a custom script that
  completely replaces /var/lib/pkgtools/setup/setup.01.mkinitrd, let's also
  allow defining a POST_INSTALL_SCRIPT in /etc/default/geninitrd. If defined,
  it will be run after geninitrd has completed its usual tasks. This could be
  used to copy the kernel and initrd to the EFI partition for rEFInd or some
  other bootloader.
  Thanks to j12i.
  Export ${KERNEL_VERSION} for use by an override or post-install script.
  Thanks to ZhaoLin1547.
d/python-setuptools-80.4.0-x86_64-1.txz:  Upgraded.
kde/extra-cmake-modules-6.14.0-x86_64-1.txz:  Upgraded.
n/openresolv-3.16.3-noarch-1.txz:  Upgraded.

diff --git a/source/a/mkinitrd/geninitrd b/source/a/mkinitrd/geninitrd
--- a/source/a/mkinitrd/geninitrd
+++ b/source/a/mkinitrd/geninitrd
@@ -71,6 +71,17 @@ if [ ! -z "$KERNEL" ]; then
   export KERNEL
 fi
 
+# Let's find the kernel version and define it as $KERNEL_VERSION, since this
+# might be useful for an override or post-install script:
+if [ -r $KERNEL ]; then
+  KERNEL_VERSION=$(strings $KERNEL | grep '([^ ]*@[^ ]*) #' | cut -f1 -d' ')
+  if [ -z "$KERNEL_VERSION" ]; then
+    echo "error: $KERNEL is not a Linux kernel."
+    exit 1
+  fi
+  export KERNEL_VERSION
+fi
+
 # In case you cannot make this script do exactly what you require, you're
 # welcome to create your own script to be run instead. Define this in
 # /etc/default/geninitrd (GENINITRD_OVERRIDE_SCRIPT).
@@ -85,4 +96,15 @@ if [ -x "$RELATIVE_OVERRIDE_SCRIPT" ]; then
   chroot . $GENINITRD_OVERRIDE_SCRIPT
 else # we will run the default handler from the setup scripts:
   chroot . /var/lib/pkgtools/setup/setup.01.mkinitrd
+fi
+
+# Is there a post-install script? If so, run it here:
+if [ ! -z "$POST_INSTALL_SCRIPT" ]; then
+  # If this is an absolute pathname, make it relative to /:
+  if [ "$(echo $POST_INSTALL_SCRIPT | cut -b 1)" = "/" ]; then
+    POST_INSTALL_SCRIPT="$(echo $POST_INSTALL_SCRIPT | cut -b 2-)"
+  fi
+  if [ -x "$POST_INSTALL_SCRIPT" ]; then
+    chroot . $POST_INSTALL_SCRIPT
+  fi
 fi
