Slackware 13.1
Wed May 19 08:58:23 UTC 2010
Slackware 13.1 x86_64 stable is released!
Lots of thanks are due -- see the RELEASE_NOTES and the rest of the
ChangeLog for credits.  The ISOs are on their way to replication,
a 6 CD-ROM 32-bit set and a dual-sided 32-bit/64-bit x86/x86_64 DVD.
We are taking pre-orders now at store.slackware.com, and offering
a discount if you sign up for a subscription.  Consider picking up
a copy to help support the project.  Thanks again to the Slackware
community for testing, contributing, and generally holding us to a
high level of quality.  :-)
Enjoy!

diff --git a/source/a/mkinitrd/init b/source/a/mkinitrd/init
--- a/source/a/mkinitrd/init
+++ b/source/a/mkinitrd/init
@@ -4,7 +4,7 @@
 #         This requires that your kernel supports initramfs!!!
 #
 # Copyright 2004  Slackware Linux, Inc., Concord, CA, USA
-# Copyright 2007, 2008  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2007, 2008, 2009, 2010  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -33,95 +33,131 @@
 #
 # Config files used by this script:
 #
-# /rootdev   Contains the name of the root device, such as: /dev/hda1 
+# /rootdev        Contains the name of the root device, such as: /dev/hda1 
 #
-# /rootfs    Contains the root filesystem type, such as: xfs
+# /rootfs         Contains the root filesystem type, such as: xfs
 #
 # /initrd-name    Contains the name of the initrd file.
 #
+# /resumedev      Contains the name of the device to resume from hibernation.
+#
+# /luksdev        Contains colon separated list of luks encrypted devices to
+#                 be unlocked.
+#
+# /lukskey        Contains the path to a LUKS key-file for automatic unlock
+#                 Format: LABEL=<partition_label>:/path/to/file
+#                         UUID=<partition_uuid>:/path/to/file
+#
+# /wait-for-root  Contains a number - the init script will wait this amount
+#                 of seconds before creating device nodes.
+#
+# /keymap         Contains the name for a custom keyboard map 
+#
 # Optional:
-# /load_kernel_modules   A script that uses insmod to load the desired
-#            modules.  If this file is not present, all the modules
-#            in /lib/modules/`uname -r`/ will be loaded in the usual
-#            sorted order.  If you need to load the modules in a
-#            certain order, or if the modules need extra options,
-#            then use a load_kernel_modules script.
 #
-#            There's an example in here.  To actually use it, you'll
-#            need to make it executable:  
+# /load_kernel_modules
+#                 A script that uses insmod to load the desired
+#                 modules.  If this file is not present, all the modules
+#                 in /lib/modules/$(uname -r)/ will be loaded in the usual
+#                 sorted order.  If you need to load the modules in a
+#                 certain order, or if the modules need extra options,
+#                 then use a load_kernel_modules script.
 #
-#                chmod 755 load_kernel_modules
+#                 There's an example in here.  To actually use it, you'll
+#                 need to make it executable:  
+#
+#                     chmod 755 load_kernel_modules
 
-INITRD=`cat /initrd-name`
-ROOTDEV=`cat /rootdev`
-ROOTFS=`cat /rootfs`
-LUKSDEV=`cat /luksdev`
-RESUMEDEV=`cat /resumedev`
-WAIT=`cat /wait-for-root`
-KEYMAP=`cat /keymap`
+INITRD=$(cat /initrd-name)
+ROOTDEV=$(cat /rootdev)
+ROOTFS=$(cat /rootfs)
+LUKSDEV=$(cat /luksdev)
+LUKSKEY=$(cat /lukskey)
+RESUMEDEV=$(cat /resumedev)
+WAIT=$(cat /wait-for-root)
+KEYMAP=$(cat /keymap)
+INIT=/sbin/init
+
+PATH="/sbin:/bin:/usr/sbin:/usr/bin"
 
 # Mount /proc and /sys:
 mount -n proc /proc -t proc
 mount -n sysfs /sys -t sysfs
 
+if grep devtmpfs /proc/filesystems 1>/dev/null 2>/dev/null ; then
+  DEVTMPFS=1
+  mount -n devtmpfs /dev -t devtmpfs
+fi	
+
 # Parse command line
-for ARG in `cat /proc/cmdline`; do
+for ARG in $(cat /proc/cmdline); do
   case $ARG in
+    0|1|2|3|4|5|6|S|s|single)
+      RUNLEVEL=$ARG
+    ;;
+    init=*)
+      INIT=$(echo $ARG | cut -f2 -d=)
+    ;;
+    luksdev=/dev/*)
+      LUKSDEV=$(echo $ARG | cut -f2 -d=)
+    ;;
+    lukskey=*)
+      LUKSKEY=$(echo $ARG | cut -f2- -d=)
+    ;;
     rescue)
       RESCUE=1
     ;;
+    resume=*)
+      RESUMEDEV=$(echo $ARG | cut -f2 -d=)
+    ;;
     root=/dev/*)
-      ROOTDEV=`echo $ARG | cut -f2 -d=`
-    ;;
-    rootfs=*)
-      ROOTFS=`echo $ARG | cut -f2 -d=`
-    ;;
-    luksdev=/dev/*)
-      LUKSDEV=`echo $ARG | cut -f2 -d=`
-    ;;
-    waitforroot=*)
-      WAIT=`echo $ARG | cut -f2 -d=`
+      ROOTDEV=$(echo $ARG | cut -f2 -d=)
     ;;
     root=LABEL=*)
-      ROOTDEV=`echo $ARG | cut -f2- -d=`
+      ROOTDEV=$(echo $ARG | cut -f2- -d=)
     ;;
-    resume=*)
-      RESUMEDEV=`echo $ARG | cut -f2 -d=`
+    root=UUID=*)
+      ROOTDEV=$(echo $ARG | cut -f2- -d=)
     ;;
-    0|1|2|3|4|5|6)
-      RUNLEVEL=$ARG
+    rootfs=*)
+      ROOTFS=$(echo $ARG | cut -f2 -d=)
+    ;;
+    waitforroot=*)
+      WAIT=$(echo $ARG | cut -f2 -d=)
     ;;
   esac
 done
 
 # Load kernel modules:
-if [ ! -d /lib/modules/`uname -r` ]; then
-  echo "No kernel modules found for Linux `uname -r`."
+if [ ! -d /lib/modules/$(uname -r) ]; then
+  echo "No kernel modules found for Linux $(uname -r)."
 elif [ -x ./load_kernel_modules ]; then # use load_kernel_modules script:
   echo "${INITRD}:  Loading kernel modules from initrd image:"
   . ./load_kernel_modules
 else # load modules (if any) in order:
-  if ls /lib/modules/`uname -r`/*.*o 1> /dev/null 2> /dev/null ; then
+  if ls /lib/modules/$(uname -r)/*.*o 1> /dev/null 2> /dev/null ; then
     echo "${INITRD}:  Loading kernel modules from initrd image:"
-    for module in /lib/modules/`uname -r`/*.*o ; do
-      insmod $module
+    for module in /lib/modules/$(uname -r)/*.*o ; do
+      /sbin/insmod $module
     done
     unset module
   fi
 fi
 
-# Sometimes the devices needs extra time to be available.
-# root on USB are good example of that.
+# Sometimes the devices need extra time to be available.
+# A root filesystem on USB is a good example of that.
 sleep $WAIT
 
 # If udevd is available, use it to generate block devices
 # else use mdev to read sysfs and generate the needed devices 
 if [ -x /sbin/udevd -a -x /sbin/udevadm ]; then
   /sbin/udevd --daemon
-  /sbin/udevadm trigger --subsystem-match=block
+  /sbin/udevadm control --property=STARTUP=1
+  /sbin/udevadm trigger --subsystem-match=block --action=add
   /sbin/udevadm settle --timeout=10
+  /sbin/udevadm control --property=STARTUP=
 else
-  mdev -s
+  [ "$DEVTMPFS" != "1" ] && mdev -s
 fi
 
 # Load a custom keyboard mapping:
@@ -136,62 +172,106 @@ if [ "$RESCUE" = "" ]; then
     /sbin/mdadm -E -s >/etc/mdadm.conf
     /sbin/mdadm -A -s
   fi
-  
-  # Find root device if a label was given:
-  if echo $ROOTDEV | grep -q "LABEL=" ; then
-    ROOTDEV=`findfs $ROOTDEV`
-  fi
 
-  # Make encrypted root partition available:
-  # The useable device will be under /dev/mapper/
-  # Three scenarios for the commandline exist:
-  # 1- ROOTDEV is on a LUKS volume, and LUKSDEV is a real block device
-  # 2- ROOTDEV is on a LVM volume, and LUKSDEV is a real block device
-  # 3- ROOTDEV is on a LUKS volume, and LUKSDEV is on a LVM volume
-  # Case (3) will have to wait until we initialize the LVM.
-  # Test if ROOTDEV is "/dev/someting" or just "something" - the first means
-  # ROOTDEV is on a LVM volume (scenario 2); we don't need to rewrite ROOTDEV.
-  # The second means that ROOTDEV is on a LUKS volume (scenario 1).
-  CRYPTDEV=""
+  # Unlock any encrypted partitions necessary to access the
+  # root filesystem, such as encrypted LVM Physical volumes, disk
+  # partitions or mdadm arrays.
+  # Unavailable devices such as LVM Logical Volumes will need to be
+  # deferred until they become available after the vgscan.
+
   if [ -x /sbin/cryptsetup ]; then
-    # If we find a LUKS device now, it is on a real block device: 
-    if /sbin/cryptsetup isLuks ${LUKSDEV} 1>/dev/null 2>/dev/null ; then
-      CRYPTDEV=$(basename $ROOTDEV)
-      echo "Unlocking LUKS crypt volume '${CRYPTDEV}' on device '$LUKSDEV':"
-      /sbin/cryptsetup luksOpen ${LUKSDEV} $CRYPTDEV </dev/systty >/dev/systty 2>&1
-      if [ "$CRYPTDEV" == "$ROOTDEV" ]; then # scenario 1
-        ROOTDEV="/dev/mapper/${CRYPTDEV}"
+
+    # Determine if we have to use a LUKS keyfile:
+    if [ ! -z "$LUKSKEY" ]; then
+      mkdir  /mountkey
+      KEYPART=$(echo $LUKSKEY |cut -f1 -d:)
+      LUKSPATH="/mountkey$(echo $LUKSKEY |cut -f2 -d:)"
+      # Catch possible mount failure:
+      if blkid -t TYPE=vfat $KEYPART 1>/dev/null 2>&1 ; then
+        MOUNTOPTS="-t vfat -o shortname=mixed"
+      else
+        MOUNTOPTS="-t auto"
+      fi
+      mount $MOUNTOPTS $(findfs $KEYPART) /mountkey 2>/dev/null
+      # Check if we can actually use this file:
+      if [ ! -f $LUKSPATH ]; then
+        LUKSKEY=""
+      else
+        echo ">>> Using LUKS key file: '$LUKSKEY'"
+        LUKSKEY="-d $LUKSPATH"
       fi
     fi
+
+    LUKSLIST_DEFERRED=""
+    LUKSLIST=$(echo $LUKSDEV | tr -s ':' ' ')
+    for LUKSDEV in $LUKSLIST ; do
+      if /sbin/cryptsetup isLuks ${LUKSDEV} 1>/dev/null 2>/dev/null ; then
+        if echo $ROOTDEV | grep -q "LABEL=" || echo $ROOTDEV | grep -q "UUID=" ; then
+          CRYPTDEV="luks$(basename $LUKSDEV)"
+        elif [ "x$ROOTDEV" = "x$(basename $ROOTDEV)" ]; then
+          CRYPTDEV="$ROOTDEV"
+        else
+          CRYPTDEV="luks$(basename $LUKSDEV)"
+        fi
+        echo "Unlocking LUKS encrypted device '${LUKSDEV}' as luks mapped device '$CRYPTDEV':"
+        /sbin/cryptsetup ${LUKSKEY} luksOpen ${LUKSDEV} ${CRYPTDEV} </dev/tty0 >/dev/tty0 2>&1
+        if [ "$ROOTDEV" = "$LUKSDEV" -o "$ROOTDEV" = "$CRYPTDEV" ] ; then
+          ROOTDEV="/dev/mapper/$CRYPTDEV"
+        fi
+      else
+        LUKSLIST_DEFERRED="${LUKSLIST_DEFERRED} ${LUKSDEV}"
+      fi
+    done
   fi
 
   # Initialize LVM:
-  if [ -x /sbin/vgscan ]; then
-    /sbin/vgscan --mknodes --ignorelockingfailure
-    sleep 10
+  if [ -x /sbin/vgchange ]; then
     /sbin/vgchange -ay --ignorelockingfailure
   fi
   
-  # Make encrypted root partition available (scenario 3):
-  # We have to handle cases here where the LUKS volume is created on a LV
-  if [ -x /sbin/cryptsetup ]; then
-    if /sbin/cryptsetup isLuks ${LUKSDEV} 1>/dev/null 2>/dev/null ; then
-      # Only act if we could not open the LUKS device before (i.e. is on a LV):
-      if [ "x$CRYPTDEV" == "x" ]; then
-        echo "Unlocking LUKS crypt volume '${ROOTDEV}' on device '$LUKSDEV':"
-        /sbin/cryptsetup luksOpen ${LUKSDEV} $ROOTDEV </dev/systty >/dev/systty 2>&1
-        ROOTDEV="/dev/mapper/${ROOTDEV}"
+  # Unlock any LUKS encrypted devices that were deferred above but have now
+  # become available due to the vgscan (i.e. filesystems on LVM Logical Volumes)
+
+  if [ -x /sbin/cryptsetup -a -n "${LUKSLIST_DEFERRED}" ]; then
+    for LUKSDEV in ${LUKSLIST_DEFERRED} ; do
+      if /sbin/cryptsetup isLuks ${LUKSDEV} 1>/dev/null 2>/dev/null ; then
+        if echo $ROOTDEV | grep -q "LABEL=" || echo $ROOTDEV | grep -q "UUID=" ; then
+          CRYPTDEV="luks$(basename $LUKSDEV)"
+        elif [ "x$ROOTDEV" = "x$(basename $ROOTDEV)" ]; then
+          CRYPTDEV="$ROOTDEV"
+        else
+          CRYPTDEV="luks$(basename $LUKSDEV)"
+        fi
+        echo "Unlocking LUKS encrypted device '${LUKSDEV}' as luks mapped device '$CRYPTDEV':"
+        /sbin/cryptsetup ${LUKSKEY} luksOpen ${LUKSDEV} ${CRYPTDEV} </dev/tty0 >/dev/tty0 2>&1
+        if [ "$ROOTDEV" = "$LUKSDEV" -o "$ROOTDEV" = "$CRYPTDEV" ] ; then
+          ROOTDEV="/dev/mapper/$CRYPTDEV"
+        fi
+      else
+        echo "LUKS device '${LUKSDEV}' unavailable for unlocking!"
       fi
-    fi
+    done
   fi
 
+  # Find root device if a label or UUID was given:
+  if echo $ROOTDEV | grep -q "LABEL=" || \
+     echo $ROOTDEV | grep -q "UUID=" ; then
+    ROOTDEV=$(findfs $ROOTDEV)
+  fi
+
+  # Clean up after LUKS unlock using a keyfile:
+  if grep -q mountkey /proc/mounts 2>/dev/null ; then
+    umount -l /mountkey
+    rmdir /mountkey 2>/dev/null
+  fi
+  
   # Resume state from swap
   if [ "$RESUMEDEV" != "" ]; then
     if ls -l $RESUMEDEV | grep -q "^l" ; then
-      RESUMEDEV=`ls -l $RESUMEDEV | awk '{ print $NF }'`
+      RESUMEDEV=$(ls -l $RESUMEDEV | awk '{ print $NF }')
     fi
     echo "Trying to resume from $RESUMEDEV"
-    RESMAJMIN=`ls -l $RESUMEDEV | tr , : | awk '{ print $5$6 }'`
+    RESMAJMIN=$(ls -l $RESUMEDEV | tr , : | awk '{ print $5$6 }')
     echo $RESMAJMIN > /sys/power/resume
   fi
   
@@ -206,6 +286,7 @@ if [ "$RESCUE" = "" ]; then
     /bin/sh
   fi
 else
+  echo
   echo "RESCUE mode"
   echo
   echo "        You can try to fix or rescue your system now. If you want"
@@ -219,12 +300,13 @@ else
   /bin/sh
 fi
 
-if ps axc | grep -q udevd ; then
-  killall udevd
+if pgrep udevd >/dev/null ; then
+  pkill udevd
 fi
 
 unset ERR
-umount /proc
-umount /sys
+mount -o move /proc /mnt/proc
+mount -o move /sys /mnt/sys
+[ "$DEVTMPFS" = "1" ] && mount -o move /dev /mnt/dev
 echo "${INITRD}:  exiting"
-exec switch_root /mnt /sbin/init $RUNLEVEL
+exec switch_root /mnt $INIT $RUNLEVEL
diff --git a/source/a/shadow/shadow.SlackBuild b/source/a/shadow/shadow.SlackBuild
--- a/source/a/shadow/shadow.SlackBuild
+++ b/source/a/shadow/shadow.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2005-2009  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2005-2010  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,24 +20,40 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-VERSION=4.0.3
-ARCH=${ARCH:-x86_64}
-BUILD=${BUILD:-18}
+VERSION=4.1.4.2
+BUILD=${BUILD:-3}
+
+NUMJOBS=${NUMJOBS:--j6}
+
+# Automatically determine the architecture we're building on:
+if [ -z "$ARCH" ]; then
+  case "$( uname -m )" in
+    i?86) export ARCH=i486 ;;
+    arm*) export ARCH=arm ;;
+    # Unless $ARCH is already set, use uname -m for all other archs:
+       *) export ARCH=$( uname -m ) ;;
+  esac
+fi
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-shadow
 
+if [ "$ARCH" = "i486" ]; then
+  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+elif [ "$ARCH" = "s390" ]; then
+  SLKCFLAGS="-O2"
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-O2 -fPIC"
+else
+  SLKCFLAGS="-O2"
+fi
+
 rm -rf $PKG
 mkdir -p $TMP $PKG
-
-# Explode the package framework:
-cd $PKG
-explodepkg $CWD/_shadow.tar.gz
-
 cd $TMP
 rm -rf shadow-$VERSION
-tar xjvf $CWD/shadow-$VERSION.tar.bz2
+tar xvf $CWD/shadow-$VERSION.tar.?z* || exit 1
 cd shadow-$VERSION
 
 chown -R root:root .
@@ -47,110 +63,91 @@ find . \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \;
 
-zcat $CWD/shadow.shadowconfig.diff.gz | patch -p1 --verbose --backup || exit 1
-zcat $CWD/shadow.newgrp.nopam.gz | patch -p0 --verbose --backup || exit 1
-zcat $CWD/shadow.login.defs.diff.gz | patch -p0 --verbose --backup || exit 1
-zcat $CWD/shadow.newgrp.getlogin.gz | patch -p1 --verbose --backup || exit 1
-zcat $CWD/shadow.gcc34.diff.gz | patch -p1 --verbose --backup || exit 1
-zcat $CWD/shadow.remove.obsolete.options.diff.gz | patch -p1 --verbose --backup --suffix=.orig || exit 1
-if [ "$ARCH" = "x86_64" ]; then
-  zcat $CWD/shadow-4.0.3.x86_64.diff.gz | patch -p1 --verbose --backup --suffix=.orig || exit 1
-fi
-
+CFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/usr \
+  --sysconfdir=/etc \
+  --mandir=/usr/man \
+  --docdir=/usr/doc/shadow-$VERSION \
   --disable-shared \
-  --disable-desrpc \
+  --without-libcrack \
   --build=$ARCH-slackware-linux
 
-make -j6 || exit 1
-cat etc/login.defs.linux > $PKG/etc/login.defs.new
-cat etc/login.access > $PKG/etc/login.access.new
+#  --enable-utmpx   # defaults to 'no'
+
+make $NUMJOBS || make || exit 1
+make install DESTDIR=$PKG || exit 1
+
+# Fix user group = 100:
+zcat $CWD/useradd.gz > $PKG/etc/default/useradd
+
+# /bin/groups is provided by coreutils.
+rm -f $PKG/bin/groups
+find $PKG -name groups.1 -exec rm {} \;
+
+# Install a login.defs with unsurprising defaults:
+rm -f $PKG/etc/login.defs
+zcat $CWD/login.defs.gz > $PKG/etc/login.defs.new
+
+mv $PKG/etc/login.access $PKG/etc/login.access.new
+
+# I don't think this works well enough to recommend it.
+#mv $PKG/etc/limits $PKG/etc/limits.new
+rm -f $PKG/etc/limits
+
+# Add the friendly 'adduser' script:
 cat $CWD/adduser > $PKG/usr/sbin/adduser
+chmod 0755 $PKG/usr/sbin/adduser
 
-# These things aren't needed when using glibc, as it
-# supplies its own shadow functions:
-#cat lib/libshadow.a > $PKG/usr/lib/libshadow.a
-#cp -a lib/pwauth.h $PKG/usr/include/shadow/pwauth.h
-#cp -a lib/shadow_.h $PKG/usr/include/shadow/shadow.h
-#chmod 644 $PKG/usr/include/shadow/*
-#chown root.root $PKG/usr/include/shadow/*
+# Add sulogin to the package:
+cp -a src/sulogin $PKG/sbin
+( cd $PKG/bin ; ln -s ../sbin/sulogin )
 
-cd po
-for file in *.gmo ; do
-  mkdir -p $PKG/usr/share/locale/$(basename $file .gmo)/LC_MESSAGES
-  cat $file > $PKG/usr/share/locale/$(basename $file .gmo)/LC_MESSAGES/shadow.mo
-done
-cd ../src
-cat login > $PKG/bin/login
-cat su > $PKG/bin/su
-cat sulogin > $PKG/sbin/sulogin
-cat ../debian/shadowconfig.sh > $PKG/usr/sbin/shadowconfig
-for file in chpasswd dpasswd faillog groupadd groupdel groupmod grpck \
-lastlog logoutd mkpasswd newusers pwck useradd userdel usermod \
-pwconv pwunconv grpconv grpunconv vipw ; do
-  cat $file > $PKG/usr/sbin/$file
-done
-for file in chage chfn chsh expiry gpasswd newgrp passwd ; do
-  cat $file > $PKG/usr/bin/$file
-done
-cd ..
-cp contrib/adduser.sh /sbin/adduser
+# Add the empty faillog log file:
+mkdir -p $PKG/var/log
+touch $PKG/var/log/faillog.new
+
+# Put some stuff back in "old" locations and make symlinks for compat
+( cd $PKG/usr/bin
+  mv faillog ../sbin
+  mv lastlog ../sbin
+  ln -s ../sbin/faillog
+  ln -s ../sbin/lastlog
+)
+
+# Fixup a few permissions:
+chmod 4711 $PKG/bin/su
+chmod 4711 $PKG/usr/bin/*
+
+# Compress and if needed symlink the man pages:
+if [ -d $PKG/usr/man ]; then
+  ( cd $PKG/usr/man
+    for manpagedir in $(find . -type d -name "man*") ; do
+      ( cd $manpagedir
+        for eachpage in $( find . -type l -maxdepth 1) ; do
+          ln -s $( readlink $eachpage ).gz $eachpage.gz
+          rm $eachpage
+        done
+        gzip -9 *.?
+      )
+    done
+  )
+fi
+
 mkdir -p $PKG/usr/doc/shadow-$VERSION
 cp -a \
-  ABOUT-NLS ChangeLog NEWS README TODO doc/* \
+  COPYING ChangeLog NEWS README TODO doc/{README*,HOWTO,WISHLIST,*.txt} \
   $PKG/usr/doc/shadow-$VERSION
-chmod 644 $PKG/usr/doc/shadow-$VERSION/*
+#chmod 0644 $PKG/usr/doc/shadow-$VERSION/*
 
-install_man_pages() {
-for file in chage.1 chfn.1 chsh.1 gpasswd.1 groups.1 login.1 newgrp.1 \
-passwd.1 su.1 ; do
-  if [ -r $file ]; then
-    mkdir -p $1/man1
-    gzip -9c $file > $1/man1/$file.gz
-  fi
-done
-for file in pw_auth.3 shadow.3 ; do
-  if [ -r $file ]; then
-    mkdir -p $1/man3
-    gzip -9c $file > $1/man3/$file.gz
-  fi
-done
-for file in faillog.5 limits.5 login.access.5 login.defs.5 passwd.5 \
-porttime.5 shadow.5 suauth.5 ; do
-  if [ -r $file ]; then
-    mkdir -p $1/man5
-    gzip -9c $file > $1/man5/$file.gz
-  fi
-done
-for file in chpasswd.8 dpasswd.8 faillog.8 groupadd.8 groupdel.8 groupmod.8 \
-grpck.8 lastlog.8 logoutd.8 mkpasswd.8 newusers.8 pwauth.8 pwck.8 pwconv.8 \
-shadowconfig.8 sulogin.8 useradd.8 userdel.8 usermod.8 vipw.8 ; do
-  if [ -r $file ]; then
-    mkdir -p $1/man8
-    gzip -9c $file > $1/man8/$file.gz
-  fi
-done
-}
-
-cd man
-  install_man_pages $PKG/usr/man
-  for dir in * ; do
-    if [ -d $dir ] ; then
-      ( cd $dir ; install_man_pages $PKG/usr/man/$dir )
-    fi
-  done
-cd ..
+# The entire ChangeLog is excessive for most users:
+cat $PKG/usr/doc/shadow-$VERSION/ChangeLog | head -n 2000 > $PKG/usr/doc/shadow-$VERSION/CL
+mv $PKG/usr/doc/shadow-$VERSION/CL $PKG/usr/doc/shadow-$VERSION/ChangeLog
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
+zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
 
-# Build the package:
 cd $PKG
-makepkg -l y -c n $TMP/shadow-$VERSION-$ARCH-$BUILD.txz
+/sbin/makepkg -l y -c n $TMP/shadow-$VERSION-$ARCH-$BUILD.txz
 
-# Clean up the extra stuff:
-if [ "$1" = "--cleanup" ]; then
-  rm -rf $TMP/shadow-$VERSION
-  rm -rf $PKG
-fi
diff --git a/source/n/wpa_supplicant/wpa_supplicant.SlackBuild b/source/n/wpa_supplicant/wpa_supplicant.SlackBuild
--- a/source/n/wpa_supplicant/wpa_supplicant.SlackBuild
+++ b/source/n/wpa_supplicant/wpa_supplicant.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # Copyright 2004-2008 Eric Hameleers, Eindhoven, NL
-# Copyright 2008-2009  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2008-2010  Patrick J. Volkerding, Sebeka, MN, USA
 #  Permission to use, copy, modify, and distribute this software for
 #  any purpose with or without fee is hereby granted, provided that
 #  the above copyright notice and this permission notice appear in all
@@ -21,10 +21,19 @@
 #  SUCH DAMAGE.
 # -----------------------------------------------------------------------------
 
-PRGNAM=wpa_supplicant
-VERSION=${VERSION:-0.6.9}
-ARCH=${ARCH:-x86_64}
-BUILD=${BUILD:-2}
+PKGNAM=wpa_supplicant
+VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z* | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
+BUILD=${BUILD:-1}
+
+# Automatically determine the architecture we're building on:
+if [ -z "$ARCH" ]; then
+  case "$( uname -m )" in
+    i?86) export ARCH=i486 ;;
+    arm*) export ARCH=arm ;;
+    # Unless $ARCH is already set, use uname -m for all other archs:
+       *) export ARCH=$( uname -m ) ;;
+  esac
+fi
 
 NUMJOBS=${NUMJOBS:-" -j7 "}
 
@@ -45,6 +54,9 @@ elif [ "$ARCH" = "arm" ]; then
 elif [ "$ARCH" = "armel" ]; then
   SLKCFLAGS="-O2 -march=armv4t"
   LIBDIRSUFFIX=""
+else
+  SLKCFLAGS="-O2"
+  LIBDIRSUFFIX=""
 fi
 
 # Support for some of the wireless drivers needs the header files of those
@@ -59,19 +71,19 @@ BROADCOM_INCLUDES=""
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp}
-PKG=$TMP/package-$PRGNAM
+PKG=$TMP/package-$PKGNAM
 rm -rf $PKG
 mkdir -p $TMP $PKG
 
-if ! [ -f $CWD/${PRGNAM}.defconfig ]; then
-  echo "Could not find ${PRGNAM}.defconfig!"
+if ! [ -f $CWD/${PKGNAM}.defconfig ]; then
+  echo "Could not find ${PKGNAM}.defconfig!"
   exit 1
 fi
 
 cd $TMP
-rm -rf ${PRGNAM}-${VERSION}
-tar -xvf $CWD/${PRGNAM}-${VERSION}.tar.bz2 || exit 1
-cd ${PRGNAM}-${VERSION}
+rm -rf ${PKGNAM}-${VERSION}
+tar xvf $CWD/${PKGNAM}-${VERSION}.tar.?z* || exit 1
+cd ${PKGNAM}-${VERSION}
 chown -R root:root .
 find . \
   \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
@@ -87,7 +99,7 @@ find . \
 cd wpa_supplicant
 
 # Create the configuration file for building wpa_supplicant:
-cat $CWD/${PRGNAM}.defconfig > .config
+cat $CWD/${PKGNAM}.defconfig > .config
 if [ ! -z $MADWIFI_INCLUDES -a -d $MADWIFI_INCLUDES ]; then
   echo "Adding madwifi driver (Atheros) support"
   cat <<-EOT >> .config
@@ -162,7 +174,7 @@ done
 # Install a default configuration file:
 mkdir -p $PKG/etc
 cat <<-_EOT_ > $PKG/etc/wpa_supplicant.conf.new
-	# See /usr/doc/${PRGNAM}-${VERSION}/wpa_supplicant.conf.sample
+	# See /usr/doc/${PKGNAM}-${VERSION}/wpa_supplicant.conf.sample
 	# for many more options that you can use in this file.
 	
 	# This line enables the use of wpa_cli which is used by rc.wireless
@@ -219,11 +231,11 @@ config etc/dbus-1/system.d/dbus-wpa_supplicant.conf.new
 EOINS
 
 # Add the documentation:
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a $DOCS $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a $CWD/README.slackware $PKG/usr/doc/${PRGNAM}-${VERSION}/
-chmod -R a-w $PKG/usr/doc/$PRGNAM-$VERSION/*
-chown -R root:root $PKG/usr/doc/$PRGNAM-$VERSION/*
+mkdir -p $PKG/usr/doc/$PKGNAM-$VERSION
+cp -a $DOCS $PKG/usr/doc/$PKGNAM-$VERSION
+cp -a $CWD/README.slackware $PKG/usr/doc/${PKGNAM}-${VERSION}/
+chmod -R a-w $PKG/usr/doc/$PKGNAM-$VERSION/*
+chown -R root:root $PKG/usr/doc/$PKGNAM-$VERSION/*
 
 # This should only be read/write by root:
 chmod 600 $PKG/etc/wpa_supplicant.conf.new
@@ -244,5 +256,5 @@ fi
 
 # Build the package:
 cd $PKG
-/sbin/makepkg -l y -c n $TMP/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}.txz
+/sbin/makepkg -l y -c n $TMP/${PKGNAM}-${VERSION}-${ARCH}-${BUILD}.txz
 
diff --git a/source/xap/pidgin/pidgin.SlackBuild b/source/xap/pidgin/pidgin.SlackBuild
--- a/source/xap/pidgin/pidgin.SlackBuild
+++ b/source/xap/pidgin/pidgin.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2006, 2007, 2008, 2009  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2006, 2007, 2008, 2009, 2010  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -22,12 +22,21 @@
 
 
 PKGNAM=pidgin
-VERSION=${VERSION:-2.5.9}
-PIDGINENC=${PIDGINENC:-3.0}
-ARCH=${ARCH:-x86_64}
+VERSION=${VERSION:-2.7.0}
+PIDGINENC=${PIDGINENC:-3.1}
 BUILD=${BUILD:-1}
 
-NUMJOBS=${NUMJOBS:-" -j7 "}
+# Automatically determine the architecture we're building on:
+if [ -z "$ARCH" ]; then
+  case "$( uname -m )" in
+    i?86) export ARCH=i486 ;;
+    arm*) export ARCH=arm ;;
+    # Unless $ARCH is already set, use uname -m for all other archs:
+       *) export ARCH=$( uname -m ) ;;
+  esac
+fi
+
+NUMJOBS=${NUMJOBS:-" -j6 "}
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp}
@@ -38,18 +47,23 @@ mkdir -p $TMP $PKG
 if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
   LIBDIRSUFFIX=""
+  ARCHQUADLET=""
 elif [ "$ARCH" = "s390" ]; then
   SLKCFLAGS="-O2"
   LIBDIRSUFFIX=""
+  ARCHQUADLET=""
 elif [ "$ARCH" = "x86_64" ]; then
   SLKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
+  ARCHQUADLET=""
 elif [ "$ARCH" = "arm" ]; then
-  SLKCFLAGS="-O2 -march=armv4 -mtune=xscale"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "armel" ]; then
   SLKCFLAGS="-O2 -march=armv4t"
   LIBDIRSUFFIX=""
+  ARCHQUADLET="-gnueabi"
+else
+  SLKCFLAGS="-O2"
+  LIBDIRSUFFIX=""
+  ARCHQUADLET=""
 fi
 
 cd $TMP
@@ -80,15 +94,19 @@ CXXFLAGS="$SLKCFLAGS" \
   --enable-dbus \
   --enable-gnutls=yes \
   --enable-nss=no \
+  --disable-vv \
   --enable-gtkspell \
   --enable-cyrus-sasl \
-  --with-perl-lib=vendor \
+  --enable-perl \
   --disable-meanwhile \
   --disable-avahi \
   --disable-nm \
   --program-prefix= \
   --program-suffix= \
-  --build=$ARCH-slackware-linux
+  --build=$ARCH-slackware-linux$ARCHQUADLET || exit 1
+
+# Fix install location:
+grep -lr -- "lib/perl" . | xargs sed -i 's?lib/perl?lib'"$LIBDIRSUFFIX"'/perl?g'
 
 # Build and install:
 make $NUMJOBS || make || exit 1
@@ -99,11 +117,21 @@ eval $(perl '-V:archlib')
 eval $(perl '-V:privlib')
 VENDORPERL="$(echo $archlib | sed -e "s/perl5/perl5\/vendor_perl/")"
 
-find $PKG -type f -name perllocal.pod -exec mv {} $PKG/$VENDORPERL/Pidgin.pod \;
+mkdir -vpm755 $PKG/$VENDORPERL/
+find $PKG -type f -name perllocal.pod -exec mv -fv {} $PKG/$VENDORPERL/Pidgin.pod \;
+# Fix install location for 64bit:
+sed -i 's?/lib/perl?/lib'"$LIBDIRSUFFIX"'/perl?g' $PKG/$VENDORPERL/Pidgin.pod
 mkdir -p $PKG/usr/man/man3
-find $PKG/usr/share/man -type f -name *.3 -exec mv {} $PKG/usr/man/man3 \;
+find $PKG/usr/share/man -type f -name *.3 -exec mv -fv {} $PKG/usr/man/man3 \;
 rm -rf $PKG/usr/share/man
 rm -r $PKG$privlib
+# This is empty:
+rmdir $PKG/usr/lib$LIBDIRSUFFIX/perl[0-9]*/$ARCH-linux-thread-multi/
+
+# In case of unwanted junk dirs on 64-bit...  this may fail, but doesn't hurt:
+rmdir $PKG/usr/lib/perl[0-9]*/$ARCH-linux-thread-multi/
+rmdir $PKG/usr/lib/perl[0-9]*
+rmdir $PKG/usr/lib
 
 # This removes our DESTDIR from the packlist filenames, to keep perl's
 # internal inventories consistent and correct.
@@ -142,7 +170,11 @@ done
   --with-nspr-libs=/usr/lib${LIBDIRSUFFIX}/seamonkey/ \
   --program-prefix="" \
   --program-suffix="" \
-  --build=$ARCH-slackware-linux
+  --build=$ARCH-slackware-linux$ARCHQUADLET || exit 1
+
+  # Fix install location:
+  grep -lr -- "lib/perl" . | xargs sed -i 's?lib/perl?lib'"$LIBDIRSUFFIX"'/perl?g'
+
   make $NUMJOBS || make || exit 1
   make install DESTDIR=$PKG || exit 1
 ) || exit 1
