Wed Jan  9 22:44:36 UTC 2019
a/kernel-generic-4.19.14-x86_64-1.txz:  Upgraded.
a/kernel-huge-4.19.14-x86_64-1.txz:  Upgraded.
a/kernel-modules-4.19.14-x86_64-1.txz:  Upgraded.
a/sysvinit-2.93-x86_64-2.txz:  Rebuilt.
  Patched to fix version number display.
a/util-linux-2.33.1-x86_64-1.txz:  Upgraded.
d/kernel-headers-4.19.14-x86-1.txz:  Upgraded.
k/kernel-source-4.19.14-noarch-1.txz:  Upgraded.
l/alsa-plugins-1.1.8-x86_64-2.txz:  Rebuilt.
  Remove symlink that breaks audio output.
extra/pure-alsa-system/alsa-plugins-1.1.8-x86_64-2_alsa.txz:  Rebuilt.
  Remove symlink that breaks audio output.
isolinux/initrd.img:  Rebuilt.
kernels/*:  Upgraded.
usb-and-pxe-installers/usbboot.img:  Rebuilt.

diff --git a/source/a/sysvinit/sysvinit.SlackBuild b/source/a/sysvinit/sysvinit.SlackBuild
--- a/source/a/sysvinit/sysvinit.SlackBuild
+++ b/source/a/sysvinit/sysvinit.SlackBuild
@@ -24,7 +24,7 @@ cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=sysvinit
 VERSION=${VERSION:-2.93}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -64,6 +64,9 @@ find . \
 
 # Fix paths for /etc/forcefsck and /etc/fastboot:
 zcat $CWD/sysvinit.paths.diff.gz | patch -p1 -E --verbose --backup --suffix=.orig || exit 1
+
+# Fix failure to show program version:
+zcat $CWD/sysvinit.version.2.93.diff.gz | patch -p1 --verbose || exit 1
 
 # Use /dev/initctl instead of /run/initctl ; this is a named pipe and probably
 # should be in /dev anyway, but more importantly, having the upgraded package
