Slackware 14.1
Mon Nov  4 17:08:47 UTC 2013
Slackware 14.1 x86_64 stable is released!

It's been another interesting release cycle here at Slackware bringing
new features like support for UEFI machines, updated compilers and
development tools, the switch from MySQL to MariaDB, and many more
improvements throughout the system.  Thanks to the team, the upstream
developers, the dedicated Slackware community, and everyone else who
pitched in to help make this release a reality.

The ISOs are off to be replicated, a 6 CD-ROM 32-bit set and a
dual-sided
32-bit/64-bit x86/x86_64 DVD.  Please consider supporting the Slackware
project by picking up a copy from store.slackware.com.  We're taking
pre-orders now, and offer a discount if you sign up for a subscription.

Have fun!  :-)

diff --git a/source/a/udev/rule_generator.diff b/source/a/udev/rule_generator.diff
--- a/source/a/udev/rule_generator.diff
+++ b/source/a/udev/rule_generator.diff
@@ -1,17 +1,62 @@
-diff -Nur udev-182.orig/src/rule_generator/write_cd_rules udev-182/src/rule_generator/write_cd_rules
---- udev-182.orig/src/rule_generator/write_cd_rules	2012-03-24 22:47:53.138527732 -0500
-+++ udev-182/src/rule_generator/write_cd_rules	2012-03-24 22:59:42.595889830 -0500
+--- ./src/rule_generator/write_cd_rules.orig	2012-01-28 18:15:46.958827013 -0600
++++ ./src/rule_generator/write_cd_rules	2013-01-17 22:58:27.294859303 -0600
 @@ -3,7 +3,8 @@
  # This script is run if an optical drive lacks a rule for persistent naming.
  #
  # It adds symlinks for optical drives based on the device class determined
 -# by cdrom_id and used ID_PATH to identify the device.
-+# by cdrom_id and uses ID_PATH or ID_SERIAL or ID_MODEL and ID_REVISION to
++# by cdrom_id and uses ID_SERIAL or ID_MODEL and ID_REVISION to
 +# identify the device.
  
  # (C) 2006 Marco d'Itri <md@Linux.IT>
  #
-@@ -105,18 +106,57 @@
+@@ -66,37 +67,16 @@
+         exit 1
+ fi
+ 
+-if [ "$1" ]; then
+-        METHOD="$1"
++# ID_PATH is gone from the ata subsystem used in recent kernels, so
++# always use the by-id method:
++if [ "$ID_SERIAL" ]; then
++        RULE="ENV{ID_SERIAL}==\"$ID_SERIAL\""
++elif [ "$ID_MODEL" -a "$ID_REVISION" ]; then
++        RULE="ENV{ID_MODEL}==\"$ID_MODEL\", ENV{ID_REVISION}==\"$ID_REVISION\""
+ else
+-        METHOD='by-path'
+-fi
+-
+-case "$METHOD" in
+-        by-path)
+-        if [ -z "$ID_PATH" ]; then
+-                echo "$DEVPATH not supported by path_id. by-id may work." >&2
+-                exit 1
+-        fi
+-        RULE="ENV{ID_PATH}==\"$ID_PATH\""
+-        ;;
+-
+-        by-id)
+-        if [ "$ID_SERIAL" ]; then
+-                RULE="ENV{ID_SERIAL}==\"$ID_SERIAL\""
+-        elif [ "$ID_MODEL" -a "$ID_REVISION" ]; then
+-                RULE="ENV{ID_MODEL}==\"$ID_MODEL\", ENV{ID_REVISION}==\"$ID_REVISION\""
+-        else
+-                echo "$DEVPATH not supported by ata_id. by-path may work." >&2
+-                exit 1
+-        fi
+-        ;;
+-
+-        *)
+-        echo "Invalid argument (must be either by-path or by-id)." >&2
++        echo "$DEVPATH not supported by ata_id.  Unable to generate persistent rules." >&2
+         exit 1
+-        ;;
+-esac
++fi
+ 
+ # Prevent concurrent processes from modifying the file at the same time.
+ lock_rules_file
+@@ -105,18 +85,62 @@
  choose_rules_file
  
  link_num=$(find_next_available 'cdrom[0-9]*')
@@ -19,8 +64,9 @@ diff -Nur udev-182.orig/src/rule_generator/write_cd_rules udev-182/src/rule_gene
  
  match="SUBSYSTEM==\"block\", ENV{ID_CDROM}==\"?*\", $RULE"
  
- comment="$ID_MODEL ($ID_PATH)"
+-comment="$ID_MODEL ($ID_PATH)"
 -
++comment="$ID_MODEL ($ID_SERIAL)"
          write_rule "$match" "cdrom$link_num" "$comment"
 -[ "$ID_CDROM_CD_R" -o "$ID_CDROM_CD_RW" ] && \
 -        write_rule "$match" "cdrw$link_num"
@@ -28,47 +74,52 @@ diff -Nur udev-182.orig/src/rule_generator/write_cd_rules udev-182/src/rule_gene
 -        write_rule "$match" "dvd$link_num"
 -[ "$ID_CDROM_DVD_R" -o "$ID_CDROM_DVD_RW" -o "$ID_CDROM_DVD_RAM" ] && \
 -        write_rule "$match" "dvdrw$link_num"
-+        if [ "$(find_all_rules 'SYMLINK+=' cdrom)" = "" ]; then
++        if [ "$link_num" = "0" ]; then
 +                write_rule "$match" "cdrom"
 +        fi
 +
 +        if [ "$ID_CDROM_CD_R" ]; then
-+                       write_rule "$match" "cdr$link_num"
-+                if [ "$(find_all_rules 'SYMLINK+=' cdr)" = "" ]; then
++                write_rule "$match" "cdr$link_num"
++                if [ "$link_num" = "0" ]; then
 +                        write_rule "$match" "cdr"
 +                fi
 +
 +                write_rule "$match" "cdwriter$link_num"
-+                if [ "$(find_all_rules 'SYMLINK+=' cdwriter)" = "" ]; then
++                if [ "$link_num" = "0" ]; then
 +                        write_rule "$match" "cdwriter"
 +                fi
 +
 +                if [ "$ID_CDROM_CD_RW" ]; then
 +                        write_rule "$match" "cdrw$link_num"
-+                        if [ "$(find_all_rules 'SYMLINK+=' cdrw)" = "" ]; then
++                        if [ "$link_num" = "0" ]; then
 +                                write_rule "$match" "cdrw"
 +                        fi
 +                fi
 +
-+                if [ "$(find_all_rules 'SYMLINK+=' writer)" = "" ]; then
++                if [ "$link_num" = "0" ]; then
 +                        write_rule "$match" "writer"
 +                fi
 +        fi
 +
 +        if [  "$ID_CDROM_DVD" ]; then
 +                write_rule "$match" "dvd$link_num"
-+                if [ "$(find_all_rules 'SYMLINK+=' dvd)" = "" ]; then
++                if [ "$link_num" = "0" ]; then
 +                        write_rule "$match" "dvd"
 +                fi
 +
 +                if [ "$ID_CDROM_DVD_R" -o "$ID_CDROM_DVD_RW" -o "$ID_CDROM_DVD_RAM" ]; then
++                        write_rule "$match" "dvdr$link_num"
++                        if [ "$link_num" = "0" ]; then
++                                write_rule "$match" "dvdr"
++                        fi
++
 +                        write_rule "$match" "dvdrw$link_num"
-+                        if [ "$(find_all_rules 'SYMLINK+=' dvdrw)" = "" ]; then
++                        if [ "$link_num" = "0" ]; then
 +                                write_rule "$match" "dvdrw"
 +                        fi
 +
 +                        write_rule "$match" "dvdwriter$link_num"
-+                        if [ "$(find_all_rules 'SYMLINK+=' dvdwriter)" = "" ]; then
++                        if [ "$link_num" = "0" ]; then
 +                                write_rule "$match" "dvdwriter"
 +                        fi
 +                fi
diff --git a/source/ap/pm-utils/pm-utils.SlackBuild b/source/ap/pm-utils/pm-utils.SlackBuild
--- a/source/ap/pm-utils/pm-utils.SlackBuild
+++ b/source/ap/pm-utils/pm-utils.SlackBuild
@@ -3,7 +3,7 @@
 # Slackware build script for pm-utils
 
 # Copyright 2008, 2009, 2010  Robby Workman, Northport, Alabama, USA 
-# Copyright 2008, 2009, 2010  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2008, 2009, 2010, 2013  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -25,7 +25,7 @@
 
 PKGNAM=pm-utils
 VERSION=$(echo ${PKGNAM}-*.tar.?z* | rev | cut -f 3- -d . | cut -f 1 -d - | rev)
-BUILD=${BUILD:-2}
+BUILD=${BUILD:-5}
 
 QUIRKS=20100619	# Version of the quirks database
 
@@ -72,8 +72,18 @@ find . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
 
-zcat $CWD/use_more_sane_harddrive_defaults.patch.gz | patch -p1 || exit 1
-zcat $CWD/fix-wrong-path-in-intel-audio-powersave.patch.gz | patch -p1 || exit 1
+zcat $CWD/patches/use_more_sane_harddrive_defaults.patch.gz | patch -p1 || exit 1
+zcat $CWD/patches/fix-wrong-path-in-intel-audio-powersave.patch.gz | patch -p1 || exit 1
+
+# Thanks to Fedora for these:
+# Use append instead of write for init_logfile
+zcat $CWD/patches/init-logfile-append.patch.gz | patch -p1 || exit 1
+# Fix hooks exit code logging
+zcat $CWD/patches/hook-exit-code-log.patch.gz | patch -p1 || exit 1
+# Fix line spacing in logs to be easier to read
+zcat $CWD/patches/log-line-spacing-fix.patch.gz | patch -p1 || exit 1
+# Add support for in-kernel (from kernel 3.6) suspend to both
+zcat $CWD/patches/add-in-kernel-suspend-to-both.patch.gz | patch -p1 || exit 1
 
 CFLAGS="$SLKCFLAGS" \
 ./configure \
@@ -101,26 +111,29 @@ chown -R root:root $PKG/$PM_UTILS_LIBDIR/video-quirks
   chmod 0755 49bluetooth-generic
 )
 
-# Remove the NetworkManager hook since we don't ship it; 
-# it should be included with NetworkManager
-rm -f $PKG/usr/lib64/pm-utils/sleep.d/55NetworkManager
+# Remove the NetworkManager hook - recent NM listens to upower events
+# directly to know when the system is suspending/waking
+rm -f $PKG/usr/lib${LIBDIRSUFFIX}/pm-utils/sleep.d/55NetworkManager
+
+# Remove hooks which have shown to not reduce, or even increase power
+# usage (thanks to Debian for this, and to Marin Glibic for the referral)
+rm -f $PKG/usr/lib${LIBDIRSUFFIX}/pm-utils/power.d/journal-commit
+rm -f $PKG/usr/lib${LIBDIRSUFFIX}/pm-utils/power.d/readahead
+
+# HAL is gone, so this should be too:
+rm -f $PKG/usr/lib${LIBDIRSUFFIX}/pm-utils/power.d/hal-cd-polling
+
+# Actually, it is a bad thing(tm) for pm-utils to go messing around with all
+# of the user's settings with the hooks in the power.d directory.  Anything
+# that wasn't already taken out back behind the shed should be disabled by
+# default:
+chmod 644 $PKG/usr/lib${LIBDIRSUFFIX}/pm-utils/power.d/*
 
 find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 
-if [ -d $PKG/usr/man ]; then
-  ( cd $PKG/usr/man
-    for manpagedir in $(find . -type d -name "man*") ; do
-      ( cd $manpagedir
-        for eachpage in $( find . -type l -maxdepth 1) ; do
-          ln -s $( readlink $eachpage ).gz $eachpage.gz
-          rm $eachpage
-        done
-        gzip -9 *.*
-      )
-    done
-  )
-fi
+find $PKG/usr/man -type f -exec gzip -9 {} \;
+for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
 
 mkdir -p $PKG/usr/doc/$PKGNAM-$VERSION
 cp -a \
diff --git a/source/x/fontconfig/fontconfig.SlackBuild b/source/x/fontconfig/fontconfig.SlackBuild
--- a/source/x/fontconfig/fontconfig.SlackBuild
+++ b/source/x/fontconfig/fontconfig.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2008, 2009, 2010  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2008, 2009, 2010, 2013  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -86,6 +86,10 @@ CFLAGS=$SLKCFLAGS \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --mandir=/usr/man \
   --sysconfdir=/etc \
+  --with-templatedir=/etc/fonts/conf.avail \
+  --with-baseconfigdir=/etc/fonts \
+  --with-configdir=/etc/fonts/conf.d \
+  --with-xmldir=/etc/fonts \
   --localstatedir=/var \
   --enable-static=no \
   --build=$ARCH-slackware-linux
@@ -93,6 +97,15 @@ CFLAGS=$SLKCFLAGS \
 # Uses a currently non-functional sgml tool, thus '-i':
 make $NUMJOBS || make || exit 1
 make install DESTDIR=$PKG || exit 1
+
+# Upstream has changed the default templatedir to /usr/share/fontconfig/conf.avail.
+# This change, if accepted, would break any existing font package containing a
+# conf.avail directory.  The safest thing to do is to keep things in the
+# traditional location, but put a link in the new place so that font packages
+# following the new standard location will work.  Let's hear it for being
+# "more correct" at the expense of having things "just work"!
+mkdir -p $PKG/usr/share/fontconfig
+( cd $PKG/usr/share/fontconfig ; ln -sf /etc/fonts/conf.avail . )
 
 mkdir -p $PKG/usr/doc/fontconfig-$VERSION
 cp -a \
@@ -120,7 +133,6 @@ find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
 # Set up the default options in /etc/fonts/conf.d:
 (  cd $PKG/etc/fonts/conf.d
    for fontconf in \
-        20-fix-globaladvance.conf \
         20-unhint-small-vera.conf \
         30-urw-aliases.conf \
         30-metric-aliases.conf \
@@ -135,7 +147,12 @@ find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
         69-unifont.conf \
         80-delicious.conf \
         90-synthetic.conf ; do
-     ln -sf ../conf.avail/$fontconf . || exit 1
+     if [ -r ../conf.avail/$fontconf ]; then
+       ln -sf ../conf.avail/$fontconf .
+     else
+       echo "ERROR:  unable to symlink ../conf.avail/$fontconf, file does not exist."
+       exit 1
+     fi
    done
    if [ ! $? = 0 ]; then
      exit 1
@@ -166,5 +183,5 @@ cat $CWD/slack-desc > $PKG/install/slack-desc
 zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
 
 cd $PKG
-/sbin/makepkg -l y -c n $TMP/fontconfig-$VERSION-$ARCH-$BUILD.txz
+/sbin/makepkg -l y -c n --prepend $TMP/fontconfig-$VERSION-$ARCH-$BUILD.txz
 
diff --git a/source/xap/mozilla-firefox/mozilla-firefox.SlackBuild b/source/xap/mozilla-firefox/mozilla-firefox.SlackBuild
--- a/source/xap/mozilla-firefox/mozilla-firefox.SlackBuild
+++ b/source/xap/mozilla-firefox/mozilla-firefox.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2008, 2009, 2010, 2011, 2012  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2008, 2009, 2010, 2011, 2012, 2013  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -25,22 +25,20 @@
 
 VERSION=$(basename $(ls firefox-*.tar.bz2 | cut -d - -f 2 | rev | cut -f 3- -d . | rev) .source)
 RELEASEVER=$(echo $VERSION | cut -f 1 -d r | cut -f 1 -d b)
+# With esr releases we need to fix this
+if [ "${RELEASEVER}r" = "$VERSION" ]; then
+  RELEASEVER=$(echo $RELEASEVER | cut -f 1 -d e)
+  RELEASEVERMAJ=$(echo $RELEASEVER | cut -f 1 -d .)
+fi  
 BUILD=${BUILD:-1}
 
-CWD=$(pwd)
-TMP=${TMP:-/tmp}
-PKG=$TMP/package-mozilla-firefox
-
-# Figure out if this is a beta, or a release:
-if echo $VERSION | grep -q b ; then # we think it is a beta
-  if bzgrep -q mozilla-beta/ $CWD/firefox-$VERSION.source.tar.bz2 ; then
-    MOZVERS=${MOZVERS:-beta}
-  else # blindly assume it is a release
-    MOZVERS=${MOZVERS:-release}
-  fi
-else # release, no "b" in the tarball version:
-  MOZVERS=${MOZVERS:-release}
-fi
+# Specify this variable for a localized build.
+# For example, to build a version of Firefox with Italian support, run
+# the build script like this:
+#
+# MOZLOCALIZE=it ./mozilla-firefox.SlackBuild
+#
+MOZLOCALIZE=${MOZLOCALIZE:-}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -51,6 +49,33 @@ if [ -z "$ARCH" ]; then
        *) export ARCH=$( uname -m ) ;;
   esac
 fi
+
+# Use PGO?  Doubles the time and drive space requirements for the build,
+# but should provide a performance increase.  How much depends on which
+# benchmarks you believe, but I've typically seen around 2.5%.  I've also
+# seen some which say it can be negligably (a fraction of a percent) slower
+# with this enganged.  The anecdotal reports usually say there's a noticable
+# improvement in overall responsiveness.  Seems like a good bet if you have
+# the time and your system is able to handle it.  Set the variable to
+# anything else prior to the build to compile Firefox in less time (but
+# without the possible benefits of Profile-Guided Optimization).
+#
+# NOTE:  The 23.0 release fails to compile with a GLib assert error if PGO
+# is enabled, so it is being disabled by default.  I can't say I ever noticed
+# a lot of difference with this anyway (other than a much, much longer compile
+# time.  But pass PGO=yes to the SlackBuild if you want to try it.
+#if [ "$ARCH" = "x86_64" ]; then
+#  PGO=${PGO:-yes}
+#else
+#  # 32-bit systems have problems compiling with PGO, as the per-process
+#  # memory requirements are too large.  Possibly compiling with a 64-bit
+#  # kernel could be a workaround for this, but for now we will default to
+#  # using PGO only for x86_64.
+#  PGO=${PGO:-no}
+#fi
+#
+# PGO is disabled by default:
+PGO=${PGO:-no}
 
 # Try to be gentle to the compiler, no optimizations:
 if [ "$ARCH" = "i486" ]; then
@@ -70,6 +95,23 @@ elif [ "$ARCH" = "armel" ]; then
   LIBDIRSUFFIX=""
 fi
 
+CWD=$(pwd)
+TMP=${TMP:-/tmp}
+PKG=$TMP/package-mozilla-firefox
+
+# If not specified, figure out if this is a beta, an esr
+# or a release (we start assuming this last):
+MOZVERS=${MOZVERS:-release}
+if echo $VERSION | grep -q b ; then # we think it is a beta
+  if bzgrep -q ^mozilla-beta/ $CWD/firefox-$VERSION.source.tar.bz2 ; then
+    MOZVERS=beta
+  fi
+elif echo $VERSION | grep -q esr ; then # we think it is an esr
+  if bzgrep -q ^mozilla-esr$RELEASEVERMAJ/ $CWD/firefox-$VERSION.source.tar.bz2 ; then
+    MOZVERS=esr$RELEASEVERMAJ
+  fi
+fi
+
 NUMJOBS=${NUMJOBS:-" -j7 "}
 
 rm -rf $PKG
@@ -79,6 +121,16 @@ cd $TMP
 rm -rf mozilla-$MOZVERS
 tar xvf $CWD/firefox-$VERSION.source.tar.bz2 || exit 1
 cd mozilla-$MOZVERS || exit 1
+
+# Fetch localization, if requested:
+if [ ! -z $MOZLOCALIZE ]; then
+  LOC_TAG="FIREFOX_$( echo $VERSION | tr \. _ )_RELEASE"
+  rm -f $LOC_TAG.tar.bz2
+  if echo $MOZVERS | grep -q esr ; then LOC_VERS=release ; else LOC_VERS=$MOZVERS ; fi
+  wget https://hg.mozilla.org/releases/l10n/mozilla-$LOC_VERS/$MOZLOCALIZE/archive/$LOC_TAG.tar.bz2
+  tar xvf $LOC_TAG.tar.bz2
+  mv $MOZLOCALIZE-$LOC_TAG $MOZLOCALIZE
+fi
 
 # Fix a long standing bug that's prevented staying current on GTK+.
 # Thanks to the BLFS folks.  :-)
@@ -111,18 +163,8 @@ if gcc --version | grep -q "gcc (GCC) 4.7.0" ; then
  sed -i 's# ""##' browser/base/Makefile.in
 fi
 
-# Mozilla devs enforce using an objdir for building
-# and launching configure with the absolute path
-# https://developer.mozilla.org/en/Configuring_Build_Options#Building_with_an_objdir
-mkdir obj
-cd obj
-export MOZILLA_OFFICIAL="1" &&
-export BUILD_OFFICIAL="1" &&
-export MOZ_PHOENIX="1" &&
-export CFLAGS="$SLKCFLAGS" &&
-export CXXFLAGS="$SLKCFLAGS" &&
-export MOZ_MAKE_FLAGS="$NUMJOBS" &&
-$TMP/mozilla-$MOZVERS/configure \
+# Our building options, in a configure-like display ;)
+OPTIONS="\
   --enable-official-branding \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
@@ -143,29 +185,75 @@ $TMP/mozilla-$MOZVERS/configure \
   --enable-strip \
   --enable-cpp-rtti \
   --enable-single-profile \
+  --disable-gnomevfs \
   --disable-ldap \
   --disable-accessibility \
   --disable-crashreporter \
   --disable-debug \
-  --disable-tests \
   --disable-pedantic \
   --disable-installer \
   --disable-mailnews \
   --disable-composer \
-  --disable-profilesharing
-  # Complains about missing APNG support in Slackware's libpng:
-  #--with-system-png \
-
+  --disable-profilesharing"
+# Complains about missing APNG support in Slackware's libpng:
+# --with-system-png \
 # This option breaks mozilla-12.0:
 # --enable-system-cairo \
-#
+if [ ! -z $MOZLOCALIZE ]; then
+  OPTIONS=$OPTIONS" \
+  --enable-ui-locale=$MOZLOCALIZE
+  --with-l10n-base=.."
+  # There's no dictionaries in localized builds
+  sed -i "/@BINPATH@\/dictionaries\/\*/d" browser/installer/package-manifest.in || exit 1
+fi
 
-#make -f client.mk build MOZ_MAKE_FLAGS="$NUMJOBS" || exit 1
-make MOZ_MAKE_FLAGS="$NUMJOBS" $NUMJOBS || exit 1
-make install DESTDIR=$PKG || exit 1
+export MOZILLA_OFFICIAL="1"
+export BUILD_OFFICIAL="1"
+export MOZ_PHOENIX="1"
+export MOZ_PACKAGE_JSSHELL="1"
+export CFLAGS="$SLKCFLAGS"
+export CXXFLAGS="$SLKCFLAGS"
+export MOZ_MAKE_FLAGS="$NUMJOBS"
 
-# Exit obj directory:
-cd ..
+# Clear some variables that could break the build
+unset DBUS_SESSION_BUS_ADDRESS ORBIT_SOCKETDIR SESSION_MANAGER \
+  XDG_SESSION_COOKIE XAUTHORITY MAKEFLAGS
+
+# Assemble our .mozconfig, we use this method for building, seems
+# needed for PGO.
+echo ". \$topsrcdir/browser/config/mozconfig" > .mozconfig
+
+# Mozilla devs enforce using an objdir for building
+# https://developer.mozilla.org/en/Configuring_Build_Options#Building_with_an_objdir
+mkdir obj
+echo "mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj" >> .mozconfig
+
+if [ "$MOZLOCALIZE" ]; then
+  echo "mk_add_options MOZ_CO_LOCALES=\"$MOZLOCALIZE\"" >> .mozconfig
+fi
+
+# Write in it the options above
+for option in $OPTIONS; do echo "ac_add_options $option" >> .mozconfig; done
+
+# https://developer.mozilla.org/en-US/docs/Building_with_Profile-Guided_Optimization
+# Thanks to ArchLinux and Gentoo for the additional hints.
+if [ "$PGO" = "yes" ]; then
+  # Do a PGO build, double time and disk space but worth it.
+  export MOZ_PGO=1
+  echo "mk_add_options PROFILE_GEN_SCRIPT='EXTRA_TEST_ARGS=10 \$(MAKE) -C \$(MOZ_OBJDIR) pgo-profile-run'" >> .mozconfig
+  export DISPLAY=:99
+  # Launch Xvfb to let the profile scripts run in a X session.
+  # Ugly note: if the build breaks you may want to do a "killall Xvfb".
+  Xvfb -nolisten tcp -extension GLX -screen 0 1280x1024x24 $DISPLAY &
+  dbus-launch --exit-with-session make -f client.mk build || exit 1
+  kill $! || true
+else
+  # Do a normal build
+  echo "ac_add_options --disable-tests" >> .mozconfig
+  make -f client.mk build || exit 1
+fi
+
+make -f client.mk install DESTDIR=$PKG || exit 1
 
 # We don't need these (just symlinks anyway):
 rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/firefox-devel-$RELEASEVER
@@ -190,8 +278,6 @@ rm -rf $PKG/usr/include
 mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/mozilla/plugins
 mkdir -p $PKG/usr/share/applications
 cat $CWD/mozilla-firefox.desktop > $PKG/usr/share/applications/mozilla-firefox.desktop
-mkdir -p $PKG/usr/share/pixmaps
-cat $CWD/firefox.png > $PKG/usr/share/pixmaps/firefox.png
 
 # These files/directories are usually created if Firefox is run as root,
 # which on many systems might (and possibly should) be never.  Therefore, if we
@@ -208,14 +294,17 @@ cat $CWD/firefox.png > $PKG/usr/share/pixmaps/firefox.png
 )
 
 # Need some default icons in the right place:
-mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/firefox-$RELEASEVER/chrome/icons/default
-install -m 644 other-licenses/branding/firefox/default16.png \
-  $PKG/usr/lib${LIBDIRSUFFIX}/firefox-$RELEASEVER/icons/
-install -m 644 other-licenses/branding/firefox/default16.png \
-  $PKG/usr/lib${LIBDIRSUFFIX}/firefox-$RELEASEVER/chrome/icons/default/ 
-( cd $PKG/usr/lib${LIBDIRSUFFIX}/firefox-$RELEASEVER
-  install -m 644 icons/{default,mozicon50}.xpm chrome/icons/default/
-)
+for i in 16 22 24 32 48 256; do
+  install -m 0644 -D browser/branding/official/default${i}.png \
+    $PKG/usr/share/icons/hicolor/${i}x${i}/apps/firefox.png
+done
+mkdir -p $PKG/usr/share/pixmaps
+( cd $PKG/usr/share/pixmaps ; ln -sf /usr/share/icons/hicolor/256x256/apps/firefox.png . )
+mkdir -p $PKG/usr/lib$LIBDIRSUFFIX/firefox-$RELEASEVER/chrome/icons/default
+install -m 644 browser/branding/official/default16.png \
+  $PKG/usr/lib$LIBDIRSUFFIX/firefox-$RELEASEVER/icons/
+install -m 644 browser/branding/official/default16.png \
+  $PKG/usr/lib$LIBDIRSUFFIX/firefox-$RELEASEVER/chrome/icons/default/
 
 # Copy over the LICENSE
 install -p -c -m 644 LICENSE $PKG/usr/lib${LIBDIRSUFFIX}/firefox-$RELEASEVER/
@@ -224,5 +313,9 @@ mkdir $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
-/sbin/makepkg -l y -c n $TMP/mozilla-firefox-$VERSION-$ARCH-$BUILD.txz
+if [ -z $MOZLOCALIZE ]; then
+  /sbin/makepkg -l y -c n $TMP/mozilla-firefox-$VERSION-$ARCH-$BUILD.txz
+else
+  /sbin/makepkg -l y -c n $TMP/mozilla-firefox-$VERSION-$ARCH-${BUILD}_$MOZLOCALIZE.txz
+fi
 
