Slackware 14.2
Thu Jun 30 20:26:57 UTC 2016
Slackware 14.2 x86_64 stable is released!

The long development cycle (the Linux community has lately been living in
"interesting times", as they say) is finally behind us, and we're proud to
announce the release of Slackware 14.2.  The new release brings many updates
and modern tools, has switched from udev to eudev (no systemd), and adds
well over a hundred new packages to the system.  Thanks to the team, the
upstream developers, the dedicated Slackware community, and everyone else
who pitched in to help make this release a reality.

The ISOs are off to be replicated, a 6 CD-ROM 32-bit set and a dual-sided
32-bit/64-bit x86/x86_64 DVD.  Please consider supporting the Slackware
project by picking up a copy from store.slackware.com.  We're taking
pre-orders now, and offer a discount if you sign up for a subscription.

Have fun!  :-)

diff --git a/extra/source/tigervnc/tigervnc.SlackBuild b/extra/source/tigervnc/tigervnc.SlackBuild
--- a/extra/source/tigervnc/tigervnc.SlackBuild
+++ b/extra/source/tigervnc/tigervnc.SlackBuild
@@ -1,5 +1,7 @@
-#!/bin/sh
-# Copyright 2010, 2011, 2012, 2013  Eric Hameleers, Eindhoven. NL
+#!/bin/bash
+# $Id: tigervnc.SlackBuild,v 1.25 2015/08/26 18:24:43 root Exp root $
+# Copyright 2010, 2011, 2012, 2013, 2014, 2015  Eric Hameleers, Eindhoven. NL
+# Copyright 2015  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 #   Permission to use, copy, modify, and distribute this software for
@@ -20,16 +22,65 @@
 #   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 #   SUCH DAMAGE.
 # -----------------------------------------------------------------------------
-
+#
+# Slackware SlackBuild script 
+# ===========================
+# By:         Eric Hameleers <alien@slackware.com>
+# For:        tigervnc
+# Descr:      VNC server and client
+# URL:        http://tigervnc.org/
+# Needs:      
+# BuildNeeds: jdk (only when building the java applet)
+# Changelog:  
+# r4126-1:    31/Aug/2010 by Eric Hameleers <alien@slackware.com>
+#             * Initial build.
+# r4126-2:    02/sep/2010 by Eric Hameleers <alien@slackware.com>
+#             * Fix a syntax error in thye doinst.sh script
+# 1.0.90-1:   14/may/2011 by Eric Hameleers <alien@slackware.com>
+#             * Update to 1.1.beta1
+# 1.1.0-1:    14/nov/2011 by Eric Hameleers <alien@slackware.com>
+#             * Update to 1.1.0
+# 1.2.0-1:    23/jun/2012 by Eric Hameleers <alien@slackware.com>
+#             * Update.
+# 1.1.0-2:    28/jul/2012 by Eric Hameleers <alien@slackware.com>
+#             * Build 1.1.0 again, using a revised script which can be used
+#               on Slackware 14 as well.  Also, enable compositing in the
+#               server.  Abandon the tigervnc-1.2 branch for now, because
+#               the fltk based viewer rewrite is not yet fully functional.
+# 1.1.0-3:    22/may/2013 by Eric Hameleers <alien@slackware.com>
+#             * Build 1.1.0 again, on slackware-current (nee 14.1) with new
+#               X.Org 1.13 patches.
+# 1.1.0-4:    11/oct/2013 by Eric Hameleers <alien@slackware.com>
+#             * Build 1.1.0 again, on slackware-current (nee 14.1) with new
+#               X.Org 1.14 patches.
+# 1.3.0-1:    12/dec/2013 by Eric Hameleers <alien@slackware.com>
+#             * Update.  All my issues except copy/paste from local to remote
+#               seem to have been addressed in 1.3.0.
+#               Build against private versions of libjpeg-turbo and fltk,
+#               in order to eliminate external dependencies.
+# 1.4.3-1:    11/apr/2015 by Eric Hameleers <alien@slackware.com>
+#             * Update.
+# 1.4.3-2:    03/may/2015 by Eric Hameleers <alien@slackware.com>
+#             * Rebuild for slackware-current (fix libgcrypt.so library error)
+# 1.5.0-1:    14/jul/2015 by Eric Hameleers <alien@slackware.com>
+#             * Update.
+# 1.5.0-2:    24/aug/2015 by Eric Hameleers <alien@slackware.com>
+#             * Rebuild was needed on slackware-current.
+# 1.5.0-3:    26/aug/2015 by Eric Hameleers <alien@slackware.com>
+#             * I uploaded the wrong package so I needed to update the BUILD.
+# 1.5.0-1:    07/nov/2015 by Patrick Volkerding <volkerdi@slackware.com>
+#             * Removed bundled FLTK and libjpeg-turbo builds.
+#             * Reset build to -1 for inclusion in Slackware's /extra.
+# 1.6.0-1:    22/feb/2016 by Patrick Volkerding <volkerdi@slackware.com>
+# 
+# -----------------------------------------------------------------------------
 
 PKGNAM=tigervnc
-VERSION=${VERSION:-1.1.0}
-BUILD=${BUILD:-1}
-NUMJOBS=${NUMJOBS:" -j4 "}
+VERSION=${VERSION:-1.6.0}
+PVER=$(echo $VERSION | cut -f1,2 -d. --output-delimiter=)
+BUILD=${BUILD:-3}
+NUMJOBS=${NUMJOBS:" -j7 "}
 TAG=${TAG:-}
-
-# Do we build the java applet (needs jdk)?
-DO_APPLET=${DO_APPLET:-"NO"}
 
 # TigerVNC needs to use source of the X.Org server whose version matches
 # that of your installed X.Org package:
@@ -39,11 +90,32 @@ MAXPATCHVER="$(echo $XORG | cut -f1,2 -d. | tr -d '.')"
 # OS Stamp into the binaries:
 OSNAME="$(head -1 /etc/slackware-version)"
 OSVENDOR="Slackware Linux Project"
-BUILDER="Built by Alien BOB on $(date -u)"
+BUILDER="Built by Slackware on $(date -u)"
+
+# Do we build the java applet (needs jdk)?
+DO_APPLET=${DO_APPLET:-"NO"}
+
+# Check for the availability of a Java compiler:
+if [ "$DO_APPLET" = "YES" ]; then
+  if ! javac -version 1>/dev/null 2>&1 ; then
+    echo "**"
+    echo "** DO_APPLET="YES" means to compile the Java viewer,"
+    echo "** However you do not have a Java JDK installed."
+    echo "** Press Ctrl-C to abort this script,"
+    echo "** or wait 10 seconds to continue without building the Java viewer."
+    echo "**"
+    sleep 10
+    DO_APPLET="NO"
+  fi
+fi
 
 # This covers most filenames you'd want as documentation. Change if needed.
-DOCS="LICENCE.TXT doc/TODO doc/*.txt doc/*.odt"
+DOCS="BUILDING.txt LICENCE.TXT README.txt doc/TODO doc/*.txt doc/*.odt"
 DOCS_XORG="COPYING ChangeLog"
+
+CWD=$(pwd)
+TMP=${TMP:-/tmp}
+PKG=$TMP/package-$PKGNAM
 
 if [ -e $CWD/machine.conf ]; then
   . $CWD/machine.conf ]
@@ -54,15 +126,15 @@ else
   MARCH=$( uname -m )
   if [ -z "$ARCH" ]; then
     case "$MARCH" in
-      i?86)    export ARCH=i486 ;;
+      i?86)    export ARCH=i586 ;;
       arm*)    export ARCH=arm ;;
       # Unless $ARCH is already set, use uname -m for all other archs:
       *)       export ARCH=$MARCH ;;
     esac
   fi
   # Set CFLAGS/CXXFLAGS and LIBDIRSUFFIX:
-  if [ "$ARCH" = "i486" ]; then
-    SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  if [ "$ARCH" = "i586" ]; then
+    SLKCFLAGS="-O2 -march=i586 -mtune=i686"
     LIBDIRSUFFIX=""
   elif [ "$ARCH" = "s390" ]; then
     SLKCFLAGS="-O2"
@@ -84,62 +156,11 @@ case "$ARCH" in
     *)    TARGET=$ARCH-slackware-linux ;;
 esac
 
-CWD=$(pwd)
-TMP=${TMP:-/tmp}
-PKG=$TMP/package-$PKGNAM
-
-rm -rf $PKG
-mkdir -p $TMP $PKG
-cd $TMP
-rm -rf $PKGNAM-$VERSION
-rm -rf xorg-server-${XORG}
-tar xvf $CWD/$PKGNAM-$VERSION.tar.?z* || exit 1
-tar xvf $CWD/xorg-server-${XORG}.tar.?z* || exit 1
-cd $PKGNAM-$VERSION || exit 1
-
-# Move the xorg-server sources into the TigerVNC tree:
-mv unix/xserver/hw/vnc ../xorg-server-${XORG}/hw/
-rm -rf unix/xserver/hw
-mv ../xorg-server-${XORG}/* unix/xserver/
-
-# We have patches for X.Org later than 1.10 which tigervnc does not have:
-for PATCHVER in 111 112 113 114 ; do
-  if [ -e $CWD/patches/tigervnc$(echo $VERSION | cut -f1,2 -d. --output-delimiter=)-xorg${PATCHVER}.patch ]; then
-    cp $CWD/patches/tigervnc$(echo $VERSION | cut -f1,2 -d. --output-delimiter=)-xorg${PATCHVER}.patch unix/xserver${PATCHVER}.patch
-  fi
-done
-
-if [ $MAXPATCHVER -gt 110 ]; then
-  if [ $MAXPATCHVER -lt 113 ]; then
-    # The sed magic in the hw/vnc Makefile needs some love:
-    # ... taken care of in the xserver113 patch if we ever move to X.Org 1.13.
-    cat $CWD/patches/tigervnc$(echo $VERSION | cut -f1,2 -d. --output-delimiter=)-xorg_headers.patch | patch -p1 --verbose || exit 1
-  else
-    # We need to rewrite the xserver110.patch for X.Org 1.13 and newer:
-    cp $CWD/patches/tigervnc$(echo $VERSION | cut -f1,2 -d. --output-delimiter=)-xorg110.patch unix/xserver110.patch
-  fi
-fi
-
-# Patch the xorg-server source to include building the vnc driver
-cd unix/xserver
-  if [ $MAXPATCHVER -le 110 ]; then
-    # apply one of the tigervnc-provided patches:
-    cat ../xserver${MAXPATCHVER}.patch | patch -p1 --verbose || exit 1
-  else
-    # these external patches are incremental and must be applied in order:
-    for PATCHVER in 110 111 112 113 114 ; do
-      if [ $PATCHVER -le $MAXPATCHVER -a -e ../xserver${PATCHVER}.patch ]; then
-        cat ../xserver${PATCHVER}.patch | patch -p1 --verbose || exit 1
-      fi
-    done
-  fi
-cd -
-
-# We use Java7:
-cat $CWD/patches/tigervnc11-java7.patch | patch -p1 --verbose || exit 1
-
-# Explicitly put the java applet into a directory named 'tigervnc':
-sed -i -e 's#/vnc/class#/tigervnc/class#'g $(grep -rl vnc/class .)
+rm -rf $TMP/tmp-${PKGNAM} $PKG
+mkdir -p $TMP/tmp-${PKGNAM}/deps/usr $PKG
+cd $TMP/tmp-${PKGNAM}
+tar --owner=root --group=root -xvf $CWD/sources/$PKGNAM-$VERSION.tar.?z* || exit 1
+tar --owner=root --group=root -xvf $CWD/sources/xorg-server-${XORG}.tar.?z* || exit 1
 
 # Make sure ownerships and permissions are sane:
 chown -R root:root .
@@ -149,91 +170,124 @@ find . \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \;
 
-export LDFLAGS="$SLKLDFLAGS -lpthread"
+export LDFLAGS="$SLKLDFLAGS"
 export CXXFLAGS="$SLKCFLAGS"
 export CFLAGS="$SLKCFLAGS"
 
-echo -e "\n*** Building tigervnc ***\n"
-autoreconf -vif
-./configure \
-  --prefix=/usr \
-  --libdir=/usr/lib${LIBDIRSUFFIX} \
-  --mandir=/usr/man \
-  --docdir=/usr/doc/$PKGNAM-$VERSION \
-  --localstatedir=/var \
-  --sysconfdir=/etc \
-  --disable-static \
-  --program-prefix= \
-  --program-suffix= \
-  --build=$TARGET
 
-make $NUMJOBS || make || exit 1
-make DESTDIR=$PKG install || exit 1
+cat <<EOT
+#
+# Compile tigervnc:
+#
+EOT
 
-cd unix/xserver
-  echo -e "\n*** Building xserver ***\n"
-  export CXXFLAGS="$SLKCFLAGS -fpermissive"
+cd $PKGNAM-$VERSION || exit 1
+
+# Explicitly link against libpng to prevent linking errors:
+cat $CWD/patches/tigervnc13_link_png.patch | patch -p1 --verbose || exit 1
+
+# Allow compiling for xorg-server-1.18.x:
+cat $CWD/patches/tigervnc.support.xorg.118.patch | patch -p1 --verbose || exit 1
+
+# Fix a compile error with xorg-server-1.18.x:
+cat $CWD/patches/tigervnc-xorg118-QueueKeyboardEvents.patch | patch -p1 --verbose || exit 1
+
+[ "$DO_APPLET" = "YES" ] && CMAKE_JAVA="ON" || CMAKE_JAVA="OFF"
+# Explicitly put the java applet into a directory named 'tigervnc':
+sed -i -e 's#/vnc/class#/tigervnc/class#'g $(grep -rl vnc/class .)
+sed -i -e 's#DESTINATION vnc/class#DESTINATION share/tigervnc/class#'g $(grep -rl vnc/class .)
+
+export LDFLAGS="$SLKLDFLAGS -ldl -lpthread"
+export CXXFLAGS="$SLKCFLAGS -fpermissive -I $(pwd)/common"
+
+# Fix the man page and documentation installation:
+sed -e 's,set(MAN_DIR "${DATA_DIR}/man"),set(MAN_DIR "${MAN_INSTALL_DIR}"),' \
+    -e 's,set(DOC_DIR "${CMAKE_INSTALL_PREFIX}/share/,set(DOC_DIR "${CMAKE_INSTALL_PREFIX}/,' \
+    -i CMakeLists.txt
+
+mkdir -p build
+cd build
+  echo -e "\n*** Building vnc client ***\n"
+  cmake \
+    -G "Unix Makefiles" \
+    -Wno-dev \
+    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
+    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
+    -DCMAKE_INSTALL_PREFIX=/usr \
+    -DMAN_INSTALL_DIR=/usr/man \
+    -DSYSCONF_INSTALL_DIR=/etc \
+    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
+    -DENABLE_PAM:BOOL=OFF \
+    -DBUILD_JAVA:BOOL=${CMAKE_JAVA} \
+    ..
+  make V=1 $NUMJOBS || make || exit 1
+  make DESTDIR=$PKG install || exit 1
+cd -
+
+# Do we have a patch for X.Org which tigervnc does not have?
+if [ ! -f unix/xserver${MAXPATCHVER}.patch -a -f $CWD/patches/xserver${MAXPATCHVER}.patch ]
+then
+  cp $CWD/patches/xserver${MAXPATCHVER}.patch unix/
+fi
+
+# Prepare the Xvnc sources (we are building out-of-tree, in ./build directory):
+mkdir -p build/unix
+cp -R unix/xserver unix/xserver${MAXPATCHVER}.patch build/unix/
+cp -R ../xorg-server-${XORG}/* build/unix/xserver/
+
+cd build/unix/xserver/
+  # Patch the xorg-server source to include building vnc driver:
+  cat ../xserver${MAXPATCHVER}.patch | patch -p1 --verbose
+  echo -e "\n*** Building vnc server ***\n"
   autoreconf -vif
 
   # Default font paths to be used by the X server
   DEF_FONTPATH="/usr/share/fonts/local,/usr/share/fonts/TTF,/usr/share/fonts/OTF,/usr/share/fonts/Type1,/usr/share/fonts/misc,/usr/share/fonts/CID,/usr/share/fonts/75dpi/:unscaled,/usr/share/fonts/100dpi/:unscaled,/usr/share/fonts/75dpi,/usr/share/fonts/100dpi,/usr/share/fonts/cyrillic"
 
+  CFLAGS="$CFLAGS -std=c99" \
   ./configure \
     --prefix=/usr \
     --libdir=/usr/lib${LIBDIRSUFFIX} \
     --sysconfdir=/etc \
     --localstatedir=/var \
     --mandir=/usr/man \
-    --disable-dri \
+    --disable-dri  --enable-dri2  --disable-dri3 \
     --disable-static \
     --disable-xorg --disable-xnest --disable-xvfb --disable-dmx \
-    --disable-xwin --disable-xephyr --disable-kdrive \
-    --disable-xinerama \
+    --disable-xwin --disable-xephyr --disable-kdrive --disable-xwayland \
     --enable-composite \
+    --enable-glx --enable-glx-tls \
     --enable-install-libxf86config \
     --enable-xcsecurity \
-    --enable-glx-tls --enable-dri2 \
-    --with-pic \
+    --enable-xinerama \
     --with-int10=x86emu \
     --with-default-font-path="${DEF_FONTPATH}" \
-    --with-module-dir=/usr/lib${LIBDIRSUFFIX}/xorg/modules \
     --with-dri-driver-path=/usr/lib${LIBDIRSUFFIX}/xorg/modules/dri \
+    --with-module-dir=/usr/lib${LIBDIRSUFFIX}/xorg/modules \
+    --with-pic \
     --with-xkb-path=/etc/X11/xkb \
     --with-xkb-output=/var/lib/xkb \
     --disable-config-dbus \
     --disable-config-hal \
     --disable-config-udev \
-    --disable-devel-docs \
+    --disable-docs --disable-devel-docs \
+    --disable-selective-werror \
     --disable-unit-tests \
     --without-dtrace \
     --with-os-name="$OSNAME" \
     --with-os-vendor="$OSVENDOR" \
     --with-builderstring="$BUILDER" \
-    --build=$TARGET
+    --build=$TARGET || exit 1
 
-  make $NUMJOBS || make || exit 1
-  make -C hw/vnc DESTDIR=$PKG install
+  make V=1 TIGERVNC_SRCDIR="$TMP/tmp-${PKGNAM}/${PKGNAM}-${VERSION}" $NUMJOBS || exit 1
+  make TIGERVNC_SRCDIR="$TMP/tmp-${PKGNAM}/${PKGNAM}-${VERSION}" -C hw/vnc \
+    DESTDIR=$PKG install || exit 1
 cd -
 
-if [ "$DO_APPLET" = "YES" ]; then
-  # Compile the java applet (needs the JDK... JRE is not enough):
-  cd java/src/com/tigervnc/vncviewer
-    make || exit 1
-  cd -
-fi
-
-# Create .png icons from the .svg file:
-make -C media
-
-if [ "$DO_APPLET" = "YES" ]; then
-  # Install the java applet:
-  cd java/src/com/tigervnc/vncviewer
-    mkdir -p $PKG/usr/share/tigervnc/classes
-    install -m0755 VncViewer.jar $PKG/usr/share/tigervnc/classes/
-    install -m0644 index.vnc $PKG/usr/share/tigervnc/classes/
-    install -m0644 *.class $PKG/usr/share/tigervnc/classes/
-  cd -
-fi
+# Provide a sample configuration for the libvnc.so extension of X.Org,
+# documentation is available inside the file:
+mkdir -p $PKG/etc/X11/xorg.conf.d
+install -m644 $CWD/10-libvnc.conf $PKG/etc/X11/xorg.conf.d/10-libvnc.conf.new
 
 # Install menu entry:
 mkdir -p $PKG/usr/share/{applications,icons/hicolor/{16x16,24x24,32x32,48x48}/apps}
@@ -244,7 +298,7 @@ done
 cat <<EOT > $PKG/usr/share/applications/tigervnc.desktop
 [Desktop Entry]
 Encoding=UTF-8
-Name=TigerVNC
+Name=TigerVNC Viewer
 GenericName=VNCViewer (RFB Client)
 Comment=Connect to remote desktop
 SwallowExec=
@@ -262,6 +316,24 @@ EOT
 # Add this to the doinst.sh:
 ! [ -d $PKG/install ] && mkdir -p $PKG/install
 cat <<EOT >> $PKG/install/doinst.sh
+# Handle the incoming configuration files:
+config() {
+  for infile in \$1; do
+    NEW="\$infile"
+    OLD="\`dirname \$NEW\`/\`basename \$NEW .new\`"
+    # If there's no config file by that name, mv it over:
+    if [ ! -r \$OLD ]; then
+      mv \$NEW \$OLD
+    elif [ "\`cat \$OLD | md5sum\`" = "\`cat \$NEW | md5sum\`" ]; then
+      # toss the redundant copy
+      rm \$NEW
+    fi
+    # Otherwise, we leave the .new copy for the admin to consider...
+  done
+}
+
+config etc/X11/xorg.conf.d/10-libvnc.conf.new
+
 # Update the desktop database:
 if [ -x usr/bin/update-desktop-database ]; then
   chroot . /usr/bin/update-desktop-database usr/share/applications 1>/dev/null 2>&1
@@ -282,9 +354,13 @@ fi
 EOT
 
 # Add documentation:
+# First, remove files which were misplaced:
+rm -f $PKG/usr/doc/* 2> /dev/null
+cd $TMP/tmp-${PKGNAM}/${PKGNAM}-${VERSION}
 mkdir -p $PKG/usr/doc/$PKGNAM-$VERSION
 cp -a $DOCS $PKG/usr/doc/$PKGNAM-$VERSION || true
-for FIL in $(echo $DOCS_XORG); do cp -a unix/xserver/$FIL $PKG/usr/doc/$PKGNAM-$VERSION/${FIL}.xorg ; done
+for FIL in $(echo $DOCS_XORG); do cp -a build/unix/xserver/$FIL $PKG/usr/doc/$PKGNAM-$VERSION/${FIL}.xorg ; done || true
+#cat $CWD/$(basename $0) > $PKG/usr/doc/$PKGNAM-$VERSION/$PKGNAM.SlackBuild
 chown -R root:root $PKG/usr/doc/$PKGNAM-$VERSION
 find $PKG/usr/doc -type f -exec chmod 644 {} \;
 
@@ -296,7 +372,7 @@ fi
 
 # Strip binaries (if any):
 find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
 # Add a package description:
 mkdir -p $PKG/install
@@ -307,5 +383,5 @@ fi
 
 # Build the package:
 cd $PKG
-/sbin/makepkg -l y -c n $TMP/${PKGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txz
+/sbin/makepkg -l y -c n $TMP/${PKGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz}
 
diff --git a/source/a/pkgtools/scripts/upgradepkg b/source/a/pkgtools/scripts/upgradepkg
--- a/source/a/pkgtools/scripts/upgradepkg
+++ b/source/a/pkgtools/scripts/upgradepkg
@@ -1,7 +1,8 @@
-#!/bin/sh
+#!/bin/bash
 # Copyright 1999  Patrick Volkerding, Moorhead, Minnesota, USA 
 # Copyright 2001, 2002, 2003  Slackware Linux, Inc., Concord, California, USA
-# Copyright 2009  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2009, 2015  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2015  Michal Nazarewicz <mina86@mina86.com>
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -34,29 +35,20 @@
 # Support new compression types and package extensions.
 # Converted to use new pkgbase() function to remove pathname and
 # valid package extensions.
+#
+# Sat 17 Jan 16:21:32 UTC 2015  mina86
+# Various optimisation mostly resolving around avoiding having to fork
+# and call cut, basename and other helper commands.  Slight
+# refactoring of code calling removepkg.
 
 # Return a package name that has been stripped of the dirname portion
 # and any of the valid extensions (only):
 pkgbase() {
-  PKGEXT=$(echo $1 | rev | cut -f 1 -d . | rev)
-  case $PKGEXT in
-  'tgz' )
-    PKGRETURN=$(basename $1 .tgz)
-    ;;
-  'tbz' )
-    PKGRETURN=$(basename $1 .tbz)
-    ;;
-  'tlz' )
-    PKGRETURN=$(basename $1 .tlz)
-    ;;
-  'txz' )
-    PKGRETURN=$(basename $1 .txz)
-    ;;
-  *)
-    PKGRETURN=$(basename $1)
-    ;;
+  PKGRETURN=${1##*/}
+  case "$PKGRETURN" in *.t[gblx]z)
+    PKGRETURN=${PKGRETURN%.*}
   esac
-  echo $PKGRETURN
+  echo "$PKGRETURN"
 }
 
 usage() {
@@ -101,6 +93,8 @@ umask 022
 # $ROOT defined?
 if [ -d "$ROOT" ]; then
   export ROOT
+else
+  unset ROOT
 fi
 
 # --help or no args?
@@ -147,173 +141,158 @@ done # processing args
 # old package.
 
 package_name() {
-  STRING=$(pkgbase $1)
-  # Check for old style package name with one segment:
-  if [ "$(echo $STRING | cut -f 1 -d -)" = "$(echo $STRING | cut -f 2 -d -)" ]; then
+  STRING=$(pkgbase "$1")
+  case "$STRING" in
+  *-*-*-*)
+    # At least four segments, strip version arch and build and return name:
+    echo "${STRING%-*-*-*}"
+    # cruft for later ;)
+    # BUILD=${STRING##*-}
+    # STRING=${STRING%*-}
+    # ARCH=${STRING##*-}
+    # STRING=${STRING%*-}
+    # VER=${STRING%*-}
+    ;;
+  *)
+    # Old style package name with one segment or we don't have four
+    # segments: return the old-style (or out of spec) package name.
     echo $STRING
-  else # has more than one dash delimited segment
-    # Count number of segments:
-    INDEX=1
-    while [ ! "$(echo $STRING | cut -f $INDEX -d -)" = "" ]; do
-      INDEX=$(expr $INDEX + 1)
-    done
-    INDEX=$(expr $INDEX - 1) # don't include the null value
-    # If we don't have four segments, return the old-style (or out of spec) package name:
-    if [ "$INDEX" = "2" -o "$INDEX" = "3" ]; then
-      echo $STRING
-    else # we have four or more segments, so we'll consider this a new-style name:
-      NAME=$(expr $INDEX - 3)
-      NAME="$(echo $STRING | cut -f 1-$NAME -d -)"
-      echo $NAME
-      # cruft for later ;)
-      #VER=$(expr $INDEX - 2)
-      #VER="$(echo $STRING | cut -f $VER -d -)"
-      #ARCH=$(expr $INDEX - 1)
-      #ARCH="$(echo $STRING | cut -f $ARCH -d -)"
-      #BUILD="$(echo $STRING | cut -f $INDEX -d -)"
-    fi
-  fi
+  esac
 }
 
 ERRCODE=0
 
 # Main processing loop:
-while [ ! "$1" = "" ]; do
+for ARG; do
+  OLD=${ARG%'%'*}  # first segment, = $ARG if no %
+  NEW=${ARG#*'%'}  # second segment, = $ARG if no %
 
-# Simple package integrity check:
-if [ ! -f $(echo $1 | cut -f 2 -d '%') ]; then
-  ERRCODE=4
-  echo "Cannot install $1:  file not found"
-  shift 1
-  continue;
-fi
-
-# Figure out the names of the old and new packages:
-OLD=$(echo $1 | cut -f 1 -d '%')
-NEW=$(echo $1 | cut -f 2 -d '%')
-INCOMINGDIR=$(dirname $NEW)
-# These are the package names with the extension:
-NNAME=$(basename $NEW)
-ONAME=$(basename $OLD)
-# These are the package names without the extension:
-OLD=$(pkgbase $OLD)
-NEW=$(pkgbase $NEW)
-
-# Make sure the extension is valid:
-if [ "$NNAME" = "$NEW" ]; then
-  # We won't throw an ERRCODE for this, but the package is skipped:
-  echo "Cannot install $1:  invalid package extension"
-  shift 1
-  continue;
-fi
-
-# Check and fix the old package name:
-SHORT="$(package_name $OLD)"
-if [ ! -r $ROOT/var/log/packages/$OLD ]; then
-  if ls $ROOT/var/log/packages/$SHORT* 1> /dev/null 2> /dev/null ; then
-    for installed_package in $ROOT/var/log/packages/$SHORT* ; do
-      if [ "$(package_name $installed_package)" = "$SHORT" ]; then # found one
-        OLD="$(basename $installed_package)"
-        break
-      fi
-    done
+  # Simple package integrity check:
+  if ! [ -f "$NEW" ]; then
+    ERRCODE=4
+    echo "Cannot install $ARG:  file not found"
+    continue;
   fi
-fi
 
-# Test to see if both the old and new packages are where we expect them
-# to be -- skip to the next package (or package pair) if anything's wrong:
+  # Figure out the names of the old and new packages:
+  INCOMINGDIR=$(dirname $NEW)
+  # These are the package names with the extension:
+  NNAME=${NEW##*/}
+  ONAME=${OLD##*/}
+  # These are the package names without the extension:
+  OLD=$(pkgbase $OLD)
+  NEW=$(pkgbase $NEW)
 
-if [ ! -r $ROOT/var/log/packages/$OLD ]; then
-  if [ ! "$INSTALL_NEW" = "yes" ]; then
-    if [ "$DRY_RUN" = "true" ]; then
-      echo "$OLD would not be upgraded (no installed package named $SHORT)."
-    else  
-      echo
-      echo "Error:  there is no installed package named $OLD."
-      echo "        (looking for $ROOT/var/log/packages/$OLD)"
-      echo
+  # Make sure the extension is valid:
+  if [ "$NNAME" = "$NEW" ]; then
+    # We won't throw an ERRCODE for this, but the package is skipped:
+    echo "Cannot install $OLD:  invalid package extension"
+    continue;
+  fi
+
+  # Check and fix the old package name:
+  SHORT="$(package_name $OLD)"
+  if [ ! -r $ROOT/var/log/packages/$OLD ]; then
+    if ls $ROOT/var/log/packages/$SHORT* 1> /dev/null 2> /dev/null ; then
+      for installed_package in $ROOT/var/log/packages/$SHORT* ; do
+        if [ "$(package_name $installed_package)" = "$SHORT" ]; then # found one
+          OLD="${installed_package##*/}"
+          break
+        fi
+      done
     fi
-    ERRCODE=1
-  else # --install-new was given, so install the new package:
-    if [ "$DRY_RUN" = "true" ]; then
-      echo "$NEW would be installed (new package)."
-    else
-      cat << EOF
+  fi
+
+  # Test to see if both the old and new packages are where we expect them
+  # to be -- skip to the next package (or package pair) if anything's wrong:
+
+  if [ ! -r $ROOT/var/log/packages/$OLD ]; then
+    if [ ! "$INSTALL_NEW" = "yes" ]; then
+      if [ "$DRY_RUN" = "true" ]; then
+        echo "$OLD would not be upgraded (no installed package named $SHORT)."
+      else
+        echo
+        echo "Error:  there is no installed package named $OLD."
+        echo "        (looking for $ROOT/var/log/packages/$OLD)"
+        echo
+      fi
+      ERRCODE=1
+    else # --install-new was given, so install the new package:
+      if [ "$DRY_RUN" = "true" ]; then
+        echo "$NEW would be installed (new package)."
+      else
+        cat << EOF
 
 +==============================================================================
 | Installing new package $INCOMINGDIR/$NNAME
 +==============================================================================
 
 EOF
-      /sbin/installpkg $INCOMINGDIR/$NNAME
+        /sbin/installpkg $INCOMINGDIR/$NNAME
+      fi
     fi
-  fi
-  shift 1
-  continue;
-elif [ ! -r "$INCOMINGDIR/$NNAME" ]; then
-  if [ "$DRY_RUN" = "true" ]; then
-    echo "$NEW incoming package not found (command line)."
-  else
-    echo
-    echo "Error:  incoming package $INCOMINGDIR/$NNAME not found."
-    echo
-  fi
-  shift 1
-  ERRCODE=1
-  continue;
-fi
-
-# Unless --reinstall was given, compare the package names
-# and skip any exact matches:
-if [ ! "$REINSTALL" = "true" ]; then
-  if [ "$OLD" = "$NEW" ]; then
+    continue;
+  elif [ ! -r "$INCOMINGDIR/$NNAME" ]; then
     if [ "$DRY_RUN" = "true" ]; then
-      echo "$NEW would be skipped (already installed)."
+      echo "$NEW incoming package not found (command line)."
     else
-      cat << EOF
+      echo
+      echo "Error:  incoming package $INCOMINGDIR/$NNAME not found."
+      echo
+    fi
+    ERRCODE=1
+    continue;
+  fi
+
+  # Unless --reinstall was given, compare the package names
+  # and skip any exact matches:
+  if [ ! "$REINSTALL" = "true" ]; then
+    if [ "$OLD" = "$NEW" ]; then
+      if [ "$DRY_RUN" = "true" ]; then
+        echo "$NEW would be skipped (already installed)."
+      else
+        cat << EOF
 
 +==============================================================================
 | Skipping package $NEW (already installed)
 +==============================================================================
 
 EOF
+      fi
+      continue;
     fi
-    shift 1
-    continue; 
   fi
-fi
 
-# Showtime.  Let's do the upgrade.  First, we will rename all the
-# installed packages with this basename to make them easy to remove later:
+  # Showtime.  Let's do the upgrade.  First, we will rename all the
+  # installed packages with this basename to make them easy to remove later:
 
-TIMESTAMP=$(date +%Y-%m-%d,%T)
-SHORT="$(package_name $OLD)"
-if [ "$DRY_RUN" = "true" ]; then
-  echo -n "$NEW would upgrade: "
+  TIMESTAMP=$(date +%Y-%m-%d,%T)
+  SHORT="$(package_name $OLD)"
+  if [ "$DRY_RUN" = "true" ]; then
+    echo -n "$NEW would upgrade: "
+    for installed_package in $ROOT/var/log/packages/$SHORT* ; do
+    if [ "$(package_name $installed_package)" = "$SHORT" ]; then
+      echo -n "$(pkgbase $installed_package)"
+    fi
+    done
+    echo
+    continue
+  fi
   for installed_package in $ROOT/var/log/packages/$SHORT* ; do
-  if [ "$(package_name $installed_package)" = "$SHORT" ]; then
-    echo -n "$(pkgbase $installed_package)"
-  fi
-  done
-  echo
-  shift 1
-  continue
-fi
-for installed_package in $ROOT/var/log/packages/$SHORT* ; do
-  if [ "$(package_name $installed_package)" = "$SHORT" ]; then
-    mv $installed_package ${installed_package}-upgraded-$TIMESTAMP
-  fi
-done
-for installed_script in $ROOT/var/log/scripts/$SHORT* ; do
-  if [ "$(package_name $installed_script)" = "$SHORT" ]; then
-    if [ -r $installed_script ]; then
-      mv $installed_script ${installed_script}-upgraded-$TIMESTAMP
+    if [ "$(package_name $installed_package)" = "$SHORT" ]; then
+      mv $installed_package ${installed_package}-upgraded-$TIMESTAMP
     fi
-  fi
-done
+  done
+  for installed_script in $ROOT/var/log/scripts/$SHORT* ; do
+    if [ "$(package_name $installed_script)" = "$SHORT" ]; then
+      if [ -r $installed_script ]; then
+        mv $installed_script ${installed_script}-upgraded-$TIMESTAMP
+      fi
+    fi
+  done
 
-# Print a banner for the current upgrade:
-cat << EOF
+  # Print a banner for the current upgrade:
+  cat << EOF
 
 +==============================================================================
 | Upgrading $OLD package using $INCOMINGDIR/$NNAME
@@ -321,67 +300,49 @@ cat << EOF
 
 EOF
 
-# Next, the new package is pre-installed:
-if [ "$VERBOSE" = "verbose" ]; then
-  /sbin/installpkg $INCOMINGDIR/$NNAME
-  RETCODE=$?
-else
-  echo "Pre-installing package $NEW..."
-  /sbin/installpkg $INCOMINGDIR/$NNAME 1> /dev/null
-  RETCODE=$?
-fi
-# Make sure that worked:
-if [ ! $RETCODE = 0 ]; then
-  echo "ERROR:  Package $INCOMINGDIR/$NNAME did not install"
-  echo "correctly.  You may need to reinstall your old package"
-  echo "to avoid problems.  Make sure the new package is not"
-  echo "corrupted."
-  sleep 30
-  # Skip this package, but still try to proceed.  Good luck...
-  shift 1
-  continue;
-fi
+  # Next, the new package is pre-installed:
+  if [ "$VERBOSE" = "verbose" ]; then
+    /sbin/installpkg $INCOMINGDIR/$NNAME
+    RETCODE=$?
+  else
+    echo "Pre-installing package $NEW..."
+    /sbin/installpkg $INCOMINGDIR/$NNAME 1> /dev/null
+    RETCODE=$?
+  fi
+  # Make sure that worked:
+  if [ ! $RETCODE = 0 ]; then
+    echo "ERROR:  Package $INCOMINGDIR/$NNAME did not install"
+    echo "correctly.  You may need to reinstall your old package"
+    echo "to avoid problems.  Make sure the new package is not"
+    echo "corrupted."
+    sleep 30
+    # Skip this package, but still try to proceed.  Good luck...
+    continue;
+  fi
 
-# Now, the leftovers from the old package(s) can go.  Pretty simple, huh? :)
-if [ -d "$ROOT" ]; then
-  ( cd $ROOT/var/log/packages
-    for rempkg in *-$TIMESTAMP ; do
-      if [ "$VERBOSE" = "verbose" ]; then
-        ROOT=$ROOT /sbin/removepkg $rempkg
-      else
-        ROOT=$ROOT /sbin/removepkg $rempkg | grep -v "Skipping\." | grep -v "Removing files:"
-      fi
-    done
-  )
-else
-  ( cd /var/log/packages
-    for rempkg in *-$TIMESTAMP ; do
-      if [ "$VERBOSE" = "verbose" ]; then
-        /sbin/removepkg $rempkg
-      else
-        /sbin/removepkg $rempkg | grep -v "Skipping\." | grep -v "Removing files:"
-      fi
-    done
-  )
-fi
-echo
+  # Now, the leftovers from the old package(s) can go.  Pretty simple, huh? :)
+  for rempkg in "$ROOT/var/log/packages/"*"-$TIMESTAMP"; do
+    if [ "$VERBOSE" = "verbose" ]; then
+      /sbin/removepkg "${rempkg##*/}"
+    else
+      /sbin/removepkg "${rempkg##*/}" | grep -v 'Skipping\.\|Removing files:'
+    fi
+  done
+  echo
 
-# Again!  Again!
-# Seriously, the reinstalling of a package can be crucial if any files
-# shift location, so we should always reinstall as the final step:
-if [ ! "$NOT_PARANOID" = "true" ]; then
-  /sbin/installpkg $INCOMINGDIR/$NNAME
-fi
+  # Again!  Again!
+  # Seriously, the reinstalling of a package can be crucial if any files
+  # shift location, so we should always reinstall as the final step:
+  if [ ! "$NOT_PARANOID" = "true" ]; then
+    /sbin/installpkg $INCOMINGDIR/$NNAME
+  fi
 
-echo "Package $OLD upgraded with new package $INCOMINGDIR/$NNAME."
-ERRCODE=0
-
-# Process next parameter:
-shift 1
-
+  echo "Package $OLD upgraded with new package $INCOMINGDIR/$NNAME."
+  ERRCODE=0
 done
 
 if [ ! "$DRY_RUN" = "true" ]; then
   echo
 fi
 exit $ERRCODE
+
diff --git a/source/ap/vim/vim.SlackBuild b/source/ap/vim/vim.SlackBuild
--- a/source/ap/vim/vim.SlackBuild
+++ b/source/ap/vim/vim.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2008, 2009, 2010, 2013  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2008, 2009, 2010, 2013, 2016  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,16 +20,31 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-VIMVER=7.4
+VIMBRANCH=7.4
 CTAGSVER=5.8
-# This is the directory in the VIM source archive to cd into.
-DIRVER=74
 BUILD=${BUILD:-1}
+
+CWD=$(pwd)
+
+if [ -r vim-${VIMBRANCH}*.tar.xz ]; then # if there's a source archive already, use the version number from it:
+  VERSION=$(echo vim-${VIMBRANCH}*.tar.xz | rev | cut -f 3- -d . | cut -f 1 -d - | rev)
+else # need to fetch the latest source archive for this branch:
+  VERSION="$(echo $(basename $(wget -q -O - https://github.com/vim/vim/releases | grep v${VIMBRANCH} | head -n 1 | cut -f 2 -d \" )) | cut -b2- )"
+  ( lftpget https://github.com/vim/vim/archive/v${VERSION}.tar.gz
+    gzip -d v${VERSION}.tar.gz
+    mv v${VERSION}.tar vim-${VERSION}.tar
+    xz -9 -v vim-${VERSION}.tar
+    if [ ! -r vim-${VERSION}.tar.xz ]; then
+      echo "ERROR:  Something went wrong trying to fetch https://github.com/vim/vim/archive/v${VERSION}.tar.gz"
+      exit 1
+    fi
+  ) || exit 1
+fi
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) export ARCH=i486 ;;
+    i?86) export ARCH=i586 ;;
     arm*) export ARCH=arm ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
@@ -49,31 +64,17 @@ else
 fi
 export SLKLDFLAGS="-L/usr/lib${LIBDIRSUFFIX}"
 
-CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-vim
 
 rm -rf $PKG
 mkdir -p $TMP $PKG
 
-# Determine VIM patchlevel:
-if [ -d $CWD/patches ] ; then
-  cd $CWD/patches
-  PATCHLEVEL=$(/bin/ls ?.?.????.gz 2> /dev/null | tail -1 | cut -f 3 -d . )
-  if [ "$PATCHLEVEL" = "" ]; then
-    PATCHLEVEL=$(/bin/ls ?.?.???.gz 2> /dev/null | tail -1 | cut -f 3 -d . )
-    if [ "$PATCHLEVEL" = "" ]; then
-      PATCHLEVEL=000
-    fi
-  fi
-  cd $CWD
-fi
-
 # ctags was once a part of vim,
 # but now we have to bundle it in
 cd $TMP
 rm -rf ctags-$CTAGSVER
-tar xvf $CWD/ctags-$CTAGSVER.tar.gz || exit 1
+tar xvf $CWD/ctags-$CTAGSVER.tar.xz || exit 1
 cd ctags-$CTAGSVER
 chown -R root:root .
 find . \
@@ -93,13 +94,13 @@ mkdir -p $PKG/usr/man/man1
 cat ctags.1 | gzip -9c > $PKG/usr/man/man1/ctags.1.gz
 mkdir -p $PKG/usr/doc/ctags-$CTAGSVER
 cp -a \
-  COPYING EXTENDING.html FAQ INSTALL INSTALL.oth NEWS README \
+  COPYING* EXTENDING.html FAQ INSTALL INSTALL.oth NEWS README* \
   $PKG/usr/doc/ctags-$CTAGSVER
 chmod 644 $PKG/usr/doc/ctags-$CTAGSVER/*
 
 cd $TMP
-rm -rf vim$DIRVER
-tar xvf $CWD/vim-$VIMVER.tar.?z* || exit 1
+rm -rf vim-${VERSION}
+tar xvf $CWD/vim-${VERSION}.tar.xz || exit 1
 
 config_vim() {
 CFLAGS="$SLKCFLAGS" \
@@ -120,21 +121,7 @@ CFLAGS="$SLKCFLAGS" \
   #  --enable-rubyinterp
 }
 
-cd $TMP/vim$DIRVER
-
-# If there's no syntax update, create one:
-if ! ls $CWD/vim-runtime-syntax-* 1> /dev/null 2> /dev/null ; then
-  rm -rf runtime/syntax.orig
-  cp -a runtime/syntax runtime/syntax.orig
-  echo "Fetching vim syntax updates from ftp.nluug.nl..."
-  rsync -avzcP ftp.nluug.nl::Vim/runtime/syntax/ runtime/syntax/
-  diff -u -r --new-file runtime/syntax.orig runtime/syntax | gzip -9c > $CWD/vim-runtime-syntax-$(date +%Y%m%d).diff.gz
-  rm -rf runtime/syntax
-  mv runtime/syntax.orig runtime/syntax
-fi
-
-# Apply the syntax update:
-zcat $CWD/vim-runtime-syntax-*.diff.gz | patch -p0 --verbose || exit 1
+cd $TMP/vim-$VERSION || exit 1
 
 chown -R root:root .
 find . \
@@ -142,11 +129,6 @@ find . \
   -exec chmod 755 {} \; -o \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \;
-for file in $CWD/patches/?.?.???.gz $CWD/patches/?.?.????.gz ; do
-  if [ -f $file ]; then
-    zcat $file | patch -p0 --verbose || exit 1
-  fi
-done
 
 config_vim --without-x --disable-gui
 make $NUMJOBS || make || exit 1
@@ -192,11 +174,11 @@ fi
 ( cd $PKG/usr/bin ; rm -rf evim )
 ( cd $PKG/usr/bin ; ln -sf vim evim )
 
-mkdir -p $PKG/usr/doc/vim-$VIMVER.$PATCHLEVEL
-cp -a README.txt $PKG/usr/doc/vim-$VIMVER.$PATCHLEVEL
-find $PKG/usr/doc/vim-$VIMVER.$PATCHLEVEL -type f | xargs chmod 644
-( cd $PKG/usr/doc/vim-$VIMVER.$PATCHLEVEL ; rm -rf doc )
-( cd $PKG/usr/doc/vim-$VIMVER.$PATCHLEVEL ; ln -sf /usr/share/vim/vim$DIRVER doc )
+mkdir -p $PKG/usr/doc/vim-$VERSION
+cp -a README.txt $PKG/usr/doc/vim-$VERSION
+find $PKG/usr/doc/vim-$VERSION -type f | xargs chmod 644
+( cd $PKG/usr/doc/vim-$VERSION ; rm -rf doc )
+( cd $PKG/usr/doc/vim-$VERSION ; ln -sf /usr/share/vim/vim$(echo $VIMBRANCH | tr -d .) doc )
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc.vim > $PKG/install/slack-desc
@@ -221,5 +203,5 @@ find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 
 cd $PKG
-/sbin/makepkg -l y -c n $TMP/vim-$VIMVER.$PATCHLEVEL-$ARCH-$BUILD.txz
+/sbin/makepkg -l y -c n $TMP/vim-$VERSION-$ARCH-$BUILD.txz
 
diff --git a/source/l/gtk+2/gtk+2.SlackBuild b/source/l/gtk+2/gtk+2.SlackBuild
--- a/source/l/gtk+2/gtk+2.SlackBuild
+++ b/source/l/gtk+2/gtk+2.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2008, 2009, 2010, 2011, 2012, 2013  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2008, 2009, 2010, 2011, 2012, 2013, 2016  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -29,7 +29,7 @@ NUMJOBS=${NUMJOBS:-" -j7 "}
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) export ARCH=i486 ;;
+    i?86) export ARCH=i586 ;;
     arm*) export ARCH=arm ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
@@ -40,8 +40,8 @@ CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-gtk2
 
-if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+if [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "s390" ]; then
   SLKCFLAGS="-O2"
@@ -77,8 +77,13 @@ zcat $CWD/gtk.xid.nowarningflood.diff.gz | patch -p1 --verbose || exit 1
 
 # Patch to restore commonly used icon names, otherwise everything breaks.
 # I fail to see the point of this "cleanup"
-zcat $CWD/gtk+-2.24.x.icon-compat.diff.gz | patch -p1 --verbose || exit 1
 zcat $CWD/gtk+-2.24.x.icon-compat.am.diff.gz | patch -p1 --verbose || exit 1
+zcat $CWD/gtk+-2.24.x.icon-compat.diff.gz | patch -p1 --verbose || exit 1
+
+# Prevents build failures in the docs.  Found online.
+# Only needed if autoreconf is used...  ?
+zcat $CWD/gtk.gtk-faq.diff.gz | patch -p1 --verbose || exit 1
+zcat $CWD/gtk.gtk-tut.diff.gz | patch -p1 --verbose || exit 1
 
 # Regenerate ./configure:
 libtoolize --force
@@ -117,7 +122,10 @@ make install \
 mv $PKG/etc/gtk-2.0/im-multipress.conf $PKG/etc/gtk-2.0/im-multipress.conf.new || exit 1
 
 # Install a "starter" gtkrc
-echo 'gtk-theme-name="GTK+"' > $PKG/etc/gtk-2.0/gtkrc.new
+# /etc/gtk-2.0/gtkrc overrides this  --rworkman
+echo 'gtk-theme-name="GTK+"' > $PKG/usr/share/gtk-2.0/gtkrc
+echo 'gtk-icon-theme-name="Adwaita"' >> $PKG/usr/share/gtk-2.0/gtkrc
+echo 'gtk-fallback-icon-theme = "Tango"' >> $PKG/usr/share/gtk-2.0/gtkrc
 
 # We need to have separate 32-bit and 64-bit binaries
 # for places where we have two copies of the GTK+ package installed.
diff --git a/source/l/netpbm/netpbm.SlackBuild b/source/l/netpbm/netpbm.SlackBuild
--- a/source/l/netpbm/netpbm.SlackBuild
+++ b/source/l/netpbm/netpbm.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2006, 2007, 2008, 2009  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2006, 2007, 2008, 2009, 2015  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -22,21 +22,21 @@
 
 
 PKGNAM=netpbm
-VERSION=${VERSION:-10.49.02}
-BUILD=${BUILD:-1}
+VERSION=${VERSION:-10.66.02}
+BUILD=${BUILD:-4}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) export ARCH=i486 ;;
+    i?86) export ARCH=i586 ;;
     arm*) export ARCH=arm ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
   esac
 fi
 
-if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+if [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "s390" ]; then
   SLKCFLAGS="-O2"
@@ -59,6 +59,9 @@ cd $TMP
 rm -rf ${PKGNAM}-${VERSION}
 tar xvf $CWD/${PKGNAM}-$VERSION.tar.?z* || exit 1
 cd ${PKGNAM}-$VERSION
+
+zcat $CWD/netpbm-noppmtompeg.patch.gz | patch -p1 --verbose || exit 1
+zcat $CWD/netpbm-pnmtops.patch.gz | patch -p1 --verbose || exit 1
 
 # Make sure ownerships and permissions are sane:
 chown -R root:root .
@@ -92,9 +95,20 @@ find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   cd usr
   mkdir -p doc/netpbm-$VERSION
   mv VERSION bin/doc.url doc/netpbm-$VERSION
-  ( cd lib ; ln -sf libnetpbm.so.10 libnetpbm.so )
+  if [ -r lib/libnetpbm.so.11 ]; then
+    ( cd lib ; rm -f libnetpbm.so ; ln -sf libnetpbm.so.11 libnetpbm.so )
+  else
+    echo "ERROR:  libnetpbm.so.11 not found."
+    echo "Please edit the correct library major version into the build script"
+    exit 1
+  fi
   mv lib lib${LIBDIRSUFFIX}
-  rm -rf config_template link misc pkginfo man/man1/manweb.1 man/web
+  # Remove junk directories:
+  rm -rf link misc
+  # Remove manweb related files:
+  rm -rf bin/manweb man/man1/manweb.1* man/web
+  # Any other files in /usr are junk:
+  rm --verbose * 2> /dev/null
 )
 
 # Compress and link manpages, if any:
diff --git a/source/xap/mozilla-thunderbird/mozilla-thunderbird.SlackBuild b/source/xap/mozilla-thunderbird/mozilla-thunderbird.SlackBuild
--- a/source/xap/mozilla-thunderbird/mozilla-thunderbird.SlackBuild
+++ b/source/xap/mozilla-thunderbird/mozilla-thunderbird.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2008, 2009, 2010, 2011, 2012  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2008, 2009, 2010, 2011, 2012, 2014, 2016  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -25,64 +25,47 @@
 # Thanks to the folks at the Mozilla Foundation for permission to
 # distribute this, and for all the great work!  :-)
 
-TARBALLVER=$(basename $(ls thunderbird-*.tar.bz2 | cut -d - -f 2 | rev | cut -f 3- -d . | rev) .source)
-# Strip the end from beta versions:
-VERSION=$(echo $TARBALLVER | cut -f 1 -d b)
-MAJORVER=$(echo $TARBALLVER | cut -f 1 -d .)
+VERSION=$(basename $(ls thunderbird-*.tar.?z* | cut -d - -f 2 | rev | cut -f 3- -d . | rev) .source)
+RELEASEVER=$(echo $VERSION | cut -f 1 -d e | cut -f 1 -d b)
 BUILD=${BUILD:-1}
+
+# Specify this variable for a localized build.
+# For example, to build a version of Thunderbird with Italian support, run
+# the build script like this:
+#
+# MOZLOCALIZE=it ./mozilla-firefox.SlackBuild
+#
+MOZLOCALIZE=${MOZLOCALIZE:-}
+
+# Automatically determine the architecture we're building on:
+if [ -z "$ARCH" ]; then
+  case "$( uname -m )" in
+    i?86) export ARCH=i586 ;;
+    armv7hl) export ARCH=armv7hl ;;
+    arm*) export ARCH=arm ;;
+    # Unless $ARCH is already set, use uname -m for all other archs:
+       *) export ARCH=$( uname -m ) ;;
+  esac
+fi
+
+if [ "$ARCH" = "i586" ]; then
+  LIBDIRSUFFIX=""
+  OPTIMIZE=" --enable-optimize=-O2 "
+  # On IA32, use gold since GNU ld runs out of memory linking libxul.so:
+  PATH="$(pwd)/gold:$PATH"
+  export CC="gcc -B$(pwd)/gold"
+  export CXX="g++ -B$(pwd)/gold"
+elif [ "$ARCH" = "x86_64" ]; then
+  LIBDIRSUFFIX="64"
+  OPTIMIZE=" --enable-optimize=-O2 "
+else
+  LIBDIRSUFFIX=""
+  OPTIMIZE=" --enable-optimize=-O2 "
+fi
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-mozilla-thunderbird
-
-# Figure out if this is a beta, or a release:
-if echo $TARBALLVER | grep -q b ; then # we think it is a beta
-  if bzgrep -q comm-beta/ $CWD/thunderbird-$TARBALLVER.source.tar.bz2 ; then
-    MOZVERS=${MOZVERS:-beta}
-  else # blindly assume it is a release
-    MOZVERS=${MOZVERS:-release}
-  fi
-else # release, no "b" in the tarball version:
-  if bzgrep -q comm-esr${MAJORVER}/ $CWD/thunderbird-$TARBALLVER.source.tar.bz2 ; then
-    # Looks like we get this sometimes even when the tarball isn't labeled as esr...
-    MOZVERS=${MOZVERS:-esr${MAJORVER}}
-  else
-    MOZVERS=${MOZVERS:-release}
-  fi
-fi
-
-# Automatically determine the architecture we're building on:
-MARCH=$( uname -m )
-if [ -z "$ARCH" ]; then
-  case "$MARCH" in
-    i?86)    export ARCH=i486 ;;
-    armv7hl) export ARCH=$MARCH ;;
-    arm*)    export ARCH=arm ;;
-    # Unless $ARCH is already set, use uname -m for all other archs:
-    *)       export ARCH=$MARCH ;;
-  esac
-fi
-
-# Try to be gentle to the compiler, no optimizations:
-if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "s390" ]; then
-  SLKCFLAGS="-O"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O -fPIC"
-  LIBDIRSUFFIX="64"
-elif [ "$ARCH" = "arm" ]; then
-  SLKCFLAGS="-O2 -march=armv4 -mtune=xscale"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "armel" ]; then
-  SLKCFLAGS="-O2 -march=armv4t"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "armv7hl" ]; then
-  SLKCFLAGS="-O2 -march=armv7-a -mfpu=vfpv3-d16"
-  LIBDIRSUFFIX=""
-fi
 
 NUMJOBS=${NUMJOBS:-" -j7 "}
 
@@ -90,19 +73,25 @@ rm -rf $PKG
 mkdir -p $TMP $PKG/usr/lib${LIBDIRSUFFIX}
 
 cd $TMP
-rm -rf comm-$MOZVERS
-tar xvf $CWD/thunderbird-$TARBALLVER.source.tar.bz2 || exit 1
-cd comm-$MOZVERS || exit 1
+rm -rf thunderbird-$VERSION
+# Unpack this in a subdirectory to prevent changing permissions on /tmp:
+rm -rf thunderbird-unpack
+mkdir thunderbird-unpack
+cd thunderbird-unpack
+tar xvf $CWD/thunderbird-$VERSION.source.tar.?z* || exit 1
+mv * ..
+cd ..
+rm -rf thunderbird-unpack
+cd thunderbird-$VERSION || exit 1
 
-# Fix a long standing bug that's prevented staying current on GTK+.
-# Thanks to the BLFS folks.  :-)
-cat << EOF >> mozilla/layout/build/Makefile.in
-
-ifdef MOZ_ENABLE_CANVAS
-EXTRA_DSO_LDOPTS += \$(XLDFLAGS) -lX11 -lXrender
-endif
-
-EOF
+# Fetch localization, if requested:
+if [ ! -z $MOZLOCALIZE ]; then
+  LOC_TAG="THUNDERBIRD_$( echo $VERSION | tr \. _ )_RELEASE"
+  rm -f $LOC_TAG.tar.bz2
+  wget https://hg.mozilla.org/releases/l10n/mozilla-release/$MOZLOCALIZE/archive/$LOC_TAG.tar.bz2
+  tar xvf $LOC_TAG.tar.bz2
+  mv $MOZLOCALIZE-$LOC_TAG $MOZLOCALIZE
+fi
 
 # Arch-dependent patches:
 case "$ARCH" in
@@ -121,44 +110,15 @@ find . \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \;
 
-if gcc --version | grep -q "gcc (GCC) 4.7.0" ; then
- # Enable compiling with gcc-4.7.0:
- sed -i '/fcntl.h/a#include <unistd.h>' \
-   mozilla/ipc/chromium/src/base/{file_util_linux,message_pump_libevent,process_util_posix}.cc &&
- sed -i '/sys\/time\.h/a#include <unistd.h>' mozilla/ipc/chromium/src/base/time_posix.cc &&
- sed -i 's#\"PRIxPTR#\" PRIxPTR#g' mozilla/layout/base/tests/TestPoisonArea.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/base/search/src/nsMsgSearchAdapter.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/base/src/nsMsgFolderCompactor.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/compose/src/nsSmtpProtocol.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/imap/src/nsImapMailFolder.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/imap/src/nsImapProtocol.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/imap/src/nsImapServerResponseParser.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/local/src/nsPop3Protocol.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/mime/src/mimedrft.cpp &&
- sed -i 's#\"MSG_LINEBREAK#\" MSG_LINEBREAK#g' mailnews/mime/src/mimemult.cpp &&
- sed -i 's#\"MSG_LINEBREAK#\" MSG_LINEBREAK#g' mailnews/base/src/nsMsgFolderCompactor.cpp &&
- sed -i 's# ""##' mozilla/browser/base/Makefile.in
-fi
-
-# Mozilla devs enforce using an objdir for building
-# and launching configure with the absolute path
-# https://developer.mozilla.org/en/Configuring_Build_Options#Building_with_an_objdir
-mkdir obj
-cd obj
-export MOZILLA_DIR=$TMP/comm-$MOZVERS/mozilla &&
-export MOZILLA_OFFICIAL="1" &&
-export BUILD_OFFICIAL="1" &&
-export MOZ_PHOENIX="1" &&
-export CFLAGS="$SLKCFLAGS" &&
-export CXXFLAGS="$SLKCFLAGS" &&
-export MOZ_MAKE_FLAGS="$NUMJOBS" &&
-$TMP/comm-$MOZVERS/configure \
+# Our building options, in a configure-like display ;)
+OPTIONS="\
   --enable-official-branding \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --with-default-mozilla-five-home=/usr/lib${LIBDIRSUFFIX}/thunderbird-$VERSION \
   --with-system-zlib \
   --enable-application=mail \
+  --enable-calendar \
   --enable-default-toolkit=cairo-gtk2 \
   --enable-startup-notification \
   --enable-crypto \
@@ -167,34 +127,60 @@ $TMP/comm-$MOZVERS/configure \
   --enable-svg \
   --enable-canvas \
   --enable-xft \
-  --enable-xinerama \
-  --enable-optimize \
+  $OPTIMIZE \
   --enable-reorder \
   --enable-strip \
   --enable-cpp-rtti \
-  --enable-single-profile \
   --disable-accessibility \
   --disable-crashreporter \
   --disable-debug \
   --disable-tests \
-  --disable-logging \
   --disable-pedantic \
-  --disable-installer \
-  --disable-profilesharing
+  --host=$ARCH-slackware-linux \
+  --target=$ARCH-slackware-linux \
+  --build=$ARCH-slackware-linux"
   # Complains about missing APNG support in Slackware's libpng:
   #--with-system-png \
   # Broken with 12.0:
   #--enable-system-cairo \
+if [ ! -z $MOZLOCALIZE ]; then
+  OPTIONS=$OPTIONS" \
+  --enable-ui-locale=$MOZLOCALIZE
+  --with-l10n-base=.."
+  # There are no dictionaries in localized builds
+  sed -i \
+    -e "/@BINPATH@\/dictionaries\/\*/d" \
+    -e "/@RESPATH@\/dictionaries\/\*/d" \
+    mail/installer/package-manifest.in || exit 1
+fi
 
-#make -f client.mk build MOZ_MAKE_FLAGS="$NUMJOBS" || exit 1
-make $NUMJOBS || exit 1
-make install DESTDIR=$PKG || exit 1
+export BUILD_OFFICIAL=1
+export MOZILLA_OFFICIAL=1
+export MOZ_PHOENIX=1
+export MOZ_MAKE_FLAGS="$NUMJOBS"
 
-# Exit obj directory:
-cd ..
+# Clear some variables that could break the build
+unset DBUS_SESSION_BUS_ADDRESS ORBIT_SOCKETDIR SESSION_MANAGER \
+  XDG_SESSION_COOKIE XAUTHORITY MAKEFLAGS
+
+# Assemble our .mozconfig:
+echo > .mozconfig
+
+# Mozilla devs enforce using an objdir for building
+# https://developer.mozilla.org/en/Configuring_Build_Options#Building_with_an_objdir
+mkdir obj
+echo "mk_add_options MOZ_OBJDIR=$(pwd)/obj" >> .mozconfig
+# This directory is also needed or the build will fail:
+mkdir -p mozilla/obj
+
+# Write in it the options above
+for option in $OPTIONS; do echo "ac_add_options $option" >> .mozconfig; done
+
+make -f client.mk build || exit 1
+make -f client.mk install DESTDIR=$PKG || exit 1
 
 # We don't need these (just symlinks anyway):
-rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/thunderbird-devel-$VERSION
+rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/thunderbird-devel-$RELEASEVER
 
 # Nor these:
 rm -rf $PKG/usr/include
@@ -212,10 +198,10 @@ cat $CWD/mozilla-thunderbird.desktop > $PKG/usr/share/applications/mozilla-thund
 mkdir -p $PKG/usr/share/pixmaps
 cat $CWD/thunderbird.png > $PKG/usr/share/pixmaps/thunderbird.png
 
-# These files/directories are usually created if Firefox is run as root,
+# These files/directories are usually created if Thunderbird is run as root,
 # which on many systems might (and possibly should) be never.  Therefore, if we
 # don't see them we'll put stubs in place to prevent startup errors.
-( cd $PKG/usr/lib${LIBDIRSUFFIX}/thunderbird-$VERSION
+( cd $PKG/usr/lib${LIBDIRSUFFIX}/thunderbird-$RELEASEVER
   if [ -d extensions/talkback\@mozilla.org ]; then
     if [ ! -r extensions/talkback\@mozilla.org/chrome.manifest ]; then
       echo > extensions/talkback\@mozilla.org/chrome.manifest
@@ -227,21 +213,27 @@ cat $CWD/thunderbird.png > $PKG/usr/share/pixmaps/thunderbird.png
 )
 
 # Need some default icons in the right place:
-mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/thunderbird-$VERSION/chrome/icons/default
-install -m 644 other-licenses/branding/thunderbird/default16.png \
-  $PKG/usr/lib${LIBDIRSUFFIX}/thunderbird-$VERSION/icons/
-install -m 644 other-licenses/branding/thunderbird/default16.png \
-  $PKG/usr/lib${LIBDIRSUFFIX}/thunderbird-$VERSION/chrome/icons/default/ 
-( cd $PKG/usr/lib${LIBDIRSUFFIX}/thunderbird-$VERSION
-  install -m 644 icons/{default,mozicon50}.xpm chrome/icons/default/
-)
+for i in 16 22 24 32 48 256; do
+  install -m 0644 -D other-licenses/branding/thunderbird/mailicon${i}.png \
+    $PKG/usr/share/icons/hicolor/${i}x${i}/apps/thunderbird.png
+done
+mkdir -p $PKG/usr/share/pixmaps
+( cd $PKG/usr/share/pixmaps ; ln -sf /usr/share/icons/hicolor/256x256/apps/thunderbird . )
+mkdir -p $PKG/usr/lib$LIBDIRSUFFIX/thunderbird-$RELEASEVER/chrome/icons/default
+install -m 644 other-licenses/branding/thunderbird/mailicon16.png \
+  $PKG/usr/lib$LIBDIRSUFFIX/thunderbird-$RELEASEVER/icons/
+install -m 644 other-licenses/branding/thunderbird/mailicon16.png \
+  $PKG/usr/lib$LIBDIRSUFFIX/thunderbird-$RELEASEVER/chrome/icons/default/
 
 # Copy over the LICENSE
-install -p -c -m 644 LICENSE $PKG/usr/lib${LIBDIRSUFFIX}/thunderbird-$VERSION/
+install -p -c -m 644 LICENSE $PKG/usr/lib${LIBDIRSUFFIX}/thunderbird-$RELEASEVER/
 
 mkdir $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
-/sbin/makepkg -l y -c n $TMP/mozilla-thunderbird-$TARBALLVER-$ARCH-$BUILD.txz
-
+if [ -z $MOZLOCALIZE ]; then
+  /sbin/makepkg -l y -c n $TMP/mozilla-thunderbird-$VERSION-$ARCH-$BUILD.txz
+else
+  /sbin/makepkg -l y -c n $TMP/mozilla-thunderbird-$VERSION-$ARCH-${BUILD}_$MOZLOCALIZE.txz
+fi
diff --git a/source/xap/seamonkey/seamonkey.SlackBuild b/source/xap/seamonkey/seamonkey.SlackBuild
--- a/source/xap/seamonkey/seamonkey.SlackBuild
+++ b/source/xap/seamonkey/seamonkey.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2008, 2009, 2010, 2011, 2012, 2013  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -23,28 +23,45 @@
 TARBALLVER=${VERSION:-$(basename $(ls seamonkey-*.tar.* | cut -d - -f 2 | rev | cut -f 3- -d . | rev) .source)}
 # Strip the end from beta versions:
 VERSION=$(echo $TARBALLVER | cut -f 1 -d b)
-COMM=${COMM:-release}
 BUILD=${BUILD:-1}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) export ARCH=i486 ;;
+    i?86) export ARCH=i586 ;;
     arm*) export ARCH=arm ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
   esac
 fi
 
-if [ "$ARCH" = "x86_64" ]; then
+if [ "$ARCH" = "i586" ]; then
+  LIBDIRSUFFIX=""
+  OPTIMIZE_FLAG="-O2"
+  # On IA32, use gold since GNU ld runs out of memory linking libxul.so:
+  PATH="$(pwd)/gold:$PATH"
+  export CC="gcc -B$(pwd)/gold"
+  export CXX="g++ -B$(pwd)/gold"
+elif [ "$ARCH" = "x86_64" ]; then
   LIBDIRSUFFIX="64"
   OPTIMIZE_FLAG="-O2"
 else
   LIBDIRSUFFIX=""
-  OPTIMIZE_FLAG="-Os"
+  OPTIMIZE_FLAG="-O2"
 fi
 
 NUMJOBS=${NUMJOBS:-" -j7 "}
+
+# Workaround to prevent unidentified crashes when compiling with recent gcc.
+# Presumably a newer version will fix this (as it did with Firefox), so only
+# enable the workaround for known crashing versions.
+# Test page to check for crash:  http://onet.pl
+if [ $VERSION = 2.39 -o \
+     $VERSION = 2.40 ]; then
+  OPTIMIZE_FLAG="$(echo "$OPTIMIZE_FLAG" | sed 's/O2/Os/g')"
+  echo "Detected Seamonkey $VERSION...  enabling crash workaround O2 -> Os."
+  sleep 1
+fi
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp}
@@ -53,9 +70,9 @@ rm -rf $PKG
 mkdir -p $TMP $PKG/usr
 
 cd $TMP
-rm -rf comm-$COMM
+rm -rf seamonkey-${TARBALLVER}
 tar xvf $CWD/seamonkey-${TARBALLVER}.source.tar.?z* || exit 1
-cd comm-$COMM || exit 1
+cd seamonkey-${TARBALLVER} || exit 1
 
 # Make sure the perms/ownerships are sane:
 chown -R root:root .
@@ -65,44 +82,10 @@ find . \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \;
 
-# Fix a long standing bug that's prevented staying current on GTK+.
-# Thanks to the BLFS folks.  :-)
-cat >> mozilla/layout/build/Makefile.in << EOF
-
-ifdef MOZ_ENABLE_CANVAS
-EXTRA_DSO_LDOPTS += \$(XLDFLAGS) -lX11 -lXrender
-endif
-
-EOF
-
-if gcc --version | grep -q "gcc (GCC) 4.7.0" ; then
- # Enable compiling with gcc-4.7.0:
- sed -i '/fcntl.h/a#include <unistd.h>' \
-   mozilla/ipc/chromium/src/base/{file_util_linux,message_pump_libevent,process_util_posix}.cc &&
- sed -i '/sys\/time\.h/a#include <unistd.h>' mozilla/ipc/chromium/src/base/time_posix.cc &&
- sed -i 's#\"PRIxPTR#\" PRIxPTR#g' mozilla/layout/base/tests/TestPoisonArea.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/base/search/src/nsMsgSearchAdapter.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/base/src/nsMsgFolderCompactor.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/compose/src/nsSmtpProtocol.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/imap/src/nsImapMailFolder.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/imap/src/nsImapProtocol.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/imap/src/nsImapServerResponseParser.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/local/src/nsPop3Protocol.cpp &&
- sed -i 's#\"CRLF#\" CRLF#g' mailnews/mime/src/mimedrft.cpp &&
- sed -i 's#\"MSG_LINEBREAK#\" MSG_LINEBREAK#g' mailnews/mime/src/mimemult.cpp &&
- sed -i 's#\"MSG_LINEBREAK#\" MSG_LINEBREAK#g' mailnews/base/src/nsMsgFolderCompactor.cpp &&
- sed -i 's# ""##' mozilla/browser/base/Makefile.in
-fi
-
 chown -R root:root .
 
-# Mozilla devs enforce using an objdir for building
-# and launching configure with the absolute path
-# https://developer.mozilla.org/en/Configuring_Build_Options#Building_with_an_objdir
-mkdir obj
-cd obj
-BUILD_OFFICIAL=1 MOZILLA_OFFICIAL=1 \
-$TMP/comm-$COMM/configure \
+# Our building options, in a configure-like display ;)
+OPTIONS="\
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --enable-optimize=$OPTIMIZE_FLAG \
@@ -116,6 +99,7 @@ $TMP/comm-$COMM/configure \
   --disable-crashreporter \
   --enable-svg \
   --enable-canvas \
+  --enable-gstreamer=1.0 \
   --disable-short-wchar \
   --enable-nspr-autoconf \
   --enable-extensions=default,irc \
@@ -129,12 +113,35 @@ $TMP/comm-$COMM/configure \
   --enable-xft \
   --host=$ARCH-slackware-linux \
   --target=$ARCH-slackware-linux \
-  --build=$ARCH-slackware-linux
+  --build=$ARCH-slackware-linux"
 
   # --enable-system-cairo \
   # --with-system-png
-make $NUMJOBS || exit 1
-DESTDIR=$PKG make install || exit 1
+
+export BUILD_OFFICIAL=1
+export MOZILLA_OFFICIAL=1
+export MOZ_MAKE_FLAGS="$NUMJOBS"
+
+# Clear some variables that could break the build
+unset DBUS_SESSION_BUS_ADDRESS ORBIT_SOCKETDIR SESSION_MANAGER \
+  XDG_SESSION_COOKIE XAUTHORITY MAKEFLAGS
+
+# Assemble our .mozconfig:
+echo > .mozconfig
+
+# Mozilla devs enforce using an objdir for building
+# https://developer.mozilla.org/en/Configuring_Build_Options#Building_with_an_objdir
+mkdir obj
+echo "mk_add_options MOZ_OBJDIR=$(pwd)/obj" >> .mozconfig
+# This directory is also needed or the build will fail:
+mkdir -p mozilla/obj
+
+# Write in it the options above
+for option in $OPTIONS; do echo "ac_add_options $option" >> .mozconfig; done
+
+echo "ac_add_options --disable-tests" >> .mozconfig
+make -f client.mk build || exit 1
+make -f client.mk install DESTDIR=$PKG || exit 1
 
 # Install nspr/nss headers.
 for includedir in nspr nspr/obsolete nspr/private ; do
@@ -156,9 +163,6 @@ cp -aL mozilla/dist/sdk/include/* $PKG/usr/include/seamonkey-${VERSION}
   ln -sf . plugin
   ln -sf . xpcom
 )
-
-# Exit obj directory:
-cd ..
 
 # We don't need this stuff in the package:
 rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/seamonkey-devel-$VERSION
diff --git a/source/xap/xine-lib/xine-lib.SlackBuild b/source/xap/xine-lib/xine-lib.SlackBuild
--- a/source/xap/xine-lib/xine-lib.SlackBuild
+++ b/source/xap/xine-lib/xine-lib.SlackBuild
@@ -1,6 +1,8 @@
 #!/bin/sh
 
 # Copyright 2008, 2009, 2012  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2011, 2012  Eric Hameleers, Eindhoven, NL
+# Copyright 2015  Heinz Wiesinger, Amsterdam, NL
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -22,51 +24,102 @@
 
 
 # Version on the tarball
-VERSION=1.1.21
+VERSION=1.2.6
 # Version used in the source directory to cd into
-DIRVER=1.1.21
+DIRVER=1.2.6
 # Version used for the Slackware package
-PKGVER=1.1.21
+PKGVER=1.2.6
 
-BUILD=${BUILD:-2}
+# Version used for statically linked ffmpeg
+FFMPEG_VERSION=${FFMPEG_VERSION:-$(echo ../MPlayer/ffmpeg-*.tar.xz | rev | cut -f 3- -d . | cut -f 1 -d- | rev)}
+
+BUILD=${BUILD:-8}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) export ARCH=i686 ;;
+    i?86) export ARCH=i586 ;;
     arm*) export ARCH=arm ;;
     # Unless $ARCH is already set, use uname -m for all other archs:
        *) export ARCH=$( uname -m ) ;;
   esac
 fi
 
-# I would use "-march=i486 -mtune=i686" here as usual, but with XINE it's all or nothing.
-# I'd rather have it work well for the i686/Athlon crowd than suck for everyone.
 TARGET=${TARGET:-$ARCH-pc-linux-gnu}
 
 NUMJOBS=${NUMJOBS:-" -j7 "}
 
 if [ "$ARCH" = "x86_64" ]; then
   LIBDIRSUFFIX="64"
+  FFARCHOPTS="--arch=x86_64 --enable-pic"
+elif [ "$ARCH" = "i586" ]; then
+  LIBDIRSUFFIX=""
+  # 32bit x86 fails without this... let me know if you have a fix
+  FFARCHOPTS="--disable-asm"
 else
   LIBDIRSUFFIX=""
+  FFARCHOPTS=""
 fi
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-xine-lib
-rm -rf $PKG
-mkdir -p $TMP $PKG/usr
+FFMPEG_PKG=$TMP/package-ffmpeg
+rm -rf $PKG $FFMPEG_PKG
+mkdir -p $TMP $PKG/usr $FFMPEG_PKG
 
 cd $TMP
+rm -rf ffmpeg*
+tar xvf $CWD/../MPlayer/ffmpeg-$FFMPEG_VERSION.tar.xz || exit 1
+cd ffmpeg* || exit 1
+
+  chown -R root:root .
+  find . \
+   \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
+   -exec chmod 755 {} \; -o \
+   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
+   -exec chmod 644 {} \;
+
+  echo Building static ffmpeg libs ...
+
+  FFMPEGDIR=/tmp/ff-$(mcookie)
+
+  CFLAGS="$SLKCFLAGS -fvisibility=hidden -I/usr/include/openmj2-2.1" \
+  CXXFLAGS="$SLKCFLAGS -fvisibility=hidden -I/usr/include/openmj2-2.1" \
+  ./configure \
+    --prefix=$FFMPEGDIR/usr \
+    --libdir=$FFMPEGDIR/usr/lib${LIBDIRSUFFIX} \
+    --shlibdir=$FFMPEGDIR/usr/lib${LIBDIRSUFFIX} \
+    --enable-gpl \
+    --enable-version3 \
+    --enable-libtheora \
+    --enable-postproc \
+    --disable-doc \
+    --disable-avfilter \
+    --disable-avdevice \
+    --disable-swresample \
+    --disable-ffserver \
+    --disable-ffplay \
+    --disable-ffmpeg \
+    --disable-ffprobe \
+    --enable-pthreads \
+    --disable-debug \
+    --disable-shared \
+    --enable-static \
+    --enable-hardcoded-tables \
+    --enable-memalign-hack \
+    --enable-bzlib \
+    --enable-zlib \
+    --enable-libopenjpeg \
+    ${FFARCHOPTS}
+
+    make $NUMJOBS V=1 || exit 1
+    make install # Note: no DESTDIR !!
+cd -
+
 rm -rf xine-lib-$VERSION
 tar xvf $CWD/xine-lib-$VERSION.tar.xz || exit 1
 cd xine-lib-$DIRVER || exit 1
-
-zcat $CWD/xine-lib.XvMClib.h.diff.gz | patch -p1 --verbose || exit 1
-
-# Fix for zlib-1.2.6 (or higher):
-sed -i 's#gzgetc(#gzgetc_(#' src/xine-engine/osd.c
 
 chown -R root:root .
 find . \
@@ -75,6 +128,11 @@ find . \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \;
 
+export PKG_CONFIG_PATH="${FFMPEGDIR}/usr/lib${LIBDIRSUFFIX}/pkgconfig"
+export CFLAGS="-I${FFMPEGDIR}/usr/include $SLKCFLAGS"
+export CXXFLAGS="-I${FFMPEGDIR}/usr/include $SLKCFLAGS"
+export LDFLAGS="-L${FFMPEGDIR}/usr/lib${LIBDIRSUFFIX} $SLKLDFLAGS"
+
 XINE_BUILD=$TARGET \
 ./configure \
   --prefix=/usr \
@@ -82,12 +140,17 @@ XINE_BUILD=$TARGET \
   --docdir=/usr/doc/xine-lib-$VERSION \
   --mandir=/usr/man \
   --with-w32-path=/usr/lib${LIBDIRSUFFIX}/codecs \
-  --with-arts \
+  --with-wavpack \
   --disable-nosefart \
-  --without-speex
+  --disable-vcd \
+  --without-speex \
+  --with-external-dvdnav
 
 make $NUMJOBS || make || exit 1
 make install DESTDIR=$PKG || exit 1
+
+# Remove .la files:
+rm -f $PKG//usr/lib${LIBDIRSUFFIX}/*.la
 
 mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/codecs
 
