Slackware 13.37
Mon Apr 25 13:37:00 UTC 2011
Slackware 13.37 x86_64 stable is released!

Thanks to everyone who pitched in on this release: the Slackware team,
the folks producing upstream code, and linuxquestions.org for providing
a great forum for collaboration and testing.

The ISOs are off to be replicated, a 6 CD-ROM 32-bit set and a
dual-sided
32-bit/64-bit x86/x86_64 DVD.  Please consider supporting the Slackware
project by picking up a copy from store.slackware.com.  We're taking
pre-orders now, and offer a discount if you sign up for a subscription.

As always, thanks to the Slackware community for testing, suggestions,
and feedback.  :-)

Have fun!

diff --git a/source/a/minicom/minicom.SlackBuild b/source/a/minicom/minicom.SlackBuild
--- a/source/a/minicom/minicom.SlackBuild
+++ b/source/a/minicom/minicom.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2008, 2009, 2010  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2008, 2009, 2010, 2011  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -21,8 +21,10 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 
-VERSION=2.1
-BUILD=${BUILD:-4}
+VERSION=2.5
+BUILD=${BUILD:-1}
+
+NUMJOBS=${NUMJOBS:--j6}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -59,97 +61,99 @@ cd minicom-$VERSION
 
 # The following command renames the internal implementation of getline
 # to g_getline as newer versions of Glibc provide an incompatible version:
-sed -i -e "s/getline/g_&/" $(grep -lr getline *)
+#sed -i -e "s/getline/g_&/" $(grep -lr getline *)
 
 chown -R root:root .
 find . -perm 777 -exec chmod 755 {} \;
 find . -perm 664 -exec chmod 644 {} \;
-# Fix re-declaration of BC in termcap.h
-zcat $CWD/wintcap.diff.gz | patch -p1 --verbose || exit 1
 
-## Forget it...  it just doesn't help.
-## Remove the autoconf program for this sorry old turd or abandon all hope.
-#touch configure
 CFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/usr \
-  --sysconfdir=/etc
-make -j3 || exit 1
+  --sysconfdir=/etc \
+  --mandir=/usr/man \
+  --build=$ARCH-slackware-linux
+
+make $NUMJOBS || make || exit 1
 make install DESTDIR=$PKG || exit 1
+
 mkdir -p $PKG/etc
 zcat $CWD/minicom.users.gz > $PKG/etc/minicom.users.new
-zcat $CWD/minirc.dfl.gz > $PKG/etc/minirc.dfl.new
-gzip -9 $PKG/usr/man/man?/*.?
+printf "# Machine-generated file - use "minicom -s" to change parameters.\n" \
+       > $PKG/etc/minirc.dfl.new
+
 mkdir -p $PKG/usr/doc/minicom-$VERSION
 cp -a \
-  ABOUT-NLS AUTHORS COPYING ChangeLog FILE_ID.DIZ INSTALL NEWS README TODO \
-  doc \
+  AUTHORS COPYING* ChangeLog FILE_ID.DIZ INSTALL NEWS README* TODO doc \
   $PKG/usr/doc/minicom-$VERSION
+rm -f $PKG/usr/doc/minicom-$VERSION/doc/{ChangeLog.old,Makefile*}
+
+# If there's a ChangeLog, installing at least part of the recent history
+# is useful, but don't let it get totally out of control:
+if [ -r ChangeLog ]; then
+  DOCSDIR=$(echo $PKG/usr/doc/*-$VERSION)
+  cat ChangeLog | head -n 1000 > $DOCSDIR/ChangeLog
+  touch -r ChangeLog $DOCSDIR/ChangeLog
+fi
 
 # lzrz
-# If autoconf causes failure here (which it probably will),
-# remove it temporarily and the build should work fine...
+# If autotools causes failure here (which it probably will), temporarily 
+# move /usr/bin/auto{conf,header,make} out of the way and it should work... 
+
 cd $TMP
-tar xzvf $CWD/lrzsz_0.12.21.orig.tar.gz || exit 1
+rm -rf lrzsz-990823
+tar xvf $CWD/lrzsz_0.12.21.orig.tar.gz || exit 1
 cd lrzsz-990823
+chown -R root:root .
+
 # Make x86_64 a valid machine type (thanks to Fred Emmott)
 zcat $CWD/config.sub-x86_64.diff.gz | patch -p1 --verbose || exit 1
-zcat $CWD/lrzsz_0.12.21-4.diff.gz | patch -p1 --verbose || exit 1
-chown -R root:root .
-#touch configure
+
+# Apply some of the debian patches
+zcat $CWD/lrzsz_0.12.21-5.diff.gz | patch -p1 --verbose || exit 1
+rm -f debian/patches/{206499_ymodemg.diff.unchecked,206648_dszlog.diff.unchecked}
+for i in debian/patches/* ; do patch -p1 < $i || exit 1 ; done
+
 ./configure \
   --prefix=/usr \
-  $ARCH-slackware-linux
-make -j3 || exit 1
-cd src
-cat lrz > $PKG/usr/bin/lrz
-cat lsz > $PKG/usr/bin/lsz
-chmod 755 $PKG/usr/bin/l*z
-cd ../man
-for page in lrz.1 lsz.1 ; do
-  cat $page | gzip -9c > $PKG/usr/man/man1/$page.gz
-done
-echo '.so man1/lrz.1' | gzip -9c > $PKG/usr/man/man1/rz.1.gz
-echo '.so man1/lsz.1' | gzip -9c > $PKG/usr/man/man1/sz.1.gz
-cd ../po
-mkdir -p $PKG/usr/share/locale/de/LC_MESSAGES
-cat de.gmo > $PKG/usr/share/locale/de/LC_MESSAGES/lrzsz.mo
-cd ..
-mkdir -p $PKG/usr/doc/lrzsz-0.12.21
-cp -a ABOUT-NLS AUTHORS COMPATABILITY COPYING INSTALL NEWS README-alpha \
-  README.cvs README.gettext README.isdn4linux README.systems \
-  README.tests THANKS TODO $PKG/usr/doc/lrzsz-0.12.21
+  --mandir=/usr/man \
+  --build=$ARCH-slackware-linux
 
+make $NUMJOBS || make || exit 1
+
+cp src/lrz src/lsz $PKG/usr/bin
+chmod 0755 $PKG/usr/bin/{lrz,lsz}
+
+cp man/{lrz,lsz}.1 $PKG/usr/man/man1
+echo '.so man1/lrz.1' > $PKG/usr/man/man1/rz.1
+echo '.so man1/lsz.1' > $PKG/usr/man/man1/sz.1
+
+mkdir -p $PKG/usr/share/locale/de/LC_MESSAGES
+cat po/de.gmo > $PKG/usr/share/locale/de/LC_MESSAGES/lrzsz.mo
+
+mkdir -p $PKG/usr/doc/lrzsz-0.12.21
+cp -a \
+  AUTHORS COMPATABILITY COPYING* INSTALL NEWS README* THANKS TODO \
+  $PKG/usr/doc/lrzsz-0.12.21
+
+( cd $PKG/usr/bin
+  for i in lrb lrx rz ; do ln -s lrz $i ; done
+  for i in lsb lsx sz ; do ln -s lsz $i ; done
+  for i in rx rb ; do ln -s rz $i ; done
+  for i in sb sx ; do ln -s sz $i ; done
+)
 
 ( cd $PKG
-  ( cd usr/bin ; rm -rf rx )
-  ( cd usr/bin ; ln -sf  rz rx )
-  ( cd usr/bin ; rm -rf rb )
-  ( cd usr/bin ; ln -sf  rz rb )
-  ( cd usr/bin ; rm -rf sb )
-  ( cd usr/bin ; ln -sf  sz sb )
-  ( cd usr/bin ; rm -rf sx )
-  ( cd usr/bin ; ln -sf  sz sx )
-  ( cd usr/bin ; rm -rf rz )
-  ( cd usr/bin ; ln -sf lrz rz )
-  ( cd usr/bin ; rm -rf lrb )
-  ( cd usr/bin ; ln -sf lrz lrb )
-  ( cd usr/bin ; rm -rf lrx )
-  ( cd usr/bin ; ln -sf lrz lrx )
-  ( cd usr/bin ; rm -rf sz )
-  ( cd usr/bin ; ln -sf lsz sz )
-  ( cd usr/bin ; rm -rf lsb )
-  ( cd usr/bin ; ln -sf lsz lsb )
-  ( cd usr/bin ; rm -rf lrx )
-  ( cd usr/bin ; ln -sf lsz lrx )
   find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
   find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
 )
+
+find $PKG/usr/man -type f -exec gzip -9 {} \;
+
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
 
-
 cd $PKG
-makepkg -l y -c n $TMP/minicom-$VERSION-$ARCH-$BUILD.txz
+/sbin/makepkg -l y -c n $TMP/minicom-$VERSION-$ARCH-$BUILD.txz
 
diff --git a/source/a/udev/udev.SlackBuild b/source/a/udev/udev.SlackBuild
--- a/source/a/udev/udev.SlackBuild
+++ b/source/a/udev/udev.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2006, 2008, 2009, 2010  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2006, 2008, 2009, 2010, 2011  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -21,7 +21,7 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 VERSION=${VERSION:-$(echo udev-*.tar.* | cut -d - -f 2 | rev | cut -f 3- -d . | rev)}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 
 NUMJOBS=${NUMJOBS:-" -j7 "}
 
@@ -58,6 +58,14 @@ find . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
 
+# So this is a major bug.  At least, it triggers one in the kernel.
+# We'll revert it for now.  If left in place, machines using ATA
+# (especially PATA) are liable to randomly crash on reboot.
+# The last little bit of this patch fails to reverse but it won't matter.
+if [ $VERSION = 165 ]; then
+  zcat $CWD/udev.git-560de575148b7efda3b34a7f7073abd483c5f08e.patch.gz | patch -p1 -R
+fi
+
 # Fixup the rule generator for our use
 zcat $CWD/rule_generator.diff.gz | patch -p1 || exit 1
 
@@ -73,7 +81,7 @@ zcat $CWD/rule_generator.diff.gz | patch -p1 || exit 1
   --disable-introspection \
   --mandir=/usr/man \
   --docdir=/usr/doc/udev-$VERSION \
-  --build=$ARCH-slackware-linux
+  --build=$ARCH-slackware-linux || exit 1
 
 make $NUMJOBS || make || exit 1
 make install DESTDIR=$PKG || exit 1
@@ -106,6 +114,8 @@ find $PKG/etc -type d -exec chmod 755 {} \;
 chmod 0755 $PKG/etc/rc.d/rc.udev.new
 
 # Add extra device nodes to the package that udev doesn't make:
+# As of 156, some of these aren't be needed any more:
+# removed core@  fd@  stderr@  stdin@  stdout@ 
 tar xvf $CWD/udev-fixed-devices.tar.gz -C $PKG
 
 # Add various helper scripts:
@@ -113,18 +123,15 @@ for file in $CWD/config/scripts/* ; do
   cp -a $file $PKG/lib/udev/
 done
 chown -R root:root $PKG/lib/udev
-chmod 755 $PKG/lib/udev/*
+chmod 0755 $PKG/lib/udev/*
 
 # Move the pkgconfig file to where we expect it
 mv $PKG/usr/share/pkgconfig/* $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig
 rmdir $PKG/usr/share/pkgconfig
 
-# Kill the ConsoleKit stuff
-rm -rf $PKG/usr/lib/ConsoleKit ; rmdir $PKG/usr/lib 2>/dev/null
-
 mkdir -p $PKG/usr/doc/udev-$VERSION
 cp -a \
-  COPYING* README* TODO \
+  COPYING* README* TODO extras/keymap/README.keymap.txt \
   $PKG/usr/doc/udev-$VERSION
 
 # Don't package the API docs:
diff --git a/source/l/glibc/glibc.SlackBuild b/source/l/glibc/glibc.SlackBuild
--- a/source/l/glibc/glibc.SlackBuild
+++ b/source/l/glibc/glibc.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2006, 2008, 2009, 2010  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2006, 2008, 2009, 2010, 2011  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -22,9 +22,9 @@
 
 ## build glibc-$VERSION for Slackware
 
-VERSION=${VERSION:-2.11.1}
+VERSION=${VERSION:-2.13}
 CHECKOUT=${CHECKOUT:-""}
-BUILD=${BUILD:-3}
+BUILD=${BUILD:-4}
 
 ## Included in glibc now:
 ## glibc-libidn version
@@ -41,92 +41,6 @@ if [ -z "$ARCH" ]; then
        *) export ARCH=$( uname -m ) ;;
   esac
 fi
-
-CVSVER=${VERSION}${CHECKOUT}
-
-# NOTE!!!  glibc needs to be built against the sanitized kernel headers,
-# which will be installed under /usr/include by the kernel-headers package.
-# Be sure the correct version of the headers package is installed BEFORE
-# building glibc!
-
-CWD=$(pwd)
-# Temporary build location.  This should not be a directory
-# path a non-root user could create later...
-TMP=${TMP:-/glibc-tmp-$(mcookie)}
-mkdir -p $TMP
-
-NUMJOBS=${NUMJOBS:--j4}
-
-# Sanity check on the version number in the install scripts:
-if ! grep -vq libutil-$VERSION}.so $CWD/doinst.sh-glibc ; then
-  echo "FATAL:  doinst.sh scripts have wrong version numbers."
-  exit 1
-fi
-
-case $ARCH in
-  x86_64)
-    TARGET=${TARGET:-x86_64}
-    ;;
-  i486)
-    # This should be i486 for all 32-bit x86 arch:
-    TARGET=${TARGET:-i486}
-    ;;
-esac
-
-# This function fixes a doinst.sh file for x86_64.
-# With thanks to Fred Emmott.
-fix_doinst() {
-  if [ "x$LIBDIRSUFFIX" = "x" ]; then
-    return;
-  fi;
-  # Fix "( cd usr/lib ;" occurrences
-  sed -i "s#lib ;#lib${LIBDIRSUFFIX} ;#" install/doinst.sh
-  # Fix "lib/" occurrences
-  sed -i "s#lib/#lib${LIBDIRSUFFIX}/#g" install/doinst.sh
-  # Fix "( cd lib" occurrences
-  sed -i "s#( cd lib\$#( cd lib${LIBDIRSUFFIX}#" install/doinst.sh
-
-  if [ "$ARCH" = "x86_64" ]; then
-    sed -i 's#ld-linux.so.2#ld-linux-x86-64.so.2#' install/doinst.sh
-  fi
-}
-
-# This is a patch function to put all glibc patches in the build script
-# up near the top.
-apply_patches() {
-  # Use old-style locale directories rather than a single (and strangely
-  # formatted) /usr/lib/locale/locale-archive file:
-  zcat $CWD/glibc.locale.no-archive.diff.gz | patch -p1 --verbose || exit 1
-  # The is_IS locale is causing a strange error about the "echn" command
-  # not existing.  This patch reverts is_IS to the version shipped in
-  # glibc-2.5:
-  zcat $CWD/is_IS.diff.gz | patch -p1 --verbose || exit 1
-  # Fix NIS netgroups:
-  zcat $CWD/glibc.nis-netgroups.diff.gz | patch -p1 --verbose || exit 1
-  # Support ru_RU.CP1251 locale:
-  zcat $CWD/glibc.ru_RU.CP1251.diff.gz | patch -p1 --verbose || exit 1
-  # Fix missing MAX macro in getcwd.c:
-  zcat $CWD/glibc.getcwd.max.macro.diff.gz | patch -p1 --verbose || exit 1
-  # Fix resolver problem with glibc-2.9:
-  zcat $CWD/glibc-2.10-dns-no-gethostbyname4.diff.gz | patch -p0 --verbose || exit 1
-  # This reverts a patch that was made to glibc to fix "namespace leakage",
-  # which seems to cause some build failures (e.g. with conntrack):
-  zcat $CWD/glibc.revert.to.fix.build.breakages.diff.gz | patch -p1 --verbose || exit 1
-  # Update the timezone information.
-  ( cd timezone
-    tar xzf $CWD/tzdata?????.tar.gz
-    chown root:root *
-    mv yearistype.sh yearistype
-    chmod 644 *
-    chmod 755 yearistype
-    mkdir tzcode
-    cd tzcode
-    tar xzf $CWD/tzcode?????.tar.gz
-    chown -R root:root .
-    chmod 644 *
-    cp -a *.c *.h ..
-  )
-}
 
 # I'll break this out as an option for fun  :-)
 case $ARCH  in
@@ -163,6 +77,109 @@ case $ARCH  in
     LIBDIRSUFFIX=""
     ;;
 esac
+
+case $ARCH in
+  x86_64)
+    TARGET=${TARGET:-x86_64}
+    ;;
+  i486)
+    # This should be i486 for all 32-bit x86 arch:
+    TARGET=${TARGET:-i486}
+    ;;
+esac
+
+# Hand off the $ARCH variable to $SLACKWARE_ARCH to avoid confusing glibc:
+SLACKWARE_ARCH=$ARCH
+unset ARCH
+
+CVSVER=${VERSION}${CHECKOUT}
+
+# NOTE!!!  glibc needs to be built against the sanitized kernel headers,
+# which will be installed under /usr/include by the kernel-headers package.
+# Be sure the correct version of the headers package is installed BEFORE
+# building glibc!
+
+CWD=$(pwd)
+# Temporary build location.  This should not be a directory
+# path a non-root user could create later...
+TMP=${TMP:-/glibc-tmp-$(mcookie)}
+mkdir -p $TMP
+
+NUMJOBS=${NUMJOBS:--j4}
+
+# Sanity check on the version number in the install scripts:
+if ! grep -vq libutil-${VERSION}.so $CWD/doinst.sh-glibc ; then
+  echo "FATAL:  doinst.sh scripts have wrong version numbers."
+  exit 1
+fi
+
+# This function fixes a doinst.sh file for x86_64.
+# With thanks to Fred Emmott.
+fix_doinst() {
+  if [ "x$LIBDIRSUFFIX" = "x" ]; then
+    return;
+  fi;
+  # Fix "( cd usr/lib ;" occurrences
+  sed -i "s#lib ;#lib${LIBDIRSUFFIX} ;#" install/doinst.sh
+  # Fix "lib/" occurrences
+  sed -i "s#lib/#lib${LIBDIRSUFFIX}/#g" install/doinst.sh
+  # Fix "( cd lib" occurrences
+  sed -i "s#( cd lib\$#( cd lib${LIBDIRSUFFIX}#" install/doinst.sh
+
+  if [ "$SLACKWARE_ARCH" = "x86_64" ]; then
+    sed -i 's#ld-linux.so.2#ld-linux-x86-64.so.2#' install/doinst.sh
+  fi
+}
+
+# This is a patch function to put all glibc patches in the build script
+# up near the top.
+apply_patches() {
+  # Use old-style locale directories rather than a single (and strangely
+  # formatted) /usr/lib/locale/locale-archive file:
+  zcat $CWD/glibc.locale.no-archive.diff.gz | patch -p1 --verbose || exit 1
+  # The is_IS locale is causing a strange error about the "echn" command
+  # not existing.  This patch reverts is_IS to the version shipped in
+  # glibc-2.5:
+  zcat $CWD/is_IS.diff.gz | patch -p1 --verbose || exit 1
+  # Fix NIS netgroups:
+  zcat $CWD/glibc.nis-netgroups.diff.gz | patch -p1 --verbose || exit 1
+  # Support ru_RU.CP1251 locale:
+  zcat $CWD/glibc.ru_RU.CP1251.diff.gz | patch -p1 --verbose || exit 1
+  # Fix missing MAX macro in getcwd.c:
+  zcat $CWD/glibc.getcwd.max.macro.diff.gz | patch -p1 --verbose || exit 1
+  # Fix resolver problem with glibc-2.9:
+  zcat $CWD/glibc-2.10-dns-no-gethostbyname4.diff.gz | patch -p0 --verbose || exit 1
+  # This reverts a patch that was made to glibc to fix "namespace leakage",
+  # which seems to cause some build failures (e.g. with conntrack):
+  zcat $CWD/glibc.revert.to.fix.build.breakages.diff.gz | patch -p1 --verbose || exit 1
+  # This partial security patch still applies and might be needed:
+  zcat $CWD/glibc.git-96611391ad8823ba58405325d78cefeae5cdf699-CVE-2010-3847b.patch.gz | patch -p1 --verbose || exit 1
+  # Make it harder for people to trick ldd into running code:
+  zcat $CWD/glibc.ldd.trace.through.dynamic.linker.diff.gz | patch -p1 --verbose || exit 1
+  # Make glibc compile with binutils using --enable-initfini-array.
+  # At this time, we do not recommend this due to probable ABI breakage.
+  # The also patch needs work before it would apply.
+  # ***NOT READY***
+  #zcat $CWD/glibc.git-4a531bb0b3b582cb693de9f76d2d97d970f9a5d5.patch.gz | patch -p1 --verbose || exit 1
+  #
+  # Avoid the Intel optimized asm routines for now because they break
+  # the flash player.  We'll phase this in when it's safer to do so.
+  zcat $CWD/glibc.disable.broken.optimized.memcpy.diff.gz | patch -p1 --verbose || exit 1
+  # Update the timezone information.
+  ( cd timezone
+    tar xzf $CWD/tzdata?????.tar.gz
+    chown root:root *
+    mv yearistype.sh yearistype
+    chmod 644 *
+    chmod 755 yearistype
+    mkdir tzcode
+    cd tzcode
+    tar xzf $CWD/tzcode?????.tar.gz
+    chown -R root:root .
+    chmod 644 *
+    cp -a *.c *.h ..
+  )
+}
 
 # This is going to be the initial $DESTDIR:
 export PKG=$TMP/package-glibc-incoming-tree
@@ -232,7 +249,7 @@ fi
 
 # Make build directory:
 mkdir build-glibc-$VERSION
-cd build-glibc-$VERSION
+cd build-glibc-$VERSION || exit 1
 
 echo "BUILDING DAS NPTL GLIBC"
 CFLAGS="-g $OPTIMIZ" \
@@ -373,7 +390,7 @@ mv $PKG/usr/lib${LIBDIRSUFFIX}/lib*_p.a usr/lib${LIBDIRSUFFIX}
 ( cd usr/lib${LIBDIRSUFFIX} ; strip -g *.a )
 mkdir install
 cp -a $CWD/slack-desc.glibc-profile install/slack-desc
-makepkg -l y -c n $TMP/glibc-profile-$VERSION-$ARCH-$BUILD.txz
+makepkg -l y -c n $TMP/glibc-profile-$VERSION-$SLACKWARE_ARCH-$BUILD.txz
 
 # THIS IS NO LONGER PACKAGED (or is it?  might be better to let it be made, and then ship it or not...)
 # glibc-debug:
@@ -383,7 +400,7 @@ mkdir -p usr/lib${LIBDIRSUFFIX}
 mv $PKG/usr/lib${LIBDIRSUFFIX}/debug usr/lib${LIBDIRSUFFIX}
 mkdir install
 cp -a $CWD/slack-desc.glibc-debug install/slack-desc
-makepkg -l y -c n $TMP/glibc-debug-$VERSION-$ARCH-$BUILD.txz
+makepkg -l y -c n $TMP/glibc-debug-$VERSION-$SLACKWARE_ARCH-$BUILD.txz
 ## INSTEAD, NUKE THESE LIBS
 #rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/debug
 
@@ -397,7 +414,7 @@ cp -a $PKG/usr/share/i18n usr/share
 cp -a $PKG/usr/share/locale usr/share
 mkdir install
 cp -a $CWD/slack-desc.glibc-i18n install/slack-desc
-makepkg -l y -c n $TMP/glibc-i18n-$VERSION-$ARCH-$BUILD.txz
+makepkg -l y -c n $TMP/glibc-i18n-$VERSION-$SLACKWARE_ARCH-$BUILD.txz
 
 # glibc-solibs:
 cd $PSOLIBS
@@ -438,7 +455,7 @@ fix_doinst
 # Ditch links:
 find . -type l -exec rm {} \;
 # Build the package:
-makepkg -l y -c n $TMP/glibc-solibs-$VERSION-$ARCH-$BUILD.txz
+makepkg -l y -c n $TMP/glibc-solibs-$VERSION-$SLACKWARE_ARCH-$BUILD.txz
 
 # And finally, the complete "all-in-one" glibc package is created
 # from whatever was leftover:
@@ -460,7 +477,7 @@ fix_doinst
   mv incoming/libSegFault.so .
 )
 # Build the package:
-/sbin/makepkg -l y -c n $TMP/glibc-$VERSION-$ARCH-$BUILD.txz
+/sbin/makepkg -l y -c n $TMP/glibc-$VERSION-$SLACKWARE_ARCH-$BUILD.txz
 
 # Done!
 echo
diff --git a/source/l/gtk+2/gtk+2.SlackBuild b/source/l/gtk+2/gtk+2.SlackBuild
--- a/source/l/gtk+2/gtk+2.SlackBuild
+++ b/source/l/gtk+2/gtk+2.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2008, 2009, 2010  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2008, 2009, 2010, 2011  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -68,23 +68,20 @@ find . \
   \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \;
 
-# There's been this long standing debate about PNG and -lz
-# and this patch is the workaround.  ;-)
-zcat $CWD/gtk.pnglz.diff.gz | patch -p1 --verbose || exit 1
+# Fix build errors
+zcat $CWD/fix_build_issues_on_tutorial_and_faq.diff.gz | patch -p1 --verbose || exit 1
 
 # Do not flood the console or .xsession-errors with "trouble ahead"
 # warnings (most noticable when using Firefox and Flash):
 zcat $CWD/gtk.xid.nowarningflood.diff.gz | patch -p1 --verbose || exit 1
 
-# Use /etc/gtk-2.0/$ARCH-slackware-linux instead of /etc/gtk-2.0/
-sed -i "s/GTK_SYSCONFDIR, \\\"gtk-2\\.0\\\"/GTK_SYSCONFDIR, \\\"gtk-2\\.0\\\", HOST/g" ./gtk/gtkrc.c ./gdk-pixbuf/gdk-pixbuf-io.c
-sed -i 's/sysconfdir)\\"/&      \\\n\t-DHOST=\\\"$(host_triplet)\\\"/g' \
-gdk-pixbuf/Makefile.am \
-gtk/Makefile.am \
-modules/input/Makefile.am
+# Use /etc/gtk-2.0/$ARCH-slackware-linux instead of /etc/gtk-2.0/ for gtk.immodules
+zcat $CWD/use_host_triplet_for_gtk_immodules.diff.gz | patch -p1 --verbose || exit 1
 
-# Use libpng-1.4.x:
-zcat $CWD/gtk.png14.diff.gz | patch -p1 --verbose || exit 1
+# Patch to restore commonly used icon names, otherwise everything breaks.
+# I fail to see the point of this "cleanup"
+zcat $CWD/gtk+-2.24.x.icon-compat.diff.gz | patch -p1 --verbose || exit 1
+zcat $CWD/gtk+-2.24.x.icon-compat.am.diff.gz | patch -p1 --verbose || exit 1
 
 # Regenerate ./configure:
 libtoolize --force
@@ -101,6 +98,8 @@ CFLAGS="$SLKCFLAGS -DHOST='"'"${ARCH}-slackware-linux"'"'" \
   --sysconfdir=/etc \
   --mandir=/usr/man \
   --with-xinput=yes \
+  --enable-xkb \
+  --disable-introspection \
   --build=$ARCH-slackware-linux
 
 make $NUMJOBS || make || exit 1
@@ -112,18 +111,26 @@ if [ "x$compile_host" != "x$host" ]; then
   echo "Host mismatch: compile='$compile_host', SlackBuild='$host'" && exit 1
 fi
 
-make install DESTDIR=$PKG \
+make install \
   RUN_QUERY_IMMODULES_TEST=false RUN_QUERY_LOADER_TEST=false \
+  DESTDIR=$PKG \
   || exit 1
 
-# I'm spamming your root partition because /etc/gtk-2.0 won't install to $DESTDIR
-make install || exit 1
+# You'll probably need to install the newly made package right away to
+# fix the result of this next line, but we had to clear this.  Sorry.
+rm -rf /etc/gtk-2.0
+# I'm spamming your root partition because /etc/gtk-2.0 won't install to $DESTDIR...
+make install 
 cp -a /etc/gtk-2.0/* $PKG/etc/gtk-2.0/ || exit 1
 rm -rf $PKG/etc/gtk-2.0/$host
 mkdir -p $PKG/etc/gtk-2.0/$host
-mv $PKG/etc/gtk-2.0/* $PKG/etc/gtk-2.0/$host/
+mv $PKG/etc/gtk-2.0/gtk.immodules $PKG/etc/gtk-2.0/$host/
 
-mv $PKG/etc/gtk-2.0/$host/im-multipress.conf $PKG/etc/gtk-2.0/$host/im-multipress.conf.new || exit 1
+# Don't clobber im-multipress.conf
+mv $PKG/etc/gtk-2.0/im-multipress.conf $PKG/etc/gtk-2.0/im-multipress.conf.new || exit 1
+
+# Install a "starter" gtkrc
+echo 'gtk-theme-name="GTK+"' > $PKG/etc/gtk-2.0/gtkrc.new
 
 # We need to have separate 32-bit and 64-bit binaries
 # for places where we have two copies of the GTK+ package installed.
@@ -131,29 +138,33 @@ mv $PKG/etc/gtk-2.0/$host/im-multipress.conf $PKG/etc/gtk-2.0/$host/im-multipres
 case "$host" in
   s390x*|x86_64*)
    mv $PKG/usr/bin/gtk-query-immodules-2.0{,-64}
-   mv $PKG/usr/bin/gdk-pixbuf-query-loaders{,-64}
    ( cd $PKG/usr/bin
      ln -sf gtk-query-immodules-2.0-64 gtk-query-immodules-2.0
-     ln -sf gdk-pixbuf-query-loaders-64 gdk-pixbuf-query-loaders
    )
    ;;
   *)
    mv $PKG/usr/bin/gtk-query-immodules-2.0{,-32}
-   mv $PKG/usr/bin/gdk-pixbuf-query-loaders{,-32}
    ( cd $PKG/usr/bin
      ln -sf gtk-query-immodules-2.0-32 gtk-query-immodules-2.0
-     ln -sf gdk-pixbuf-query-loaders-32 gdk-pixbuf-query-loaders
    )
    ;;
 esac
 
 # Install wrappers for the binaries:
-cp $CWD/update-gdk-pixbuf-loaders $PKG/usr/bin/update-gdk-pixbuf-loaders
-cp $CWD/update-gtk-immodules $PKG/usr/bin/update-gtk-immodules
+cp -a $CWD/update-gtk-immodules* $PKG/usr/bin
+chown root:root $PKG/usr/bin/update-*
 chmod 0755 $PKG/usr/bin/update-*
 
-find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+# Add profile scripts to set up GTK+ environment:
+mkdir -p $PKG/etc/profile.d
+cp -a $CWD/profile.d/* $PKG/etc/profile.d
+chmod 0755 $PKG/etc/profile.d/*
+
+# Strip binaries:
+( cd $PKG
+  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
+)
 
 # Compress and if needed symlink the man pages:
 if [ -d $PKG/usr/man ]; then
@@ -172,13 +183,12 @@ fi
 
 mkdir -p $PKG/usr/doc/gtk+-$VERSION
 cp -a \
-  AUTHORS COPYING NEWS README TODO \
+  AUTHORS COPYING* NEWS README* TODO \
   $PKG/usr/doc/gtk+-$VERSION
 ( cd $PKG/usr/doc/gtk+-$VERSION
-  ln -s /usr/share/gtk-doc/html/gail-libgail-util .
-  ln -s /usr/share/gtk-doc/html/gdk .
-  ln -s /usr/share/gtk-doc/html/gdk-pixbuf .
-  ln -s /usr/share/gtk-doc/html/gtk .
+  ln -s ../../share/gtk-doc/html/gail-libgail-util .
+  ln -s ../../share/gtk-doc/html/gdk .
+  ln -s ../../share/gtk-doc/html/gtk .
 )
 
 # If there's a ChangeLog, installing at least part of the recent history
@@ -188,13 +198,6 @@ if [ -r ChangeLog ]; then
   cat ChangeLog | head -n 1000 > $DOCSDIR/ChangeLog
   touch -r ChangeLog $DOCSDIR/ChangeLog
 fi
-
-# I'm almost inclined to think this stuff is obsolete but I don't know for sure.
-# I do know that leaving it in doesn't hurt (aside from a few wasted bytes, but
-# probably less than the comments here waste ;-)
-mkdir -p $PKG/etc/profile.d
-cp -a $CWD/profile.d/* $PKG/etc/profile.d
-chmod 755 $PKG/etc/profile.d/*
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
diff --git a/source/l/soprano/soprano.SlackBuild b/source/l/soprano/soprano.SlackBuild
--- a/source/l/soprano/soprano.SlackBuild
+++ b/source/l/soprano/soprano.SlackBuild
@@ -22,9 +22,9 @@
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 
-VERSION=${VERSION:-2.4.3}
-BUILD=${BUILD:-1}
-NUMJOBS=${NUMJOBS:--j6}
+PKGNAM=soprano
+VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z* | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
+BUILD=${BUILD:-2}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -35,6 +35,8 @@ if [ -z "$ARCH" ]; then
        *) export ARCH=$( uname -m ) ;;
   esac
 fi
+
+NUMJOBS=${NUMJOBS:--j6}
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp}
@@ -57,6 +59,16 @@ fi
 rm -rf $PKG
 mkdir -p $TMP $PKG
 cd $TMP
+
+# Detect JDK, needed for libsoprano_sesame2backend.so:
+if ! ls /var/log/packages/jdk-* 1> /dev/null 2> /dev/null ; then
+  echo
+  echo "JDK package not found in /var/log/packages."
+  echo "This is needed to compile libsoprano_sesame2backend.so."
+  echo
+  exit 1
+fi
+
 rm -rf soprano-$VERSION
 tar xvf $CWD/soprano-$VERSION.tar.bz2 || exit 1
 cd soprano-$VERSION || exit 1
diff --git a/source/n/php/php.SlackBuild b/source/n/php/php.SlackBuild
--- a/source/n/php/php.SlackBuild
+++ b/source/n/php/php.SlackBuild
@@ -3,7 +3,7 @@
 # Build and package mod_php on Slackware.
 # by:  David Cantrell <david@slackware.com>
 # Modified for PHP 4-5 by volkerdi@slackware.com
-# Copyright 2007, 2008, 2009, 2010  Patrick Volkerding, Sebeka, MN, USA
+# Copyright 2007, 2008, 2009, 2010, 2011  Patrick Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -24,9 +24,9 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 
-VERSION=5.2.13
+VERSION=5.3.6
 ALPINE=2.00
-BUILD=${BUILD:-2}
+BUILD=${BUILD:-6}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -95,8 +95,8 @@ rm -rf php-$VERSION
 tar xvf $CWD/php-$VERSION.tar.?z* || exit 1
 cd php-$VERSION
 
-zcat $CWD/php.gmp5.diff.gz | patch -p1 --verbose || exit 1
-zcat $CWD/php.gd_libpng-1.4.diff.gz | patch -p1 --verbose || exit 1
+# cleanup:
+find . -name "*.orig" -delete
 
 # Add missing(?) PEAR modules back:
 if [ -d php-$VERSION/pear/packages ]; then
@@ -124,12 +124,9 @@ find . -name "*.h" -exec chmod 644 {} \;
 find . -name "*.orig" -exec rm {} \;
 
 # Patch ini files:
-zcat $CWD/php.ini.diff.gz \
-  | sed -e "s#usr/lib/php#usr/lib${LIBDIRSUFFIX}/php#" \
-  | patch -p1 --verbose --backup --suffix=.orig || exit 1
-zcat $CWD/php.recommended.ini.diff.gz \
-  | sed -e "s#usr/lib/php#usr/lib${LIBDIRSUFFIX}/php#" \
-  | patch -p1 --verbose --backup --suffix=.orig || exit 1
+zcat $CWD/php.ini-development.diff.gz | patch -p1 --verbose || exit 1
+zcat $CWD/php.ini-development.diff.gz | patch -p1 --verbose php.ini-production || exit 1
+zcat $CWD/php.session.save_path.diff.gz | patch -p1 --verbose || exit 1
 
 # Generic "kitchen sink" configure function, with as many things as possible (and
 # maybe then some ;-) compiled as shared extensions:
@@ -155,7 +152,6 @@ CFLAGS="$SLKCFLAGS" \
   --enable-xml \
   --with-libxml-dir=/usr \
   --enable-simplexml \
-  --enable-spl \
   --enable-filter \
   --disable-debug \
   --with-openssl=shared \
@@ -171,7 +167,6 @@ CFLAGS="$SLKCFLAGS" \
   --enable-dba=shared \
   --with-gdbm=/usr \
   --with-db4=/usr \
-  --enable-dbase=shared \
   --enable-exif=shared \
   --enable-ftp=shared \
   --with-gd=shared \
@@ -191,19 +186,21 @@ CFLAGS="$SLKCFLAGS" \
   --with-ldap=shared \
   --enable-mbstring=shared \
   --enable-hash \
-  --with-mhash=shared,/usr \
-  --with-mysql=shared,/usr \
-  --with-mysqli=shared,/usr/bin/mysql_config \
+  --with-mysql=shared,mysqlnd \
+  --with-mysqli=shared,mysqlnd \
+  --with-mysql-sock=/var/run/mysql/mysql.sock \
   --enable-pdo=shared \
-  --with-pdo-mysql=shared,/usr \
+  --with-pdo-mysql=shared,mysqlnd \
   --with-pdo-sqlite=shared,/usr \
   --with-pspell=shared,/usr \
+  --with-enchant=shared,/usr \
   --with-mm=/usr \
   --enable-shmop=shared \
   --with-snmp=shared,/usr \
   --enable-soap=shared \
   --enable-sockets \
   --with-sqlite=shared \
+  --with-sqlite3=shared \
   --enable-sqlite-utf8 \
   --with-regex=php \
   --enable-sysvmsg \
@@ -232,43 +229,25 @@ php_configure \
 make $NUMJOBS || make || exit 1
 make install INSTALL_ROOT=$PKG || exit 1
 
-# Make the CLI version of PHP:
+# Make the CLI/CGI version of PHP:
 make distclean
 php_configure \
-  --enable-force-cgi-redirect \
   --enable-pcntl \
   --enable-sigchild
 make $NUMJOBS || make || exit 1
 mkdir -p $PKG/usr/bin
 cat ./sapi/cli/php > $PKG/usr/bin/php
+cat ./sapi/cgi/php-cgi > $PKG/usr/bin/php-cgi
 chmod 755 $PKG/usr/bin/php
-
-# Make the FastCGI interpreter:
-make distclean
-php_configure \
-  --enable-fastcgi \
-  --enable-pcntl \
-  --enable-sigchild
-make $NUMJOBS || make || exit 1
-mkdir -p $PKG/usr/bin
-cat sapi/cgi/php-cgi > $PKG/usr/bin/php-cgi
 chmod 755 $PKG/usr/bin/php-cgi
 
 # PHP (used to) install Pear with some strange permissions.
 chmod 755 $PKG/usr/bin/pear
-   
+
 # PHP sometimes puts junk in the root directory:
 ( cd $PKG
   rm -rf .channels .depdb .depdblock .filemap .lock .registry
 )
-
-## Fix a couple broken .reg files in php-5.2.10:
-#if ! grep -q Download $PKG/usr/lib${LIBDIRSUFFIX}/php/.channels/pear.php.net.reg ; then
-#  cat $CWD/channels/pear.php.net.reg > $PKG/usr/lib${LIBDIRSUFFIX}/php/.channels/pear.php.net.reg
-#fi
-#if ! grep -q Download $PKG/usr/lib${LIBDIRSUFFIX}/php/.channels/pecl.php.net.reg ; then
-#  cat $CWD/channels/pecl.php.net.reg > $PKG/usr/lib${LIBDIRSUFFIX}/php/.channels/pecl.php.net.reg
-#fi
 
 # Fix $PKG/usr/lib/php perms:
 ( cd $PKG/usr/lib${LIBDIRSUFFIX}/php
@@ -281,13 +260,14 @@ chmod 755 $PKG/usr/bin/pear
 
 mkdir -p $PKG/usr/doc/php-$VERSION
 cp -a \
-  CODING_STANDARDS CREDITS EXTENSIONS INSTALL LICENSE NEWS README* TODO* \
+  CODING_STANDARDS CREDITS EXTENSIONS INSTALL LICENSE NEWS README* TODO* UPGRADING* \
   sapi/cgi/README.FastCGI \
   $PKG/usr/doc/php-$VERSION
 chown -R root:root $PKG/usr/doc/php-$VERSION
+chmod 644 $PKG/usr/doc/php-$VERSION/UPGRADING*
 
 mkdir -p $PKG/etc/httpd
-cp -a php.ini-dist php.ini-recommended $PKG/etc/httpd
+cp -a php.ini-development php.ini-production $PKG/etc/httpd
 cat $CWD/mod_php.conf.example | sed -e "s#lib/httpd#lib${LIBDIRSUFFIX}/httpd#" \
   > $PKG/etc/httpd/mod_php.conf.example
 chmod 644 $PKG/etc/httpd/*
